export default {
    zhuCeShiJian:  'registration time', 
    qingShuRuGuanJianCi:  'please enter a keyword', 
    chaXun:  'inquire', 
    zhongZhi:  'reset', 
    daoChu:  'export', 
    fanHui:  'back', 
    quanBuGuanBi:  'close all', 
    tongBu:  'synchronize', 
    bianJi:  'edit', 
    caoZuo:  'operate', 
    tianJiaBeiZhu:  'add remark', 
    beiZhu:  'remark', 
    zhuangTai:  'status', 
    huiYuanDaiChong:  'Top up on behalf of others by member', 
    zhuanZhangDaoHuiYuan:  'transfer to member account', 
    daiLiZhuanZhang:  'affiliate transfer', 
    xinJianXiaJiDai:  'Create a new sub-affiliate', 
    daiLiQuanXian:  'affiliate authority', 
    eDu:  'quota', 
    shengYuXinYong:  'remaining credit', 
    xinYongEDu:  'credits', 
    zhangHuYuE:  'account Balance', 
    guanFangChouYong:  '(official commission)', 
    huiYuanFanYongFang:  'Membership commission plan', 
    yongJinFangAnLei:  'Commission Plan Type', 
    daiLiCengJi:  'affiliate level', 
    suoShuShangJi:  'affiliate superior', 
    daiLiZhangHao:  'affiliate account', 
    xinChuangJian:  'create', 
    quanBu:  'all', 
    neiBu:  'internal', 
    shangJiDaiLi:  'superior affiliate', 
    daiChongFanLi:  'rebate of top up on behalf', 
    yuJiYongJin:  'estimated commission', 
    huoDongHongLiXiang:  'promotion bonus details', 
    lingQuShiJian:  'collect time', 
    lingQuZhuangTai:  'collecting status', 
    xuQiuLiuShuiJin:  'demand turnover amount', 
    jiangLiJiaZhi:  'reward value', 
    jiangLiLeiXing:  'reward type', 
    huoDongLeiXing:  'promotion type', 
    jiangLiFaFangShi:  'reward distribution time', 
    daiLiQuanXianGuan:  'affiliate authority management', 
    tongIPDiZhi:  'query with IP address', 
    tongSheBeiHaoCha:  'query with the device number', 
    chaXunRiQiQu:  'the query date range cannot exceed 90 days', 
    gongSiShuYing:  'company win or loss', 
    tiXianJinE:  'withdraw amount', 
    chongZhiJinE:  'deposit amount', 
    jinGeYueDengLu:  'the total number of logins in the past 3 months', 
    suoDingZhuangTai:  'locked status', 
    zuiHouDengLuShi:  'last login time', 
    shouJiHao:  'phone number', 
    zhangHuLeiXing:  'account type', 
    suoShuDaiLi:  'affiliate belongs to', 
    xingMing:  'name', 
    zhangHuMing:  'account name', 
    tiShiDianJiShe:  'Tip: Click on the device number to query the associated member information', 
    jinGeYueDengLu2:  'the total number of logins in the past 3 months', 
    zuiHouYiCiDeng:  'last login time', 
    ren:  'people', 
    gong:  'total', 
    weiHuoQuDaoCi:  'The device number has not been obtained', 
    sheBeiHaoDengLu:  'Device number (number of logins/proportion)', 
    sheBeiLeiXing:  'type of device', 
    shiJian:  'time', 
    shouJiHaoGuiShu:  'mobile attribution', 
    iPGuiShuDi:  'IP attribution', 
    iPDiZhiDeng:  'IP address(number of logins/proportion)', 
    xiuGaiFOR:  'Modifying {val1} auditing please be patient!', 
    tiaoZhengXinYongE:  'Adjust credit limit', 
    queDing:  'confirm', 
    quXiao:  'cancel', 
    iTEMS:  '{val1} is required', 
    gaiZhangHaoDingJi:  'The top affiliate of this account is', 
    dengLuRiZhi:  'login log', 
    yiChangJiLu:  'abnormal record', 
    houTaiCaoZuoJi:  'Backend operation record', 
    qianTaiCaoZuoJi:  'frontdesk operation record', 
    zhiXing:  'implement', 
    qingXuanZe:  'please choose', 
    piLiangCaoZuo:  'batch operation', 
    shuJuGengXinShi:  'Data update time: {val1}', 
    shenHe:  'audit', 
    chaKan:  'check', 
    erShenShiJian:  'Second audit time', 
    yiShenShiJian:  'First audit time', 
    erShenRen:  'Second audit person', 
    yiShenRen:  'First audit person', 
    shenHeZhuangTai:  'audit status', 
    shenQingYuanYin:  'Reason for application', 
    shenQingShiJian:  'Time for application', 
    shenQingRen:  'applicant', 
    xiuGaiHou:  'after modification', 
    xiuGaiQian:  'before modification', 
    xiTongZiDong:  'system automatic', 
    caoZuoLeiXing:  'operation type', 
    tiBiDiZhiT:  'Withdrawal address: {val1}', 
    zuiDiYouXiaoHui:  'Minimum number of active members:', 
    yongJinLianMoShi:  'Commission chain mode:', 
    fenPeiBaiFenBi:  ', the allocation percentage:', 
    jiDaiLi:  'level agent:', 
    yongJinFangAn:  'Commission Scheme:', 
    chouYongBaiFenBi:  ', commission percentage:', 
    zhuangTaiCON:  'status：{val1}', 
    qingSuanEDuC:  'Liquidation amount: {val1}', 
    eDuOPT:  'Quota: {val1}, status: {val2}', 
    xiuGaiBeiZhuC:  'Modification remarks: {val1}', 
    yinHangKaID:  'bank card ID：{val1}', 
    bianGengWei:  'changed to:', 
    xiuGaiDaiLiFan:  'Modify the affiliate rebate mode:', 
    zhuangTaiXiuGaiJie:  'Status Modification: Unlocked', 
    zhuangTaiXiuGaiJian:  'Status modification: indirect locking', 
    zhuangTaiXiuGaiWan:  'Status Modification: Fully Locked', 
    zhongZhiYinHangKa:  'Reset bank card and name', 
    xiuGaiCON:  'Modification: {val1}', 
    shangJiDaiLiI:  'Superior affiliate ID: {val1}', 
    jinYong:  'disabled', 
    qiYong:  'enable', 
    baiFenBi:  'percentage', 
    yuanBi:  'RMB/（numbers）', 
    jiSuZhiFuBao:  'Fast Alipay payment', 
    jiSuWeiXinZhi:  'Fast WeChat payment', 
    kuaiJieQianBao:  'Quick Wallet', 
    yunShanFuZhuanZhang:  'UnionPay transfer', 
    yunShanFu:  'UnionPay transfer', 
    kuaiJieZhiFu:  'Quick payment', 
    weiXinZhuanZhang:  'WeChat transfer', 
    zhiFuBaoZhuanZhang:  'Alipay transfer', 
    yinHangKaZhuanZhang:  'Bank card transfer', 
    jingDongZhiFu:  'JD pay', 
    yinLianSaoMaZhi:  'UnionPay scan code payment', 
    qQZhiFu:  'QQ Pay', 
    weiXinZhiFu:  'WeChat Pay', 
    zhiFuBaoZhiFu:  'Alipay payment', 
    wangYinZhiFu:  'Online banking', 
    chaoShiCheXiao:  'timeout cancellation', 
    yongHuCheXiao:  'user cancel', 
    buDanShenHeZhong:  'replenishment auditing', 
    renGongJuJueBu:  'replace order rejected by mannually', 
    buDanShenHeJu:  'replace order audit has been reject', 
    buDanShenHeCheng:  'replace order audit successful', 
    zhiFuChengGong:  'payment successful', 
    daiZhiFu:  'to be paid', 
    xiTongDingDanChuang:  'System - order creation failed', 
    sanFangDingDanChuang:  '3rd party - order creation failed', 
    daiLi:  'affiliate', 
    huiYuan:  'member', 
    buDanShenQing:  'apply for replace order', 
    chuangJianDingDan:  'create order', 
    weiTuiJian:  'not recommended', 
    yiTuiJian:  'recommended', 
    buDanShenHeBei:  'Remarks for replace order audit', 
    buDanShenQingBei:  'Remarks for replace order application', 
    ziJinTiaoZhengEr:  'Remarks for the second audit of funds adjustment', 
    ziJinTiaoZhengYi:  'Remarks for the first audit of funds adjustment', 
    ziJinTiaoZhengShen:  'Funds Adjustment Application Remarks', 
    zhiFuShiBai:  'payment failed', 
    shuZiHuoBiZhi:  'digital currency payment', 
    yinLianSaoMa:  'UnionPay scan code', 
    jiangXiNongCunXin:  'JxnxsDebitQuickPay', 
    huBeiYinHang:  'Bank of Hubei', 
    guiZhouShengNongCun:  'GznxbankQuickPay（Rural commercial bank）', 
    fuJianShengNongCun:  'FjnxCreditQuickPay', 
    quanZhouYinHang:  'Bank of Quanzhou', 
    shaoXingYinHang:  'Bank of Shaoxing', 
    beiJingShangYeYin:  'Bank of Beijing Co., Ltd', 
    wuHanNongShangYin:  'Wuhan Rural Commercial Bank', 
    hengFengYinHang:  'HengFeng Bank Co., Ltd', 
    guangXiShengNongCun:  'GxnxDebitQuickPay', 
    guangXiBeiBuWan:  'Guangxi Beibu Gulf Bank', 
    jiLinYinHang:  'Bank of Jilin Co.，Ltd', 
    qingDaoYinHang:  'Bank of Qingdao Co.，Ltd', 
    shenZhenNongShangYin:  'Shenzhen Rural Commercial Bank', 
    dongWanYinHang:  'Bank of Dongguan', 
    guangDongShengNongCun:  'Guangzhou Rural Commercial Bank', 
    zheShangYinHang:  'China Zheshang Bank Co.,Ltd', 
    haErBinYinHang:  'Harbin BANK', 
    shangHaiYinHang:  'Bank of Shanghai Co.,Ltd', 
    nanJingYinHang:  'Bank of Nanjing Co., Ltd.', 
    jiangSuYinHang:  'Bank of Jiangsu Co.,Ltd.', 
    hangZhouYinHang:  'Bank of Hangzhou Co.,Ltd', 
    changShaYinHang:  'Bank of Changsha Co., Ltd.', 
    guangZhouYinHang:  'Bank of Guangzhou', 
    beiJingYinHang:  'Bank of Beijing Co., Ltd', 
    ningBoYinHang:  'Bank of Ningbo Co., Ltd.', 
    huaXiaYinHang:  'Hua Xia Bank Co.,limited', 
    youZhengYinHang:  'Postal Savings Bank of China Co., Ltd', 
    zhongXinYinHang:  'China CITIC Bank International Limited', 
    xingYeYinHang:  'Industrial Bank Co., Ltd', 
    pingAnYinHang:  'Ping an Bank Co., Ltd.', 
    minShengYinHang:  'China Minsheng Banking Corp.,Ltd.', 
    puFaYinHang:  'Shanghai Pudong Development Bank Co., Ltd.', 
    guangDaYinHang:  'China Everbright Bank Co., Ltd', 
    guangFaYinHang:  'China Guangfa Bank', 
    jiaoTongYinHang:  'Bank of Communications Co., Ltd.', 
    zhongGuoYinHang:  'Bank of China', 
    nongYeYinHang:  'Agricultural Bank of China Limited', 
    jianSheYinHang:  'China Construction Bank Corporation', 
    gongShangYinHang:  'Industrial and Commercial Bank of China Limited', 
    zhaoShangYinHang:  'China Merchants Bank Co.,Ltd', 
    weiZhiDing:  'Unpin', 
    yiZhiDing:  'Pinned', 
    yiDongDuan:  'mobile', 
    pCDuan:  'PC', 
    anZhuo:  'Android', 
    xiaJia:  'not launched', 
    shangJia:  'launched', 
    jiSuZhuanKa:  'Fast ​​transfer card', 
    daiKeQuDao:  'agency channel', 
    yingYongQuDao:  'applicable channel', 
    daEQuDao:  'large amount channel', 
    puTongQuDao:  'normalt channel', 
    daiShenHe:  'to be audit', 
    yiShenHe:  'audited', 
    puTongChongZhi:  'normal deposit', 
    daiKeChongZhi:  'Top up on behalf of others', 
    daECunKuan:  'large amount deposit', 
    puTongCunKuan:  'normal deposit', 
    caiWuXinXi:  'Financial Information', 
    quKuanCiShu:  'Withdrawal times', 
    quKuanZongE:  'Total Withdrawal', 
    cunKuanCiShu:  'Deposit times', 
    cunKuanZongE:  'total deposit', 
    pingTaiYuE:  'Platform balance', 
    shengYuXinYongE:  'remaining credit limit', 
    shenHeZhong:  'auditing', 
    tiaoZhengEDu:  'adjust the amount', 
    keTiXianEDu:  'Withdrawable amount', 
    dongJieJinE:  'frozen amount', 
    zhuanZhang:  'transfer', 
    tiaoZhengHouEDu:  'The adjusted amount is', 
    dangQianEDu:  'current quota', 
    tiaoZhengKeTiXian:  'Adjust the amount that can be withdrawn', 
    zuiGaoKeZhuan:  'Maximum transferable', 
    yiFaFang:  'released', 
    yiJuJue:  'rejected', 
    zhengZaiJieSuan:  'is being settle', 
    weiDaBiao:  'not meet the requirement', 
    yingFaFang:  'should be issued', 
    leiJiWeiFaFang:  'Cumulative undistributed', 
    fanLiBiLi:  'Rebate ratio', 
    huiYuanDaiChongZong:  'toal amount top-up on behalf of others by customer service', 
    jianJieSuoDing:  'indirect locking', 
    wanQuanSuoDing:  'totally locked', 
    zhengChang:  'normal', 
    zhangHaoZhuangTai:  'account status', 
    shouXuFeiFangAn:  'processing fee plan', 
    jieSuanYueFen:  'Billing month', 
    yongJinXinXi:  'Commission information', 
    zhuCeXinXi:  'registration message', 
    shangCiDengLuShi:  'Last Login Time', 
    zhuCeDuan:  'Register side', 
    zhuCeDiZhi:  'Registered address', 
    zhuCeIP:  'register IP', 
    shouHuoXinXi:  'delivery information', 
    cengYongKaXinXi:  'Previously used card information', 
    yinHangKaXinXi:  'bank card information', 
    zhongZhiYinHangKa2:  'reset bank card', 
    diZhi:  'address', 
    shouHuoRen:  'Receiver', 
    shanChuShiJian:  'delete time', 
    fenXingDiZhi:  'branch address', 
    kaHao:  'card number', 
    chiKaRenXingMing:  'Cardholder's Name', 
    yinHangMingCheng:  'bank name', 
    bangDingShiJian:  'binding time', 
    shanChu:  'delete', 
    bangKa:  'binding card', 
    jiBenXinXi:  'Basic Information', 
    gaiYongHuYiYou:  'This user already has unaudited actions', 
    gongXiNiJieSuo:  'Congratulations, you have successfully unlocked the level', 
    gongXiNiSuoDing:  'Congratulations, you have successfully locked the level', 
    bianGengShangJiDai:  'The change of the superior affiliate is under review, please be patient!', 
    xiuGaiDaiLiLei:  'Modifying the affiliate type under audit, please be patient!', 
    gongXiNiXiuGai:  'Congratulations, you have successfully modified the user level', 
    xiuGai:  'modify', 
    qingXuanZeDaiLi:  'Please select an affiliate type', 
    daiLiLeiXing:  'affiliate type', 
    cengJiSuoDing:  'level lock', 
    qingXuanZeCengJi:  'Please select a level', 
    zhangHaoZhuangTai2:  'account status', 
    qingShuRuYouXiang:  'Please input the email address', 
    youXiang:  'email', 
    qingShuRuShouJi:  'Please input the phone number', 
    shouJiHaoMa:  'phone number', 
    chuShengRiQi:  'date of birth', 
    xingBie:  'sex', 
    suoDing:  'lock', 
    jieSuo:  'unlock', 
    baoCun:  'save', 
    bangDingQianBaoDi:  'Bind wallet address', 
    qianBaoXieYi:  'wallet protocol', 
    qianBaoBieMing:  'wallet alias', 
    qianBaoDiZhi:  'wallet address', 
    caoZuoShiJian:  'operating time', 
    tuiGuangXinXi:  'promotional information', 
    pREVZhuan:  '{val1} transfer to member account permissions is under audit, please be patient!', 
    guanBi:  'close', 
    kaiQi:  'open', 
    pREVXiang:  '{val1} is auditing the authority to transfer funds to the subordinate affiliate, please be patient!', 
    pREVChuang:  '{val1} is under audit for creating an affiliate, please be patient!', 
    pREVHui:  '{val1} Members top-up on behalf of others permissions are under audit, please be patient!', 
    bianGengShouXuFei:  'The change of processing fee plan is under audit, please be patient!', 
    fORMA:  '{val1})}people', 
    xiaJiDaiLiSan:  'Subordinate affiliate (level 3)', 
    xiaJiDaiLiEr:  'Subordinate affiliate (level 2)', 
    xiaXianHuiYuan:  'downline member', 
    anQuanMiMa:  'Security Code', 
    zhuanZhangDaoHuiYuan2:  'Transfer to member account:', 
    xiangXiaJiDaiLi:  'Transfer to sub-affiliate:', 
    xinJianXiaJiDai2:  'Create a new sub-affiliate:', 
    huiYuanDaiChong2:  'Top up on behalf of others by member', 
    daiLiQuanXianKong:  'Affiliate Authority Control', 
    qingXuanZeShouXu:  'please select a processing fee plan', 
    xiaQi:  'next period', 
    xiaYue:  'next month', 
    benQi:  'this period', 
    benYue:  'this month', 
    caoZuoDuan:  'Operation side', 
    daoZhangShiJian:  'received time', 
    dingDanZhuangTai:  'order status', 
    shouKuanRen:  'payee', 
    shouKuanYinHang:  'Beneficiary Bank', 
    chongZhiShangHu:  'Deposit Merchant', 
    chongZhiFangShi:  'Deposit method', 
    daoZhangJinE:  'Receipt amount', 
    shouXuFei:  'processing fee', 
    chongZhiDanHao:  'deposit order', 
    chongZhiShiJian:  'Deposit times', 
    qingShuRuChongZhi:  'Please enter the deposit order number', 
    erShenGeZhi:  'second audit on hold', 
    caoZuoHou:  'after operate', 
    caoZuoQian:  'before operate', 
    caoZuoXiangMu:  'operate project', 
    caoZuoRen:  'Operator', 
    caoZuoIPDi:  'Operating IP address', 
    liuLanQiBanBen:  'browser version', 
    sheBeiHao:  'device number', 
    dengLuSheBei:  'login device', 
    dengLuWangZhi:  'Login URL', 
    iPDiZhi:  'IP address', 
    qingShuRuSheBei:  'Please enter the device number', 
    qingShuRuDengLu:  'Please enter the login URL', 
    qingShuRuIP:  'Please enter the IP address', 
    dengLuShiJian:  'login time', 
    qingXuanZeTiJiao:  'Please select a submission time', 
    chuLiZhong:  'Processing', 
    chaoShiWeiQueRen:  'The account has not been confirmed after timeout', 
    daiQueRenDaoZhang:  'To be confirm receive', 
    chengGong:  'sucessful', 
    daiChuLi:  'To be processed', 
    shenHeJuJue:  'Audit Rejected', 
    shenHeTongGuo:  'Audit Approval', 
    chuKuanShiJian:  'payment time', 
    yinHangKaHao:  'bank card number', 
    chuKuanShangHu:  'Payment Merchant', 
    chuKuanJinE:  'payment amount', 
    tiXianDanHao:  'withdrawal order number', 
    tiXianShiJian:  'Withdrawal times', 
    qingShuRuTiXian:  'Please enter the withdrawal order number', 
    tian:  '30 days', 
    tian2:  '7 days', 
    zuoRi:  'yesterday', 
    jinRi:  'today', 
    taoLiChaXun:  'Arbitrage query', 
    bianGengJiLu:  'change log', 
    jiaoYiMingXi:  'Transaction details', 
    tiXianJiLu:  'Withdrawals record', 
    chongZhiJiLu:  'deposit record', 
    geRenZhongXin:  'personal center', 
    buKeChaoGuoWei:  'Cannot exceed 45 characters', 
    qingShuRuShenHe:  'Please enter audit remark', 
    wuXiaoDingDanShu:  'Number of invalid orders', 
    youXiaoDingDanShu:  'Number of valid orders', 
    huiYuanZhangHao:  'member account', 
    zuiHouXiaZhuShi:  'last bet time', 
    youXiaoHuiYuanXiang:  'Active member details', 
    xiaJiHuiYuanYong:  'subordinate member commission', 
    yongJin:  'commission', 
    yongJinBiLi:  'Commission rate', 
    gongSiJingShuYing:  'Company win/loss', 
    leiJiShangYue:  'Cumulative last month', 
    chengBenZongJi:  'total cost', 
    tiKuanShouXuFei:  'Withdrawal processing fee', 
    cunKuanShouXuFei:  'deposit processing fee', 
    zongJi:  'total', 
    chengBenFeiYong:  'cost', 
    xiangMu:  'project', 
    xiaJiDaiLiYong:  'Sub-affiliate commission', 
    moShi:  'mode', 
    zhiShuDaiLiShu:  'Number of direct affiliates (effective / total)', 
    fanYongTEX:  'Rebate{val1}%', 
    daiLiZhangHuMing:  'affiliate account name', 
    xiaJiDaiLiYong2:  'Total sub-affiliate commission', 
    youXiaoXiaJiDai:  'Total number of effective sub-affiliates (valid/total)', 
    yueFen:  'month', 
    gongSiZongShuYing:  'Total company win and loss', 
    gongSiZongYingLi:  'Total profit of the company', 
    wanJiaDuiZhanGong:  'PvP company commission', 
    pingTaiZuoZhuangGong:  'The platform as Banker the company win and lose', 
    youXiPingTai:  'gaming platform', 
    jieSuanZhuangTai:  'settlement status', 
    shiJiHeJiFa:  'Actual Total Issued', 
    leiJiaShangYue:  'cumulative last month', 
    fanShui:  'rebate', 
    youXiaoXiaJiDai2:  'The total number of effective sub-affiliates', 
    youXiaoHuiYuan:  'valid member', 
    fanYongFangAn:  'commission rebate scheme', 
    yongJinFangAn2:  'commission scheme', 
    qingShuRu:  'please enter', 
    qingXuanZeShenHe:  'Please select an audit status', 
    qingXuanZeYongJin:  'Please select a commission plan', 
    qingXuanZeChaXun:  'Please select the range of inquiry', 
    iTEMU:  '{val1} {val2}', 
    shuLiangUNI:  'quantity：{val1}', 
    daiLiXianTongJi:  'Affiliate Line Statistical Overview', 
    jieSuanDanGaiYao:  'Statement Summary', 
    fanHuiShouYe:  'back to home', 
    yongJinJieGou:  'commission structure', 
    paiFaYongJinZhan:  'Distribution commission ratio', 
    ciDaiLiWuYong:  'This affiliate has no commission', 
    wuShuJuZhanShi:  'No data display', 
    wu:  'none', 
    erShenBeiZhu:  'second audit remark：', 
    yiShenBeiZhu:  'first audit remark：', 
    daiLiXingMing:  'affiliate name', 
    shouXuFeiFangAn2:  'processing fee plan type', 
    yongJinJieSuanDan:  'Commission statement number', 
    zhangHuZhuangTaiZan:  'Account Status None', 
    quanBuLieBiao:  'all list', 
    daiShenHeLieBiao:  'pending audit list', 
      zhuDangGongSiJing: '注：当公司净输赢为负数时候（会员盈利），佣金比例默认为0%',
    pinMingWeiNinJia:  '...desperately loading details data for you', 
    xiangQing:  'detail', 
    qingXuanZeCaoZuo:  'Please select operation data', 
    tEXTXiu:  '{val1}ᅳModification failed {val2}', 
    uSERN:  '{val1}ᅳ{val2}ᅳcommission{val3}ᅳ{val4}', 
    tEXTU:  '{val1}-{val2}', 
    caoZuoShiBai:  'Modify failed', 
    qingShuRuCU:  'Please enter {val1}', 
    qingShuRuDaiLi:  'Please enter the affiliate account name', 
    yiShenTongGuo:  'Passed the first audit', 
    weiShenHe:  'not audited', 
    bianJiZiLiao:  'edit information', 
    tongBuChengGong:  'Synchronization succeeded', 
    qingShuRuBeiZhu:  'Please enter a remark', 
    zhiHangDiZhi:  'Branch address', 
    bangDingYinHangKa:  'Bind bank card', 
    bangDingYinHangKa2:  'Binding bank card under audit, please be patient!', 
    heJi:  'total：', 
    fenPeiBaiFenBi2:  'Allocation percentage:', 
    benJi:  '(this level)', 
    zongYongJinBiLi:  'Total commission ratio:', 
    qingXuanZeHuiYuan:  'Please select a member rebate program', 
    huiYuanFanYongFang2:  'Member rebate program:', 
    chouYongBaiFenBi2:  'Commission Percentage:', 
    sheZhiYongJinLian:  'set up commission chain', 
    yongJinLianMoShi2:  'Commission chain mode', 
    yongJinLianSheZhi:  'commission chain setting', 
    weiFenPeiYongJin:  'Unallocated commission ratio {val1}%', 
    heJiBuNengChao:  'total cannot exceed {val1}%', 
    qingXianShuRuZong:  'Please enter the total ratio first', 
    xiuGaiYongJinFang:  'The change of the commission plan is under audit, please be patient!', 
      daHuaTou: '大话骰',
    lanFangBLU:  'Blue team：{val1}<br/>Red team{val2}', 
    huanLeDouNiu:  'Fun cow fight', 
    xia:  'down：', 
    zhong:  'middle：', 
    shang:  'up：', 
    shiSanShui:  'shisanshui', 
    zhuang:  'banker：', 
    huang:  'huang：', 
    xuan:  'xuan：', 
    di:  'di：', 
    tian3:  'tian：', 
    baiRenNiuNiu:  '100 Cow', 
      wanJiaPLA: "玩家：{val1}{val2}` : ''\n        }",
    xingYunDian:  'lucky blackjack', 
    paiJiu:  'pai jiu', 
    qiangZhuangPaiJiu:  'Grab the banker pai jiu', 
    maJiang:  'mahjong', 
    erBaGang:  'two eight kong', 
    pinSanZhang:  'spell three', 
    qiangZhuangDian:  'Grab the banker blackjack', 
    deZhou:  'poker2+3', 
    xingYunWuZhang:  'lucky five pieces', 
    jingDianNiuNiu:  'classic cow', 
    kanPaiQiangZhuang:  'check the card grab banker', 
    sanGong:  'three Gong', 
    zhaJinHua:  'boom golden flower', 
    tongBiNiuNiu:  'Bi Niu Niu', 
    qiangZhuangSanZhang:  'grab banker three cards', 
    qiangZhuangNiuNiu:  'grab banker niu niu', 
    erSi:  'two four', 
    dingSan:  'ding three', 
    zaWu:  'mix five', 
    zaQi:  'mix seven', 
    zaBa:  'mix eight', 
    zaJiu:  'mix nine', 
    lingLinLiu:  'zero lin six', 
    gaoJiaoQi:  'tall seven', 
    hongTouShi:  'red head ten', 
    fuTou:  'chopper', 
    banDeng:  'bench', 
    changSan:  'long three', 
    meiPai:  'plum bossom card', 
    ePai:  'Goose card', 
    renPai:  'people card', 
    diPai:  'earth card', 
    tianPai:  'heaven card', 
    baiBan:  'White Dragon', 
    tong:  'nine dot', 
    tong2:  'eight dot', 
    tong3:  'seven dot', 
    tong4:  'six dot', 
    tong5:  'five dot', 
    tong6:  'four dot', 
    tong7:  'three dot', 
    tong8:  'two dot', 
    tong9:  'one dot', 
    fangKuai:  'Diamonds', 
    meiHua:  'clubs', 
    hongTao:  'Hearts', 
    heiTao:  'Spades', 
    qiTa:  'other', 
    yinNiPeiLu:  'Indonesian odds', 
    maLaiXiYaPei:  'Malaysia odds', 
    xiangGangPeiLu:  'Hongkong odds', 
    ouZhouPeiLu:  'European Odds', 
    xianKaiQiuQiuDui:  'kick-off team', 
    hongKaDaXiaoPan:  'red card over/under', 
    gunQiuHongKaDa:  'Live red card over/under', 
    gunQiuHongKaRang:  'Live red card handicap', 
    hongKaRangQiuPan:  'red card handicap', 
    yueWeiDaXiaoPan:  'offside over/under', 
    gunQiuYueWeiDa:  'Live offside over/under', 
    gunQiuYueWeiRang:  'Live offside handicap', 
    yueWeiRangQiuPan:  'offside handicap', 
    zongJinQiuShu:  'total goals', 
    jiaoQiuDaXiaoPan:  'Corners kicks over/under', 
    gunQiuJiaoQiuDa:  'Live corners kicks over/under', 
    gunQiuJiaoQiuRang:  'Live corners kicks handicap', 
    jiaoQiuRangQiuPan:  'Corners kicks handicap', 
    deKaZongShuDa:  'The total number of cards obtained over/under', 
    gunQiuDeKaZong:  'Live total number of cards obtained over/under', 
    gunQiuDeKaZong2:  'Live total number of cards obtained handicap', 
    deKaZongShuRang:  'The total number of cards obtained handicap', 
    qiuDuiZongJinQiu:  'Total goals scored by the team', 
    gunQiuTeBieTou:  'Live special bet', 
    teBieTouZhu:  'special bet', 
    panShuBoDan:  'Correct socre betting', 
    qiuYuanZongJinQiu:  'total number of goals scored by players', 
    dianQiuDaXiaoPan:  'Penalty over/under', 
    dianQiuRangQiuPan:  'Penalty handicap', 
    daXiao:  'Over/Under', 
    guanJunTouZhu:  'Champion bet', 
    danShuang:  'Odd/Even', 
    duYing:  '1X2', 
    zuiHouJinQiuQiu:  'last goal team', 
    zuiHouJinQiuQiu2:  'last goal player', 
    gunQiuZongJinQiu:  'Live total goals', 
    gunQiuDianQiuDa:  'Live penalty shoot-out over/under', 
    gunQiuDianQiuRang:  'Live penalty shoot-out handicap', 
    gunQiuDaXiao:  'Live Over/Under', 
    gunQiuDanShuang:  'Live Odd/Even', 
    gunQiuDuYing:  'Live 1X2', 
    gunQiuBanQuanChang:  'Live Half-Time', 
    gunQiuBoDan:  'Live correct score', 
    gunQiuRangQiu:  'Live Handicap', 
    gunQiuX:  'Live 1X2', 
    banQuanChang:  'Half time', 
    zuiXianJinQiuQiu:  'Team with the most goals', 
    shouWeiJinQiuQiu:  'first goal scorer', 
    boDan:  'correct score', 
    rangQiu:  'Handicap', 
    diSanPan:  'Third section', 
    diSanJie:  'Third Quarter', 
    diLiuPan:  'sixth section', 
    diQiPan:  'seventh section', 
    diErPan:  'second section', 
    diErJie:  'Second Quarter', 
    xiaBanChang:  'second half', 
    fen:  'score', 
    baoKuoJiaShiSai:  'including extra time and penalty shoot-out', 
    shangBanChang:  'first half', 
    quanChangFenShuTou:  'full score bet', 
    quanChang:  'full court', 
    diSiPan:  'Fourth section', 
    diSiJie:  'Fourth quarter', 
    diYiPan:  'first section', 
    diYiJie:  'First quarter', 
    diWuPan:  'Fifth section', 
    diSiCiJiaShi:  'Fourth extra time', 
    diSanCiJiaShi:  'Third extra time', 
    diErCiJiaShi:  'Second extra time', 
    diYiCiJiaShi:  'First extra time', 
    qianWuJu:  'First five rounds', 
    xiao:  'under', 
    huoYiShang:  '7 or above', 
    huoYiShang2:  '3 or above', 
    da:  'over', 
    qiTa2:  'other', 
    dan:  'odd', 
    wuJinQiu:  'no goal', 
    zhuDuiJingShengQiu:  'Home team - goal difference by 5 goals or more', 
    zhuDui:  'home', 
    zhuZhu:  'home home', 
    zhuHe:  'home draw', 
    zhuKe:  'home away', 
    dongJiYunDong:  'winter sports', 
    paiQiu:  'volleyball', 
    tianJing:  'Athletics', 
    wangQiu:  'tennis', 
    pingPangQiu:  'pingpong', 
    youYong:  'swimming', 
    teBieXiangMu:  'special sport', 
    leiQiu:  'Softball', 
    siNuoKeTaiQiu:  'Snooker', 
    ganLanQiu:  'Rugby football', 
    saiChe:  'racing car', 
    gengDuoYunDong:  'more sports', 
    caiPiao:  'Lottery', 
    bingQiu:  'Ice hockey', 
    shouQiu:  'handball', 
    tiCao:  'gymnastics', 
    gaoErFuQiu:  'golf', 
    shiNeiZuQiu:  'indoor soccer', 
    jinRongTouZhu:  'financial betting', 
    quGunQiu:  'hockey', 
    dianZiJingJi:  'esport', 
    feiBiao:  'darts', 
    ziXingChe:  'bicycle', 
    banQiu:  'Cricket', 
    quanJiGeDou:  'boxing', 
    xuanMeiDaSai:  'beauty pageant', 
    shaTanPaiQiu:  'Beach Volleyball', 
    shaTanZuQiu:  'Beach football', 
    zuQiu:  'football', 
    lanQiu:  'basketball', 
    bangQiu:  'baseball', 
    yuMaoQiu:  'badminton', 
      zhuSuoShuShangJi:    '注：所属上级默认为admin，可以填写其他代理，设定后无法再次修改',
      qingShuRuSuoShu: '请输入所属上级',
    geShuZiZiMu:  '8-20 numbers/letters/special characters', 
    miMa:  'password', 
    qingShuRuYongHu:  'please enter username', 
    yongHuMing:  'username', 
    bianJiDaiLi:  'edit affiliate', 
    xinZengDaiLi:  'add affiliate', 
    fuZhiChengGong:  'Copy successfully!', 
    xinZengChengGong:  'added successfully', 
    fuZhiXinXi:  'copy message', 
    dengLuWangZhi2:  'Login URL:', 
    shouJiHaoMa2:  'phone number:', 
    dengLuMiMa:  'login password:', 
    daiLiZhangHao2:  'affiliate account：', 
    yongHuYiCunZai:  'user already exists', 
    touZhuNeiRong:  'betting content', 
    zongPeiLu:  'Total Odds', 
    xiaZhuJinE:  'bet amount', 
    panKou:  'Handicap', 
    xiaZhuNeiRong:  'bet content', 
    danChangPeiLu:  'single odds', 
    shuangFang:  'both sides:', 
    lianSai:  'the league', 
    saiShi:  'match', 
    ziYouXi:  'sub game', 
    xuHao:  'serial number', 
    qingShuRuZhangHu:  'Please enter the account name, please separate multiple account names with ","', 
    xinZengShiChangBu:  'Add marketing affiliate', 
    xinZengSEO:  'Added SEO affiliate', 
    zhuanRuJinEBu:  'The transfer amount cannot be less than 0', 
    qingShuRuZhuanRu:  'Please enter the transfer amount', 
    congZhongXinQianBao:  'Transfer from central wallet to {val1}', 
    mWBuYuBu:  '(mw fishing does not support converting to decimals)', 
    zhuanRuJinE:  'Transfer amount', 
    gaiZhangHuZhuZhang:  'The balance of the main account of this account is 0', 
    gongXiNiCaoZuo:  'Congratulations, the operation is successful', 
    shenQingXiuGaiZi:  'Apply for data modification', 
    zhangHaoBianJiShen:  'Account editing under audit, please be patient!', 
    paiChuSuoDing:  'remove lock', 
    yiGouXuanSE:  'ticked{val1}data', 
    dangQianVIP:  'Current VIP level', 
    shiFouSuoDingCeng:  'sure to lock the level', 
    qingXuanZeDengJi:  'Please select a level', 
    vIPDengJi:  'The VIP level is changed to', 
    iSMUL:  '{val1}', 
    piLiangXiuGaiV:  'Successfully modified VIP in batches', 
    xiuGaiVIP:  'Modify VIP successfully', 
    yiGuoLuDiaoV:  'Users whose VIP status is locked have been filtered out', 
    qingShuRuShenQing:  'Please enter the reason for requesting deletion, up to 45 characters', 
    shenQingShanChuYuan:  'Request for removal reason', 
    shenQingShanChuYin:  'Application to delete bank card', 
    shanChuYinHangKa:  'Deleting bank card under auditing , please be patient!', 
    qingShuRuShenQing2:  'Please enter the reason for request modification', 
    shenQingXiuGaiYuan:  'Reason for application modification', 
    shenQingZhongZhiYin:  'Apply to reset bank card', 
    zhongZhiYinHangKa3:  'Reset bank card under audit, please be patient!', 
    shuRuYongHuMing:  'Enter your username', 
    gouXuanYongHuMing:  'tick for username', 
    sELEC:  '{val1} and other {val2} accounts', 
    xiaYiBu:  'next', 
    yiXiaZhangHaoBu:  'The following accounts do not exist: {val1}', 
    yiGouXuanSE2:  'ticked{val1}data', 
    qingShuRuGE:  'Please enter {val1}', 
    jieSuoSuoDing:  'unlock', 
    yongHuKeYiDeng:  'Users can login, but cannot bet, deposit, withdraw or transfer', 
    shanChuBangDingDe:  'Delete the bound mobile phone/email', 
    yongHuWuFaDeng:  'User cannot login to the platform', 
    suoDingFangShi:  'locking method', 
    dangQianZhuangTai:  'current status', 
    ninYiChengGongFa:  'You have successfully initiated {val1} {val2} operations, please wait for audit', 
    shiBaiPiLiangU:  'Failed to batch {val1}{val2} operations, failure reason: {val3}', 
    niYiChengGongFa:  'You have successfully initiated {val1} {val2} operations, failed {val3} \n {val4} operations, failure reason: {val5}', 
    ninYiChengGongFa2:  'You have successfully initiated {val1} {val2} operations, please wait for audit', 
    uSERL:  '{val1} failed, failure reason: {val2}', 
    shenQingJieSuoYuan:  'Reason for applying for unlocking', 
    shenQingJieSuo:  'Application: Unlock', 
    shenQingSuoDingYuan:  'Application lock reason', 
    shenQingSuoDing:  'Application: locked', 
    shenQingPiLiangJie:  'Application Batch: Unlock', 
    shenQingPiLiangSuo:  'Application Batch: lock', 
    chuXianWeiZhiCuoWu:  'An unknown error occurred! error code is', 
    piLiangBeiZhu:  'Batch Remarks', 
};
