export default {
  config: {
        xiuGaiChengGong: '修改失败',
    huiTiaoDiZhiBu:  '\n ที่อยู่ติดต่อกลับ (ห้ามเว้นว่าง) ', 
    zhiFuBaoGongYao:  '\n คีย์สาธารณะของอาลีเพย์ (ห้ามเว้นว่าง) ', 
    shangHuSiYaoBu:  ' คีย์ส่วนตัวขอร้านค้า (ห้ามเว้นว่าง) ', 
    qingShuRuShangJia:  ' กรุณากรอกเลขที่บัญชีร้านค้า ', 
    qingShuRuAP:  ' กรุณากรอก appID ', 
    baoCunPeiZhi:  ' บันทึกการกำหนดค่า ', 
    zhiFuJieGuoYi:  ' ที่อยู่แจ้งผลการชำระเงินแบบอะซิงโครนัส ', 
    yiBuTongZhi:  ' การแจ้งเตือนแบบอะซิงโครนัส ', 
    dingDanWanChengHou:  ' ที่อยู่ที่ส่งกลับหลังจากการรายการเสร็จสมบูรณ์ ', 
    huiTiaoDiZhi:  ' ที่อยู่เรียกกลับมา ', 
    zhiFuBaoGongYao2:  ' คีย์สาธารณะของ Alipay ', 
    shangHuSiYaoNi:  ' คีย์ส่วนตัวของร้านค้า คีย์ส่วนตัว RSA2 ของคุณในรูปแบบ PKCS8 ', 
    shangHuSiYao:  ' คีย์ส่วนตัวของร้านค้า ', 
    shangJiaZhangHao:  ' เลขที่บัญชีร้านค้า ', 
    yingYongAPP:  ' ใช้ APPID บัญชีรับเงินต้องเป็น APPID ที่สอดคล้องกับบัญชี Alipay ', 
  },
  index: {
    zhiFuSheZhi:  ' การตั้งค่าการชำระเงิน ', 
    ruXuFuKuanCe:  '\n สำหรับการทดสอบการชำระเงิน โปรดใช้หมายเลขบัญชี: uuxesw9745@sandbox.com รหัสผ่านและรหัสผ่านการชำระเงิน: 111111 ', 
    zhiFuBaoKaiFa:  ' แพลตฟอร์มการพัฒนา Alipay ', 
    ceShiSuoYongCan:  ' พารามิเตอร์ที่ใช้ในการทดสอบคือสภาพแวดล้อมของแซนด์บ็อกซ์ทั้งหมดซึ่งมีไว้สําหรับการทดสอบเท่านั้น ที่อยู่แอปพลิเคชัน： ', 
    zhuYi:  ' ระวัง ', 
    shiYongShuoMing:  ' คำแนะนำสำหรับการใช้งาน ', 
    zhiFuCeShi:  ' การทดสอบการชำระเงิน ', 
    canShuPeiZhi:  ' การกำหนดค่าพารามิเตอร์ ', 
  },
  toPay: {
    shangPinMiaoShuBu:  ' รายละเอียดสินค้า (ห้ามเว้นว่าง) ', 
    shangPinJiaGeBu:  ' ราคาสินค้า (ห้ามเว้นว่าง) ', 
    shangPinMingChengBu:  ' ชื่อสินค้า (ห้ามเว้นว่าง) ', 
    quZhiFu:  ' ไปที่การชำระเงิน ', 
    shangPinMiaoShu:  ' รายละเอียดสินค้า ', 
    ceShiYunXuQu:  ' ช่วงทดสอบที่อนุญาต(0,5000] ', 
    shangPinJiaGe:  ' ราคาสินค้า ', 
    shangPinMingCheng:  ' ชื่อสินค้า ', 
  },
};
