export default {
  index: {
    qingShuRuBuShu:  '\n โปรดป้อนสคริปต์การปรับใช้ \n', 
    qingShuRuQiDong:  ' โปรดป้อนสคริปต์เริ่มต้น ', 
    qingShuRuBeiFen:  ' โปรดป้อนโฟลเดอร์สำรอง ', 
    qingShuRuBuShu2:  ' โปรดป้อนโฟลเดอร์การปรับใช้ ', 
    qingShuRuShangChuan:  '\n โปรดป้อนอัปโหลดโฟลเดอร์ ', 
              yingYong:  ' แอปพลิเคชัน ', 
    caoZuo:  ' การดำเนินการ ', 
         beiFenMuLu:  ' โฟลเดอร์สำรอง ', 
    buShuMuLu:  ' โฟลเดอร์การปรับใช้ ', 
    shangChuanMuLu:  ' อัปโหลดโฟลเดอร์ ', 
    duanKouHao:  ' หมายเลขพอร์ต ', 
                   qiDongJiaoBen:  ' เริ่มสคริปต์ ', 
    buShuJiaoBen:  ' สคริปต์การปรับใช้ ', 
    liRuOPT:  ' ตัวอย่าง: /opt/backup ', 
    liRuOPT2:  ' ตัวอย่าง: /opt/app ', 
    liRuOPT3:  ' ตัวอย่าง: /opt/upload ', 
    liRu:  ' ตัวอย่าง: 8080 ', 
    yingYongDuanKou:  ' พอร์ตแอปพลิเคชัน ', 
    buShuHouDeWen:  ' ชื่อของไฟล์หรือโฟลเดอร์ที่จะใช้สำหรับการสำรองข้อมูลหลังการปรับใช้ ', 
    fuZhi:  ' คัดลอก ', 
    jieShuRiQi:  ' วันที่สิ้นสุด ', 
    kaiShiRiQi:  ' วันที่เริ่มต้น ', 
    shuRuMingChengSou:  ' ป้อนชื่อเพื่อค้นหา ', 
  }
}
