export default {
    gangWeiLeiBie:  'job category', 
    tiJiao:  'submit', 
    bianJiZhangHao:  'edit account', 
    xinJianZhangHao:  'create new account', 
    qingShuRuDaiLi:  'Please enter the aff, please use "," to separate multiple account names', 
    shuRuDaiLi:  'enter affiliate', 
    keJianDaiLi:  'visible affiliate', 
    youXiaoShiJian:  'Effective time', 
    zhangHaoYouXiaoQi:  'account validity period', 
    qingXuanZeGangWei:  'Please select a job category', 
    qingShuRuMiMa:  'please enter password', 
    gongXiNinBianJi:  'Congratulations, you have successfully edited your account', 
    gongXiNinXinZeng:  'Congratulations, you have successfully added an account', 
    shenFenMa:  'identity verification', 
    shenFenYanZhengMa:  'identity verification', 
    gongXiNiFuZhi:  'Congratulations, the copy is successful', 
    zhongZhiShenFenYan:  'reset identity verification', 
    beiZhuROW:  'remark：{val1}', 
    gangWeiMingCheng:  'position name', 
    buMenMingCheng:  'department name', 
    xinJianShiJian:  'create time', 
    qingShuRuZhangHao:  'please enter account', 
    yunWeiGuanLiXi:  'Ops management system', 
    kaiQiZhangHao:  'turn on account', 
    gongXiCaoZuoCheng:  'Congratulations, the operation is successful~', 
    queDingYaoOP:  'Are you sure you want the login permission of {val1}?', 
    kaiQiBuMen:  'turn on department', 
    kaiQiGangWei:  'turn on position', 
    suoDingBuMen:  'locked department', 
    suoDingGangWei:  'locked position', 
    suoDingZhangHao:  'locked account', 
    kaiQiCiBuMen:  'turn on this department', 
    kaiQiCiGangWei:  'turn on this position', 
    suoDingCiBuMen:  'locked this department', 
    suoDingCiGangWei:  'locked this position', 
    suoDingCiZhangHao:  'locked this account', 
    caoZuoChengGong:  ', the operation was successful~', 
    xiTongQuanXian:  'system authority', 
    qingXuanZeXiTong:  'Please select a system icon', 
    xiTongTuBiao:  'system icon', 
    qingXuanZeXiTong2:  'Please select a system description', 
    xiTongMiaoShu:  'system description', 
    qingShuRuXiTong:  'Please enter a system name', 
    xiTongMingCheng:  'system name', 
    chuangJianYeWuXi:  'Create business system/manage business system', 
    qingGouXuanXiTong:  'Please tick the system permissions!', 
    xinHuaiDaXiangFa:  'Think Big, Have Little Fortune', 
    chengGongJiuShiRi:  'Success is the accumulation of hard work day after day', 
    tianShiBuRuDi:  'The time isn't as important as the terrain; but the terrain isn't as important as unity with the people.', 
    yunWeiDeShiJie:  'The world of OPS is like an ancient clock, ticking', 
    shengMingJiuXiangYi:  'Life is like a box of chocolates, the results are often unexpected', 
    shuJuJiuXiangYi:  'Data is like a magic book, all skills can be obtained happily here', 
    guiHuaDeMuDi:  'The purpose of planning is to achieve goals faster and more efficiently', 
    dangFengXianLaiLin:  'When the risk comes, face it with a smile and solve it with wisdom', 
    guanLiXiTongQuan:  'Manage System Authorised', 
    zuiHouXiuGaiShi:  'Last Modified Time', 
    qingQiuZuiXinCai:  'request latest menu', 
    gongXiNiQingQiu:  'Congratulations, the request for the latest menu is successful!', 
    houTaiZhangHaoGuan:  'Backend account management', 
    houTaiGangWeiQuan:  'Backend post permissions', 
    yunWeiXiTong:  'OPS system', 
    yongHuXiTong:  'user system', 
    shuJuXiTong:  'data system', 
    fengKongXiTong:  'Risk control system', 
    yunYingXiTong:  'operating system', 
    caiWuXiTong:  'Financial System', 
    neiBuDaiLi:  'internal affiliate', 
    zhanKai:  'expand', 
    quanXuan:  'all', 
    shouHuoDiZhi:  'Shipping address', 
    shuJuQuanXian:  'data permission:', 
    shuJuKeJian:  'The data can be seen at:', 
    gangWeiQuanXianShe:  'Post permission settings ({val1})', 
    gongXiNinCaoZuo:  'Congratulations, the operation is successful!', 
    fuZhiQuanXian:  'Copy permission', 
    gangWeiMa:  'position?', 
    queDingJiangXuanZhong:  'confirm copy the selected post permissions to', 
    fuZhiChengGong:  'Copy successfully~', 
    feiBiXuanMoRen:  'Not required, all unchecked by default, you can view all information after checking', 
    zuiJinDengLu:  'recently logged in', 
    chengYuanGuanLi:  'member management', 
    pOSTI:  '{val1}remark：', 
    pOSTJ:  '{val1}remark：', 
    qingShuRuGangBei:  'Please enter post remarks:!', 
    beiZhu:  'remark：', 
    qingShuRuGangWei:  'Please enter the job title!', 
    gangWeiMingChengI:  'Position title {val1}', 
    qingShuRuBeiZhu:  'Please enter a remark', 
    gangWeiMingChengN:  'Position title 0&nbsp;', 
    qingShuRuBeiZhu2:  'Please enter a remark:!', 
    qingShuRuBuMen:  'Please enter a department name!', 
    buMenMingCheng2:  'Department name:', 
    bianJiBuMen:  'edit department', 
    xinZengBuMenGang:  'Add new department/post', 
    gongXiCaoZuoCheng2:  'Congratulations, the operation is successful~', 
    beiZhuNAM:  '{val1}remark：', 
    gangWeiQuanXianShe2:  'Post permission setting', 
    gangWeiQuanXianShe3:  'Post permission setting ({val1})', 
    gaiYeMianZanWu:  'There is no query plan for this page', 
    gaiYeMianZanWu2:  'There is no query plan setting on this page', 
    zhuYi:  'attention', 
    renXuanQiYiCha:  'choose one to query', 
    biTianChaXunTiao:  'Required query conditions', 
    yunXuChaXunTiao:  'Allow query conditions', 
    lieBiaoShiFouLei:  'Is it the list cumulative', 
    chaXunShiJianFan:  'query time range', 
    yeMianQuanXianShe:  'Page permission settings ({val1}/{val2} - {val3})', 
    weiHuDengJi:  'maintenance level', 
    hao:  'No. 68', 
    chuangJianShiJian:  'creation time', 
    hao2:  'No. 68', 
    tYPEGuan:  '{val1}related no.68', 
};
