export default {
  addAwake: {
    sCEEN:  ' [{val1}] เชื่อมโยงกับ [{val2}]! ', 
    bianJiChengGong:  ' แก้ไขสำเร็จ! ', 
         qingXuanZeGuanLian:  ' โปรดเลือกกลุ่มทักษะที่เกี่ยวข้อง ', 
    qingXuanZeHuanXing:  ' โปรดเลือกสถานการณ์ปลุก ', 
              beiZhu:  ' หมายเหตุ ', 
    ruoYouDuoGeYe:  ' หากมีหลายหน้า โปรดใช้ ', 
    huanXingYeMian:  ' หน้าปลุก ', 
         guanLianJiNeng:  ' ทักษะที่เกี่ยวข้อง ', 
    huanXingChangJing:  ' หน้าปลุก ', 
    huanXingID:  ' ไอดี ปลุก ', 
  },
  awakenIndex: {
              shuoMingRuGuoShang:  ' หมายเหตุ: หากร้านค้าเรียก ID นี้ ลูกค้าจะเข้าสู่หน้าสอบถามก่อนหน้าโดยตรงหลังจากการลบ ', 
         shanChuHuanXingChang:  ' ลบหน้าปลุก ', 
    tianJiaHuanXingChang:  ' เพิ่มหน้าปลุก ', 
    bianJiHuanXingChang:  ' แก้ไขหน้าปลุก ', 
    huanXingChangJingLie:  ' รายการหน้าปลุก ', 
              caoZuo:  ' การดำเนินการ ', 
         suoYouJiNengZu:  ' กลุ่มทักษะทั้งหมด ', 
    suoYouHuanXingChang:  ' หน้าปลุกทั้งหมด ', 
    suoYouHuanXingI:  ' ไอดี หน้าปลุกทั้งหมด ', 
  },
};
