export default {
  addAwake: {
    sCEEN: "[{val1}] เชื่อมโยงกับ [{val2}]!", 
    bianJiChengGong: "แก้ไขสำเร็จ!", 
    tianJiaChengGong: "เพิ่มสำเร็จ!", 
    qingXuanZeGuanLian: "โปรดเลือกกลุ่มทักษะที่เกี่ยวข้อง", 
    qingXuanZeHuanXing: "โปรดเลือกสถานการณ์ปลุก", 
    queRen: "ยืนยัน", 
    quXiao: "ยกเลิก", 
    beiZhu: "หมายเหตุ", 
    ruoYouDuoGeYe: "หากมีหลายหน้า โปรดใช้", 
    huanXingYeMian: "หน้าปลุก", 
    qingXuanZeJiNeng: "กรุณาเลือกกลุ่มทักษะ", 
    guanLianJiNeng: "ทักษะที่เกี่ยวข้อง", 
    huanXingChangJing: "หน้าปลุก", 
    huanXingID: "ไอดี ปลุก", 
  },
  awakenIndex: {
    shanChuChengGong: "ลบสำเร็จแล้ว", 
    queDing: "ยืนยัน", 
    shuoMingRuGuoShang: "หมายเหตุ: หากร้านค้าเรียก ID นี้ ลูกค้าจะเข้าสู่หน้าสอบถามก่อนหน้าโดยตรงหลังจากการลบ", 
    ninQueDingShanChu: "คุณแน่ใจหรือไม่ที่จะลบบันทึกของ [{val3}] ที่เชื่อมโยงกับ [{val1} (ID{val2})]", 
    shanChuHuanXingChang: "ลบหน้าปลุก", 
    tianJiaHuanXingChang: "เพิ่มหน้าปลุก", 
    bianJiHuanXingChang: "แก้ไขหน้าปลุก", 
    huanXingChangJingLie: "รายการหน้าปลุก", 
    shanChu: "ลบ", 
    bianJi: "แก้ไข", 
    caoZuo: "การดำเนินการ", 
    tianJia: "เพิ่ม", 
    suoYouJiNengZu: "กลุ่มทักษะทั้งหมด", 
    suoYouHuanXingChang: "หน้าปลุกทั้งหมด", 
    suoYouHuanXingI: "ไอดี หน้าปลุกทั้งหมด", 
  },
};
