export default {
  index: {
        quXiao: '取消',
    queDing: "ยืนยัน", 
    jieChuYongHuHei: "ปลดบล็อกรายการบัญชีผู้ใช้", 
    queDingJiangGaiYong: "ยืนยันเพื่อยกเลิกการบล็อกผู้ใช้รายนี้ {val1}?", 
    puTongKeHu: "ลูกค้าทั่วไป", 
    fou: "ไม่", 
    shi: "ใช่", 
    xingMing: "ชื่อ", 
    keHuZhangHuMing: "ชื่อบัญชีลูกค้า", 
    gengXinRiQi: "วันที่อัปเดต", 
    chuangJianRiQi: "วันที่สร้าง", 
    heiMingDan: "บล็อก", 
    jieJin: "ปลดบล็อก", 
    xiangQing: "รายละเอียด", 
    caoZuo: "การดำเนินการ", 
    chuangJianGengXinRi: "วันที่สร้าง/อัปเดต", 
    laHeiLeiXing: "ประเภทบล็อก", 
    keHuFenZu: "กลุ่มลูกค้า", 
    vIPJiBie: "ระดับ VIP", 
    keHuDengJi: "ระดับลูกค้า", 
    shiFouXinKeHu: "ใช่ลูกค้าใหม่หรือไม่", 
    jieShuRiQi: "วันที่สิ้นสุด", 
    kaiShiRiQi: "วันที่เริ่มต้น", 
    qingShuRuSouSuo: "กรุณากรอกเนื้อหาการค้นหา", 
  },
};
