export default {
  setFunction: {
    zhiNengXiuGaiCheng: "แก้ไขฟังก์ชันเรียบร้อยแล้ว", 
    zhiNengBuNengWei: "ฟังก์ชัน (ห้ามเว้นว่าง)", 
    qingXuanZeZhiNeng: "กรุณาเลือกฟังก์ชั่น", 
    qingXianXuanZeZhi: "กรุณาเลือกฟังก์ชั่นก่อน", 
    xiuGaiZhiNeng: "แก้ไขฟังก์ชั่น", 
  },
  updateEmail: {
    huoQuYanZhengMa: "รับรหัสยืนยัน", 
    youXiangXiuGaiCheng: "แก้ไขอีเมลเรียบร้อยแล้ว", 
    chongXinFaSong: "ส่งใหม่อีกครั้ง", 
    miaoHouChongXinFa: "ส่งอีกครั้งในไม่กี่วินาที", 
    faSongChengGongYan: "ส่งสำเร็จ รหัสยืนยันมีอายุ 5 นาที", 
    yanZhengMaFaSong: "กำลังส่งรหัสยืนยัน", 
    yanZhengMaBuNeng: "รหัสยืนยัน (ห้ามเว้นว่าง)", 
    dangQianMiMaBu: "รหัสผ่านปัจจุบัน (ห้ามเว้นว่าง)", 
    xiuGaiYouXiang: "แก้ไขอีเมล", 
    youXiangGeShiCuo: "ข้อผิดพลาดของรูปแบบอีเมล", 
    xinYouXiangBuNeng: "อีเมลใหม่ต้องไม่เหมือนกับอีเมลเก่า", 
    xinYouXiangBuNeng2: "อีเมลใหม่ (ห้ามเว้นว่าง)", 
    dangQianMiMa: "รหัสผ่านปัจจุบัน", 
    yanZhengMa: "รหัสยืนยัน", 
    xinYouXiang: "อีเมลใหม่", 
  },
  updatePass: {
    miMaXiuGaiCheng: "เปลี่ยนรหัสผ่านสำเร็จ กรุณาเข้าสู่ระบบอีกครั้ง", 
    weiYiShangMiMa: "รหัสผ่านมากกว่า 8-20 ตัว ประกอบด้วยตัวเลขและตัวอักษรอย่างน้อย 2 ชนิด ห้ามมีภาษาจีนและเว้นวรรค", 
    weiShuZiZiMu: "8-20 ตัว ประกอบด้วยตัวเลขและตัวอักษรอย่างน้อย 2 ชนิด ห้ามมีภาษาจีนและเว้นวรรค", 
    qingShuRuXinMi: "กรุณาใส่รหัสผ่านใหม่", 
    qingShuRuJiuMi: "กรุณาใส่รหัสผ่านเก่า", 
    qingShuRuZhangHu: "กรุณาใส่ชื่อบัญชี", 
    xinMiMaBuNeng: "รหัสผ่านใหม่ต้องไม่เหมือนกับรหัสผ่านเริ่มต้น", 
    qingZaiCiShuRu: "กรุณาใส่รหัสผ่านอีกครั้ง", 
    liangCiShuRuDe: "รหัสผ่านที่ป้อนสองครั้งไม่ตรงกัน", 
    queRenMiMa: "ยืนยันรหัสผ่าน", 
    xinMiMa: "รหัสผ่านใหม่", 
    chuShiMiMa: "รหัสผ่านเริ่มต้น", 
    yuanZhangHuMiMa: "รหัสผ่านบัญชีเดิม", 
    zhangHu: "บัญชี", 
    weiLeNinDeZhang: "เพื่อความปลอดภัยในบัญชีของคุณ โปรดเปลี่ยนรหัสผ่านเข้าสู่ระบบของคุณ คุณจะต้องเข้าสู่ระบบอีกครั้งหลังจากการเปลี่ยนแปลงเสร็จสิ้น", 
    xiuGaiMiMa: "เปลี่ยนรหัสผ่าน", 
    xiuGaiZhangHuHe: "แก้ไขบัญชีและรหัสผ่าน", 
  },
};
