export default {
  index: {
    xiangYingCuoWuQing:  ' เกิดข้อผิดพลาดในการตอบกลับ โปรดลองอีกครั้งในภายหลัง! ', 
    feiTiaoZhuan:  ' ไม่สามารถโดดข้าม ', 
    weiJieJue:  ' ยังไม่ได้แก้ไข ', 
    yiJieJue:  ' แก้ไขแล้ว ', 
                   keFuZhuanJie:  ' การโอนบริการลูกค้า ', 
    yaoQingHuiHua:  ' เชิญบทสนทนา ', 
    ziDongFenPei:  ' การจัดสรรอัตโนมัติ ', 
    paiDuiLiKai:  ' คิวที่จะออก ', 
    paiDuiJinRu:  ' เข้าคิว ', 
    weiPaiDui:  ' ไม่มีคิว ', 
    fou:  ' ไม่ ', 
         zhiJianRenZhiJian:  ' คนตรวจสอบ/เวลาตรวจสอบ ', 
         keFuZongJie:  ' สรุปผลการบริการลูกค้า ', 
        huiHuaLeiXing: '会话类型',
    paiDuiXinXi:  ' ข้อมูลคิว ', 
    jieDaiKeFu:  ' ฝ่ายต้อนรับลูกค้า ', 
         wenTiShiChang:  ' คำถาม/ระยะเวลา ', 
    keHuQuDao:  ' ลูกค้า/ช่องทาง ', 
    keFuLeiXing:  ' ประเภทการบริการลูกค้า ', 
    keHuLeiXing:  ' ประเภทลูกค้า ', 
    yiZhiJianHuiHua:  ' การสทนาที่ผ่านการตรวจสอบ ', 
    weiZhiJianHuiHua:  ' การสทนาที่ยังไม่ผ่านการตรวจสอบ ', 
    buHeGeLuShu:  ' อัตราไม่ผ่าน/จำนวน ', 
    jiGeLuShu:  ' อัตราการผ่าน/จำนวน ', 
    liangHaoLuShu:  ' อัตราดี/จำนวน ', 
    youXiuLuShu:  ' อัตราที่ยอดเยี่ยม/จำนวน ', 
    heGeLuShu:  ' อัตราผ่าน/จำนวน ', 
    zhiJianLuShu:  ' อัตราการตรวจสอบคุณภาพ/จำนวน ', 
    sheZhiXianShiZi:  ' ตั้งค่าฟิลด์แสดงผล ', 
                   huiHuaJieShuLei:  ' ประเภทการสิ้นสุดบทสนทนา ', 
    huiHuaShiFouJie:  ' บทสนทนาได้รับการแก้ไขแล้วหรือไม่ ', 
    keFuZongJieLei:  ' หมวดหมู่สรุปผลการบริการลูกค้า ', 
    pingJiaLeiXing:  ' ประเภทการประเมิน ', 
    xingJiPingJia:  ' ระดับดาว ', 
    miao:  ' วินาที ', 
         shouCiXiangYingShi:  ' เวลาตอบกลับครั้งแรก ', 
    huiHuaShiChang:  ' ระยะเวลาบทสนทนา ', 
              quanBuJieDaiKe:  ' ฝ่ายบริการลูกค้าทั้งหมด ', 
  },
  session_table: {
    yiPingJia:  ' ประเมินแล้ว ', 
         jieShuFangShi:  ' วิธีการสิ้นสุด ', 
    zuiDaXiangYingShi:  ' ระยะเวลาตอบสนองสูงสุด ', 
              shiFouJieJue:  ' แก้ไขแล้วหรือไม่ ', 
              shiFouPingJia:  ' ประเมินหรือไม่ ', 
    keHuPingJia:  ' การประเมินของลูกค้า ', 
    yeWu:  ' ธุรกิจ ', 
        huiHuaLeiBie: '会话类别',
  },
};
