export default {
  PieChart: {
        bCGeZhanD: '{b} : {c}个(占{d}%)'
  },
  a: {
    danXuan:  ' เลือกเดี่ยว ', 
                      },
  barOne: {
    shiChang:  ' ระยะเวลา ', 
  },
  chatInfo: {
    language:  ' ภาษา ', 
    anZhuo:  ' แอนดรอยด์ ', 
    haoDe:  ' ตกลง ', 
              paiDuiLiKai:  ' คิวที่จะออก ', 
    paiDuiJinRu:  ' เข้าคิว ', 
    weiPaiDui:  ' ไม่มีคิว ', 
    fou:  ' ไม่ ', 
                   weiJieJue:  ' ยังไม่ได้แก้ไข ', 
    yiJieJue:  ' แก้ไขแล้ว ', 
    weiZhiJian:  ' ยังไม่ผ่านการตรวจสอบ ', 
    yiZhiJian:  ' ตรวจสอบแล้ว ', 
         keHuZiXunCi:  ' จำนวนครั้งที่ลูกค้าสอบถาม ', 
        keHuZiXunCiByDay: '当日客户咨询次数：',
    keHuDuanKeFu:  ' หน้าลูกค้า/เวอร์ชันระบบบริการลูกค้า ', 
    jinRuYuMing:  ' เข้าถึงชื่อโดเมน： ', 
    iPDiZhi:  ' ที่อยู่ IP. ', 
    fangWenLiuLanQi:  ' เข้าถึงเบราว์เซอร์： ', 
        fangWenDi: '访问地区：',
    jinRuYeMian:  ' หน้าการเข้าถึง ', 
    keHuNiCheng:  ' ชื่อเล่นลูกค้า ', 
        keHuXingMing: '客户姓名：',
    keHuXinXi:  ' ข้อมูลลูกค้า ', 
        keHuLevel: '用户星级：',
    pingJiaNeiRong:  ' เนื้อหาการประเมิน ', 
         pingJiaXingJi:  ' การประเมินระดับดาว ', 
    shiFouJieJue:  ' แก้ไขแล้วหรือไม่ ', 
              pingJiaLeiXing:  ' ประเภทการประเมิน ', 
    keHuPingJia:  ' การประเมินของลูกค้า ', 
    fuWuZongJie:  ' สรุปบริการ ', 
    weiZhiJian2:  '\n ยังไม่ผ่านการตรวจสอบ \n', 
    yiZhiJian2:  '\n ตรวจสอบแล้ว \n', 
    chuangJianShiJian:  ' เวลาที่สร้าง ', 
    xiaZhuZhangHao:  ' วางบัญชี: ', 
    dingDanZhuangTai:  ' สถานะรายการ: ', 
        tixianLeixing: '提现类型',
        yuyueDaozhang: '预约到账',
        xiaoshi: '小时',
        yuyueTixian: '预约提现',

    shuYingJieGuo:  ' ผลการชนะ/แพ้: ', 
    xiaZhuJinE:  ' จำนวนเงินเดิมพัน: ', 
    youXiChanPin:  ' สินค้าเกม: ', 
    tiXianZhangHao:  ' หมายเลขบัญชีถอน: ', 
    daoZhangShuLiang:  ' จำนวนเงินที่เข้าบัญชี: ', 
    tiXianJinE:  ' จำนวนเงินที่ถอน: ', 
    tiXianFangShi:  ' วิธีการถอนเงิน: ', 
        tixianBiZhong: '提现币种:',
        chongzhiBiZhong: '充值币种:',
        xiazhuBiZhong: '下注币种:',
    chongZhiZhangHao:  ' เลขที่บัญชีเงินฝาก: ', 
         zhiFuFangShi:  ' วิธีการชำระ ', 
    chongZhiFangShi:  ' วิธีการ ฝากเงิน ', 
    dingDanHao:  ' เลขรายการ ', 
    yiChangGuanBi:  ' ปิดผิดปกติ ', 
    chiXuShiChang:  '\n ระยะเวลา: ', 
    jieShuFangShi:  '\n วิธีการสิ้นสุด ', 
    huiHuaZhong:  ' อยู่ระหว่างบทสนทนา ', 
    huiHuaXiaoXiShu:  '\n จำนวนข้อความบทสนทนา ', 
              paiDuiXinXi:  '\n ข้อมูลคิว ', 
    jieRuFangShi:  '\n วิธีการเข้าถึง ', 
    huiHuaID:  '\n ไอดี บทสนทนา ', 
    chaXun:  ' ตรวจสอบ ', 
    zongJieLeiXing:  ' ประเภทสรุป ', 
         zuoTian:  ' เมื่อวาน ', 
    jinTian:  ' วันนี้ ', 
    quanBu:  ' ทั้งหมด ', 
  },
  chatInfoResult: {
    zhiJianShiJian:  ' เวลาตรวจสอบคุณภาพ ', 
    zhiJianRen:  ' คนตรวจสอบคุณภาพ ', 
         keHuChaPingYuan2:  ' เหตุผลสำหรับแบบประเมินที่ไม่ดีจากลูกค้า: ', 
    zhiJianYiJian:  ' แบบประเมินจากคนตรวจสอบคุณภาพ ', 
                  con: '：',
    fen2:  ' คะแนน ', 
         huiHuaZhiJian:  ' การตรวจสอบคุณภาพบทสนทนา ', 
  },
  chatInfoSubmit: {
    zhiJianChengGong:  ' การควบคุมคุณภาพสำเร็จ ', 
    fenShuBuZaiZhi:  ' คะแนนไม่อยู่กฎเกณฑ์ที่ตั้งไว้ ', 
    buManYi:  ' ไม่พอใจ ', 
    yiBan:  ' ทั่วไป ', 
    manYi:  ' พอใจ ', 
    feiChangManYi:  ' พอใจมาก ', 
                             feiWuXingDuSuan:  ' ที่ไม่ใช่ห้าดาวถือเป็นแบบประเมินที่ไม่ดี ', 
    keHuChaPingYuan2:  ' เหตุผลสำหรับแบบประเมินที่ไม่ดีจากลูกค้า: ', 
    zhiJianYiJian:  ' แบบประเมินจากคนตรวจสอบคุณภาพ ', 
                   zhiJianJieGuo2:  ' ผลการตรวจสอบคุณภาพ. ', 
  },
  dateCommon: {
    shiJianXuanZeFan:  ' ช่วงเวลาเลือกได้ไม่เกิน 31 วัน! ', 
    jieShuRiQi:  ' วันที่สิ้นสุด ', 
    kaiShiRiQi:  ' วันที่เริ่มต้น ', 
  },
  editSelect: {
    woDeYeWuLei:  ' การกำหนดค่าประเภทธุรกิจของฉัน ', 
    woDeYeWuPei:  ' การกำหนดค่าธุรกิจของฉัน ', 
    yeWuMingCheng:  ' ชื่อธุรกิจ ', 
  },
  filters: {
    chuFa:  ' 11 ทริกเกอร์ ', 
    zhongZhi:  ' รีเซ็ต ', 
    shaiXuan:  ' กรอง ', 
  },
  onlineServer: {
         zhaKanZaiXianKe:  ' ตรวจดูการบริการลูกค้าออนไลน์ ', 
  },
  serviceSummary: {
    feiKeFuWuFa:  ' ไม่ใช่ฝ่ายบริการลูกค้าไม่สามารถส่งได้! ', 
    qingXuanZeYeWu:  ' กรุณาเลือกธุรกิจ ', 
    iDPaiXu:  ' การเรียงลำดับ ไอดี ', 
         yeWu:  ' ธุรกิจ ', 
    xuanZeYeWu:  ' เลือกธุรกิจ ', 
        aBaChaDaE: '阿八嚓哒妸发旮哈讥咔垃痳拏噢妑七呥扨它穵夕丫帀',
    qingXuanZeSuoShu:  ' กรุณาเลือกธุรกิจของคุณ ', 
    zongJie:  ' สรุป ', 
         zongJie2:  '\n สรุป \n', 
    yu:  ' ใน \n', 
         beiZhuShuoMing:  ' หมายเหตุ: ', 
    yeWuLeiXing2:  ' ประเภทธุรกิจ: ', 
                   zheShiGeWuXiao:  ' นี่เป็นบทสนทนาที่ไม่มีประสิทธิภาพ ', 
    youXiaoHuiHuaTi:  ' บทสนทนาที่มีประสิทธิภาพ ส่งสรุป ', 
    qingTianXieBeiZhu:  ' กรุณากรอกหมายเหตุ ', 
    benYeWuWeiPei:  ' ไม่มีการกำหนดค่าประเภทสำหรับบริการนี้ ', 
    qingXuanZeYeWu2:  ' กรุณาเลือกประเภทบริการ ', 
    wo:  ' ฉัน ', 
        suo: '所'
  },
  setBoard: {
        zuiShaoYaoPeiZhi: '最少要配置5个哦',
    kePeiZhiDeBan:  '\n บอร์ดที่กำหนดค่าได้ \n', 
  }
}
