export default {
  badReason: {
        shanChuChengGong: '删除成功',
    quXiao:  ' ยกเลิก ', 
    queDing:  ' ยืนยัน ', 
    shanChuChaPingYuan:  ' ลบประเภทของเหตุผลแบบประเมินที่ไม่ดี ', 
              youYiTiaoJiLu:  ' มีหนึ่งบันทึกที่กำลังแก้ไข ', 
    tianJiaChaPingYuan:  ' เพิ่มประเภทเหตุผลแบบประเมินที่ไม่ดี \n', 
         baoCun:  ' บันทึก ', 
         caoZuo:  ' การดำเนินการ ', 
         qingShuRuChaPing:  ' กรุณากรอกประเภทเหตุผลแบบประเมินที่ไม่ดี ', 
    feiWuXingDuSuan:  ' ที่ไม่ใช่ห้าดาวถือเป็นแบบประเมินที่ไม่ดี ', 
    keHuChaPingYuan2:  '\n เหตุผลสำหรับแบบประเมินที่ไม่ดีจากลูกค้า: \n', 
    keHuChaPingYuan3:  '\n เหตุผลสำหรับแบบประเมินที่ไม่ดีจากลูกค้า: ', 
  },
  scroreResult: {
         buJiGe:  ' ไม่ผ่าน ', 
    jiGe:  ' ผ่าน ', 
    liangHao:  ' ดี ', 
    youXiu:  ' ยอดเยี่ยม ', 
    zuiZhongPingFenJie:  ' ผลคะแนนสุดท้าย ', 
    deFenFanWei:  ' ช่วงคะแนน ', 
    pingFenJieGuo:  ' ผลการให้คะแนน ', 
    geiZuiZhongFenShu:  ' กำหนด 4 ระดับสำหรับคะแนนสุดท้าย ', 
    zuiZhongPingFenJie2:  '\n ผลคะแนนสุดท้าย \n', 
    zuiZhongPingFenJie3:  '\n ผลคะแนนสุดท้าย ', 
  },
  AppMain: {
        dot: ' ⋅ '
  },
  Navbar: {
    quXiao:  ' ยกเลิก ', 
    queDing:  ' ยืนยัน ', 
         queDingZhuXiaoBing:  ' แน่ใจว่าจะล็อกเอาท์และออกจากระบบ? ', 
    keFuHouTaiGuan:  ' บริการจัดการระบบหลังบ้านของฝ่ายบริการลูกค้า ', 
    jinRu:  '\n เข้าสู่ ', 
    huanYingNin:  '\n ยินดีต้อนรับ ', 
    tuiChuDengLu:  '\n ออกจากระบบ \n', 
    geRenZhongXin:  '\n บัญชีของฉัน \n', 
    buJuSheZhi:  ' การตั้งค่าเค้าโครง ', 
    quanPingSuoFang:  ' ซูมเต็มหน้าจอ ', 

        xiaZaiLieBiao: '下載列表(',
        shanChu: '刪除',
    xiaZai:  ' ดาวน์โหลด ', 
    caoZuo:  ' การดำเนินการ ', 
    zhuangTai:  ' สถานะ ', 
        chuangJianRiQi: '创建日期',
    wenJianMing:  ' ชื่อไฟล์ ', 
        quanBuQingChu: '全部清除',
        xiaZaiLieBiao2: '下載列表'
  },
  scroreTarget: {
    deFenFanWeiBu:  ' ช่วงคะแนนไม่สามารถทับซ้อนกันได้ ', 
         shanChuPingFenZhi:  ' ลบตัวดัชนีการให้คะแนน ', 
    pingFenZhiBiaoLie:  ' รายการตัวดัชนีการให้คะแนน ', 
    tianJiaPingFenZhi:  ' เพิ่มดัชนีการให้คะแนน \n', 

        sureDeleteScore: '您确定删除此评分指标吗?',

    buManYi:  ' ไม่พอใจ ', 
    yiBan:  ' ทั่วไป ', 
    manYi:  ' พอใจ ', 
    feiChangManYi:  ' พอใจมาก ', 
    qingShuRuPingFen:  ' กรุณาใส่ค่าคะแนน ', 
    pingFenBiaoZhun:  ' เกณฑ์การให้คะแนน ', 
    qingShuRuPingFen2:  ' โปรดกรอกดัชนีการให้คะแนน ', 
    pingFenZhiBiao:  ' ดัชนีการให้คะแนน ', 
    xuHao:  ' หมายเลขซีเรียล ', 
    duoGeZhiBiaoDi:  ' คะแนนเฉลี่ยของตัวดัชนีหลายตัวคือคะแนนสุดท้ายของบทสนทนา ', 
    pingFenZhiBiao2:  '\n ดัชนีการให้คะแนน \n', 
    pingFenZhiBiao3:  '\n ดัชนีการให้คะแนน ', 
  },
  sessionTags: {
    shanChuBiaoQian:  ' ลบแท็ก ', 
                                     },
  Editor: {
         fuWenBenJiYu:  '\n ขึ้นอยู่กับ Rich Text \n', 
  },
  MarkDown: {
    mARKD:  '\n ขึ้นอยู่กับ Markdown \n', 
  },
  YamlEdit: {
    zhanShiShuJuRu:  ' #แสดงข้อมูล หากคุณต้องการเปลี่ยนธีม โปรดค้นหาชื่อธีมดั้งเดิมในsrc/components/YamlEdit เพื่อแทนที่ \n', 
    zhuTiYuLanDi:  ' ที่อยู่ดูตัวอย่างธีม ', 
    zhuTiYuLanDi2:  ' ที่อยู่ดูตัวอย่างธีม ', 
    yAMLBian:  '\n โปรแกรมแก้ไข Yaml ขึ้นอยู่กับ \n', 
    yAMLBian2:  '\n โปรแกรมแก้ไข Yaml ขึ้นอยู่กับ ', 
  }
}
