export default {
  index: {
        tiShi: '提示',
    queDingYaoZhiXing: "แน่ใจไหมว่าต้องการดำเนินการ {val1} นี้", 
    buChuLi: "ไม่ดำเนินการ", 
    yiHuiFang: "ตอบกลับ", 
    haoDe: "ตกลง", 
    zhaKanLiuYan: "ดูข้อความ", 
    weiShouLi: "ไม่ผ่านการประมวลผล", 
    chuLiRen: "คนดำเนินการ", 
    chuLiJieGuo: "ผลดำเนินการ", 
    liuYanRiQi: "วันที่ข้อความ", 
    zhaKan: "ตรวจดู", 
    liuYanTuPian: "รูปภาพข้อความ", 
    liuYanNeiRong: "เนื้อหาข้อความ", 
        lianxufangshi: '联系方式',

    weiXin: "วีแชท", 
    shouJi: "โทรศัพท์มือถือ", 
    nu: "ผู้หญิง", 
    nan: "ผู้ชาย", 
    xingMingXingBie: "ชื่อ/เพศ", 
    ziXunWenTi: "ปรึกษาปัญหา", 
    keHuDengJiV: "ระดับลูกค้า/ระดับวีไอพี", 
    keHuZhangHuNi: "บัญชีลูกค้า/ชื่อเล่น", 
    quanBuKeFu: "ฝ่ายบริการลูกค้าทั้งหมด", 
    suoYouKeFu: "ฝ่ายบริการลูกค้าทั้งหมด", 
    qingShuRuKeHu: "กรุณากรอกบัญชีลูกค้าของคุณ", 
    quanXuanJiNengZu: "เลือกกลุ่มทักษะทั้งหมด", 
    quanBuJiNengZu: "กลุ่มทักษะทั้งหมด", 
    quanBuKeHuV: "ระดับวีไอพีของลูกค้าทั้งหมด", 
    quanBuKeHuDeng: "ลูกค้าทุกระดับ", 
  },
  lookPicture: {
    jiaZaiZhong: "กำลังโหลด", 
  },
  passwordvalite: {
    qingShuRuMiMa: "กรุณากรอกรหัสผ่านของคุณ", 
    qingShuRuNinDe: "กรุณากรอกรหัสผ่านเข้าสู่ระบบของคุณ", 
    dengLuMiMa: "รหัสผ่านในการเข้าสู่ระบบ", 
    dengLuYongHuMing: "เข้าสู่ระบบด้วยชื่อผู้ใช้", 
    zhaKanXiangQingMi: "ตรวจดูรายละเอียดการยืนยันรหัสผ่าน", 
  }
}
