export default {
  index: {
    laHeiROW: "บล็อก {val1}", 
    shanChuYongHuR: "ยืนยันการลบผู้ใช้ {val1}", 
    queDingShanChuR: "ต้องการลบโปรไฟล์ผู้ใช้ {val1} หรือไม่ จะไม่สามารถกู้คืนได้หลังจากการลบ", 
    queDingJiangGaiYong: "ยืนยันเพื่อยกเลิกการบล็อกผู้ใช้รายนี้ {val1}?", 
    laHeiChengGong: "บล็อกเรียบร้อย!", 
    shanChuChengGong: "ลบสำเร็จ", 
    keHuZhangHu: "บัญชีลูกค้า", 
    buYunXuShuRu: "ไม่อนุญาตให้ใช้อักขระที่ผิดกฎ", 
    qingShuRuLaHei: "โปรดกรอกเหตุผลในการบล็อก", 
    qingXuanZe: "กรุณาเลือก", 
    keHuLieBiao: "รายชื่อลูกค้า", 
    queRen: "ยืนยัน", 
    biTian: "จำเป็นต้องกรอก...", 
    laHeiYuanYin: "เหตุผลการบล็อก", 
    laHeiLeiXing: "ประเภทบล็อก", 
    laHeiYongHu: "ผู้ใช้บัญชีที่ถูกบล็อก", 
    laHei: "บล็อก", 
    shiFouLaHei: "ต้องการบล็อกหรือไม่", 
    liShiZiXunShu: "จำนวนการตรวจสอบประวัติ", 
    zhongZhi: "รีเซ็ต", 
    chaXun: "ตรวจสอบ", 
  },
};
