export default {
  autoAcceptCustomerType: {
        shanChuChengGong: '删除成功',
    quXiao:  ' ยกเลิก ', 
    queDing:  ' ยืนยัน ', 
         shiFouShanChu:  ' ลบหรือไม่ ', 
    queRenShanChu:  ' ยืนยันการลบ ', 
    yaoQingJieDaiLie:  ' รายการรับเชิญ ', 
         caoZuo:  ' การดำเนินการ ', 
    zuiHouXiuGaiRen:  ' แก้ไขล่าสุดโดย ', 
    zuiHouXiuGaiRi:  ' วันที่แก้ไขล่าสุด ', 
         keHuLeiXing:  ' ประเภทลูกค้า ', 
    keFuLeiXing:  ' ประเภทการบริการลูกค้า ', 
         suoYouKeHuLei:  ' ประเภทลูกค้าทั้งหมด ', 
    suoYouKeFuLei:  ' ประเภทการบริการลูกค้าทั้งหมด ', 
  },
  receptSet: {
    qingNinQueRen:  ' คุณช่วยยืนยัน？ ', 
    shanChuHouSE:  ' หลังจากลบ {val1} แล้ว คุณจะไม่สามารถรับ {val2} ได้ ', 
    keJieDaiKeHu:  ' คลิกเลือกลูกค้าที่สามารถรับได้ ไม่สามารถเพิ่มได้！ ', 
    keHuJieDaiLie:  ' รายการรับลูกค้า ', 
         keHuZuMing:  ' ชื่อกลุ่มลูกค้า ', 
    keFuZuMing:  ' ชื่อกลุ่มบริการลูกค้า ', 
    keJieDaiDeKe:  ' ลูกค้าที่มีอยู่ ', 
         keHuJieDaiPei:  ' การกำหนดค่าการรับลูกค้า ', 
                   ziDongJieDaiKe2:  ' การรับประเภทลูกค้าโดยอัตโนมัติ ', 
  },
};
