export default {
  execute: {
        zhiXingChengGong: '执行成功',
         shangChuanHouXiTong:  ' หลังจากอัปโหลด ระบบจะเรียกใช้สคริปต์ SQL โดยอัตโนมัติ ', 
    dianJiShangChuan:  ' คลิกอัปโหลด ', 
    jiangWenJianTuoDao:  '\n ลากและวางไฟล์ที่นี่ หรือ \n', 
    zhiXingJiaoBen:  ' สคริปต์การดำเนินการ ', 
  },
  index: {
    lianJieShiBai:  ' การเชื่อมต่อล้มเหลว ', 
    lianJieChengGong:  ' การเชื่อมต่อสำเร็จ ', 
    qingShuRuShuJu:  ' กรุณากรอกรหัสผ่านของฐานข้อมูล ', 
         qingShuRuShuJu2:  ' โปรดกรอกที่อยู่การเชื่อมต่อฐานข้อมูล ', 
    qingShuRuShuJu3:  ' กรุณากรอกชื่อฐานข้อมูล ', 
    shuJuKu:  ' ฐานข้อมูล ', 
    yongHuMing:  ' ชื่อผู้ใช้ ', 
    lianJieDiZhi:  ' ที่อยู่การเชื่อมต่อ ', 
    shuJuKuMingCheng:  ' ชื่อฐานข้อมูล ', 
         yongHu:  ' ผู้ใช้ ', 
    ceShi:  ' ทดสอบ ', 
    jDBCDi:  ' ที่อยู่ JDBC ', 
    lianJieMingCheng:  ' ชื่อการเชื่อมต่อ ', 
    zhiXingJiaoBen:  ' สคริปต์การดำเนินการ \n', 
    moHuSouSuo:  ' ค้นหา ', 
  },
};
