export default {
    guanJunPanKou:  'Champions handicap', 
    duYingPan:  '1X2', 
    gunQiuDuYingPan:  'Live 1X2', 
    jiaShiDianQiu:  'extra time and penalty shoot-out', 
    shuang:  'even', 
    heJu:  'draw', 
    heZhu:  'draw home', 
    heHe:  'draw draw', 
    heKe:  'draw away', 
    keDui:  'away', 
    keDuiJingShengQiu:  'Away team - goal difference by 5 goals or more', 
    qiTaBiFen:  'other score', 
    keZhu:  'away home', 
    keHe:  'away draw', 
    keKe:  'away away', 
    meiShiZuQiu:  'American football', 
    xiang:  'item', 
    chuanGuan:  'parley：', 
    tongBuShiJian:  'synchronised time', 
    xiaZhuIP:  'bet IP', 
    zhuDanZhuangTai:  'order status', 
    saiShiIDJu:  'match id/matches number', 
    youXiZhangHuMing:  'game account name', 
    paiCaiShiJian:  'bonus payout time', 
    xiaZhuShiJian:  'betting time', 
    touZhuID:  'betting id', 
    touZhuID2:  'betting ID', 
    sanFangDingDanHao:  'Third party order number', 
    quanBuHuiZong:  'Summarize all', 
    qingXuanZeShiFou:  'Please choose whether to settle in advance', 
    tiQianJieSuan:  'settle in advance', 
    zhenDuiTiYuZhu:  'For sports bets order, enter English', 
    lianSaiMingCheng:  'league name', 
    wuXiaoDingDanI:  'Invalid order: {val1}, bet amount {val2} RMB', 
    yiQuXiaoZhuDan:  'Canceled bets: {val1} bet amount {val2} RMB', 
    weiJieSuanZhuDan:  'Unsettled bets: {val1} bet amount {val2} RMB', 
    zhi:  'to', 
    xuanXiang:  'options', 
    daiChongFanLiZong:  'total rebate amount of top up on behalf of others', 
    cuoWuDaiChongKou:  'The total amount top up on behalf of others deducted by mistake', 
    shengYuXinYongZong:  'total remaining credit', 
    yiShiYongXinYong:  'Total credit used', 
    xinYongZongE:  'total credit', 
    yiShiYongXinYong2:  'credit limit used', 
    mingXiShuJuYue:  'Detailed data month:', 
    detail:  '{val1} and other {val2} items, total {val3} RMB', 
};
