export default {
    wEBSO:  ' เกิดข้อผิดพลาดในการเชื่อมต่อ WebSocket ', 
              duoGeYingYongShang:  ' มีการอัปโหลดแอปพลิเคชันหลายรายการด้วยชื่อไฟล์ all.zip และสคริปต์การอัปเดตฐานข้อมูลนามสกุล .sql และระบบจะปรับใช้โดยอัตโนมัติหลังจากอัปโหลดสำเร็จ ', 
    yingYongBuShu:  ' การปรับใช้แอปพลิเคชัน ', 
  index: {
    fuWuQiBuNeng:  ' เซิร์ฟเวอร์ (ห้ามเว้นว่าง) ', 
    yingYongBuNengWei:  ' แอปพลิเคชัน (ห้ามเว้นว่าง) ', 
    buShu:  ' การปรับใช้ ', 
    buShuRiQi:  ' วันที่ปรับใช้ ', 
    fuWuQiLieBiao:  ' รายการเซิร์ฟเวอร์ ', 
         fuWuQi:  ' เซิร์ฟเวอร์ ', 
    yiJianBuShu:  ' ปรับใช้คลิกเดียว \n', 
    yiJianBuShu2:  ' ปรับใช้คลิกเดียว ', 
    tingZhi:  ' หยุด \n', 
    tingZhi2:  ' หยุด ', 
    qiDong:  ' เริ่ม \n', 
    qiDong2:  ' เริ่ม ', 
    zhuangTaiChaXun:  ' ตรวจสอบสถานะ \n', 
    zhuangTaiChaXun2:  ' ตรวจสอบสถานะ ', 
    xiTongHuanYuan:  ' ระบบการเรียกคืน \n', 
    xiTongHuanYuan2:  ' ระบบการเรียกคืน ', 
       },
  sysRestore: {
    qingXuanZeYaoHai:  ' โปรดเลือกข้อมูลสำรองที่จะกู้คืน ', 
    buShuRenYuan:  ' ปรับใช้โดย ', 
    buShuShiJian:  ' เวลาปรับใช้ ', 
    buShuIP:  ' IP การปรับใช้ ', 
    souSuo:  ' ค้นหา ', 
  },
};
