export default {
    wEBSO: "เกิดข้อผิดพลาดในการเชื่อมต่อ WebSocket", 
    xiuGaiChengGong: "แก้ไขเรียบร้อยแล้ว", 
    tianJiaChengGong: "เพิ่มเรียบร้อยแล้ว", 
  duoGeYingYongShang:
    '多个应用上传文件名称为all.zip,数据库更新脚本扩展名为.sql,上传成功后系统自动部署系统。',
    yingYongBuShu: "การปรับใช้แอปพลิเคชัน", 
  index: {
    fuWuQiBuNeng: "เซิร์ฟเวอร์ (ห้ามเว้นว่าง)", 
    yingYongBuNengWei: "แอปพลิเคชัน (ห้ามเว้นว่าง)", 
    buShu: "การปรับใช้", 
    buShuRiQi: "วันที่ปรับใช้", 
    fuWuQiLieBiao: "รายการเซิร์ฟเวอร์", 
    qingXuanZe: "กรุณาเลือก", 
    fuWuQi: "เซิร์ฟเวอร์", 
    yiJianBuShu: "ปรับใช้คลิกเดียว", 
    yiJianBuShu2: "ปรับใช้คลิกเดียว", 
    tingZhi: "หยุด", 
    tingZhi2: "หยุด", 
    qiDong: "เริ่ม", 
    qiDong2: "เริ่ม", 
    zhuangTaiChaXun: "ตรวจสอบสถานะ", 
    zhuangTaiChaXun2: "ตรวจสอบสถานะ", 
    xiTongHuanYuan: "ระบบการเรียกคืน", 
    xiTongHuanYuan2: "ระบบการเรียกคืน", 
    shuRuYingYongMing: "กรอกชื่อแอปพลิเคชันเพื่อค้นหา", 
  },
  sysRestore: {
    qingXuanZeYaoHai: "โปรดเลือกข้อมูลสำรองที่จะกู้คืน", 
    buShuRenYuan: "ปรับใช้โดย", 
    buShuShiJian: "เวลาปรับใช้", 
    buShuIP: "IP การปรับใช้", 
    souSuo: "ค้นหา", 
  },
};
