export default {
  index: {
        qieHuan: '切换',
    laiYuanZhongHouTai:  ' ที่มาระบบหลังบ้าน ', 
    laiYuanYouKe:  ' ที่มาผู้เยี่ยมชม ', 
    qiYong:  ' เปิดใช้งาน ', 
    jinYong:  ' ปิดการใช้งาน ', 
    keHuMOM:  ' รายละเอียดบทสนทนาของลูกค้า momo699 และเชอร์รีฝ่ายบริการลูกค้า ', 
    laHeiLiShiJi:  ' ประวัติการถูกบล็อก ', 
    lianXiKeFuJi:  ' ติดต่อบันทึกการบริการลูกค้า ', 
    keHuXiangQingLie:  ' รายการรายละเอียดลูกค้า ', 
    jieChuKeFu:  ' ยกเลิกบริการลูกค้า ', 
    jieChuLeiXing:  ' ประเภทการยกเลิก ', 
    laHeiYuanYin:  ' เหตุผลการบล็อก ', 
    laHeiLaiYuan:  ' ที่มาการบล็อก ', 
    laHeiKeFu:  ' บริการลูกค้าบล็อก ', 
    laHeiShiJian:  ' เวลาบล็อก ', 
    huiHuaZhong:  ' อยู่ระหว่างบทสนทนา ', 
    renGongXiaoXiShu:  ' จำนวนข้อความของพนังงาน ', 
         manYiDu:  ' ความพึงพอใจ ', 
    weiChuLi:  ' ยังไม่ดำเนินการ ', 
    yiChuLi:  ' ดำเนินการแล้ว ', 
              huiHuaLaiYuan:  ' ที่มาบทสนทนา ', 
    jieDaiKeFu:  ' ฝ่ายต้อนรับลูกค้า ', 
    jiNengZu:  ' กลุ่มทักษะ ', 
    paiDuiShiChang:  ' ระยะเวลาของคิว ', 
    huiHuaShiChang:  ' ระยะเวลาบทสนทนา ', 
         chuangJianShiJian:  ' เวลาที่สร้าง ', 
              keHuDengJiV:  ' ระดับลูกค้า/ระดับวีไอพี ', 
    liXian:  ' ออฟไลน์ ', 
    zaiXianHuiHuaZhong:  ' กำลังสนทนาออนไลน์ ', 
  },
};
