export default {
  config: {
    sMTPDuan:  ' พอร์ต SMTP (ห้ามเว้นว่าง) ', 
    sMTPDi:  ' ที่อยู่ SMTP (ห้ามเว้นว่าง) ', 
         qingShuRuFaJian:  ' กรุณากรอกชื่อผู้ส่ง ', 
         qingShuRuFaJian2:  ' กรุณากรอกที่อยู่อีเมลของผู้ส่ง ', 
    sMTPDuan2:  ' พอร์ต SMTP ', 
    sMTPDi2:  ' ที่อยู่ SMTP ', 
    youXiangMiMa:  ' รหัสผ่านอีเมล ', 
    faJianYongHuMing:  ' ชื่อผู้ส่ง ', 
    faJianRenYouXiang:  ' อีเมลของผู้ส่ง ', 
  },
  index: {
    hUTOO:  ' ชุดเครื่องมือ hutool ', 
    gengDuoBangZhuQing:  ' สำหรับความช่วยเหลือเพิ่มเติม โปรดตรวจสอบเอกสารประกอบที่ ', 
    gengDuoBangZhu:  ' ความช่วยเหลือเพิ่มเติม ', 
    youJianFuWuQi:  ' # ที่อยู่ SMTP ของเมลเซิร์ฟเวอร์ เป็นทางเลือก ค่าเริ่มต้นคือ smtp # พอร์ต SMTP ของเมลเซิร์ฟเวอร์ เป็นทางเลือก ค่าเริ่มต้นคือ 465 หรือ 25 # ผู้ส่ง (ต้องถูกต้อง มิฉะนั้นการส่งจะล้มเหลว) # ชื่อผู้ใช้ ค่าเริ่มต้นคือคำนำหน้ากล่องจดหมายของผู้ส่ง # รหัสผ่าน ( โปรดทราบว่ากล่องจดหมายบางกล่องต้องการรหัสผ่านแยกต่างหากสำหรับบริการ SMTP เช่น QQ และ 163 เป็นต้น) # ไม่ว่าจะเปิด ssl ค่าเริ่มต้นคือเปิด ', 
    youJianFuWuQi2:  ' การกำหนดค่าเซิร์ฟเวอร์อีเมล ', 
    faSongYouJian:  ' ส่งอีเมล ', 
    youXiangPeiZhi:  ' การกำหนดค่าอีเมล ', 
  },
  send: {
    faSongChengGong:  ' ส่งเรียบร้อย ', 
    shouJianYouXiangGe:  ' รูปแบบอีเมลผู้รับไม่ถูกต้อง ', 
    shouJianYouXiangBu:  ' อีเมลผู้รับ (ห้ามเว้นว่าง) ', 
    qingZhiShaoBaoLiu:  ' โปรดเหลือผู้ติดต่ออย่างน้อยหนึ่งคน ', 
         shouJianYouXiang:  ' อีเมลผู้รับ ', 
    youJianBiaoTi:  ' หัวข้ออีเมล ', 
  },
};
