export default {
  index: {
    zanWuZaiXianKe:  ' ไม่มีบริการลูกค้าออนไลน์ในขณะนี้! ', 
    zanWuZaiXianKe2:  ' ไม่มีบริการลูกค้าออนไลน์ในขณะนี้! ', 
    paiDuiLiKai:  ' คิวที่จะออก ', 
    weiPaiDui:  ' ไม่มีคิว ', 
    ziXunShu:  ' จำนวนสอบถาม ', 
    paiDuiXinXi:  ' ข้อมูลคิว ', 
    jiNengZu:  ' กลุ่มทักษะ ', 
    chaPingLu:  ' แบบประเมินที่ไม่ดี % ', 
    chaPingShuLu:  ' จำนวน/อัตราแบบประเมินที่ไม่ดี % (1-2) ', 
    zhongPingLu:  ' อัตราแบบประเมินปานกลาง % ', 
    zhongPingShuLu:  ' จำนวน/อัตราแบบประเมินปานกลาง (3-4) ', 
    haoPingLu:  ' แบบประเมินดี % ', 
    haoPingShuLuFen:  ' จำนวน/อัตราแบบประเมินที่ดี (5) ', 
    pingJiaJieJueLu:  ' อัตราความละเอียดในการประเมิน % ', 
    pingJiaJieJueShu:  ' จำนวน/อัตราความละเอียดในการประเมิน ', 
    pingJunKeHuPing:  ' คะแนนเฉลี่ยแบบประเมินของลูกค้า ', 
    keHuZhuDongPing:  ' อัตราการประเมินโดยลูกค้าเอง % ', 
    keHuZhuDongPing2:  ' จำนวน/อัตราของการประเมินโดยลูกค้าเอง ', 
    keFuYaoQingPing:  ' อัตราคำเชิญประเมินการบริการ % ', 
    keFuYaoQingPing2:  ' จำนวน/อัตราคำเชิญประเมินการบริการ ', 
         keHuPingJiaShu:  ' จำนวน/อัตราการประเมินของลูกค้า ', 
              weiJieJue:  ' ยังไม่ได้แก้ไข ', 
    yiJieJue:  ' แก้ไขแล้ว ', 
    yiPingJia:  ' ประเมินแล้ว ', 
                  xing2: '4星',
    xing3:  ' 3 ดาว ', 
        xing4: '2星',
         xiangQing:  ' รายละเอียด ', 
    caoZuo:  ' การดำเนินการ ', 
         xing6:  ' ดาว ', 
         shiFouJieJue:  ' แก้ไขแล้วหรือไม่ ', 
    pingJiaLaiYuan:  ' ที่มาการประเมิน ', 
    shiFouPingJia:  ' ประเมินหรือไม่ ', 
    pingJiaXinXi:  ' รายละเอียดการประเมิน ', 
         keFuZu:  ' กลุ่มบริการลูกค้า ', 
    jieDaiKeFu:  ' ฝ่ายต้อนรับลูกค้า ', 
    keHuZhangHu:  ' บัญชีลูกค้า ', 
    huiHuaID:  ' ไอดี บทสนทนา ', 
    zanWuShuJuQing:  '\n ไม่มีข้อมูล โปรดเลือกเกณฑ์การค้นหาเพื่อค้นหาอีกครั้ง! \n', 
              quanBuKeFu:  ' ฝ่ายบริการลูกค้าทั้งหมด ', 
    keHuPingJiaJi:  ' บันทึกการประเมินของลูกค้า ', 
    keHuPingJiaTong:  ' สถิติการประเมินลูกค้า ', 
  },
  serversevalua: {
         keFuPingJiaBao:  ' รายงานการประเมินการบริการลูกค้า ', 
    chaPingShuChaPing:  ' จำนวนการประเมินที่ไม่ดี/อัตราการประเมินที่ไม่ดี ', 
    zhongPingShuZhongPing:  ' จำนวนการประเมินปานกลาง/อัตราการประเมินปานกลาง ', 
    haoPingShuHaoPing:  ' จำนวนการประเมินดี/อัตราการประเมินดี ', 
    pingJunPingJiaFen:  ' คะแนนการประเมินเฉลี่ย ', 
    yaoQingPingJiaShu:  ' จำนวนคำเชิญประเมิน/อัตราการเชิญ ', 
    pingJiaShuPingJia:  ' จำนวนการประเมิน/อัตราการประเมิน ', 
         daoChuBaoBiao:  ' รายงานการส่งออก ', 
    xianShiYinCangKong:  ' แสดง/ซ่อนข้อมูลที่ว่างเปล่า ', 
    keFuPingJiaTong:  ' รายงานสถิติการประเมินการบริการลูกค้า ', 
  },
};
