export default {
      quKuanJiLu: '取款纪录',
    cunKuanJiLu:  'deposit records', 
    quKuanFang:  'Withdrawal party:', 
    cunKuanFang:  'deposit party:', 
    daoZhangShiJian:  'time of received payment', 
    chongZhiShiJian:  'deposit time', 
    dingDanBianHao:  'order number', 
    dingDanZhuangTai:  'order status', 
    qingShuRuDingDan:  'Please enter order number', 
    chuangJianDingDanLi:  'Create order history', 
    shouKuanKaYinHang:  'debit card bank', 
    shouKuanKaXingMing:  'debit card name', 
    dingDanJinE:  'order amount', 
    shangHuHao:  'Merchant number', 
    chongZhiTongDao:  'deposit channel', 
    dingDanHao:  'order', 
    tianJiaTuPian:  'upload picture', 
    shangChuanTuPianShi:  'Failed to upload picture', 
    zuiDuoZhiNengShang:  'You can only upload up to 3 pictures', 
    chongZhiShangHuHao:  'Deposit Merchant Number', 
    dingDanHaoDA:  'order：{val1}', 
    chuangJianDingDanCheng:  'Create order successfully', 
    weiHuoQuDaoGuan:  'The associated tracking number data has not been obtained', 
    dingDanXiangQing:  'order detail', 
    shouKuanRenXingMing:  'Payee's Name', 
    shouKuanKaHao:  'Beneficiary card number', 
    yinHangKaHaoQian:  'bank card number / wallet address', 
    chongZhiRenXingMing:  'deposit person's name', 
    shouKuanYinHangQian:  'Beneficiary Account Name / wallet protocol', 
    chongZhiLeiXing:  'deposit type', 
    zhiFuShangHuHao:  'payment merchant's number', 
    zhiFuShangHuMing:  'payment merchant's name', 
    douDiCeng:  'Basic level', 
    buDanShenHeRen:  'replace order auditor', 
    buDanShenHeShi:  'replace order audit time', 
    buDanFaQiRen:  'replace order initiator', 
    buDanShiJian:  'replace order time', 
    buDanJinE:  'replace order amount', 
    shiJiShouDaoU:  'Actually received USDT', 
    shiJiHuiLu:  'Actually exchange rates', 
    dingDanHuiLu:  'Order exchange rates', 
    daiZhiFuUS:  'Pending Payment USDT', 
    juHeDingDanXiang:  'polymerization order details', 
    quDaoShangHuHao:  'channel merchant number', 
    xiaYouQuDao:  'downstream channel', 
    wuPingZhengJieTu:  'Screenshots without any proof', 
    shangHuHouTaiDing:  'Merchant backend order status', 
    queDingJuJue:  'Confirmed to reject', 
    baoCunChengGong:  'save successful！', 
    tuPianShangChuanCuo:  'picture upload error', 
    buCunZaiDeZhang:  'non-existent account：{val1}', 
    yiJingCunZaiFen:  'already existing account：{val1}', 
    caoZuoChengGong:  'operate successful', 
    renGongChuKuan:  'Payment by mannually', 
    sanFangShouDongChu:  'Payment by 3rd party mannually', 
    tuiHui:  'return', 
    fengKongShenHeShi:  'risk control audit time', 
    chuKuanFangShi:  'Payment Method', 
    huiYuanXingMing:  'member name', 
    tiXianDingDanJin:  'withdraw order amount', 
    chuKuanJiLu:  'Payment history', 
    xuanZeChuKuanShang:  'Choose Payment Merchant', 
    tiXianShiJianDuan:  'withdraw time period', 
    queDingQiangZhiShi:  'Confirmed to enforcement to failed？', 
    qiangZhiShiBai:  'enforcement failed', 
    qiangZhiChengGong:  'enforcement successful', 
    juJueYuanYin:  'reason of reject', 
    uSDTShu:  'USDT quantity', 
    canKaoHuiLu:  'Reference exchange rate', 
    qingShuRuChuKuan:  'Please input withdraw account detail', 
    chuKuanZhangHuXin:  'withdraw account detail', 
    qingShuRuChuKuan2:  'Please input withdraw account', 
    chuKuanZhangHao:  'withdraw account', 
    kaiHuXingDiZhi:  'Bank address/wallet address', 
    yinHangKaHaoXie:  'Bank card number/protocol type', 
    yinHangMingChengU:  'Bank Name/USDT Withdrawal', 
    queRenChuKuan:  'Confirm withdraw', 
    juJueChuKuan:  'Refusal to withdraw', 
    buZhiChiYuE:  'Does not support balance inquiries', 
    qingShuRuChuKuan3:  'Please enter the payment card name', 
    chuKuanKaYinHang:  'withdraw bank', 
    chuKuanKaXingMing:  'withdraw name', 
    yuE:  'balance', 
    chuKuanZhiFuShang:  'Payment merchants', 
    tiXianTuiHui:  'withdraw return', 
    shuRuHuiYuanXing:  'Enter member name', 
    shiBai:  'fail', 
    ziDongChuKuan:  'automatic payment', 
    sanFangZiDongChu:  '3rd party automatic payment', 
    juJueQiangZhiCheng:  'Refuse to enforcement success', 
    tongGuoQiangZhiCheng:  'success by enforcement', 
    ziDongChuKuanShi:  'Automatic payment failed', 
    shenQingQiangZhiCheng:  'enforcement successful application', 
    juJueTuiHui:  'refuse to return', 
    tuiHuiChengGong:  'returned successfully', 
    shenQingTuiHuiZhong:  'Application is being returned', 
    juJueChuKuanChu:  'Reject payment (payment failure)', 
    chuKuanChengGong:  'Payment successful', 
    fengXianShenHeTong:  'Risk audit passed (to be paid out)', 
    tiXianLeiXing:  'Withdrawal type', 
    chuKuanShiJian:  'Payment time', 
    tiXianShiJian:  'Withdrawal time', 
    quKuanJinE:  'Withdrawal amount:', 
    fuZhi:  'copy', 
    fengXianShenHeJu:  'Risk audit rejected', 
    fengXianDaiShenHe:  'Risk pending audit', 
    geZhi:  'on hold', 
    daiZhiFu:  'to be paid', 
    yunShanFuZhuanZhang:  'UnionPay transfer', 
      chaoShiWeiQueRen: '超时未确认到帐',
    daiQueRenDaoZhang:  'To be confirm receive', 
    chaoShiCheXiao:  'timeout cancellation', 
    yongHuCheXiao:  'user cancel', 
    buDanShenHeZhong:  'replenishment auditing', 
    renGongJuJueBu:  'replace order rejected by mannually', 
    buDanShenHeJu:  'replace order audit has been reject', 
    buDanShenHeCheng:  'replace order audit successful', 
    jiSuZhuanKa:  'Fast ​​transfer card', 
    daiKeChongZhi:  'Top up on behalf of others', 
    puTongChongZhi:  'normal deposit', 
      qingShuRuXingMing: '请输入姓名，多个姓名请用","隔开',
      fuKuanRen: '付款人',
      qingShuRuFuKuan: '请输入付款人',
      biZhong: '币种',
      hashZhi: '哈希值',
      qingShurHashZhi: '请输入哈希值',
      chuangJianXinDingDan: '创建新订单',
      oRIGI: '{val1}原',
      chongZhiBiZhong: '充值币种',
      chongZhiShangHuXin: '充值商户信息',
      shouKuanKaXinXi: '收款卡信息',
      buDan: '补单',
      shouKuanKaYinHang2: '收款卡银行',
      shiJianNeiRong: '事件内容',
      cuoHeSuoDing: '撮合锁定',
      queRenShouKuan: '确认收款',
      queRenFuKuan: '确认付款',
      tiXianDingDanQu: '提现订单取消',
      chongZhiDingDanQu: '充值订单取消',
      tiXianDingDanChuang: '提现订单创建',
      cuoHeChengGong: '撮合成功',
      cuoHeSuoDingJie: '撮合锁定解除',
      daEChongZhi: '大额充值',
};
