export default {
    shenQingBeiZhu:  'application remarks', 
    tiaoZhengJinE:  'Adjustment amount', 
    ziJinTiaoZhengDan:  'Funds Adjustment Order', 
    shenHeRen:  'auditor', 
    erShenZhuangTai:  'second audit status', 
    yiShenZhuangTai:  'first audit status', 
    keTiEDu:  'Amount can be withdraw', 
    tiaoZhengZiLeiXing:  'Adjustment Subtype', 
    tiaoZhengLeiXing:  'Adjustment type', 
    zhangHuXinXi:  'Account detail', 
    sanFangShangHuDing:  'third party merchant order number', 
    guanLianDanHao:  'related order', 
    qingShuRuDanHao:  'please input order number', 
    qingShuRuTiaoZheng:  'please input adjustment reason', 
    qingShuRuSanFang:  'please input third party merchant order number', 
    qingShuRuGuanLian:  'Please enter the related order number', 
    guanLianDingDanHao:  'related order number', 
    qingShuRuXuQiu:  'please input request turnover amount', 
    qingShuRuTiXian:  'please input withdrawal amount , can't > adjustment amount', 
    danBiADJ:  'single≤{val1}RMB', 
    qingShuRuChongZhi:  'please input deposit amount , if don't have please input 0', 
    tiXianLiuShui:  'Withdrawal turnover', 
    shiJiFaFangJin:  'Actual released amount', 
    jiangLiJinE:  'bonus amount', 
    daiLiHuoDongXuan:  'affiliate promotion choose', 
    ziJinTiaoZhengShen:  'amount adjustment apply', 
    qingXuanZeDaiLi:  'please choose affiliate promotion', 
    zhangHaoSUC:  'Account {val1} amount adjustment apply successful', 
    zhangHaoFAI:  'Account {val1} does not support {val2}', 
    zhangHaoINV:  'Account {val1} does not exist', 
    jinBanNianJiaBi:  'Add on currency records in the past six months', 
    qingXuanZeShenHe:  'Please choose audit results', 
    shenHeJieGuo:  'Audit results', 
    erShenBeiZhu:  'second audit remark', 
    yiShenBeiZhu:  'first audit remark', 
    shenQingYuanYou:  'Apply reason', 
    erCiShenHe:  'second audit', 
    yiCiShenHe:  'first audit', 
};
