export default {
  config: {
    shengChengChengGong:  ' สร้างเรียบร้อยแล้ว ', 
    baoCunChengGong:  ' บันทึกสำเร็จ ', 
         buNengWeiKong:  ' (ห้ามเว้นว่าง) ', 
    jieKouMingChengBu:  ' ชื่ออินเทอร์เฟซ (ห้ามเว้นว่าง) ', 
    qianDuanLuJingBu:  ' เส้นทางส่วนหน้า (ห้ามเว้นว่าง) ', 
    baoLuJingBuNeng:  ' เส้นทางแพ็คเกจ (ห้ามเว้นว่าง) ', 
    zuoZheBuNengWei:  ' ผู้เขียน (ห้ามเว้นว่าง) ', 
    jinFangWuCaoZuo:  ' โปรดเลือกอย่างระมัดระวังเพื่อป้องกันการใช้ผิดประเภท ', 
    fou:  ' ไม่ ', 
         shiFouFuGai:  ' ทับหรือไม่ ', 
    moRenBuQuChu:  ' ตามค่าเริ่มต้น คำนำหน้าตารางจะไม่ถูกลบออก ซึ่งสามารถกำหนดเองได้ ', 
    moRenBuQuChu2:  ' ตามค่าเริ่มต้น คำนำหน้าตารางจะไม่ถูกลบออก ', 
    quBiaoQianZhui:  ' ลบคำนำหน้าตาราง ', 
    shuRuVIE:  ' ป้อนไดเร็กทอรีภายใต้โฟลเดอร์ view หรือสร้างไดเร็กทอรีหากไม่มีอยู่ ', 
    qianDuanLuJing:  ' เส้นทางเบื้องหน้า ', 
    jieKouDeMingCheng:  ' ชื่อของอินเตอร์เฟส ใช้ในเอกสารคู่มือคอนโทรลเลอร์และอินเตอร์เฟส ', 
    jieKouMingCheng:  ' ชื่ออินเทอร์เฟซ ', 
    xiangMuBaoDeMing:  ' ชื่อของแพ็คเกจโครงการ รหัสที่สร้างขึ้นในแพ็คเกจใด ', 
    zhiYuBaoXia:  ' สำหรับแพ็คเกจ ', 
    moKuaiDeMingCheng:  ' ชื่อโมดูล โปรดเลือกโมดูลที่มีอยู่แล้วในโครงการ ', 
    moKuaiMingCheng:  ' ชื่อโมดูล ', 
        leiShangMianDeZuo: '类上面的作者名称',
    zuoZheMingCheng:  ' ชื่อผู้แต่ง ', 
    baoCun:  ' บันทึก ', 
    shengChengPeiZhi:  ' สร้างการกำหนดค่า ', 
         guanLianZiDian:  ' พจนานุกรมที่เกี่ยวข้อง ', 
    ziDongGengXinShi:  ' เวลาอัปเดตอัตโนมัติ ', 
    ziDongChuangJianShi:  ' เวลาที่สร้างอัตโนมัติ ', 
    riQiZhuJie:  ' หมายเหตุวันที่ ', 
    chaXunFangShi:  ' วิธีตรวจสอบ ', 
    riQiKuang:  ' ช่องวันที่ ', 
    xiaLaKuang:  ' ช่องแบบเลื่อนลง ', 
    danXuanKuang:  ' เลือกช่องเดียว ', 
    wenBenYu:  ' ช่องข้อความ ', 
    wenBenKuang:  ' กล่องข้อความ ', 
    biaoDanLeiXing:  ' ประเภทแบบฟอร์ม ', 
    biaoDan:  ' แบบฟอร์ม ', 
    lieBiao:  ' รายการ ', 
         ziDuanMiaoShu:  ' คำอธิบายฟิลด์ ', 
    ziDuanLeiXing:  ' ประเภทฟิลด์ ', 
    ziDuanMingCheng:  ' ชื่อฟิลด์ ', 
         shuJuKuZhongBiao:  ' ใช้ฟังก์ชันนี้เมื่อเขตข้อมูลตารางในฐานข้อมูลเปลี่ยนแปลง ', 
    baoCunShengCheng:  ' บันทึกและสร้าง ', 
    ziDuanPeiZhi:  ' การกำหนดค่าฟิลด์ ', 
  },
  index: {
    shengCheng:  ' สร้าง ', 
         xiaZai:  ' ดาวน์โหลด ', 
        yuLan: '预览',
    caoZuo:  ' การดำเนินการ ', 
         beiZhu:  ' หมายเหตุ ', 
    ziFuBianMaJi:  ' ดูตัวอย่าง ', 
    shuJuKuYinQing:  ' คลังฐานข้อมูล ', 
    biaoMing:  ' ชื่อตาราง ', 
    qingShuRuBiaoMing:  ' กรุณากรอกชื่อตาราง ', 
  },
};
