export default {
  App: {
    jianTing:  ' กำลังฟัง 11111 ', 
  },
  home: {
    keFuYiBeiJin:  ' บริการลูกค้าถูกปิดใช้งาน ', 
    haoDeWoQuPei:  ' ตกลง ฉันจะไปกำหนดค่า ', 
    ninYiXiaDeJi:  ' ยังไม่ได้กำหนดค่าข้อความต้อนรับส่วนตัวของคุณสำหรับกลุ่มทักษะต่อไปนี้ โปรดกำหนดค่าให้เสร็จสิ้นก่อนเข้าสู่ระบบในโต๊ะทำงาน ', 
         gongNengKaiFaZhong:  ' กำลังพัฒนาฟังก์ชั่น.... ', 
         yeLiHao:  ' ราตรีสวัสดิ์! ', 
    wanShangHao:  ' สวัสดีตอนกลางคืน! ', 
    bangWanHao:  ' สวัสดีตอนกลางคืน! ', 
    xiaWuHao:  ' สวัสดีตอนกลางคืน! ', 
    zhongWuHao:  ' สวัสดีตอนบ่าย! ', 
    shangWuHao:  ' สวัสดีตอนเช้า! ', 
    zaoShangHao:  ' สวัสดีตอนเช้า! ', 
    lingChenHao:  ' สวัสดีตอนเช้า! ', 
    keFuLieBiao:  ' รายการบริการลูกค้า ', 
    keHuLieBiao:  ' รายชื่อลูกค้า ', 
    shiShiJianKong:  ' การตรวจสอบตามเวลาจริง ', 
    keFuGongZuoTai:  ' โต๊ะทำงานบริการลูกค้า ', 
    kuaiSuKaiShiBian:  ' เริ่มต้นอย่างรวดเร็ว / การนำทางที่สะดวก ', 
    shangCiDengLuShi:  ' \n เวลาเข้าสู่ระบบครั้งล่าสุด:\n ', 
    zhouDaoDeFuWu:  ' )\n การบริการที่เอาใจใส่เป็นวิธีเดียวที่จะชนะใจลูกค้า!!! \n ', 
    zhouDaoDeFuWu2:  ' ")\n การบริการที่เอาใจใส่เป็นวิธีเดียวที่จะได้รับความไว้วางใจจากลูกค้าของเรา!!! ', 
    zhuNinKaiXinMei:  ' เราหวังว่าคุณจะมีความสุขในวันนี้! ', 
  },
  login: {
    jiesuonidezhanghao:  ' โปรดติดต่อผู้ดูแลระบบเพื่อปลดล็อกบัญชีของคุณ! ', 
    haoDeWoZhiDao:  ' โอเค ฉันเข้าใจแล้ว ', 
    ninDeZhangHaoMi:  ' บัญชี/รหัสผ่านของคุณถูกป้อนผิดหลายครั้งเกินไป บัญชีถูกล็อคและไม่สามารถเข้าสู่ระบบได้! ', 
    zhangHaoYiBeiSuo:  ' บัญชีถูกล็อค ', 
    zhongShi:  ' ลองอีกครั้ง ', 
    wangLuoYiChangQing:  ' เครือข่ายผิดปกติ โปรดลองอีกครั้ง! ', 
    yanZhengMaBuNeng:  ' รหัสยืนยัน (ห้ามเว้นว่าง) ', 
         yongHuMingBuNeng:  ' ชื่อผู้ใช้ (ห้ามเว้นว่าง) ', 
        'dot': ' ⋅ ',
    haoDeYiYongG:  ' ตกลง ผูกกับ Google Authenticator แล้ว ', 
    woYiShiYongG:  ' \n ฉันใช้ Google Authenticator โดยการสแกนรหัสเพื่อผูก \n ', 
    qingNinXianDaKai:  ' \n โปรดเปิด Google Authenticator ก่อนแล้วสแกนรหัสเพื่อผูก จากนั้นเข้าสู่ระบบ \n ', 
    gaiZhangHuHaiWei:  ' บัญชียังไม่ได้ผูกกับ Goolge Authenticator และไม่สามารถเข้าสู่ระบบได้ ', 
    saoMiaoErWeiMa:  ' สแกนคิวอาร์โค้ด ', 
    dengLu:  ' เข้าสู่ระบบ ', 
    jiZhuWo:  ' \n จำฉันไว้\n ', 
    yanZhengMaXianShi:  ' หากรหัสยืนยันไม่ปรากฏขึ้น โปรดลองล้างแคชของเบราว์เซอร์และเข้าเบราว์เซอร์ใหม่หรือเปลี่ยนเบราว์เซอร์ ', 
    qingShuRuGO:  ' โปรดป้อนรหัสยืนยันของ Google ', 
    yanZhengMa:  ' รหัสยืนยัน ', 
         zhangHao:  ' บัญชี ', 
    nCSPB:  ' \n B sport admin system\n ', 
  },
};
