export default {
    caiJiNeiRongXiang:  ' รายละเอียดเนื้อหาคอลเลกชัน ', 
      'dota': '…',
    neiCunXinXi:  ' ข้อมูลหน่วยความจำ ', 
         cPUZongShu:  ' จำนวนซีพียูทั้งหมด ', 
    shiFouYouSD:  ' มี SD การ์ดหรือไม่ ', 
    pingMuGaoDu:  ' ความสูงของหน้าจอ ', 
    pingMuKuanDu:  ' ความกว้างของหน้าจอ ', 
    keHuDuanDiLi:  ' ที่ตั้งทางภูมิศาสตร์ของหน้าลูกค้า ', 
    lianWangLeiXing:  ' ประเภทเครือข่าย ', 
    jieRuYuMing:  ' เข้าถึงชื่อโดเมน ', 
         ziXunWenTiLei:  ' ประเภทคำถามให้คำปรึกษา ', 
    faQiQingQiuLu:  ' เส้นทางขอ ', 
    faQiQingQiuJie:  ' เริ่มต้นอินเทอร์เฟซคำขอ ', 
    keHuDuanBanBen:  ' เวอร์ชันหน้าลูกค้า ', 
         caiJiLieBiao:  ' รายการรวบรวม ', 
    caiJiXiangQing:  ' รายละเอียดรวบรวม ', 
    caoZuo:  ' การดำเนินการ ', 
         diLiWeiZhi:  ' ที่ตั้ง ', 
    caiJiJieMianMing:  ' ชื่อส่วนต่อประสานรวบรวม ', 
    xiTongHuanJing:  ' สภาพแวดล้อมของระบบ ', 
    zhongDuanLeiBie:  ' ประเภทเทอร์มินัล ', 
    wenTiLeiXing:  ' ประเภทปัญหา ', 
    zhangHuMing:  ' ชื่อบัญชี ', 
    tiJiaoShiJian:  ' เวลายื่น ', 
    quanBu:  ' ทั้งหมด ', 
    qingXuanZeZhongDuan:  ' โปรดเลือกประเภทเทอร์มินัล ', 
         qingXuanZeXiTong:  ' กรุณาเลือกสภาพแวดล้อมของระบบ ', 
     };
