export default {
  customerTypeSetting: {
        sERGR: '【{val1}】邀请【{val2}】的邀请配置？',
  },
  inviteIndex: {
         qingXianXuanZe:  ' กรุณาเลือกก่อน! ', 
    jiNengZuMing:  ' ชื่อกลุ่มทักษะ ', 
         keYaoQingDeJi:  ' กลุ่มทักษะที่เชิญได้ ', 
         yaoQingJiNengZu:  ' เชิญกำหนดค่ากลุ่มทักษะ ', 
    yaoQingPeiZhi:  ' เชิญกำหนดค่า ', 
    suoYouJiNengZu:  ' กลุ่มทักษะทั้งหมด ', 
    suoYouKeHuZu:  ' กลุ่มลูกค้าทั้งหมด ', 
    suoYouKeFuZu:  ' กลุ่มบริการลูกค้าทั้งหมด ', 
    yaoQingKeHuPei:  ' เชิญกำหนดค่าลูกค้า ', 
    yaoQingKeHuLei:  ' เชิญกำหนดค่าประเภทลูกค้า ', 
  },
  inviteSetting: {
    chengGong:  ' สำเร็จ ', 
              youXianYaoQingGao:  ' เชิญผู้ใช้คิวระดับสูงก่อน ', 
         kaiQi:  ' เปิด ', 
    youXianYaoQingYao:  ' ให้ความสำคัญกับการเชิญผู้ใช้ที่มีทักษะการจับคู่ก่อน ', 
         dengDaiShiJianChang:  ' ลูกค้าคิวที่มีเวลารอนานจะถูกจัดเรียงก่อน ', 
    youXianYaoQingDeng:  ' เชิญผู้ใช้ที่มีเวลารอนานก่อน ', 
         liVIPYong:  ' ตัวอย่าง: ผู้ใช้ VIP2>ผู้ใช้ VIP>ผู้ใช้ผู้เยี่ยมชม ', 
         youXianYaoQingJi:  ' เชิญผู้ใช้ที่มีทักษะการจับคู่ก่อน ', 
    paiDuiKeHuPai:  ' กฎการเรียงลำดับคิวลูกค้า ', 
    kaiQiHouNengGou:  ' "หลังจากเปิดใช้งาน การบริการลูกค้าที่สามารถเชิญลูกค้า VIP ได้จะแสดงเฉพาะลูกค้า VIP ที่อยู่ในคิวและเชิญการสนทนาเมื่อมีลูกค้า VIP ที่อยู่ในคิว เมื่อไม่มีลูกค้า VIP ที่อยู่ในคิ วจะแสดงเฉพาะลูกค้าปกติและลูกค้าผู้เยี่ยมชมที่อยู่ในคิว V เข้าร่วมสนทนาได้ ', 
    vIPKeHu:  ' ลูกค้าVIPได้รับเชิญก่อน ', 
    paiDuiKeHuXian:  ' กฎการแสดงคิวของลูกค้า ', 
        'con': '：',
  },
};
