export default {
  addKey: {
    xiuGaiChengGong: "แก้ไขเรียบร้อยแล้ว", 
    tianJiaChanPin: "เพิ่มสินค้า", 
    xiuGaiChanPin: "แก้ไขสินค้า", 
    shi: "ใช่", 
    fou: "ไม่", 
    shiFouJieRuZhong: "เข้าสู่ระบบหลังบ้านหรือไม่", 
    qiYong: "เปิดใช้งาน", 
    jinYong: "ปิดการใช้งาน", 
    zhuangTai: "สถานะ", 
    siYao: "คีย์ส่วนตัว", 
    gongYao: "คีย์สาธารณะ", 
    moRenHuanYingYu: "ข้อความต้อนรับเริ่มต้น", 
    zhuTiSe: "สีของธีม", 
    yingYongLeiXing: "ประเภทแอปพลิเคชัน", 
    chanPinID: "ไอดี สินค้า", 
  },
  keyIndex: {
    ninQueDingShanChu: "คุณแน่ใจหรือไม่ที่จะลบบันทึกของ [{val3}] ที่เชื่อมโยงกับ [{val1} (ID{val2})]", 
    bianJiChengGong: "แก้ไขสำเร็จ!", 
    chanPinLieBiao: "รายการสินค้า", 
    xiuGai: "แก้ไข", 
    gengXinShiJian: "เวลาอัปเดต", 
    chuangJianShiJian: "เวลาที่สร้าง", 
    qingShuRuChanPin: "กรุณาใส่ชื่อสินค้า", 
    qingShuRuYingYong: "โปรดป้อนพอร์ตแอปพลิเคชัน", 
    qingShuRuYingYong2: "กรุณากรอกชื่อแอปพลิเคชัน", 
    suoYouYingYongLei: "แอปพลิเคชันทุกประเภท", 
    suoYouZhuangTai: "สถานะทั้งหมด", 
    chanPinZhuangTai: "สถานะสินค้า", 
  },
};
