export default {
  addKey: {
        xiuGaiChengGong: '修改失败！',
    tianJiaChanPin:  ' เพิ่มสินค้า ', 
    xiuGaiChanPin:  ' แก้ไขสินค้า ', 
         fou:  ' ไม่ ', 
    shiFouJieRuZhong:  ' เข้าสู่ระบบหลังบ้านหรือไม่ ', 
    qiYong:  ' เปิดใช้งาน ', 
    jinYong:  ' ปิดการใช้งาน ', 
    zhuangTai:  ' สถานะ ', 
    siYao:  ' คีย์ส่วนตัว ', 
    gongYao:  ' คีย์สาธารณะ ', 
    moRenHuanYingYu:  ' ข้อความต้อนรับเริ่มต้น ', 
    zhuTiSe:  ' สีของธีม ', 
    yingYongLeiXing:  ' ประเภทแอปพลิเคชัน ', 
    chanPinID:  ' ไอดี สินค้า ', 
  },
  keyIndex: {
         bianJiChengGong:  ' แก้ไขสำเร็จ! ', 
    chanPinLieBiao:  ' รายการสินค้า ', 
         gengXinShiJian:  ' เวลาอัปเดต ', 
    chuangJianShiJian:  ' เวลาที่สร้าง ', 
    qingShuRuChanPin:  ' กรุณาใส่ชื่อสินค้า ', 
              suoYouYingYongLei:  ' แอปพลิเคชันทุกประเภท ', 
    suoYouZhuangTai:  ' สถานะทั้งหมด ', 
    chanPinZhuangTai:  ' สถานะสินค้า ', 
  },
};
