export default {
  addKey: {
        xiuGaiChengGong: '修改失败！',
    tianJiaChanPin: "เพิ่มสินค้า", 
    xiuGaiChanPin: "แก้ไขสินค้า", 
    shi: "ใช่", 
    fou: "ไม่", 
    shiFouJieRuZhong: "เข้าสู่ระบบหลังบ้านหรือไม่", 
    qiYong: "เปิดใช้งาน", 
    jinYong: "ปิดการใช้งาน", 
    zhuangTai: "สถานะ", 
    siYao: "คีย์ส่วนตัว", 
    gongYao: "คีย์สาธารณะ", 
    moRenHuanYingYu: "ข้อความต้อนรับเริ่มต้น", 
    zhuTiSe: "สีของธีม", 
    yingYongLeiXing: "ประเภทแอปพลิเคชัน", 
    chanPinID: "ไอดี สินค้า", 
  },
  keyIndex: {
    ninQueDingShanChu: "คุณแน่ใจหรือที่จะลบ [{val1}(ID{val2})]?", 
    bianJiChengGong: "แก้ไขสำเร็จ!", 
    chanPinLieBiao: "รายการสินค้า", 
    xiuGai: "แก้ไข", 
    gengXinShiJian: "เวลาอัปเดต", 
    chuangJianShiJian: "เวลาที่สร้าง", 
    qingShuRuChanPin: "กรุณาใส่ชื่อสินค้า", 
    qingShuRuYingYong: "กรุณากรอกชื่อแอปพลิเคชัน", 
    qingShuRuYingYong2: "กรุณากรอกเลขที่แอปพลิเคชัน", 
    suoYouYingYongLei: "แอปพลิเคชันทุกประเภท", 
    suoYouZhuangTai: "สถานะทั้งหมด", 
    chanPinZhuangTai: "สถานะสินค้า", 
  },
};
