export default {
  editDialog: {
    bianJiChengGong: "แก้ไขสำเร็จ!", 
    danXuan: "เลือกเดี่ยว", 
    weiXin: "วีแชท", 
    shouJiHao: "หมายเลขโทรศัพท์มือถือ", 
    fou: "ไม่", 
    shi: "ใช่", 
    shiFouBiTian: "จำเป็นต้องกรอกหรือไม่", 
    lianXiFangShi: "ข้อมูลติดต่อ", 
    liuYanTuPian: "รูปภาพข้อความ", 
    qingShuRuNeiRong: "โปรดป้อนการแจ้งเตือนเนื้อหา", 
    liuYanNeiRong: "เนื้อหาข้อความ", 
    ziXunWenTi: "ปรึกษาปัญหา", 
    xingXingBie: "นามสกุล(เพศ)", 
    keHuZhangHao: "หมายเลขบัญชีลูกค้า", 
    liuYanBanZiDuan: "กระดานฝากข้อความ", 
        tianXieShengR: '请必须填写你生日'
  },
  index: {
    ninShiFouQueDing: "คุณแน่ใจหรือไม่ว่าต้องการให้ {val1}ลูกค้า VIP ได้รับเชิญเป็นกฎข้อแรก", 
    languageTemplate: "(ภาษา: {val1})", 
    sheZhi: "ตั้งค่า", 
    xuanTian: "ไม่จำเป็น", 
    biTian: "จำเป็นต้องกรอก...", 
    liuYanZiDuanShe: "การตั้งค่าฝากข้อความ", 
    keHuLiuYanDang: "หากข้อความของลูกค้าเกินจำนวนครั้งในวันนั้น จะไม่สามารถทิ้งข้อความได้อีก", 
    shiFouKaiQiLiu: "ต้องการเปิดฟังก์ชั่นฝากข้อความหรือไม่", 
    liuYanSheZhi: "การตั้งค่าฝากข้อความ", 
    zhiNengShuRuDa: "ป้อนได้เฉพาะตัวเลขที่มากกว่า 0 เท่านั้น", 
    qingShuRu: "กรุณากรอก", 
    liuYanTuPian: "รูปภาพข้อความ", 
    liuYanNeiRongBi: "\n เนื้อหาข้อความ (จำเป็น)\n", 
    ziXunWenTiBi: "\n คำถามปัญหา (จำเป็น)\n", 
    xingXingBieBiTian: "\n นามสกุล(เพศ)\n(จำเป็น)\n", 
    keHuZhangHaoBi: "\n หมายเลขบัญชีลูกค้า (จำเป็น)\n", 
    meiRiZuiDuoLiu: "จำนวนข้อความสูงสุดต่อวัน", 
    bianJi: "แก้ไข", 
    baoCun: "บันทึก", 
  }
}
