export default {
    wuYuLanNeiRong:  'No preview content display', 
    qinAiDeYongHu:  'Dear user！', 
    buKeChaoGuoGe:  'Cannot exceed 150 characters', 
    dingShiFaSong:  'Scheduled sending', 
    liJiFaSong:  'send immediately', 
    faSongShiJian:  'sending time', 
    yuLanAPP:  'Preview APP effect', 
    yuLanPCXiao:  'Preview PC effect', 
    neiRong:  'content', 
    biaoTi:  'heading', 
    faSongZhi:  'send to', 
    baoCunShiBaiD:  'Save failed.{val1}', 
    gongXiNiCaoZuo:  'Congratulations, the operation is successful', 
    qingXuanZeRiQi:  'Please choose date！', 
    qingShuRuNeiRong:  'Please input content！', 
    daiChong:  'top up on behalf of others', 
    zhuZhangHuYuE:  'main account balance', 
    vIPZhuangTai:  'VIP status', 
    vIPDengJi:  'VIP level', 
    cengJiZhuangTai:  'level status', 
    wanJiaCengJi:  'player level', 
    piLiangDaiChong:  'top up on behalf of others in batch', 
    piLiangBeiZhu:  'Batch Remarks', 
    qingShuRuDiSan:  'please input third party account name', 
    diSanFangZhangHu:  'third party account name', 
    yaoQingRen:  'inviter', 
    niCheng:  'nickname', 
    biaoQianLeiXing:  'label type', 
    tianJiaRen:  'added by', 
    tianJiaShiJian:  'added time', 
    biaoQianMingCheng:  'label name', 
    tianJia:  'add', 
    qingXuanZeBiaoQian:  'Please select a label name', 
    biaoQianGuanLi:  'Tag management', 
    gongXiNinShanChu:  'Congratulations，deleted successful！', 
    gongXiNinTianJia:  'Congratulations，added successful！', 
    yongHuBeiZhu:  'user remark', 
    yongHuZhuangTai:  'user status', 
    shengYuDaiChongE:  'Remaining top up on behalf by other amount', 
    vIPDengJi2:  'VIP level record', 
    shenHeShiJian:  'audit time', 
    shenQingLiYou:  'Application reason', 
    caoZuoLeiBie:  'Operation category', 
    tiBiDiZhiT:  'Withdrawal address: {val1}', 
    jinYanYuanYin:  'Reason for mute', 
    jinYanJieShuShi:  'Mute end time', 
    jinYanShiChang:  'Mute time', 
    jinYanKaiShiShi:  'Muting start time', 
    sheBeiHaoDE:  'Device ({val1}) added successfully', 
    queRenShiFouYao:  'Are you sure you want to add this device number as a trusted device?', 
    tianJiaKeXinShe:  'Add trusted device ({val1})', 
    tiaoZhengFangShi:  'Adjustment method', 
    tiaoZhengHou:  'after adjust', 
    tiaoZhengQian:  'before adjust', 
    tiaoZhengShiJian:  'adjust time', 
    qingXuanZeTiaoZheng:  'Please select the adjustment method', 
    qingXuanZeTiaoZheng2:  'please choose level after adjustment', 
    qingXuanZeTiaoZheng3:  'please choose level before adjustment', 
    queRen:  'confirm', 
    xinZengKeXinShe:  'Add trusted device', 
    xinZeng:  'new', 
    sheBeiJiLuD:  'Device record ({val1}) deleted successfully', 
    keXinSheBeiHao:  'trusted device number', 
    buKeChaoGuoWei:  'Cannot exceed 100 characters', 
    xiuGaiBeiZhu:  'modify remark', 
    shouDongTiaoZheng:  'mannually adjustment', 
    shouDongTiaoZhengShen:  'mannually adjustment auditing', 
    jinBiXinXi:  'Coin information', 
    jinBiYuE:  'Coin balance', 
    pingTaiTongJi:  'platform statistics', 
    huiYuanShuYing:  'member win and lose', 
    youXiaoTouZhu:  'valid bet', 
    touZhuJinE:  'bet amount', 
    huiZong:  'summary', 
    pingTai:  'platform', 
    yuLe:  'casino', 
    tiYuDianJing:  'esport', 
    liuShuiXiangQing:  'turnover detail', 
    tiXianLiuShuiXin:  'Withdrawal turnover information', 
    liuShuiKaiShiTong:  'turnover starting calculate time', 
    shengYuLiuShui:  'remaining turnover', 
    yiWanChengTouZhu:  'already finished bet turnover', 
    suoXuLiuShui:  'required turnover', 
    yongHuYuE:  'user balance', 
    zongPaiCai:  'totally bonus', 
    hongLi:  'bonus', 
    wanJiaShuYing:  'player win and loss', 
    fINAN:  '{val1}times（normal{val2}times，large amount{val3}times', 
    daiChongCiShu:  'times of top up on behalf of others', 
    daiChongZongE:  'total amount of top up on behalf of others', 
    yuEZongJi:  'Total balance:', 
    zhuanRu:  'transfer to', 
    yiJianHuiShou:  'One-click recover', 
    baoJiJingYanZhi:  '(Relegation) experience value:', 
    baoJiShiJian:  'relegation time', 
    shengJiJingYanZhi:  '(Upgrade) EXP:', 
    zuiJinDaDaoDang:  'recently time to reach current level:', 
    shengJiTiKuanCi:  '(Upgrade) time to withdrawals:', 
    chaKanMingXi:  'view details', 
    vIPShengJi:  'VIP upgrade progress', 
    zhongZhiYinHangKa:  'Reset bank card auditing', 
    huiYuanDuanSheZhi:  'Member side settings', 
    tiXianAnQuan:  'withdraw security', 
    touZhuSheZhi:  'betting settings', 
    panKouSheZhi:  'handicap settings', 
    fanShuiLingQu:  'Rebate collection', 
    shouCunShiJian:  'first deposit time', 
    shouCunJinE:  'first deposit amount', 
    gongXiNiJieSuo:  'Congratulations, you have successfully unlocked the VIP level', 
    gongXiNiSuoDing:  'Congratulations, you have successfully locked the VIP level', 
    shiFouISL:  'Whether {val1} VIP level', 
    gongXiNiXiuGai:  'Congratulations, you have successfully modified the VIP level', 
    shouDongLingQu:  'collect by mannually', 
    ziDongLingQu:  'automatic collect', 
    ziDongJieShouRen:  'Automatically accept any odds', 
    buJieShouRenHe:  'Do not accept any odds changes', 
    ziDongJieShouGeng:  'Automatically accept better odds', 
    ouPan:  'European handicap', 
    gangPan:  'Hongkong handicap', 
    dengJiSuoDing:  'level lock', 
    qingShuRuDaiLi:  'please input affiliate account name', 
    taiWan:  'Taiwan+886', 
    xiangGang:  'Hong kong+852', 
    aoMen:  'Macau+853', 
    daLu:  'China+86', 
    bianJiBiaoQian:  'edit label', 
    dangQianYeXiaoJi:  'Current Page Subtotal', 
    daoZhangJinE:  'Receipt amount:', 
    chongZhiJinE:  'deposit amount ：', 
    chengGongJiLuShu:  'Number of successful records:', 
    hongBaoJinE:  'angpao amount', 
    liSanBeiShu:  'discrete multiple', 
    fanLiBi:  'Rebate ratio', 
    sanFangYongHuLei:  'Three-party user type', 
    yinHangKaYongHu:  'Bank card user type', 
    yongHuShuXing:  'user characteristic', 
    hongBaoGuoQiShi:  'angpao expiration time', 
    hongBaoFaFangShi:  'angpao distribution time', 
    chongZhiChuangJianShi:  'deposit release time', 
    chongZhiDaoZhangJin:  'deposit received amount', 
    faFangShiJian:  'release time', 
    miLeHuiYuanRi:  'ML member day promotion', 
    yinHangKaHuoDong:  'Bank card promotion', 
    fuLiZhongXin:  'benefit center', 
    jiangLi:  'reward', 
    cunKuanJinE:  'deposit amount', 
    dangQianYeHuiZong:  'Summary of Current Page/Summary of All Pages', 
    huoDongShiJian:  'promotion time', 
    renWuNUM:  'mission{val1}', 
    vIPYueDu:  'VIP monthly bonus', 
    vIPShengRi:  'VIP birthday bonus', 
    vIPShengJi2:  'VIP upgrade bonus', 
    haoYouLiuShuiFen:  'Friends turnover divided', 
    shouCunBeiTuiJian:  'Referral rewards for the first deposit', 
    shouCunTuiJianJiang:  'First Deposit Referral Award', 
    si:  'four（如是按第四名，英文是Fourth）', 
    san:  'three（如是按第三名，英文是Third）', 
    er:  'two（如是按第二名，英文是Second）', 
    yi:  'one（如是按第一名，英文是First）', 
    jinBiShangCheng:  'Coin Mall', 
    haoYouTuiJian:  'friends referral', 
    shouDongFaFang:  'Manual release', 
    fuLiZhuangTai:  'benefit status', 
    fuLiBianHao:  'Benefit Number', 
    ziHuoDong:  'sub promotion', 
    huoDongMingCheng:  'promomtion name', 
    jiangPinMingCheng:  'Prize name', 
    fuLiLeiXing:  'bonus type', 
    jiangPinBianHao:  'Prize number', 
    jiuHuoDongMingCheng:  'old promotion name', 
    xinHuoDongMingCheng:  'new promotion name', 
    faJianXiang:  'send mail box', 
    shouJianXiang:  'recive mail box', 
    kuaiSuHuiFu:  'Quick Reply', 
    huiYuanShiFouYi:  'Whether the member has read', 
    huiFuRen:  'reply mail', 
    leiBie:  'type', 
    shouJianShiJian:  'recived mail time', 
    qingShuRuNeiRong2:  'please input content', 
    shiFouYiDu:  'readed or not', 
    faJianRen:  'sender', 
    xiFenLeiBie:  'distinguish type', 
    xinJianLeiBie:  'letter type', 
    qingShuRuBiaoTi:  'please input title', 
    qingShuRuXiFen:  'please enter distinguish type', 
    qingShuRuXinJian:  'please enter mail type', 
    shanChuShiBaiD:  'delete failed!{val1}', 
    shanChuChengGong:  'delete successful！', 
    queDingYaoShanChu:  'Are you sure you want to delete tihs announcement?', 
    shanChuGongGao:  'delete announcement', 
    shangYue:  'last month', 
    benZhou:  'this week', 
    zhanNeiXin:  'inbox', 
    jiangLiMingXi:  'reward details', 
    zhuDanGuanLi:  'bets order number', 
    mODAL:  '{val1}`\n }', 
    caoZuoShiBai:  'Operation failed！', 
    xianYouBiaoQian:  'current label', 
    piLiangZengJiaBiao:  'Add tags in batches', 
    caoZuoChengGong:  'Operation successful！', 
    biTian:  'must fill in', 
    tiaoZhengLiYou:  'adjustment reason', 
    tiaoZhengHouJinBi:  'gold coin amount after adjustment', 
    tiaoZhengJinBi:  'adjustment gold coin', 
    dangQianJinBi:  'gold coin amount', 
    tiaoZhengHuiYuanJin:  'adjustment member gold coin', 
    jinBiTiaoZhengShen:  'adjustment gold coin apply successful～', 
    zuiDuoGeZiFu:  'Max limited 15 character', 
    beiZhuXinXi:  'remark message', 
    qingShuRuWeiShu:  'please input 6 character number fund password', 
    ziJinMiMa:  'fund password', 
    bei:  'times', 
    qingShuRuLiuShui:  'Please enter the turnover multiple', 
    liuShuiBeiShu:  'Turnover multiple', 
    yuan:  'RMB', 
    qingShuRuDaiChong:  'please enter the amount of top up on behalf', 
    daiChongJinE:  'amount of top up on behalf of others', 
    bALAN:  '{val1}RMB', 
    qingShuRuDaiLi2:  'Please enter the affiliate account', 
    shouCunFuLi:  'first deposit benefit', 
    fuLi:  'benefit', 
    gongXiNiChongZhi:  'Congratulations，deposit successful', 
    dATAF:  '{val1} accounts deposit failed', 
    queDingWeiUS:  'confirm top up on behalf by other for{val1}those member ？', 
    queRenDaiChong:  'confirmed top up on behalf of others', 
    cANOT:  'Accounts such as {val1} cannot be deposit, please delete', 
    uSERN:  'The total amount of {val1} account top up on behalf by other cannot exceed the remaining amount', 
    zhangHaoBuNengChao:  'Accounts cannot exceed 20', 
    tiaoZhengYuanYin:  'adjustment reason', 
    daiLiTiaoZhengWei:  'affiliate adjusted to', 
    piLiangXiuGaiDai:  'modify affiliate in batch', 
    piLiangCaoZuoCheng:  'Batch operation succeeded {val1}', 
    piLiangCaoZuoCheng2:  'Batch operation succeeded {val1}, failed {val2} , failure reason: {val3}', 
    bianGengWeiDaiLi:  'Change to affiliate account', 
    dangQianDaiLi:  'current affiliate', 
      qieJiDaiLiYue:    '切忌：代理月结算数据报表生成期间，不要进行玩家变更代理的更换。',
      zhuYiWanJiaBian:    '注意：玩家变更代理需要谨慎操作，会造成代理输赢日报表的数据差异',
    zhongYaoTiXing:  'important reminder', 
    wanJiaZhangHuMing:  'Player account name: {val1}', 
    zhanNeiXinXiangQing:  'details in the inbox', 
    zhengWen:  'content', 
    faSongHuiYuan:  'send to member', 
    faBuShiJian:  'posted time', 
    huiFu:  'reply', 
    miaoShu:  'describe', 
    zhangHu:  'account', 
    jieShouShiJian:  'receiving time', 
    miaoShuTuPian:  'describe the picture', 
    huiFuNeiRong:  'reply content', 
    huiFuShiJian:  'response time', 
    qingShuRuShenQing:  'Please enter the reason for requesting deletion', 
    shenQingShanChuQian:  'Apply to delete wallet address', 
    kuaiJieDaoChu:  'quickly export', 
    congZhongXinQianBao:  'Transfer from central wallet to {val1}', 
    yiGouXuanSE:  'ticked{val1}data', 
    dangQianCengJi:  'current level', 
    cengJiXiuGaiWei:  'level changed to', 
    iSMUL:  '{val1}', 
    dATAS:  '{val1} user level modified successfully', 
    yiGouXuanSE2:  'ticked{val1}data', 
    iSMUL2:  '{val1}', 
    sELEC:  '{val1} and other {val2} accounts', 
      shiFouXuYaoPi:    '是否需要批量解锁选中的账户VIP等级？解锁后的账户会受VIP升降级规则限制',
    piLiangJieSuoV:  'Unlock VIP levels in batches', 
    yiXiaZhangHaoBu:  'below account does not exist：{val1}', 
    yiGouXuanSE3:  'ticked{val1}data', 
    buKeChaoGuoWei2:  'Cannot exceed 30 characters', 
    qingShuRuGE:  'please enter{val1}', 
    qingTianRuHuiYuan:  'Please fill in the member's new account remarks', 
    shanChuBangDingDe:  'Delete the bound mobile phone/email/bank card/USDT withdrawal address', 
    ninYiChengGongFa:  'You have successfully initiated {val1} {val2} operations, please wait for audit', 
    shiBaiPiLiangU:  'Failed to batch {val1}{val2} operations, failure reason: {val3}', 
    niYiChengGongFa:  'You have successfully initiated {val1} {val2} operations, failed {val3} \n {val4} operations, failure reason: {val5}', 
    ninYiChengGongFa2:  'You have successfully initiated {val1} {val2} operations, please wait for audit', 
    uSERL:  '{val1} failed, failure reason: {val2}', 
    shuRuTiaoZhengLiu:  'Enter the adjusted turnover amount (negative numbers minus, positive numbers plus)', 
    queDingXuYaoJiang:  'confirm to clear the user's turnover?', 
    queDingYaoQingChu:  'confirm to delete this turnover requirement?', 
    queDingYaoHuiFu:  'confirm to recover this turnover requirement?', 
    liuShuiQingLing:  'clear the turnover', 
    qingChuLiuShui:  'delete the turnover', 
    huiFuLiuShui:  'recover the turnover', 
    tiaoZhengLiuShui:  'adjust the turnover', 
    shuGuangKaiShiTong:  'start statistics time of loss all', 
    yiWanChengLiuShui:  'Turnover has been completed', 
    liuShuiXuQiu:  'turnover requirement', 
    shuaXin:  'refresh', 
    dangQianLiuShuiXin:  'current turnover details', 
    tiXianLiuShuiXiang:  'withdraw turnover details: {val1}', 
    bianDongHouLiuShui:  'Turnover after change', 
    bianDongQianLiuShui:  'Turnover before change', 
    liuShuiJinE:  'Turnover amount', 
    zhangBianJinE:  'Account change amount', 
    xiFenLeiXing:  'distinguish type', 
    bianDongLeiXing:  'change type', 
    caoZuoDanHao:  'operation order number', 
    zhangBianShiJian:  'Account change time', 
    liuShuiZhangBianMing:  'turnover account change details', 
    qingShuRuCaoZuo:  'please enter an operator', 
    qingShuRuCaoZuo2:  'please enter the operation order number', 
    touZhuJiLu:  'bet records', 
    jiaoYiJiLu:  'trading records', 
    eDuXiangQing:  'Quota details', 
    quKuanJiLu:  'withdrawal records', 
    cunKuanJiLu:  'deposit records', 
    zhuCeSheBei:  'register equipment', 
    zhuCeSheBeiHao:  'register equipment number', 
    zhuCeYuMing:  'register domain', 
    zuiHouDengRuI:  'Last login IP', 
    zuiHouDengRuRi:  'last login date', 
    zhuCeRiQi:  'registration date', 
    yaoQingRenID:  'inviter ID', 
    shengRi:  'date of birth', 
    huiYuanZhangHao:  'member account', 
    chuXianWeiZhiCuoWu:  'An unknown error occurred! error code is', 
    beiZhu:  'remark', 
};
