export default {
    faFangZhong:  'distributing', 
    yiLingQu:  'collected', 
    juJue:  'reject', 
    daiFaFang:  'to be issued', 
    xuNiTiYu:  'esport', 
    xiaoJinZhenRen:  'little gold casino', 
    shuangYingCaiPiao:  'double win lottery', 
    quanBingMuXuanKu:  'Full screen (cool)', 
    puTong:  'normal', 
    pingYong:  'mediocre', 
    erShenBuTongGuo:  'failed the second audit', 
    erShenTongGuo:  'Passed the second audit', 
    erShenWeiShenHe:  'Not yet audit in the second audit', 
    yiShenBuTongGuo:  'failed the first audit', 
    chuShenTongGuo:  'Passed the first audit', 
    yiGuoQi:  'expired', 
    daiLingQu:  'to be collected', 
    yiFaHuo:  'Shipped', 
    weiLingQu:  'uncollected', 
    buKeLingQu:  'not available', 
    yiShiYong:  'used', 
    weiShiYong:  'Unused', 
    faFangShiBai:  'Issue failed', 
    faFangChengGong:  'Issued successfully', 
    yiLingQuDaiFa:  'Picked up (to be shipped)', 
    keLingQu:  'waiting to collect', 
    yiDaBiaoWeiLing:  'Achieved but not received', 
    vIPJingYan:  'vip experience value', 
    liuShuiQuan:  'turnover coupon', 
    xianJinQuan:  'cash coupon', 
    cunSongQuan:  'deposit and reward coupon', 
    shiWu:  'real item', 
    laoHuJiJiuJi:  'Slot Machine Relief promotion', 
    shouCunHuoDong:  'first deposit promotion', 
    tiYuChuangGuanHuo:  'Sports Breakthrough Promotion', 
    zhenRenChuangGuanHuo:  'Casino Breakthrough Promotion', 
    fanShuiHuoDong:  'rebate promotion', 
    xingYunDaZhuanPan:  'Lucky Wheel Promo', 
    yinHangKaChongZhi:  'Bank card deposit and send angpao promotion', 
    yinHangKaZhuanZhang:  'Bank card transfer (including Alipay transfer)', 
    xuNiBiZhiFu:  'virtual currency payment', 
    quanBuQuDao:  'all channel', 
    leiJiChongZhi:  'Cumulative deposit', 
    danCiChongZhi:  'single deposit', 
    xuYao:  'need', 
    buXuYao:  'dont need', 
    jinBi:  'coin', 
    vIPChengZhang:  'vip growth value', 
    xianJin:  'cash', 
    fou:  'no', 
    shi:  'yes', 
    fuYingLi:  'negative profit', 
    shangZhouLiuShuiZong:  'Sum of last week's turnover', 
    shangZhouChongZhiZong:  'Total deposit last week', 
    wuEWaiQuanZhong:  'no extra strength', 
    puTongChouJiang:  'normal draw', 
    songLi:  'gift giving', 
    guanKan:  'watch', 
    dangRiDanCiChong:  'Single deposit on the day', 
    dangRiLeiJiChong:  'Cumulative recharge of the day', 
    renYiTouZhuQuan:  'Any bet (full platform)', 
    youXiaoTouZhuQuan:  'Valid Betting (All Platforms)', 
    huoYueDengLu:  'active login', 
    aPPDengLu:  'app login', 
    pCDuanDengLu:  'pc login', 
    hDuanDengLu:  'H5 login', 
    renYiDuanDengLu:  'Log in from any side', 
    shaiDan:  'post orders', 
    faYan:  'speak', 
    yuLeDuanDengLu:  'casino login', 
    tiYuDuanDengLu:  'Sports login', 
    hDuanDengLu2:  'H5 login', 
    renYiDuanDengLu2:  'Log in from any side', 
    zhiBo:  'live', 
    chongZhi:  'deposit', 
    dengLu:  'login', 
    huoYueDengLu2:  'active login', 
    aPPDengLu2:  'app login', 
    touZhu:  'bet', 
    dianJingPingTai:  'E-sports platform', 
    tiYuPingTai:  'sport platform', 
    zhuBo:  'anchor', 
    dengLu2:  'login', 
    xiaoYuDengYu:  'less than or equal to', 
    daYuDengYu:  'greater or equal to', 
    leiJiYingLi:  'cumulative profit', 
    leiJiTouZhu:  'Accumulated betting', 
    cunKuanShuaiJianWan:  'deposit decay player', 
    touZhuShuaiJianWan:  'betting decay players', 
    shangTouWanJia:  'top player', 
    banLiuShiWanJia:  'half lost player', 
    huoYueTianShu:  'active days', 
    zhouQiNeiBuXian:  'Unlimited within the certain cycle', 
    meiRiYiCi:  'once per day', 
    leiJiZhengYingLi:  'cumulative positive profit', 
    leiJiYouXiaoTou:  'cumulative valid bet', 
    jinTian:  'today', 
    shangZhou:  'last week', 
    zuoTian:  'yesterday', 
    fanShuiMoBanDan:  'deposit template (single)', 
    chongZhiSongLiMo:  'deposit gift template', 
    miLeHuiYuanRi:  'M6 membership day template', 
    miLeHuiYuanRi2:  'M6 membership day template (single)', 
    yeMianXianShiMo:  'page display template', 
    jieQingHuoDongMo:  'festival promotion template', 
    xinRenHuoDongMo:  'Newcomer member template', 
    chouJiangHuoDongMo:  'draw promotion template', 
    shouCunMuBan:  'First deposit template', 
    tongYongBaiFenBi:  'Through Percentage Promotion Template', 
    tongYongHuoDongMo:  'ThroughPromotion Template', 
    vIPChongZhi:  'VIP deposit template', 
    saiShiMuBan:  'matches template', 
    jingCaiChouJiangMo:  'quiz raffle template', 
    paiMingJiangLiMo:  'Rank Reward Template', 
    qiTaYouHui:  'other promotion', 
    fanShuiYouHui:  'rebate promotion', 
    dianZiYouHui:  'slot promotion', 
    caiPiaoYouHui:  'lottery promotion', 
    tiYuYouHui:  'sport promotion', 
    zhenRenYouHui:  'casino promotion', 
    hDuan:  'H5', 
    yuLeDuan:  'casino side', 
    tiYuDuan:  'sport side', 
    xianShiKaiFang:  'Open for a limited time', 
    zanBuKaiFang:  'temporarily closed', 
    wuXianQiKaiFang:  'open indefinitely', 
    guanFangMoShiFen:  'Official mode (divided into)', 
    xinYongMoShiFen:  'Creditl mode (divided into)', 
    guanFangMoShiChou:  'Official Mode (Rake)', 
    shanChuUSD:  'Delete USDT withdrawal address', 
    shenQingRenGongBang:  'Apply for manual card binding', 
    daiLiZhuanZhangDao:  'Affiliate transfer to member account', 
    xiangShangJiDaiLi:  'Transfer money to superior affiliate', 
    xiangXiaJiDaiLi:  'Transfer money to downline affiliate', 
    sheZhiDaiLiXin:  'Set aff credit limit', 
    sheZhiDaiLiKe:  'Set the affiliate's cash withdrawal limit', 
    xiuGaiDaiLiZhuan:  'Modify affiliate transfer settings', 
    xiuGaiDaiLiYong:  'Modify Affiliate Commission Chain Rules', 
    xiuGaiDaiLiShou:  'Modify affiliate fee rules', 
    xiuGaiHuiYuanDai:  'Modify member top up on behalf of others permissions', 
    xiuGaiDaiLiShou2:  'Modify affiliate credit authority', 
    daiChongQingSuanRen:  'top up on behalf of others settlement-mannual operation settlement', 
    daiChongQingSuanYin:  'top up on behalf of others settlement-bank card deposit settlement', 
    xiuGaiDaiLiChuang:  'Modify the affiliate to create sub affiliate permissions', 
    shouXinYuDaiChong:  'Changes to credit and top up on behalf of others settings', 
    daiChongFanLiFang:  'change of top up on behalf of others rebate scheme', 
    shouDongCengJiBian:  'Manual change level', 
    daiLiLeiXingBian:  'Affiliate Type Change', 
    daiChongQingSuanZhang:  'top up on behalf of others settlement-account balance settlement', 
    xiuGaiShangFenShe:  'modify deposit settings', 
    shanChuYinHangKa:  'delete bank card', 
    jieChuSuoDing:  'unlock', 
    dengLuSuoDing:  'login locked', 
    zhongZhiYinHangXin:  'reset bank information', 
    bianGengLianXiFang:  'change contact information', 
    bianGengShangJiDai:  'Change the superior affiliate', 
    tiXianEDuTiao:  'Withdrawal limit adjustment', 
    xiuGaiXiangXiaJi:  'Modify the transfer settings to downline affiliate', 
    sheZhiXinYongE:  'set credit limit', 
    waiBuDaiLi:  'external affiliate', 
    xiuGaiDaiLiAn:  'Modify affiliate security password', 
    xiuGaiDaiLiZi:  'Modify the affiliate fund password', 
    chuangJianXiaJiDai:  'Create sub-affiliates', 
    jieBangYinHangKa:  'Unbind bank card', 
    youXiangZhaoHuiDeng:  'forget email-login password', 
    shouJiZhaoHuiDeng:  'forget mobile - login password', 
    xiuGaiMiMa:  'change Password', 
    bangDingShouJi:  'bind phone', 
    bianJiXingBie:  'edit gender', 
    bianJiShengRi:  'edit birthday', 
    yueJieSuan:  'monthly settlement', 
    banYueJieSuan:  'semi-monthly settlement', 
    zhouJieSuan:  'Weekly settlement', 
    yongJinTiaoZheng:  'commission adjustment', 
    cuoWuDaiChongKou:  'top up on behalf of others amount by mistake and deduct', 
    jianBi:  'deduct coin', 
    tiXianShiBaiTui:  'Withdrawal failed to return', 
    renGongChongZhi:  'Manual deposit', 
    jiaBiBuJiHong:  'add on coin (excluding bonuses)', 
    tiKuan:  'withdraw', 
    cunKuan:  'deposit', 
    xiaJiSuoDing:  'downline lock', 
    benJiSuoDing:  'this level lock', 
    xiaJiDaiLi:  'Sub-affiliate', 
    huiYuanXianXiaTi:  'Member offline withdrawal', 
    cuoWuChongZhiKou:  'Incorrect depositand return amount(affiliate)', 
    daiLiTiKuan:  'affiliate withdraw', 
    xuNiEDu:  'virtual quota', 
    daiChongZhangHuTiao:  'top up on behalf of others adjust', 
    huiYuanDaiChongKou:  'top up on behalf of others deduct', 
    xiTongKouHui:  'system deduct', 
    cuoWuChongZhiKou2:  'wrong deposit and deduct（member）', 
    youXiBuFenB:  'Game rebate points-BT Sports', 
    youXiBuFenM:  'Game rebate points-M6 Sports', 
    youXiBuFenV:  'Game rebate points-VR Lottery', 
    youXiBuFenMi:  'Game rebate points-M6 Lottery', 
    youXiBuFen:  'gaming rebate points', 
    cuoWuDaiChongJia:  'wrong top up on behalf of others amount and deduct', 
    zhuanZhangBuFen:  'Transfer and replace deposit', 
    jiaBiBuJiRu:  'add on coin (excluding bonuses)', 
    daiLiHuoDong:  'affiliate promotion', 
    hongBao:  'angpao', 
    huoDongHongLi:  'promotion bonus', 
    jiaBiJiRuHong:  'add currency - including bonus', 
    youXiBuFenL:  'Game rebate points-LB Lottery', 
    youXiBuFenB2:  'Game rebate points-BB Lottery', 
    erShenJuJue:  'second audit reject', 
    yiShenJuJue:  'first audit reject', 
    tongGuo:  'approval', 
    wuCaoZuo:  'no action', 
    yiShanChu:  'deleted', 
    shiYongZhong:  'using', 
    xiTongCheXiao:  'System undo', 
    zhuDongCheDan:  'initiative undo', 
    xiTongCheDan:  'System undo', 
    weiZhongJiang:  'didn't win', 
    yiZhongJiang:  'has won', 
    weiKaiJiang:  'Not yet drawn', 
    wuXiaoDingDan:  'invalid order', 
    yiQuXiao:  'cancelled', 
    yiJieSuan:  'Settled', 
    weiJieSuan:  'Unsettlement', 
    cuoWuShangFenKou:  'wrong deposit and deduct', 
    shangFenCaoZuo:  'deposit operation', 
    yingChaoHuoDong:  'Premier League promotion', 
    vIPJiangLi:  'VIP Rewards - Monthly VIP Angpao', 
    vIPJiangLi2:  'VIP Rewards - Birthday gift', 
    vIPJiangLi3:  'VIP Rewards - Upgrade bonus', 
    duanWuJieHuoDong:  'dragon boat festival promotion', 
    chunJieHuoDongHong:  'Chinese New Year Promotion - Angpao Rain Bonus', 
    chunJieHuoDongTi:  'Chinese New Year Promotion - Sports Deposit and Withdrawal Bonus', 
    chunJieHuoDongZa:  'Chinese New Year Promotion - Smashing Golden Egg Bonus', 
    zhenRenChuangGuanHong:  'Casino breakout bonus', 
    laoHuJiJiuYuan:  'slot relief bonus', 
    tiYuChuangGuanHong:  'Sports Breakthrough Bonus', 
    zhenRenLianYingHong:  'Casino Streak Bonus', 
    shouChongHongLi:  'first deposit bonus', 
    hongLiBaoKuoJia:  'bonus（including add coin-counting in bonus）', 
    tiXianDongJieJin:  'Withdrawal freeze amount', 
    zhongXinQianBao:  'center wallet', 
    fengXianChuLiRen:  'risk handler', 
    zhuanZhangYiChangJian:  'Abnormal transfer monitoring', 
    daETiXian:  'large amount withdraw', 
    fuShuQianBao:  'Negative number wallet', 
    tiXianSheBeiChong:  'Withdrawal device conflict', 
    tiXianIPChong:  'Withdrawal IP conflict', 
    riLeiJiJinE:  'The cumulative amount in the 7th day is too large', 
    liRunYiChang:  'abnormal profit', 
    pinFanTiXian:  'Frequent withdrawals', 
    dangRiJinEGuo:  'The amount of the day is too large', 
    danBiJinEGuo:  'The single amount is too large', 
    shouTiJinEGuo:  'The first time withdrawal amount is too large', 
    fengXianShenHeGe:  'Risk audit on hold', 
    fengXianShenHeTong:  'Risk audit passed', 
    laoHuiYuan:  'old member', 
    xinHuiYuan:  'new member', 
    chuKuanZhuanYuanChu:  'The payment specialist is processing', 
    daiLiTiXian:  'affiliate withdrawal', 
    puTongTiXian:  'Normal withdrawal', 
    yiChuLi:  'settled', 
    quanLiangYongHu:  'All users', 
    zhiDingYongHu:  'assigned members', 
    daiLiAPP:  'affiliate app', 
    huiYuanAPP:  'member app', 
    quDaoBao:  'channel pack', 
    guanWangBao:  'Official website pack', 
    danBiTouZhu:  'single bet', 
    chaiDanTouZhu:  'Split betting', 
    tiXian:  'withdraw', 
    chongZhiShiBai:  'deposit failed', 
    chongZhiChengGong:  'deposit successful', 
    zhiXingWanBi:  'Finished', 
    zhengChangYunXing:  'normal operation', 
    zanTing:  'pause', 
    guanWangYuMing:  'Official website domain name', 
    daiLiZhuanShuYu:  'affiliate exclusive domain name', 
    xiaZai:  'download', 
    gengXin:  'renew', 
    quanBuYongHu:  'All users', 
    tianJiaYongHuZu:  'add to user group', 
    aPPXiaZai:  'APP download affiliate domain name', 
    pXDDYu:  'pxdd domain name configuration', 
    tiYuSSA:  'sports ssapi domain name', 
    aPPKeFu:  'app customer service secondary line ip', 
    aPPKeFu2:  'App customer service main line ip', 
    keFuCiXianLu:  'customer service secondary line ip', 
    keFuZhuXianLu:  'Customer service main line ip', 
    daiLiYuMing:  'affiliate domain name', 
    ziXunYuMing:  'Information domain name', 
    lIVEC:  'livechat customer service system ip address', 
    zhiChiKeFuXi:  'Wisdom tooth customer service system ip address', 
    huoQuSaiGuoYu:  'Get the result domain name', 
    liaoTianShiJuBao:  'Chat room report domain name', 
    liaoTianShiYuMing:  'chat room domain name', 
    qiuDuiTuBiaoYu:  'team icon domain', 
    tiYuHYuMing:  'Sports H5 domain name', 
    pUSHYu:  'push domain name', 
    aPPXiaZai2:  'app download domain name', 
    shouJiYuMing:  'mobile domain name', 
    pCYuMing:  'PC domain name', 
    sTKeFuS:  'ST customer service SDK', 
    sTKeFu:  'ST customer service', 
    lIVEC2:  'livechat customer service', 
    zhiChiKeFu:  'Wisdom teeth customer service', 
    zhiChiKeFuXi2:  'Wisdom tooth customer service system', 
    lIVEC3:  'livechat customer service system', 
    jiuXu:  'ready', 
    daiJiaZai:  'to be loaded', 
    yuanShengLeiXing:  'native type', 
    jianDanLeiXing:  'simple type', 
    buTongGuo:  'Fail', 
    anShiJianFanWei:  'Delete by time range', 
    anDanHaoShan:  'Delete by order number', 
    zhiXingZhong:  'in execution', 
    zhiXingShiBai:  'Execution failed', 
    zhiXingChengGong:  'execution succeed', 
    daiZhiXing:  'to be executed', 
    yiChang:  'abnormal', 
    dTDianZi:  'DT slot', 
    iMTiYu:  'IM sport', 
    bGZhenRen:  'BG casino', 
    bTTiYu:  'BT sport', 
    bBCaiPiao:  'BB lottery', 
    fanYaDianJing:  'Fan Asia E-sports', 
    mWBuYu:  'MW Fishing', 
    iMDianJing:  'IM esport', 
    pPDianZi:  'PP slot', 
    beiBoQiPai:  'BB Chess', 
    huanLeQiPai:  'Fun chess', 
    lBCaiPiao:  'LB lottery', 
    bBTiYu:  'BB sport', 
    pTDianZi:  'PT slot', 
    eBETZhen:  'EBET Casino', 
    aGYouXi:  'AG gaming', 
    youXiYuEDa:  'Users whose game balance is greater than 0', 
    iMDianJingSai:  'IM e-sports settlement', 
    liuHeCai:  'Mark Six', 
    feiLiuHeCai:  'Not Mark Six', 
    touZhuShiJian:  'betting time', 
    buFen:  'part', 
    linShi:  'temporary', 
    yongJiu:  'permanent', 
    kouJian:  'deduction', 
    qingLing:  'clear', 
    shouDong:  'manual', 
    ziDong:  'automatic', 
    erShenWeiTongGuo:  'Failed the second audit', 
    yiShenWeiTongGuo:  'Failed in the first audit', 
    shouGongTiaoZheng:  'manual adjustment', 
    yiShiXiao:  'expired', 
    tiXianTuiHuiShi:  'Withdrawal returned failed', 
    tiXianShiBai:  'Withdrawal failed', 
    jiaBi:  'Add coins', 
    shangJiZhuanRuDai:  'Transfer from superior (deposit)', 
    zhuanZhangShiBai:  'transfer failed', 
    tiXianChengGong:  'Successful withdrawal', 
    xiTongXiaoXiSuo:  'System Messages (Locked)', 
    xiTongXiaoXiZi:  'System Messages (Funds)', 
    huiFuXinJian:  'reply letter', 
    puTongXinJian:  'normal letter', 
    yiFaSong:  'Has been sent', 
    daiFaSong:  'to be sent', 
    yiDu:  'Have read', 
    weiDu:  'unread', 
    yiHuiFu:  'Replied', 
    daiHuiFu:  'pending reply', 
    weiChuLi:  'unprocessed', 
    cengJiBianGeng:  'level change', 
    xiuGaiPeiZhiXia:  'Modify the configuration of downline deposit settings', 
    qingKongDangQianLiu:  'Clear current turnover limit', 
    qingSuanShangFenE:  'Clearing deposit quota', 
    xiuGaiDaiLiFan:  'Modify the affiliate rebate mode', 
    zhongZhiYinHangKa:  'Reset bank card information', 
    bianGengShouJiHao:  'Change mobile number or email', 
    xinZengUSD:  'Add USDT withdrawal address', 
    zhuanJiaGuanZhuQu:  'Advisor follow/unfollow', 
    shanChuShouHuoDi:  'delete shipping address', 
    bianJiShouHuoDi:  'Edit shipping address', 
    xinJianShouHuoDi:  'New shipping address', 
    fanShuiSheZhi:  'Rebate Settings', 
    tiXianDuanXinYan:  'Cash withdrawal SMS verification', 
    bangDingYouXiang:  'Bind email', 
    chaoShiWeiLingQu:  'Not collected after timeout', 
    yiFaHuoLieBiao:  'Shipped List', 
    daiLingQuLieBiao:  'wait for collecting list', 
    daiFaHuoYiLing:  'Pending Shipment/Collected List', 
    yinHangKaChongZhi2:  'Bank card deposit promotion', 
    fuLiChunJieHong:  'Benefit Happy Chinese New Year Festival Angpao', 
    huiYuanJiaJieFu:  'Member Festive Benefits', 
    bBZhouNianQing:  'BB Anniversary Promotion', 
    nBAHuoDong:  'NBA promotion', 
    aoDaLiYaJia:  'A-League', 
    zhongQiuJieHuoDong:  'Mid-autumn festival promotion', 
    meiZhouBeiHuoDong:  'Copa América promotion', 
    chunJieHuoDongTi2:  'Chinese New Year Promotion-Sports Deposit and Withdrawal', 
    chunJieHuoDongHong2:  'Chinese New Year Promotion - Angpao Rain', 
    chunJieHuoDongZa2:  'Chinese New Year Promotion - Smashing Golden Eggs', 
    laoHuJiJiuYuan2:  'slot relief promotion', 
    zhenRenLianYingHuo:  'Casino streak promotion', 
    fanShuiLiJin:  'Rebate bonus', 
    nengLiangDian:  'energy point', 
    mianFeiCaiJin:  'free bonus', 
    kuiSunBuTieQuan:  'Loss Subsidy Coupon', 
    zhongJiangFanLiQuan:  'Winning coupons', 
    touZhuFanLiQuan:  'betting and rebate coupons', 
    chongZhiFanLiQuan:  'Deposit coupon (valid for one time)', 
    shiWuJiangLi:  'Real item rewards', 
    vIPYueDu:  'VIP Monthly Rewards', 
    vIPShengJi:  'VIP Upgrade Rewards', 
    vIPShengRi:  'VIP Birthday Rewards', 
    daiFuKuanJiSu:  'Pending payment (fast card transfer)', 
    daiQueRenDaoZhang:  'To be confirmed into the account (fast card transfer)', 
    buFenTuiHuiCheng:  'Partially return was successful (extremely fast card transfer)', 
    buFenTuiHuiZhong:  'Some are being returned (extremely fast card transfer)', 
    chaoShiWeiQueRen:  'Unconfirmed after timeout (Extremely fast card transfer)', 
    chaoShiWeiQueRen2:  'The account has not been confirmed after timeout', 
    daiQueRenDaoZhang2:  'To be confirmed', 
    shuZiHuoBi:  'digital currency', 
    weiZhi:  'unknown', 
    nu:  'Female', 
    nan:  'male', 
    moRen:  'default', 
    youXi:  'game', 
    huiYuanDaiChongHui:  'Top up on behalf of others by member rebate', 
    daiChongCaoZuo:  'Top up on behalf of others operation', 
    jianBiTuiHui:  'deduct coin and refund', 
    shangFenFanLi:  'deposit and rebate', 
    vIPDengJi:  'VIP level-Monthly VIP angpao', 
    vIPDengJi2:  'VIP Level-Birthday Gift', 
    vIPDengJi3:  'VIP level-upgrade gift money', 
    huiFuShenHeZhong:  'resume auditing', 
    qingChuShenHeZhong:  'clear auditing', 
    yiQingChu:  'cleared', 
    jiaBiBuJiHong2:  'add coins - excluding bonuses', 
    huoDongHongLiFan:  'Promotion Bonus-Rebate promotion', 
    jiaBiDaiLiBu:  'add coins - affiliate department add coins (excluding bonuses)', 
    jiaBiCaiWuBu:  'add coins - financial department add coins(excluding dividends)', 
    jiaBiHuoDongHong:  'add coins - promotion bonus (included in bonus)', 
    jiaBiHongBaoJi:  'Add coins - angpao (included in bonuses)', 
    shangFen:  'deposit', 
    meiYueVIP:  'Monthly VIP angpao', 
    shengJiLiJin:  'upgrade bonus', 
    shengRiLiJin:  'birthday gift', 
    weiSuoDing:  'unlocked', 
    yiSuoDing:  'locked', 
    liXian:  'offline', 
    zaiXian:  'online', 
    dengLuChengGong:  'login successful', 
    dengLuShiBaiBu:  'Login failed - department locked', 
    dengLuShiBaiBu2:  'Login failed - department does not exist', 
    dengLuShiBaiGang:  'Login failed - post locked', 
    dengLuShiBaiGang2:  'Login failed - post does not exist', 
    dengLuShiBaiZhang:  'Login failed - account has expired', 
    dengLuShiBaiZhang2:  'Login failed - account does not exist', 
    dengLuShiBaiZhang3:  'Login failed - account locked', 
    dengLuShiBaiGu:  'Login failed - google verification error', 
    dengLuShiBaiYong:  'Login failed - wrong username and password', 
    shenHeGeZhi:  'audit on hold', 
    xiuGaiYaoQingJiang:  'Modify Invitation Rewards', 
    xiuGaiHaoYouLei:  'Modify friend type', 
    meiCiDengRu:  'every login', 
    fuChuang:  'floating window', 
    tanChuang:  'Pop-up notification', 
    yiJieShu:  'over', 
    jinXingZhong:  'processing', 
    weiKaiShi:  'has not started', 
    zhuanShuYuMing:  'Exclusive domain name', 
    puTongYuMing:  'normal domain name', 
    daiLiZhangHao:  'affiliate account', 
    yin:  'INDO', 
    ma:  'MY', 
    gang:  'HK', 
    ou:  'EURO', 
    weiTouZhuShiJian:  'Unbetted time', 
    weiCunKuanShiJian:  'Undeposit time', 
    weiDengLuShiJian:  'Not logged in time', 
    jinXianALaBai:  'Arabic numeral integers only', 
    shuBan:  'lose half', 
    yingBan:  'win half', 
    he:  'draw', 
    quanShu:  'lose', 
    quanYing:  'win', 
    xiaoJin:  'little gold', 
    daXiaoQiu:  'Over/Under', 
    jiaoQiuDaXiao:  'Corners kicks Over/Under', 
    daiTiJiao:  'to be submitted', 
    hTMLWen:  'HTML text', 
    yiJinYong:  'disabled', 
    yiQiYong:  'activated', 
    zhuanJiaBaoLiaoTui:  'Advisor predictions push', 
    fuLiZhongXinTui:  'benefit center push', 
    zhuBoTuiSong:  'anchor push', 
    saiShiTuiSong:  'match push', 
    huoDongTuiSong:  'promotion push', 
    tian:  '10 days', 
    tian2:  '3 days', 
    tian3:  '1 days', 
    xiaoShi:  '12 hours', 
    xiaoShi2:  '3 hours', 
    xiaoShi3:  '1 hour', 
    zhuanJiaBaoLiaoFa:  'Advisor predictions publish', 
    zhuBoDongTaiFa:  'Anchor post publish', 
    zhuBoShangXian:  'The anchor is online', 
    meiYueHongBao:  'monthly angpao', 
    vIPJinJi:  'VIP promotion bonus', 
    suoYouYongHu:  'all users', 
    yiCheXiao:  'canceled', 
    yiTuiSong:  'pushed', 
    daiTuiSong:  'to be pushed', 
    dingShiTuiSong:  'Timing push', 
    liJiTuiSong:  'Push now', 
    xuNiShuJu:  'virtual data', 
    zhenShiShuJu:  'real data', 
    daiZhuanZhang:  'pending transfer', 
    chuanGuan:  'parley', 
    danChang:  'single game', 
    zhong:  'Three gain Two', 
    zhong2:  'Three gain One', 
    zhong3:  'Two gain One', 
    hei:  'black', 
    hong:  'red', 
    zhiDing:  'top', 
    tanChuWenBen:  'popup text', 
    tiaoZhuanYeMian:  'jump page', 
    tiaoZhuanSaiShi:  'jump match', 
    dianJing:  'esport', 
    daiLiXiaJiHui:  'affiliate's downline member', 
    xiaoShi4:  'Hour', 
    fenZhong:  'minute', 
    tuiGuangSuCaiYuan:  'Promotional material original picture', 
    zengSongTuiGuangTu:  'Gift promotion picture', 
    zanZhuTuiGuangTu:  'Sponsorship promotion picture', 
    aPPTuiGuang:  'app promotion picture', 
    daiLiAND:  'affiliate-Android side', 
    daiLiIOS:  'affiliate-IOS side', 
    daiLiHDuan:  'affiliate-H5 side', 
    daiLiPCDuan:  'affiliate-PC', 
    huiYuanAND:  'Member-Android side', 
    huiYuanIOS:  'Member-IOS side', 
    huiYuanHDuan:  'Member-H5 side', 
    huiYuanPCDuan:  'Member-PC side', 
    vIPShengJi2:  'VIP upgrade turnover', 
    liJin:  'bonus', 
    diGuan:  'Level 10', 
    diGuan2:  'Level 9', 
    diGuan3:  'Level 8', 
    diGuan4:  'Level 7', 
    diGuan5:  'Level 6', 
    diGuan6:  'Level 5', 
    diGuan7:  'Level 4', 
    diGuan8:  'Level 3', 
    diGuan9:  'Level 2', 
    diGuan10:  'Level 1', 
    yOPLA:  'yoplay slot machine', 
    xINLaoHu:  'XIN slot machine', 
    aGINLao:  'AGIN slot machine', 
    aGBuYu:  'AG Fishing', 
    aGDianZi:  'AG slot', 
    aGZhenRen:  'AG casino', 
    huLue:  'ignore', 
    ziDongJieJin:  'Automatically unlock', 
    renGongJieJin:  'manual unlock', 
    jinYan:  'mute', 
    jinYanZhong:  'muting', 
    juBaoCiShu:  'Number of Reports<', 
    juBaoCiShu2:  'Number of Reports>', 
    waiBuLaQu:  'external pull', 
    benZhanHuiYuan:  'Member of this site', 
    shangJiZhuanRuDai2:  'Transfer from superior (Top up on behalf of others )', 
    xiTongXiaoXiZi2:  'System Messages (Funds)', 
    xiTongXiaoXiSuo2:  'System Messages (Locked)', 
};
