export default {
  editDialog: {
    bianJiChengGong:  ' แก้ไขสำเร็จ! ', 
    touXiangXiuGaiShi:  ' แก้ไขรูปโปรไฟล์ล้มเหลว ', 
                   keFuNiChengBu:  ' ชื่อเล่นของฝ่ายบริการลูกค้า(ห้ามเว้นว่าง) ', 
    shangChuanTouXiang:  ' อัพโหลดรูปโปรไฟล์ ', 
         quXiao:  ' ยกเลิก ', 
    liRuGaiKeFu:  ' ตัวอย่างเช่น หากมีการเพิ่มกลุ่มทักษะใหม่ 1 ในฝ่ายบริการลูกค้า ข้อความต้อนรับของกลุ่มทักษะ 1 จะเป็นการกำหนดค่าเริ่มต้น ', 
    peiZhiLeXinDe:  ' หลังจากกำหนดค่ากลุ่มทักษะใหม่ ระบบจะกำหนดค่าข้อความต้อนรับให้กับกลุ่มทักษะใหม่ของฝ่ายบริการลูกค้าโดยอัตโนมัติ ', 
    shuoMing:  ' คำอธิบาย. ', 
    xinJiNengZuHuan:  ' ข้อความต้อนรับกลุ่มทักษะใหม่: ', 
         jiNengZu:  ' กลุ่มทักษะ ', 
              keFuZhuangTai:  ' สถานะการบริการลูกค้า ', 
    keFuNiCheng:  ' ชื่อเล่นฝ่ายบริการลูกค้า ', 
    qingXianXuanZe:  ' กรุณาเลือกก่อน! ', 
         suoShuDaiLi:  ' ตัวแทนในเครือ ', 
    keFuLeiXing:  ' ประเภทการบริการลูกค้า ', 
         bianJiKeFu:  ' แก้ไขการบริการลูกค้า - ', 
  },
  limitDialog: {
    jieDaiShangXianShe:  ' ตั้งค่าขีดจำกัดการรับสำเร็จแล้ว! ', 
                             sheZhiKeFuJie:  ' กำหนดขีดจำกัดสูงสุดในการรับบริการลูกค้า -- ', 
  },
  addDialog: {
    fou:  ' ไม่ ', 
         qingShuRuMingCheng:  ' กรุณากรอกชื่อ ', 
    qingShuRuJiNeng:  ' โปรดป้อนข้อความต้อนรับสำหรับกลุ่มทักษะ ', 
    jiNengZuHuanYing:  ' ข้อความต้อนรับสำหรับกลุ่มทักษะ: ', 
    shiFouQiYongLei:  ' เปิดใช้งานการจับคู่ประเภทหรือไม่ ', 
    tuiGuangShangShiFou:  ' มองเห็นผู้สนับสนุนหรือไม่ ', 
    xianShiZeYongHu:  ' ถ้าแสดง ผู้ใช้สามารถเห็นคำถาม; ถ้าไม่แสดง ผู้ใช้จะไม่เห็นคำถาม \n ', 
    xianShiZeYongHu2:  ' ถ้าแสดง ผู้ใช้สามารถเห็นคำถาม; ถ้าไม่แสดง ผู้ใช้จะไม่เห็นคำถาม \n ', 
              qingShuRuJiNeng2:  ' โปรดป้อนชื่อกลุ่มทักษะ ', 
  },
  addMember: {
              dangQianYeVA:  ' หน้าปัจจุบัน: {val1} ', 
    meiYeVAL:  ' {val1} รายการต่อหน้า ', 
    qingShuRuGeRen:  ' กรุณากรอกข้อความต้อนรับส่วนตัว ', 
         qingPeiZhiMoRen:  ' โปรดกำหนดค่าข้อความต้อนรับเริ่มต้น: ', 
  },
  deleteDialog: {
    qingXuanZeYaoYi:  ' โปรดเลือกสมาชิกที่คุณต้องการลบ ', 
    yiChuChengGong:  ' ลบสำเร็จ! ', 
    yiChu:  ' ลบ ', 
    quXiaoGuanLianKe:  ' ยกเลิกการติดต่อฝ่ายบริการลูกค้า ', 
    yiGuanLianKeFu:  ' ติดต่อฝ่ายบริการลูกค้าแล้ว ', 
    keFuZhangHu:  ' บัญชีฝ่ายบริการลูกค้า ', 
  },
  members: {
    chengYuanYiChu:  ' ลบสมาชิก ', 
    congGaiJiNengZu:  ' 】นำออกจากกลุ่มทักษะนี้หรือไม่ \n ', 
    congGaiJiNengZu2:  ' 】นำออกจากกลุ่มทักษะนี้หรือไม่ ', 
    queDingJiangKeFu:  ' \n ยืนยันว่าบริการลูกค้า【 ', 
    zuiJinDengLuShi:  ' เวลาเข้าสู่ระบบครั้งล่าสุด ', 
  },
  skillDialog: {
         jiNengZuGuanLi:  ' การจัดการการบริการลูกค้ากลุ่มทักษะ: ', 
                        zhaKanJiNengZu:  ' ดูกลุ่มทักษะ ', 
  },
  form: {
    suoShuBuMenBu:  ' แผนก(ห้ามเว้นว่าง) ', 
         quXiao:  '\n ยกเลิก \n', 
    xuanZeBuMen:  ' เลือกแผนก ', 
                   yingYongBianHao:  ' เลขที่แอปพลิเคชัน ', 
  },
  header: {
    shuRuGangWeiMing:  ' กรอกชื่อตำแหน่งที่ต้องการค้นหา ', 
    shuRuChanPinMing:  ' กรอกชื่อสินค้า ', 
         shuRuYingYongI:  ' กรอก ไอดี แอปพลิเคชัน ', 
  },
  infoDetail1: {
    fuZhiChengGong:  ' คัดลอกสำเร็จ ', 
         iMEIT:  ' \n IMEI: {val1}\n ความสูงของหน้าจอ: {val2}\n จำนวน CPU ทั้งหมด: {val3}\n ข้อมูลหน่วยความจำ: {val4}\n ความกว้างหน้าจอ: {val5}\n มีการ์ด SD หรือไม่: {val6 }\n อัตราส่วนการใช้งาน CPU: {val7}\n ... : ... \n ', 
         keHuDuanLeiBie2:  ' \n หมวดหมู่ไคลเอ็นต์: {val1}\n เวอร์ชันไคลเอนต์: {val2}\n อินเทอร์เฟซคำขอเริ่มต้น: {val3}\n เส้นทางคำขอเริ่มต้น: {val4}\n ประเภทคำถามสอบถาม: {val5}\n ', 
    suoShuBuMenBu:  ' แผนก(ห้ามเว้นว่าง) ', 
    qingShuRuXuHao:  ' กรุณากรอกหมายเลขซีเรียล ', 
    qingShuRuMingCheng:  ' กรุณากรอกชื่อ ', 
         jiaZaiZhong:  ' กำลังโหลด ', 
    yongHuShangChuan:  ' ผู้ใช้อัปโหลด ', 
         fou:  ' ไม่ ', 
    fuZhi:  ' คัดลอก ', 
    sheBeiXinXi:  ' ข้อมูลอุปกรณ์ ', 
    wangLuoXinXi:  ' ข้อมูลเครือข่าย ', 
    yingYongXinXi:  ' ข้อมูล แอปพลิเคชัน ', 
    quanBuFuZhi:  ' คัดลอกทั้งหมด ', 
    xiTongCaiJi:  ' ระบบรวบรวม ', 
    wenTiLeiXing:  ' ประเภทปัญหา ', 
    caiJiShiJian:  ' เวลารวบรวม ', 
    zhangHuMing:  ' ชื่อบัญชี ', 
  },
  
}
