export default {
  index: {
    woDeBaoBiao:  ' คำชี้แจงของฉัน ', 
             pingJunHuiHuaShi: '平均会话时长',
    jieDaiYaLiZhi:  ' ค่าความกดดันการรับ ', 
        huiFuLu: '回复率',
    jieDaiKeHuShu:  ' จำนวนลูกค้าที่ได้รับ ', 
    keHuKeFuXiao:  ' จำนวนข้อความของลูกค้า/บริการลูกค้า ', 
         keHuPingJiaPing:  ' อัตราคะแนนการประเมินของลูกค้า ', 
              keFuJieJueLu:  ' อัตรา/จำนวน การแก้ปัญหา ', 
        keFuZongJieLu: '客服总结率/数',
    sNeiXiangYingYing:  ' อัตราการตอบกลับภายใน 30 วินาที ', 
    zuiDaXiangYingShi:  ' ระยะเวลาตอบสนองสูงสุด ', 
    pingJunShouXiangShi:  ' ระยะเวลาเสียงกริ่งแรกเฉลี่ย ', 
         zuiDaJieDaiShu:  ' จำนวนการรับสูงสุด ', 
    zhuanChuHuiHuaShu:  ' จำนวนบทสทนาส่งต่อ ', 
    huiHuaShuYouXiao:  ' จำนวนบทสทนา/ที่มีประสิทธภาพ ', 
    mangLu:  ' ยุ่ง ', 
    daoChuBaoBiao:  ' รายงานการส่งออก ', 
    xianShiYinCangKong:  ' แสดง/ซ่อนข้อมูลที่ว่างเปล่า ', 
                  keFuZhangHuNi: '客服账户/昵称：',
  },
};
