export default {
  BarChart: {
    shiJian: "เวลา", 
        'con': '：',
    shiChang: "ระยะเวลา", 
  },
  BarMore: {
    zhiMang: "ยุ่ง", 
    liKai: "ออก", 
    xiLie: "ชุดที่ 2", 
    dengLuZhuangTaiM: "สถานะการเข้าสู่ระบบ (ขั้นต่ำ)", 
    zhanBi: "สัดส่วน:", 
    dengLuShiChang: "ระยะเวลาเข้าสู่ระบบ:", 
    zaiXian: "ออนไลน์", 
  },
  LineChart: {
    huiHuaXiaoXiShu: "จำนวนข้อความบทสนทนา", 
    huiHuaShu: "จำนวนบทสนทนา", 
    huiHuaXiaoXiShu2: "จำนวนข้อความบทสนทนา (อัน)", 
    huiHuaShuGe: "จำนวนบทสนทนา/อัน", 
  },
  index: {
    fenMiao: "0 นาที 0 วินาที", 
    dengLuZhuangTai: "สถานะการเข้าสู่ระบบ", 
    ge: "อัน", 
    fen: "คะแนน", 
    shu: "/จำนวน", 
    huiHuaGuanBiFen: "การวิเคราะห์การปิดบทสนทนา", 
    huiHuaJieRuFang: "วิธีการเข้าถึงบทสนทนา", 
    huiHuaQuDaoFen: "การวิเคราะห์ช่องทางบทสนทนา", 
    huiHuaJiNengZu: "สถิติบทสนทนาของกลุ่มทักษะ", 
    qingXuanZe: "กรุณาเลือก", 
    zuiShaoYaoPeiZhi: "การกำหนดค่าอย่างน้อย 5 รายการ", 
    xiangYingCuoWuQing: "เกิดข้อผิดพลาดในการตอบกลับ โปรดลองอีกครั้งในภายหลัง!", 
    zanWuShuJu: "ไม่มีข้อมูลในขณะนี้", 
    huiHuaFenXi: "การวิเคราะห์บทสนทนา", 
    huiHuaQuXian: "เส้นโค้งบทสนทนา", 
    woDeShuJu: "ข้อมูลของฉัน", 
    shuaXin: "รีเฟรช", 
    sheZhiKanBanCan: "ตั้งค่าพารามิเตอร์ป้ายโฆษณา", 
    zhongZhi: "รีเซ็ต", 
    chaXun: "ตรวจสอบ", 
    suoYouKeFu: "ฝ่ายบริการลูกค้าทั้งหมด", 
  },
};
