export default {
  index: {
    woDeBaoBiao: "คำชี้แจงของฉัน", 
    xiangYingShiChang: "เวลาตอบสนอง", 
        pingJunHuiHuaShi: '平均会话时长',
    jieDaiYaLiZhi: "ค่าความกดดันการรับ", 
        huiFuLu: '回复率',
    jieDaiKeHuShu: "จำนวนลูกค้าที่ได้รับ", 
    keHuKeFuXiao: "จำนวนข้อความของลูกค้า/บริการลูกค้า", 
    dengLuShiChang: "ระยะเวลาการเข้าสู่ระบบ", 
    keHuPingJiaPing: "อัตราคะแนนการประเมินของลูกค้า", 
    keHuPingJiaLu: "อัตรา/จำนวน การให้คะแนนของลูกค้า %", 
    yaoQingPingJiaLu: "อัตรา/จำนวน เชิญประเมิน", 
    keFuJieJueLu: "อัตรา/จำนวน การแก้ปัญหา", 
        keFuZongJieLu: '客服总结率/数',
    sNeiXiangYingYing: "อัตราการตอบกลับภายใน 30 วินาที", 
    zuiDaXiangYingShi: "ระยะเวลาตอบสนองสูงสุด", 
    pingJunShouXiangShi: "ระยะเวลาเสียงกริ่งแรกเฉลี่ย", 
    pingJunXiangYingShi: "ระยะเวลาตอบสนองเฉลี่ย", 
    zuiDaJieDaiShu: "จำนวนการรับสูงสุด", 
    zhuanChuHuiHuaShu: "จำนวนบทสทนาส่งต่อ", 
    huiHuaShuYouXiao: "จำนวนบทสทนา/ที่มีประสิทธภาพ", 
    mangLu: "ยุ่ง", 
    daoChuBaoBiao: "รายงานการส่งออก", 
    xianShiYinCangKong: "แสดง/ซ่อนข้อมูลที่ว่างเปล่า", 
    sheZhiXianShiCan: "ตั้งค่าพารามิเตอร์การแสดงผล", 
    keFuFenZu: "แบ่งกลุ่มบริการลูกค้า", 
        keFuZhangHuNi: '客服账户/昵称：',
  },
};
