export default {
  index: {
    quXiao:  ' ยกเลิก ', 
    queDing:  ' ยืนยัน ', 
         queRenQiangTuiXuan:  ' ยืนยันการบังคับออกจากระบบของผู้ใช้ {val1} หรือไม่ ', 
                   yiZongJie:  ' สรุปผลแล้ว ', 
    weiJieJue:  ' ยังไม่ได้แก้ไข ', 
    yiJieJue:  ' แก้ไขแล้ว ', 
    weiZhiJian:  ' ยังไม่ผ่านการตรวจสอบ ', 
    yiZhiJian:  ' ตรวจสอบแล้ว ', 
    weiPaiDui:  ' ไม่มีคิว ', 
    paiDuiJinRu:  ' เข้าคิว ', 
              yiPingJia:  ' ประเมินแล้ว ', 
         zhiJianRenZhiJian:  ' คนตรวจสอบ/เวลาตรวจสอบ ', 
    zhiJianZhuangTai:  ' สถานะการตรวจสอบ ', 
              shiFouJieJue:  ' แก้ไขแล้วหรือไม่ ', 
    pingJiaLaiYuan:  ' ที่มาการประเมิน ', 
    pingJiaLeiXing:  ' ประเภทการประเมิน ', 
    shiFouPingJia:  ' ประเมินหรือไม่ ', 
    keHuPingJia:  ' การประเมินของลูกค้า ', 
    yeWu:  ' ธุรกิจ ', 
         keFuZongJie:  ' สรุปผลการบริการลูกค้า ', 
        huiHuaLeiXing: '会话类型',
    paiDuiXinXi:  ' ข้อมูลคิว ', 
         wenTiShiChang:  ' คำถาม/ระยะเวลา ', 
    keHuZu:  ' กลุ่มลูกค้า ', 
    keHuQuDao:  ' ลูกค้า/ช่องทาง ', 
         quanXuanJiNengZu:  ' เลือกกลุ่มทักษะทั้งหมด ', 
            },
};
