export default {
  index: {
    woDeBaoBiao: "คำชี้แจงของฉัน", 
    xiangYingShiChang: "เวลาตอบสนอง", 
    pingJunHuiHuaShi: "ความยาวบทสทนาเฉลี่ย", 
    jieDaiYaLiZhi: "ค่าความกดดันการรับ", 
    huiFuLu: "อัตราการตอบสนอง", 
    jieDaiKeHuShu: "จำนวนลูกค้าที่ได้รับ", 
    keHuKeFuXiao: "จำนวนข้อความของลูกค้า/บริการลูกค้า", 
    dengLuShiChang: "ระยะเวลาเข้าสู่ระบบ:", 
    keHuPingJiaPing: "อัตราคะแนนการประเมินของลูกค้า", 
    keHuPingJiaLu: "อัตราการประเมินของลูกค้า %", 
    yaoQingPingJiaLu: "อัตรา/จำนวน เชิญประเมิน", 
    keFuJieJueLu: "อัตรา/จำนวน การแก้ปัญหา", 
    keFuZongJieLu: "อัตรา/จำนวน สรุปผลการบริการลูกค้า", 
    sNeiXiangYingYing: "อัตราการตอบกลับภายใน 30 วินาที", 
    zuiDaXiangYingShi: "ระยะเวลาตอบสนองสูงสุด", 
    pingJunShouXiangShi: "ระยะเวลาเสียงกริ่งแรกเฉลี่ย", 
    pingJunXiangYingShi: "เวลาตอบสนองเฉลี่ย", 
    zuiDaJieDaiShu: "จำนวนการรับสูงสุด", 
    zhuanChuHuiHuaShu: "จำนวนบทสทนาส่งต่อ", 
    huiHuaShuYouXiao: "จำนวนบทสทนา/ที่มีประสิทธภาพ", 
    mangLu: "ยุ่ง", 
    daoChuBaoBiao: "รายงานการส่งออก", 
    xianShiYinCangKong: "แสดง/ซ่อนข้อมูลที่ว่างเปล่า", 
    sheZhiXianShiCan: "ตั้งค่าพารามิเตอร์การแสดงผล", 
    keFuFenZu: "แบ่งกลุ่มบริการลูกค้า", 
    keFuZhangHuNi: "บัญชีฝ่ายบริการลูกค้า/ชื่อเล่น", 
  },
};
