export default {
  addInfoDialog: {
        tuPianShangChuanShi: '图片上传失败',
    tuPianShangChuanCheng:  ' อัปโหลดรูปภาพสำเร็จแล้ว! ', 
    shangChuanDeTuPian:  ' อัตราส่วนของภาพที่อัพโหลดต้องเป็น 2:3 และความกว้างสูงสุดต้องไม่เกิน 120px ', 
              waiBuLianJie:  ' ลิงก์ภายนอก ', 
    neiBuLianJie:  ' ลิงค์ภายใน ', 
         luJingBuNengBao:  ' เส้นทางต้องไม่มีภาษาจีน ', 
    luJingBiXuYi:  ' เส้นทางต้องขึ้นต้นด้วย / ', 
                   qingShuRuUR:  ' โปรดป้อนเส้นทาง URL เช่น:/systemSetting ', 
             lianJieURL2: '链接url路径',
    lianJieLeiXing:  ' ประเภทลิงก์ ', 
    jianYiShangChuanDe:  ' แนะนำให้อัพโหลดภาพขนาด 120*180 ', 
    kuanGaoBiZuiDa:  ' อัตราส่วนภาพ 2:3 ความกว้างสูงสุด 120 ', 
    shuoMing:  ' คำอธิบาย. ', 
    tianJiaTuPian:  ' เพิ่มรูปภาพ ', 
    qingShuRuBiaoTi:  ' กรุณากรอกหัวข้อเรื่องไม่เกิน 6 ตัวอักษร! ', 
    biaoTi:  ' หัวข้อเรื่อง ', 
    tianJiaTuWenTong:  ' เพิ่มการแจ้งเตือนกราฟิก ', 
  },
  index: {
    ninQueRenYaoShan:  ' คุณแน่ใจหรือไม่ว่าต้องการลบประกาศนี้ ', 
    queRenShanChu:  ' ยืนยันการลบ ', 
    xiaJia:  ' เอาออก ', 
    chengGong:  ' สำเร็จ ', 
    shangJia:  ' เอาขึ้น ', 
    gaiTongGao:  ' ประกาศนี้? ', 
    ninQueRenYao:  ' คุณยืนยันที่จะ ', 
    xiangQing:  ' รายละเอียด ', 
    xiaJiaShiJian:  ' เวลาที่เอาออก ', 
    shangJiaShiJian:  ' เวลาที่เอาขึ้น ', 
    tongZhiGuanLi:  ' การจัดการการแจ้งเตือน ', 
    yunWeiXiaJia:  ' ลบผู้ดูแลระบบ ', 
    yunWeiShangJia:  ' ผู้ดูแลระบบอัปโหลด ', 
    sheZhiShangJiaShi:  ' การตั้งค่าเวลาขึ้น ', 
    gengXinShangJiaShi:  ' อัปเดตเวลาขึ้น ', 
    gengXinRiQi:  ' วันที่อัปเดต ', 
    guanLianJiNengZu:  ' กลุ่มทักษะที่เกี่ยวข้อง ', 
    yiXiaJia:  ' เอาลงแล้ว ', 
    weiShangJia:  ' ยังไม่เอาขึ้น ', 
    yiShangJia:  ' เอาขึ้นแล้ว ', 
    tongZhiZhuangTai:  ' สถานะการแจ้งเตือน ', 
              tongZhiID:  ' ไอดี ผู้แจ้ง ', 
    shuoMingPuTongTong:  ' คำอธิบาย: การแจ้งเตือนทั่วไปและการแจ้งเตือนแบบกราฟิกสามารถจัดเก็บได้ในหมวดหมู่เดียวเท่านั้น ไม่สามารถจัดเก็บพร้อมกันได้ การแจ้งเตือนแบบเลื่อนสามารถจัดเก็บได้พร้อมกันกับการแจ้งเตือนทั่วไป/การแจ้งเตือนแบบกราฟิก ', 
    quanXuanJiNengZu:  ' เลือกกลุ่มทักษะทั้งหมด ', 
         quanBuTongZhiLei:  ' ประเภทการแจ้งเตือนทั้งหมด ', 
    quanBuKeFu:  ' ฝ่ายบริการลูกค้าทั้งหมด ', 
    qingShuRuTongZhi:  ' กรุณากรอกชื่อผู้แจ้ง ', 
  },
  richText: {
    danXuan:  ' เลือกเดี่ยว ', 
              qingXuanZhongLianJie:  ' กรุณาตรวจสอบข้อความลิงค์! ', 
         qingTianJiaTuWen:  ' กรุณาเพิ่มกราฟิก ', 
    qingXuanZeShiJian:  ' กรุณาเลือกเวลา ', 
    buShangJia:  ' ไม่เอาขึ้น ', 
    xiaJiaShiJianBi:  ' เวลาเอาลงต้องนานกว่าเวลาเอาขึ้น 5 นาที ', 
    shangJiaShiJianBu:  ' เวลาเอาขึ้นต้องไม่น้อยกว่าเวลาปัจจุบัน! ', 
    qingShuRuXiangQing:  ' กรุณากรอกรายละเอียด! ', 
    puTongTongZhiXiang:  ' รายละเอียดการประกาศทั่วไปต้องมีความยาวไม่เกิน 100 ', 
                       lianJieURL2: '链接url路径:',
    lianJieLeiXing:  ' ประเภทลิงก์ ', 
    lianJieWenZi:  ' ข้อความลิงค์ ', 
    jieShuRiQi:  ' วันที่สิ้นสุด ', 
    kaiShiRiQi:  ' วันที่เริ่มต้น ', 
    shangJiaShiDuan:  ' ระยะเวลาการเอาขึ้น ', 
    buShangJia2:  ' \n ไม่เอาขึ้น \n ', 
    shiFouShangJia:  ' เอาขึ้นหรือไม่ ', 
    xuTongZhiDeJi:  ' กลุ่มทักษที่ต้องการแจ้งให้ทราบ: ', 
    lianJieLuJing:  ' เส้นทางลิงก์ ', 
    tongZhiXiangQing:  ' รายละเอียดการแจ้งเตือน: ', 
              tongZhiPeiZhi:  ' การกำหนดค่าการแจ้งเตือน ', 
  },
  upTime: {
    shangJiaShiJianShe:  ' ตั้งค่าเวลาขึ้นเรียบร้อยแล้ว ', 
    shangJiaSheZhi:  ' ตั้งค่าการเอาขึ้น ', 
  },
};
