export default {
  BarChart: {
    fangWenLaiYuan: "แหล่งที่มาของการเข้าถึง", 
  },
  TimeChart: {
    miao: "วินาที", 
    miao2: "(วินาที)", 
  },
  index: {
    caoZuoChengGong: "การดำเนินการสำเร็จ", 
    quXiao: "ยกเลิก", 
    queDing: "ยืนยัน", 
    qiangZhiXiaXian: "บังคับออฟไลน์", 
    queRenJiangGaiKe: "คุณแน่ใจหรือไม่ว่าจะบังคับบริการลูกค้านี้ให้ออฟไลน์", 
    shu: "/จำนวน", 
    tuiChuPaiDui: "ออกจากคิว", 
    jinRuHuiHua: "ออกจากบทสนทนา", 
    zhuanJieJieRu: "โอนเข้า", 
    paiDuiJieRu: "ต่อแถวเข้าคิว", 
    ziDongJieRu: "เข้าอัตโนมัติ", 
    zongPaiDuiShiChang: "ระยะเวลาการเข้าคิว", 
    pingJunPaiDuiShi: "ระยะเวลาคิวเฉลี่ย", 
    huiHuaShu: "จำนวนบทสนทนา", 
    zaiXianKeFu: "ฝ่ายบริการลูกค้าออนไลน์", 
    caoZuo: "การดำเนินการ", 
    pingJiaLu: "อัตราการประเมิน", 
    yaoQingPingJiaLu: "อัตรา/จำนวน เชิญประเมิน", 
    zongJieLu: "อัตราผลสรุป", 
    liKaiShiChang: "ระยะเวลาที่ออก", 
        zhuangtaiShiChang2:'登录时长 \n 当前状态持续时长',
        jiedaiRenshuShangXian:'接待人数 \n 接待上限',

    
    zaiXianJiNengZu: "กลุ่มทักษะที่ออนไลน์", 
    keFuFenZu: "แบ่งกลุ่มบริการลูกค้า", 
    mangLu: "ยุ่ง", 
    zaiXian: "ออนไลน์", 
    liKai: "ออก", 
    keFuZhangHuMing: "ชื่อบัญชีบริการลูกค้า", 
        sZiDongShuaXin: '30s自动刷新',
    shuaXin: "รีเฟรช", 
    qingShuRuKeFu: "โปรดป้อนตัวแทนฝ่ายบริการลูกค้า", 
    qingShuRuKeFu2: "กรุณากรอกบัญชีบริการลูกค้า", 
        iTEML: 'item.label != `离线`',
    quanBu: "ทั้งหมด", 
    qingXuanZeZaiXian: "กรุณาเลือกสถานะออนไลน์", 
    qingXuanZeKeFu: "โปรดเลือกบริการลูกค้าหรือกําหนดค่าการบริการลูกค้ากลุ่มนี้", 
    quanBuKeFuZu: "กลุ่มบริการลูกค้าทั้งหมด", 
    dangQianZaiXianJie: "สถานการณ์การรับลูกค้าปัจุจบัน", 
    zanWuShuJu: "ไม่มีข้อมูลในขณะนี้", 
    chaXun: "ตรวจสอบ", 
    jinRiHuiHuaGai: "สถานการณ์บทสนทนาของวันนี้", 
    shiShiShuJu: "ข้อมูลเรียลไทม์", 
  },
};
