export default {
  BarChart: {
        fangWenLaiYuan: '访问来源',
  },
  TimeChart: {
    miao: "วินาที", 
    miao2: "(วินาที)", 
  },
  index: {
    caoZuoChengGong: "ดำเนินการสำเร็จ!", 
    quXiao: "ยกเลิก", 
    queDing: "ยืนยัน", 
    qiangZhiXiaXian: "บังคับออฟไลน์", 
    queRenJiangGaiKe: "คุณแน่ใจหรือไม่ว่าจะบังคับบริการลูกค้านี้ให้ออฟไลน์", 
    shu: "จำนวน", 
    tuiChuPaiDui: "ออกจากคิว", 
    jinRuHuiHua: "ออกจากบทสนทนา", 
    zhuanJieJieRu: "โอนเข้า", 
    paiDuiJieRu: "ต่อแถวเข้าคิว", 
    ziDongJieRu: "เข้าอัตโนมัติ", 
    zongPaiDuiShiChang: "ระยะเวลาการเข้าคิว", 
    pingJunPaiDuiShi: "ระยะเวลาคิวเฉลี่ย", 
    huiHuaShu: "จำนวนบทสนทนา", 
    zaiXianKeFu: "แชทสด", 
    caoZuo: "การดำเนินการ", 
    pingJiaLu: "อัตราการประเมิน", 
    yaoQingPingJiaLu: "อัตราคำเชิญประเมินการบริการ", 
    zongJieLu: "อัตราผลสรุป", 
    liKaiShiChang: "ระยะเวลาที่ออก", 
        zhuangtaiShiChang2:'登录时长 \n 当前状态持续时长',
        jiedaiRenshuShangXian:'接待人数 \n 接待上限',

    
    zaiXianJiNengZu: "กลุ่มทักษะที่ออนไลน์", 
    keFuFenZu: "แบ่งกลุ่มบริการลูกค้า", 
    mangLu: "ยุ่ง", 
    zaiXian: "ออนไลน์", 
    liKai: "ออก", 
    keFuZhangHuMing: "รีเฟรชอัตโนมัติ 30 วินาที", 
        sZiDongShuaXin: '30s自动刷新',
    shuaXin: "รีเฟรช", 
    qingShuRuKeFu: "กรุณากรอกตัวแทนฝ่ายบริการลูกค้า", 
    qingShuRuKeFu2: "กรุณากรอกบัญชีบริการลูกค้า", 
        iTEML: 'item.label != `离线`',
    quanBu: "ทั้งหมด", 
    qingXuanZeZaiXian: "กรุณาเลือกสถานะออนไลน์", 
    qingXuanZeKeFu: "กรุณาเลือกกลุ่มทักษะการบริการลูกค้า", 
    quanBuKeFuZu: "ทุกกลุ่มบริการลูกค้า", 
    dangQianZaiXianJie: "สถานการณ์การรับลูกค้าปัจุจบัน", 
    zanWuShuJu: "ยังไม่มีข้อมูล", 
    chaXun: "ตรวจสอบ", 
    jinRiHuiHuaGai: "สถานการณ์บทสนทนาของวันนี้", 
    shiShiShuJu: "ข้อมูลเรียลไทม์", 
  },
};
