export default {
    zhuangTai:  'status', 
    shiJianZhouQi:  'Time period', 
    zuiHouXiuGaiRen:  'last modified by', 
    leiXing:  'type', 
    duanKou:  'side', 
    zhuTi:  'theme', 
    vIPDengJi:  'VIP level', 
    sTATU:  '{val1}success', 
    queDingYaoST:  'Are you sure you want to {val1} this pop-up notifications?', 
    sTATU2:  '{val1} home page pop-up notifications ({val2})', 
    shanChuChengGong:  'successfully deleted', 
    queDingYaoShanChu:  'Are you sure you want to delete this pop-up notifications?', 
    shanChuTanChuangR:  'delete pop-up notifications（{val1}）', 
    tanChuangLeiXing:  'pop-up notifications type', 
    shangChuanTuPian:  'upload picture', 
    tuPianShangChuan:  'upload picture', 
    danChuBinLu:  'popup frequency', 
    tiaoZhuan:  'jump', 
    zhuTi2:  'theme', 
    shiJianZhouQi2:  'Time period', 
    tYPEA:  '{val1}', 
    aPPDanChuang:  'APP popup and floating window settings', 
    xinZeng:  'new', 
    bianJi:  'edit', 
};
