export default {
  index: {
    xiTongNeiZhi: "ระบบในตัว", 
    canShuJianMing: "ชื่อคีย์พารามิเตอร์", 
    canShuMingCheng: "ชื่อพารามิเตอร์", 
    canShuJianZhiBu: "ค่าคีย์พารามิเตอร์ ห้ามเว้นว่าง", 
    canShuJianMingBu: "ชื่อคีย์พารามิเตอร์ ห้ามเว้นว่าง", 
    canShuMingChengBu: "ชื่อพารามิเตอร์ ห้ามเว้นว่าง", 
    miMaBuNengWei: "รหัสผ่าน ห้ามเว้นว่าง", 
    xiTongCanShuPei: "การกำหนดค่าระบบพารามิเตอร์", 
    beiZhu: "หมายเหตุ", 
    chuangJianShiJian: "เวลาที่สร้าง", 
    canShuJianZhi: "ชื่อคีย์พารามิเตอร์", 
    canShuZhuJian: "คีย์หลักของพารามิเตอร์", 
    qingShuRuMiMa: "กรอกรหัสผ่าน", 
    yongHuMiMa: "รหัสผ่านผู้ใช้", 
    yongHuMing: "ชื่อผู้ใช้", 
    shuRuCanShuJian: "กรอกชื่อคีย์พารามิเตอร์", 
    shuRuCanShuMing: "กรอกชื่อพารามิเตอร์", 
  },
};
