export default {
  index: {
        tongBuChengGong: '同步成功',
    tuPian: "รูปภาพ", 
    chuangJianRiQi: "วันที่สร้าง", 
    kuanDu: "ความกว้าง", 
    gaoDu: "ความสูง", 
    wenJianDaXiao: "ขนาดไฟล์", 
    suoLueTu: "ภาพขนาดย่อ", 
    shangChuanZhe: "ผู้อัปโหลด", 
    wenJianMing: "ชื่อไฟล์", 
    queRen: "ยืนยัน", 
    shangChuan: "อัพโหลด", 
    tongBu: "ซิงค์", 
    shiYongTongBuGong: "หากต้องการซิงค์ คุณต้องลงทะเบียนบัญชีใน https://sm.ms/login และเปลี่ยน Secret Token ในไฟล์ application.yml", 
    jieShuRiQi: "วันที่สิ้นสุด", 
    kaiShiRiQi: "วันที่เริ่มต้น", 
    shuRuWenJianMing: "กรอกชื่อไฟล์", 
  },
};
