export default {
  publicEdit: {
    shanChuNeiRong:  ' ลบเนื้อหา ', 
         bianJiGongGongKu:  ' แก้ไขเนื้อหาคลังข้อมูลสาธารณะ ', 
    tianJiaGongGongKu:  ' เพิ่มเนื้อหาคลังข้อมูลสาธารณะ ', 
         qingShuRuPaiXu:  ' กรุณากรอกค่าการเรียงลำดับ ', 
    qingShuRuGongGong:  ' กรุณาใส่เนื้อหาของคลังข้อมูลสาธารณะ ', 
    gongGongKuNeiRong:  ' รายละเอียดเนื้อหาของคลังข้อมูลสาธารณะ ', 
    neiRongPaiXuI:  ' ไอดี การจัดเรียงเนื้อหา ', 
    gongGongKuNeiRong2:  ' เนื้อหาคลังข้อมูลสาธารณะ ', 
         dianJiBiaoQianCha:  ' คลิกที่แท็กเพื่อดูรายละเอียด ', 
    gongGongKuNeiRong3:  ' ค่าการเรียงลำดับเนื้อหาคลังข้อมูลสาธารณะ ', 
    suoShuBiaoQian:  ' แท็กที่เกี่ยวข้อง ', 
    xinZeng:  ' เพิ่มใหม่ ', 
  },
  publicIndex: {
    qingXianShanChuNei:  ' กรุณาลบเนื้อหาออกก่อน ', 
         shanChuBiaoQian:  ' ลบแท็ก ', 
    gongGongKuXL:  ' คลังข้อมูลสาธารณะ.xlsx ', 
         yiCiZhiYunXu:  ' อนุญาตให้นำเข้าไฟล์ได้ครั้งละหนึ่งไฟล์เท่านั้น! ', 
    daoRuChengGong:  ' นำเข้าเรียบร้อยแล้ว ', 
    qingXianXuanZeWen:  ' กรุณาเลือกไฟล์ก่อน! ', 
         qingShuRuBiaoQian:  ' กรุณากรอกชื่อแท็ก ', 
    qingShuRuBiaoQian2:  ' โปรดกรอกค่าการจัดเรียงแท็ก ', 
    gongGongKuBiaoQian:  ' แท็กคลังข้อมูลสาธารณะ ', 
    daoRu:  ' นำเข้า ', 
    dianJiDaoRuHou:  ' หลังจากคลิก "นำเข้า" ระบบจะดำเนินการโดยอัตโนมัติ โปรดยืนยันว่าไฟล์ถูกต้องหรือไม่ หลังจากยืนยันแล้ว โปรดคลิกนำเข้า ', 
    yiCiZhiYunXu2:  ' อนุญาตให้นำเข้าไฟล์ได้ครั้งละหนึ่งไฟล์เท่านั้น! ', 
    dianJiXuanZeWen:  ' คลิกเพื่อเลือกไฟล์ ', 
    jiangWenJianTuoDao:  ' ลากและวางไฟล์ที่นี่ หรือ ', 
    daoRuWenJian:  ' นำเข้าไฟล์ ', 
    biaoQianPaiXuI:  ' ไอดี การจัดเรียงเนื้อหา ', 
    daoChuShuJu:  ' ส่งออกข้อมูล ', 
    daoRuShuJu:  ' นำเข้าข้อมูล ', 
         quanBuBiaoQian:  ' แท็กทั้งหมด ', 
  },
};
