export default {
  form: {
    kongJianLeiXingBu:  ' ประเภทพื้นที่ ห้ามเว้นว่าง ', 
    qingShuRuWaiLian:  ' โปรดป้อนชื่อโดเมนลิงก์ภายนอก ', 
    qingShuRuKongJian:  ' กรุณากรอกชื่อช่องว่าง ', 
    qingShuRuSE:  ' กรุณากรอก secretKey ', 
    qingShuRuAC:  ' กรุณากรอก accessKey ', 
    dongNanYa:  ' เอเชียตะวันออกเฉียงใต้ ', 
    beiMei:  ' อเมริกาเหนือ ', 
    huaNan:  ' ภาคใต้ของจีน ', 
    huaBei:  ' ภาคเหนือของจีน ', 
    huaDong:  ' จีนตะวันออก ', 
    siYou:  ' ส่วนตัว ', 
    gongKai:  ' สาธารณะ ', 
    kongJianLeiXing:  ' ประเภทพื้นที่ ', 
    qingXuanZeCunChu:  ' กรุณาเลือกพื้นที่จัดเก็บ ', 
    cunChuQuYu:  ' พื้นที่จัดเก็บข้อมูล ', 
    waiLianYuMingKe:  ' ชื่อโดเมนของลิงก์ภายนอกสามารถปรับแต่งได้และจำเป็นต้องผูกไว้ใน Qiniu Cloud ', 
    waiLianYuMing:  ' ชื่อโดเมนภายนอก ', 
    cunChuKongJianMing:  ' ชื่อพื้นที่เก็บข้อมูลถูกใช้เป็นตัวระบุ Bucket เฉพาะ ', 
    kongJianMingCheng:  ' ชื่อพื้นที่ ', 
    sECRE:  ' secretKey，อยู่ในศูนย์รักษาความปลอดภัย ดูในการจัดการคีย์ ', 
    aCCES:  ' accessKey，อยู่ในศูนย์รักษาความปลอดภัย ดูในการจัดการคีย์ ', 
    qiNiuYunPeiZhi:  ' การกำหนดค่าQiniu Cloud ', 
  },
  index: {
    shuJuTongBuCheng:  ' การซิงค์ข้อมูลสำเร็จ ', 
    qiNiuYunWenJian:  ' ไฟล์ Qiniu Cloud ', 
    qingWuShangChuanWei:  ' โปรดอย่าอัปโหลดไฟล์ที่ผิดกฎหมาย และไฟล์ไม่ควรเกิน 15M ', 
    dianJiShangChuan:  ' คลิกอัปโหลด ', 
    peiZhi:  ' การกำหนดค่า ', 
       },
};
