export default {
  index: {
    puTongKeHu:  ' ลูกค้าทั่วไป ', 
         keHuZhangHuMing:  ' ชื่อบัญชีลูกค้า ', 
    gengXinRiQi:  ' วันที่อัปเดต ', 
              qingShuRuLaHei:  ' โปรดกรอกเหตุผลในการบล็อก ', 
    keHuLieBiao:  ' รายชื่อลูกค้า ', 
         chongZhiMa:  ' รหัสเติมเงิน ', 
         paiDuiShiChang:  ' ระยะเวลาของคิว ', 
    kaiShiPaiDuiShi:  ' เวลาที่เริ่มเข้าคิว ', 
        jiNengZuMingCheng: '技能组名称',
    huanXingChangJingMing:  ' ชื่อหน้าปลุก ', 
                   keHuMingCheng:  ' ชื่อลูกค้า ', 
    keHuID:  ' ไอดี ลูกค้า ', 
         quanBu:  ' ทั้งหมด ', 
    qingXuanZeVI:  ' กรุณาเลือกระดับ VIP ', 
    suoYouKeHuDeng:  ' ลูกค้าทุกระดับ ', 
         suoYouJiNengZu:  ' กลุ่มทักษะทั้งหมด ', 
    puTongKeHu:  ' ลูกค้าทั่วไป ', 
         keHuZhangHuMing:  ' ชื่อบัญชีลูกค้า ', 
    gengXinRiQi:  ' วันที่อัปเดต ', 
              qingShuRuLaHei:  ' โปรดกรอกเหตุผลในการบล็อก ', 
    keHuLieBiao:  ' รายชื่อลูกค้า ', 
         chongZhiMa:  ' รหัสเติมเงิน ', 
         paiDuiShiChang:  ' ระยะเวลาของคิว ', 
    kaiShiPaiDuiShi:  ' เวลาที่เริ่มเข้าคิว ', 
        jiNengZuMingCheng: '技能组名称',
    huanXingChangJingMing:  ' ชื่อหน้าปลุก ', 
                   keHuMingCheng:  ' ชื่อลูกค้า ', 
    keHuID:  ' ไอดี ลูกค้า ', 
         qingXuanZeVI:  ' กรุณาเลือกระดับ VIP ', 
    suoYouKeHuDeng:  ' ลูกค้าทุกระดับ ', 
         suoYouJiNengZu:  ' กลุ่มทักษะทั้งหมด ', 
  },
  look: {
    jiaZaiZhong:  ' กำลังโหลด ', 
         paiDuiShiChang:  ' ระยะเวลาของคิว ', 
    kaiShiPaiDuiShi:  ' เวลาที่เริ่มเข้าคิว ', 
        jiNengZuMingCheng: '技能组名称:',
    huanXingChangJingMing:  ' ชื่อหน้าปลุก ', 
              keHuMingChengI:  ' ชื่อและไอดี ลูกค้า: ', 
    keHuPaiDuiXin:  ' ข้อมูลคิวลูกค้า ', 
  }
}
