export default {
  BarChart: {
    paiDuiTongJi: "สถิติการเข้าคิว", 
        zhan: '，占',
    zaiCiXuanRan: "แสดงผลอีกครั้ง", 
  },
  LineChart: {
    paiDuiJieRu: "ต่อแถวเข้าคิว", 
    paiDuiShu: "จำนวนคิว", 
  },
  index: {
    pingJunPaiDuiShi: "ระยะเวลาคิวเฉลี่ย", 
    paiDuiLiKaiShu: "อัตรา/จำนวนคิวที่จะออก", 
    paiDuiJinRuHui: "อัตรา/จำนวนที่เข้าคิวบทสนทนา", 
    zongHuiHuaShu: "จำนวนบทสนทนาทั้งหมด", 
    paiDuiTongJiShi: "สถิติเวลาคิว", 
    paiDuiBaoBiao: "รายงานการเข้าคิว", 
        daNianALL: '大年allContents',
    paiDuiZhong: "อยู่ในคิว", 
    tongJiWeiDu: "มิติทางสถิติ", 
    paiDuiJieGuo: "ผลการจัดคิว", 
    paiDuiShiChang: "ระยะเวลาของคิว", 
    paiDuiKaiShiShi: "เวลาที่เริ่มเข้าคิว", 
    ziXunLaiYuan: "ที่มาสอบถาม", 
    keHuZu: "กลุ่มลูกค้า", 
    keHu: "(ลูกค้า:", 
    qingShuRuKeHu: "กรุณากรอกบัญชีลูกค้าของคุณ", 
    paiDuiJiLu: "บันทึกคิว", 
  },
};
