export default {
  index: {
    puTongKeHu: "ลูกค้าทั่วไป", 
    xingMing: "ชื่อจริง", 
    keHuZhangHuMing: "ชื่อบัญชีลูกค้า", 
    gengXinRiQi: "วันที่อัปเดต", 
    chuangJianRiQi: "วันที่สร้าง", 
    buYunXuShuRu: "ไม่อนุญาตให้ใช้อักขระที่ผิดกฎ", 
    qingShuRuLaHei: "โปรดกรอกเหตุผลในการบล็อก", 
    keHuLieBiao: "รายชื่อลูกค้า", 
    zhaKan: "ตรวจสอบดู", 
    chongZhiMa: "รหัสเติมเงิน", 
    tuPian: "รูปภาพ", 
    paiDuiShiChang: "ระยะเวลาของคิว", 
    kaiShiPaiDuiShi: "เวลาที่เริ่มเข้าคิว", 
        jiNengZuMingCheng: '技能组名称',
    huanXingChangJingMing: "ชื่อหน้าปลุก", 
    keHuFenZu: "แบ่งกลุ่มลูกค้า", 
    vIPJiBie: "ระดับ VIP", 
    keHuDengJi: "ระดับลูกค้า", 
    keHuMingCheng: "ชื่อลูกค้า", 
    keHuID: "ไอดี ลูกค้า", 
    qingShuRuKeHu: "กรุณากรอกชื่อลูกค้า", 
    quanBu: "ทั้งหมด", 
    qingXuanZeVI: "กรุณาเลือกระดับ VIP", 
    suoYouKeHuDeng: "ลูกค้าทุกระดับ", 
    quanBuJiNengZu: "กลุ่มทักษะทั้งหมด", 
    suoYouJiNengZu: "กลุ่มทักษะทั้งหมด", 
    puTongKeHu: "ลูกค้าทั่วไป", 
    xingMing: "ชื่อจริง", 
    keHuZhangHuMing: "ชื่อบัญชีลูกค้า", 
    gengXinRiQi: "วันที่อัปเดต", 
    chuangJianRiQi: "วันที่สร้าง", 
    buYunXuShuRu: "ไม่อนุญาตให้ใช้อักขระที่ผิดกฎ", 
    qingShuRuLaHei: "โปรดกรอกเหตุผลในการบล็อก", 
    keHuLieBiao: "รายชื่อลูกค้า", 
    zhaKan: "ตรวจสอบดู", 
    chongZhiMa: "รหัสเติมเงิน", 
    tuPian: "รูปภาพ", 
    paiDuiShiChang: "ระยะเวลาของคิว", 
    kaiShiPaiDuiShi: "เวลาที่เริ่มเข้าคิว", 
        jiNengZuMingCheng: '技能组名称',
    huanXingChangJingMing: "ชื่อหน้าปลุก", 
    keHuFenZu: "แบ่งกลุ่มลูกค้า", 
    vIPJiBie: "ระดับ VIP", 
    keHuDengJi: "ระดับลูกค้า", 
    keHuMingCheng: "ชื่อลูกค้า", 
    keHuID: "ไอดี ลูกค้า", 
    qingShuRuKeHu: "กรุณากรอกชื่อลูกค้า", 
    qingXuanZeVI: "กรุณาเลือกระดับ VIP", 
    suoYouKeHuDeng: "ลูกค้าทุกระดับ", 
    quanBuJiNengZu: "กลุ่มทักษะทั้งหมด", 
    suoYouJiNengZu: "กลุ่มทักษะทั้งหมด", 
  },
  look: {
    jiaZaiZhong: "กำลังโหลด", 
    tuPian: "รูปภาพ.", 
    paiDuiShiChang: "ระยะเวลาของคิว", 
    kaiShiPaiDuiShi: "เวลาที่เริ่มเข้าคิว", 
        jiNengZuMingCheng: '技能组名称:',
    huanXingChangJingMing: "ชื่อหน้าปลุก", 
    vIPJiBie: "ระดับ VIP:", 
    keHuDengJi: "ระดับลูกค้า:", 
    keHuMingChengI: "ชื่อและไอดี ลูกค้า:", 
    keHuPaiDuiXin: "ข้อมูลคิวลูกค้า", 
  }
}
