export default {
    jiaoYiBianHao:  'transaction number', 
    qingShuRuZhangHao:  'please enter an account', 
    daiLiShuYingBao:  'affiliate win and loss report', 
    huiYuanJiaoYiJi:  'Member transaction records', 
    daiChongMingXi:  'details of top up on behalf by other', 
    ziJinTiaoZhengJian:  'Funding Adjustment - deduct currency', 
    ziJinTiaoZhengJia:  'Funding Adjustment - add on currency', 
    fanShuiJinE:  'rebate amount', 
    hongLiJinE:  'bonus amount', 
    gongSiZongYingLi:  'Total profit of the company (affiliate)', 
    gongSiChouShui:  'company commission', 
    wanJiaDuiZhanLei:  'PVP type', 
    gongSiYingLi:  'company profit', 
    paiCaiJinE:  'bonus payout amount', 
    pingTaiZuoZhuang:  'platform as banker', 
    youXiRenShu:  'number of players', 
    quKuanRenShu:  'Number of withdrawals', 
    quKuanJinE:  'withdrawal amount', 
    cunKuanRenShu:  'Number of depositors', 
    shouCunRenShu:  'Number of first depositors', 
    zhuCeRenShu:  'number of registrants', 
    dangQianYeHuiZong:  'Current Page Summary', 
    pingTaiShuYingDao:  'Export of platform win and loss', 
    daoChuLieBiao:  'export list', 
    shuJuLeiXing:  'data type', 
    riQi:  'date', 
    gongSiZongYingLi2:  'Total Company Profit (affiliate)', 
    tiKuanJinE:  'withdrawal amount', 
    fuKuanRenTE:  'drawee：{val1}', 
};
