export default {
  index: {
    ziDingYi: "กำหนดเอง", 
    ziDingYiShuJu: "สิทธิ์ในข้อมูลที่กำหนดเอง ห้ามเว้นว่าง", 
    qingXuanZe: "โปรดเลือก", 
    zhiNengShuRuDa: "สามารถป้อนจำนวนเต็มที่มากกว่า 1 เท่านั้น", 
    qingXuanZeJueSe: "โปรดเลือกระดับบทบาท", 
    benJi: "ระดับนี้", 
    qingShuRuDaYu: "กรุณากรอกจำนวนเต็มมากกว่า 1", 
    jueSe: "บทบาท", 
    caiDanFenPei: "การกำหนดเมนู", 
    xuanZeZhiDingJiao: "เลือกบทบาทที่กำหนดเพื่อกำหนดเมนู", 
    keFuJueSe: "บทบาทการบริการลูกค้า", 
    jueSeJiBie: "ระดับบทบาท", 
    jueSeJiBie2: "ระดับบทบาท", 
    liRuKeFuJing: "ตัวอย่างเช่น ถ้าระดับบทบาทผู้จัดการฝ่ายบริการลูกค้าคือ 3 ผู้จัดการฝ่ายบริการลูกค้าสามารถสร้างและจัดการบทบาทที่ระดับบทบาทมากกว่า 3 และไม่สามารถสร้างและจัดการกับบทบาทที่น้อยกว่าระดับ 3", 
    jueSeJiBieShu: "ยิ่งจำนวนระดับบทบาทน้อยลงเท่าใด ระดับบทบาทก็จะยิ่งมากขึ้นเท่านั้น", 
    jueSeQuanXian: "สิทธิ์ในบทบาท", 
    shuJuQuanXian: "สิทธิ์ข้อมูล", 
    jueSeLieBiao: "รายการบทบาท", 
    miaoShuXinXi: "คำอธิบายข้อมูล", 
    qingXuanZeShuJu: "กรุณาเลือกช่วงข้อมูล", 
    shuJuFanWei: "ช่วงข้อมูล", 
    jueSeMingCheng: "ชื่อบทบาท", 
    chaXun: "ตรวจสอบ", 
    jueSeLeiXing: "ประเภทบทบาท", 
    qingXuanZeJueSe2: "กรุณาเลือกบทบาท", 
  },
};
