export default {
      zuiDuoZhiNengTian: '最多只能添加24个标签哦！',
    gaiBiaoQianYiTian: "แท็กนี้ถูกเพิ่มแล้ว!", 
    qingDianJiBianJi: "โปรดคลิกแก้ไขเพื่อลบและบันทึก!", 
    guanBiChengGong: "ปิดสำเร็จ", 
    kaiQiChengGong: "เปิดสำเร็จ", 
    sheZhiChengGong: "ตั้งค่าสำเร็จ", 
    chaoGuoGaiShiJian: "ภายใน 5 นาที ระบบจะปิดอัตโนมัติหากฝ่ายบริการลูกค้าและลูกค้าไม่มีบทสนทนา", 
    huiHuaShiXiaoShi: "เวลาหมดอายุของบทสนทนา", 
    chaoGuoGaiShiJian2: "ภายใน 3 นาที หากฝ่ายบริการลูกค้าและลูกค้าไม่มีบทสนทนา ฝ่ายบริการลูกค้าสามารถปิดบทสนทนาได้", 
    keFuZhuDongGuan: "ฝ่ายบริการลูกค้าปิดบทสนทนาเอง", 
    huiHuaJieShuShe: "ตั้งค่าสิ้นสุดบทสนทนา", 
    qingShuRuZhiJian: "โปรดป้อนจำนวนเต็มระหว่าง 10 ถึง 120", 
    qingShuRuBuXiao: "กรุณาป้อนจำนวนเต็มไม่น้อยกว่า 5", 
    qingShuRuBuXiao2: "กรุณาป้อนจำนวนเต็มไม่น้อยกว่า 3", 
    fuWuZongJiePei: "การกำหนดค่าผลสรุปการบริการ", 
    xingShuoMing: "คำอธิบายดาว:", 
    xing: "ดาว \n", 
    xing2: "ดาว", 
    xingJiPingJiaShe: "การตั้งค่าการประเมินระดับดาว", 
    quanBuShanChu: "ลบทั้งหมด", 
    yiTianJiaBiaoQian: "เพิ่มแท็กแล้ว: (", 
    zuiDuoShuRuGe: "ป้อนได้สูงสุด 8 คำ (รวมอักขระ)", 
    tianJiaPingJiaBiao: "เพิ่มคลังแท็กการประเมิน", 
    kaiQiCiGongNeng: "หลังจากเปิดใช้งานฟังก์ชันนี้ หน้าลูกค้าตอนประเมินบทสนทนาสามารถเลือกได้ว่าบทสนทนานี้ได้รับการแก้ไขแล้วหรือไม่", 
    keFuShiFouJie: "ฝ่ายบริการลูกค้าได้แก้ไขปัญหาแล้วหรือไม่", 
    manYiDuPingJia: "การตั้งค่าการประเมินความพึงพอใจ", 
    manYiDuPingJia2: "การกำหนดค่าการประเมินความพึงพอใจ", 
    yongHuPaiDuiChao: "หากคิวผู้ใช้ไม่เข้าบทสนทนาในเวลานี้ ระบบจะสิ้นสุดคิวของผู้ใช้โดยอัตโนมัติ", 
    fen: "คะแนน", 
    paiDuiChaoShiShi: "หมดเวลาของคิว", 
    paiDuiJieShuShe: "การตั้งค่าสิ้นสุดคิว", 
  serverConfig: {
    xinZengChengGong: "เพิ่มใหม่สำเร็จ!", 
    bianJiChengGong: "แก้ไขสำเร็จ!", 
    qingXianShanChuYe: "โปรดลบประเภทธุรกิจออกก่อน", 
    ninQueDingShanChu: "คุณแน่ใจหรือที่จะลบแท็กนี้ [{val1}]?", 
    shanChuYeWuMing: "ลบชื่อธุรกิจ", 
    changDuZaiDaoGe: "ความยาวตั้งแต่ 1 ถึง 20 ตัวอักษร", 
    qingShuRuYeWu: "กรุณากรอกชื่อธุรกิจ", 
    paiXuZhiBiXu: "ค่าการเรียงลำดับต้องเป็นจำนวนเต็มที่มากกว่า 0", 
    qingShuRuYeWu2: "โปรดป้อนค่าการจัดเรียงชื่อธุรกิจ", 
    fuWuZongJiePei: "รายการการกำหนดค่าผลสรุปการบริการ", 
    chuangJianRen: "สร้างโดย", 
    yeWuMingCheng: "ชื่อธุรกิจ", 
    yeWuPaiXuI: "ไอดี การจัดเรียงธุรกิจ", 
    xinZeng: "เพิ่มใหม่", 
    quanBu: "ทั้งหมด", 
    yeWuMingChengPai: "ไอดี การจัดเรียงลำดับชื่อธุรกิจ", 
  },
  serverType: {
    shanChuNeiRong: "ลบเนื้อหา", 
    bianJiYeWuLei: "แก้ไขประเภทธุรกิจ", 
    tianJiaYeWuLei: "เพิ่มประเภทธุรกิจ", 
    qingShuRuPaiXu: "กรุณากรอกค่าการเรียงลำดับ", 
    qingShuRuYeWu: "กรุณากรอกชื่อประเภทธุรกิจ", 
    yeWuLeiXingXiang: "รายละเอียดประเภทธุรกิจ", 
    yeWuLeiXingPai: "ไอดี การจัดเรียงประเภทธุรกิจ", 
    yeWuLeiXingMing: "ชื่อประเภทธุรกิจ", 
    dianJiYeWuMing: "คลิกที่ชื่อธุรกิจเพื่อดู", 
    yeWuLeiXing: "ประเภทธุรกิจ", 
  },
};
