export default {
      zuiDuoZhiNengTian: '最多只能添加24个标签哦！',
    gaiBiaoQianYiTian:  ' แท็กนี้ถูกเพิ่มแล้ว! ', 
    qingDianJiBianJi:  ' โปรดคลิกแก้ไขเพื่อลบและบันทึก! ', 
    guanBiChengGong:  ' ปิดสำเร็จ ', 
    kaiQiChengGong:  ' เปิดสำเร็จ ', 
    sheZhiChengGong:  ' ตั้งค่าสำเร็จ ', 
    chaoGuoGaiShiJian:  ' ภายใน 5 นาที ระบบจะปิดอัตโนมัติหากฝ่ายบริการลูกค้าและลูกค้าไม่มีบทสนทนา ', 
    huiHuaShiXiaoShi:  ' เวลาหมดอายุของบทสนทนา ', 
    chaoGuoGaiShiJian2:  ' ภายใน 3 นาที หากฝ่ายบริการลูกค้าและลูกค้าไม่มีบทสนทนา ฝ่ายบริการลูกค้าสามารถปิดบทสนทนาได้ ', 
    keFuZhuDongGuan:  ' ฝ่ายบริการลูกค้าปิดบทสนทนาเอง ', 
    huiHuaJieShuShe:  ' ตั้งค่าสิ้นสุดบทสนทนา ', 
         qingShuRuBuXiao:  ' กรุณาป้อนจำนวนเต็มไม่น้อยกว่า 5 ', 
    qingShuRuBuXiao2:  ' กรุณาป้อนจำนวนเต็มไม่น้อยกว่า 3 ', 
         xingShuoMing:  ' คำอธิบายดาว: ', 
              xingJiPingJiaShe:  ' การตั้งค่าการประเมินระดับดาว ', 
    quanBuShanChu:  ' ลบทั้งหมด ', 
    yiTianJiaBiaoQian:  ' เพิ่มแท็กแล้ว: ( ', 
    zuiDuoShuRuGe:  ' ป้อนได้สูงสุด 8 คำ (รวมอักขระ) ', 
         kaiQiCiGongNeng:  ' หลังจากเปิดใช้งานฟังก์ชันนี้ หน้าลูกค้าตอนประเมินบทสนทนาสามารถเลือกได้ว่าบทสนทนานี้ได้รับการแก้ไขแล้วหรือไม่ ', 
    keFuShiFouJie:  ' ฝ่ายบริการลูกค้าได้แก้ไขปัญหาแล้วหรือไม่ ', 
    manYiDuPingJia:  ' การตั้งค่าการประเมินความพึงพอใจ ', 
    manYiDuPingJia2:  ' การกำหนดค่าการประเมินความพึงพอใจ ', 
    yongHuPaiDuiChao:  ' หากคิวผู้ใช้ไม่เข้าบทสนทนาในเวลานี้ ระบบจะสิ้นสุดคิวของผู้ใช้โดยอัตโนมัติ ', 
         paiDuiChaoShiShi:  ' หมดเวลาของคิว ', 
    paiDuiJieShuShe:  ' การตั้งค่าสิ้นสุดคิว ', 
  serverConfig: {
         bianJiChengGong:  ' แก้ไขสำเร็จ! ', 
    qingXianShanChuYe:  ' โปรดลบประเภทธุรกิจออกก่อน ', 
         shanChuYeWuMing:  ' ลบชื่อธุรกิจ ', 
                   qingShuRuYeWu2:  ' โปรดป้อนค่าการจัดเรียงชื่อธุรกิจ ', 
         chuangJianRen:  ' สร้างโดย ', 
    yeWuMingCheng:  ' ชื่อธุรกิจ ', 
    yeWuPaiXuI:  ' ไอดี การจัดเรียงธุรกิจ ', 
    xinZeng:  ' เพิ่มใหม่ ', 
    quanBu:  ' ทั้งหมด ', 
    yeWuMingChengPai:  ' ไอดี การจัดเรียงลำดับชื่อธุรกิจ ', 
  },
  serverType: {
    shanChuNeiRong:  ' ลบเนื้อหา ', 
    bianJiYeWuLei:  ' แก้ไขประเภทธุรกิจ ', 
    tianJiaYeWuLei:  ' เพิ่มประเภทธุรกิจ ', 
    qingShuRuPaiXu:  ' กรุณากรอกค่าการเรียงลำดับ ', 
         yeWuLeiXingXiang:  ' รายละเอียดประเภทธุรกิจ ', 
    yeWuLeiXingPai:  ' ไอดี การจัดเรียงประเภทธุรกิจ ', 
    yeWuLeiXingMing:  ' ชื่อประเภทธุรกิจ ', 
    dianJiYeWuMing:  ' คลิกที่ชื่อธุรกิจเพื่อดู ', 
       },
};
