export default {
  index: {
    qingPeiZhiGaiKe:  ' โปรดกำหนดค่าบริการลูกค้ากลุ่มนี้! ', 
    jianTing:  ' กำลังฟัง 11111 ', 
    keFuBaoBiao:  ' รายงานการบริการลูกค้า ', 
                        mangLu:  ' ยุ่ง ', 
    zaiXianQieHuan:  ' การสลับออนไลน์ ', 
             pingJunHuiHuaShi: '平均会话时长',
    jieDaiYaLiZhi:  ' ค่าความกดดันการรับ ', 
        huiFuLu: '回复率',
    jieDaiKeHuShu:  ' จำนวนลูกค้าที่ได้รับ ', 
    keHuKeFuXiao:  ' จำนวนข้อความของลูกค้า/บริการลูกค้า ', 
    shiJian:  ' เวลา ', 
    keHuPingJia:  ' การประเมินของลูกค้า ', 
    keFuZongJie:  ' สรุปผลการบริการลูกค้า ', 
    zanWuShuJuQing:  ' ไม่มีข้อมูล โปรดเลือกเกณฑ์การค้นหาเพื่อค้นหาอีกครั้ง! ', 
    tongJiZhi:  ' ค่าทางสถิติ ', 
         renYuan:  ' บุคลากร ', 
    keFuRenYuan:  ' พนักงานบริการลูกค้า ', 
    keHuPingJiaPing:  ' อัตราคะแนนการประเมินของลูกค้า ', 
              keFuJieJueLu:  ' อัตรา/จำนวน การแก้ปัญหา ', 
        keFuZongJieLu: '客服总结率/数',
    sNeiXiangYingYing:  ' อัตราการตอบกลับภายใน 30 วินาที ', 
    zuiDaXiangYingShi:  ' ระยะเวลาตอบสนองสูงสุด ', 
    pingJunShouXiangShi:  ' ระยะเวลาเสียงกริ่งแรกเฉลี่ย ', 
    zuiDaJieDaiShu:  ' จำนวนการรับสูงสุด ', 
    zhuanChuHuiHuaShu:  ' จำนวนบทสทนาส่งต่อ ', 
    huiHuaShuYouXiao:  ' จำนวนบทสทนา/ที่มีประสิทธภาพ ', 
    mangLu2:  ' ยุ่ง ', 
         quanBuKeFuZhang:  ' บัญชีบริการลูกค้าทั้งหมด ', 
    keFuTongJi:  ' สถิติการบริการลูกค้า ', 
    suoYouKeFuBao:  ' รายงานการบริการลูกค้าทั้งหมด ', 
    danGeKeFuBao:  ' รายงานการบริการลูกค้ารายบุคคล ', 
  },
  moreBar: {
    ziDongJieRu:  ' เข้าอัตโนมัติ ', 
    zhuanJieJieRu:  ' โอนเข้า ', 
  },
};
