export default {
    chengGong:  ' สำเร็จ ', 
         queDingSTA:  ' แน่ใจเกี่ยวกับ '{val1}{val2}' ไหม ', 
    sTATE:  ' {val1}ฝ่ายบริการลูกค้า ', 
    queRenShanChu:  ' ยืนยันการลบ ', 
    ruGuoGaiKeFu:  ' หากฝ่ายบริการลูกค้าออนไลน์ ระบบจะแจ้งว่าบัญชีฝ่ายบริการลูกค้าถูกปิดใช้งานและปิดโต๊ะบริการลูกค้าลูกค้า ', 
    qiYong:  ' เปิดใช้งาน ', 
    tingYong:  ' ปิดการใช้งาน ', 
         keFuLieBiao:  ' รายการบริการลูกค้า ', 
    jieDaiShangXian:  ' ขีดจำกัดการรับ ', 
    jieSuo:  ' ปลดล็อค ', 
         qiYong2:  ' เปิดใช้งาน ', 
    tingYong2:  ' ปิดการใช้งาน ', 
    caoZuo:  ' การดำเนินการ ', 
         suoDing:  ' ล็อค ', 
    zhangHuZhuangTai:  ' สถานะบัญชี ', 
         zaiXianJiNengZu:  ' กลุ่มทักษะที่ออนไลน์ ', 
    keFuZu:  ' กลุ่มบริการลูกค้า ', 
    keFuGangWei:  ' ตำแหน่งบริการลูกค้า ', 
    touXiang:  ' รูปโปรไฟล์ ', 
         quanBuZhangHuZhuang:  ' สถานะบัญชีทั้งหมด ', 
          };
