export default {
  index: {
        kehuYuyan: '客户语言',

    cHANG: "เปลี่ยนธุรกิจ", 
    qiangTuiChengGong: "บังคับออกสำเร็จ!", 
    you: "มี", 
    wuXiaoHuiHua: "บทสนทนาไม่มีประสิทธิภาพ", 
    youXiaoHuiHua: "บทสนทนาที่มีประสิทธิภาพ", 
    weiZongJie: "ยังไม่สรุปผล", 
    weiZhiJian: "ยังไม่ผ่านการตรวจสอบ", 
    yiZhiJian: "ตรวจสอบแล้ว", 
    zongDaiID: "ไอดี ตัวแทน", 
    keFuDaiLi: "ตัวแทนบริการลูกค้า", 
    keFuLeiXing: "ประเภทการบริการลูกค้า", 
    huiHuaKaiShiShi: "เวลาเริ่มต้นบทสนทนา", 
    wenTiShiChang: "คำถาม/ระยะเวลา", 
    shangJiDaiLi: "หัวหน้าตัวแทน", 
    keHuLeiXing: "ประเภทลูกค้า", 
        vipDengji: 'vip 等级',

    xiaoXiShu: "จำนวนข้อความ", 
    zhiJianZhuangTai: "สถานะการตรวจสอบ", 
    jieShuFangShi: "วิธีการสิ้นสุด", 
    kaiShiShiJian: "เวลาเริ่มต้น", 
    huiHuaLeiXing: "ประเภทบทสนทนา", 
    fou: "ไม่", 
    shi: "ใช่", 
    xiaoYu: "ต่ำกว่า", 
    daYu: "มากกว่า", 
    zhiNengShuRuDa: "ป้อนได้เฉพาะตัวเลขที่มากกว่า 0 เท่านั้น", 
    qingShuRu: "กรุณากรอก", 
    zhiNengShuRuZheng: "ป้อนได้เฉพาะตัวเลขจำนวนเต็ม", 
    zuiDaXianZhiS: "ขีดจำกัดสูงสุด 1800 วินาที", 
    youCeBuNengXiao: "ด้านขวาต้องไม่เล็กกว่าด้านซ้าย", 
    zuoCeBuNengDa: "ด้านซ้ายต้องไม่ใหญ่กว่าด้านขวา", 
    huiHuaJiLu: "บันทึกบทสนทนา", 
    shouXiangShiChang: "ระยะเวลาเสียงแรก", 
    xiangYingShiChang: "เวลาตอบสนอง", 
    xiaoXiShuKeHu: "จำนวนข้อความ (ลูกค้า / ฝ่ายบริการลูกค้า)", 
    pingJiaLeiXing: "ประเภทการประเมิน", 
    yeWuLeiXing: "ประเภทธุรกิจ", 
    yeWu: "ธุรกิจ", 
    huiHuaLeiBie: "หมวดหมู่บทสนทนา", 
    wenTiShiChang2: "คำถาม/ระยะเวลา", 
    sheZhiZhanShiZi: "ตั้งค่าฟิลด์แสดงผล", 
    gengDuoShaiXuanTiao: "เงื่อนไขการคัดกรองมากกว่านี้", 
    gengDuoShaiXuanTiao2: "เงื่อนไขการคัดกรองมากกว่านี้", 
    qingShuRuKeHu: "กรุณากรอกบัญชีลูกค้าของคุณ", 
    quanBuYeWuLei: "ประเภทธุรกิจทั้งหมด", 
    quanBuYeWu: "ธุรกิจทั้งหมด", 
    zuiChangXiangYingShi: "ระยะเวลาตอบสนองที่ยาวที่สุด", 
    qingShuRuKeFu: "โปรดป้อนตัวแทนฝ่ายบริการลูกค้า", 
    qingShuRuKeHu2: "โปรดป้อนหัวหน้าตัวแทนของลูกค้า", 
    qingShuRuKeHu3: "กรุณากรอกชื่อบัญชีลูกค้า", 
    qingShuRuHuiHua: "โปรดกรอก ไอดี การสนทา", 
  }
}
