export default {
  index: {
    qiangJieChengGong: "แย่งการเชื่อมต่อสำเร็จ!", 
    haoDe: "ตกลง", 
    tiShi: "แจ้งเตือน", 
    fuWuYiChangQing: "การบริการผิดปกติ โปรดจัดฝ่ายบริการลูกค้าต้อนรับเพื่อปิดบทสนทนานี้!", 
    quanXuan: "เลือกทั้งหมด", 
    qiangTuiChengGong: "บังคับออกสำเร็จ!", 
    pCWangZhan: "เว็บไซต์คอมพิวเตอร์", 
    yiDongWangZhan: "เว็บไซต์มือถือ", 
    yiDongAPP: "แอพมือถือ", 
    fou: "ไม่", 
    shi: "ใช่", 
    huiHuaJianKong: "ตรวจสอบบทสนทนา", 
    qiangZhiGuanBi: "บังคับปิด", 
    zhaKanHuiHua: "ตรวจดูบทสนทนา", 
    qiangJie: "แย่งรับ", 
    shiFouYiChang: "ผิดปกติหรือไม่", 
    keHuXingBiao: "ลูกค้าติดดาว", 
    xiangYingChaoShi: "หมดเวลาการตอบสนอง", 
    huiHuaChaoShi: "หมดเวลาบทสนทนา", 
    shouXiangChaoShi: "หมดเวลาเสียงกริ่งแรก", 
    jingBaoZhuangTai: "สถานะการเตือน", 
    ziXunQuDaoXi: "ระบบ/ช่องทางสอบถาม", 
    huiHuaLeiXing: "ประเภทบทสนทนา", 
    huiHuaJianLiShi: "เวลาในการสร้างบทสนทนา", 
    keHuYongHuMing: "ชื่อผู้ใช้ของลูกค้า", 
    huiHuaShiChang: "ระยะเวลาบทสนทนา", 
    jiNengZu: "กลุ่มทักษะ", 
    keFuZu: "กลุ่มบริการลูกค้า", 
    keFuZhangHuNi: "บัญชีฝ่ายบริการลูกค้า/ชื่อเล่น", 
    miaoZiDongShuaXin: "รีเฟรชอัตโนมัติ 10 วินาที", 
    jingBaoHuiHuaZhi: "\nแจ้งเตือนบทสนทนาสูงสุด\n", 
    tiao: "บทความ \n", 
    tiaoZaiXianHuiHua: "\n บทสนทนาออนไลน์ บทสนทนาการแจ้งเตือน", 
    gong: "\n รวม \n", 
    qingShuRuKeHu: "กรุณากรอกบัญชีลูกค้าของคุณ", 
    quanBuZiXunLai: "ที่มาการสอบถามทั้งหมด", 
    quanBuKeHuZu: "ทุกกลุ่มลูกค้า", 
    suoYouKeHuZu: "กลุ่มลูกค้าทั้งหมด", 
    quanBuKeFu: "ฝ่ายบริการลูกค้าทั้งหมด", 
    quanBuJingBaoZhuang: "สถานะการแจ้งเตือนทั้งหมด", 
    suoYouHuiHuaLei: "ประเภทบทสนทนาทั้งหมด", 
    qingShuRuHuiHua: "โปรดกรอก ไอดี การสนทา", 
  },
};
