export default {
  index: {
    qiangJieChengGong:  ' แย่งการเชื่อมต่อสำเร็จ! ', 
    haoDe:  ' ตกลง ', 
                   qiangTuiChengGong:  ' บังคับออกสำเร็จ! ', 
    pCWangZhan:  ' เว็บไซต์คอมพิวเตอร์ ', 
    yiDongWangZhan:  ' เว็บไซต์มือถือ ', 
    yiDongAPP:  ' แอพมือถือ ', 
    fou:  ' ไม่ ', 
         huiHuaJianKong:  ' ตรวจสอบบทสนทนา ', 
    qiangZhiGuanBi:  ' บังคับปิด ', 
    zhaKanHuiHua:  ' ตรวจดูบทสนทนา ', 
    qiangJie:  ' แย่งรับ ', 
    shiFouYiChang:  ' ผิดปกติหรือไม่ ', 
    keHuXingBiao:  ' ลูกค้าติดดาว ', 
    xiangYingChaoShi:  ' หมดเวลาการตอบสนอง ', 
    huiHuaChaoShi:  ' หมดเวลาบทสนทนา ', 
    shouXiangChaoShi:  ' หมดเวลาเสียงกริ่งแรก ', 
    jingBaoZhuangTai:  ' สถานะการเตือน ', 
    ziXunQuDaoXi:  ' ระบบ/ช่องทางสอบถาม ', 
         huiHuaJianLiShi:  ' เวลาในการสร้างบทสนทนา ', 
    keHuYongHuMing:  ' ชื่อผู้ใช้ของลูกค้า ', 
    huiHuaShiChang:  ' ระยะเวลาบทสนทนา ', 
    jiNengZu:  ' กลุ่มทักษะ ', 
    keFuZu:  ' กลุ่มบริการลูกค้า ', 
         miaoZiDongShuaXin:  ' รีเฟรชอัตโนมัติ 10 วินาที ', 
    jingBaoHuiHuaZhi:  '\n \nแจ้งเตือนบทสนทนาสูงสุด\n \n', 
    tiao:  ' บทความ \n \n', 
    tiaoZaiXianHuiHua:  '\n \n บทสนทนาออนไลน์ บทสนทนาการแจ้งเตือน ', 
    gong:  '\n \n รวม \n \n', 
         quanBuZiXunLai:  ' ที่มาการสอบถามทั้งหมด ', 
         suoYouKeHuZu:  ' กลุ่มลูกค้าทั้งหมด ', 
    quanBuKeFu:  ' ฝ่ายบริการลูกค้าทั้งหมด ', 
    quanBuJingBaoZhuang:  ' สถานะการแจ้งเตือนทั้งหมด ', 
    suoYouHuiHuaLei:  ' ประเภทบทสนทนาทั้งหมด ', 
       },
};
