export default {
  index: {
        kehuYuyan: '客户语言',

    cHANG:  ' เปลี่ยนธุรกิจ ', 
    qiangTuiChengGong:  ' บังคับออกสำเร็จ! ', 
    you:  ' มี ', 
                   weiZhiJian:  ' ยังไม่ผ่านการตรวจสอบ ', 
    yiZhiJian:  ' ตรวจสอบแล้ว ', 
         keFuDaiLi:  ' ตัวแทนบริการลูกค้า ', 
    keFuLeiXing:  ' ประเภทการบริการลูกค้า ', 
         wenTiShiChang:  ' คำถาม/ระยะเวลา ', 
    shangJiDaiLi:  ' หัวหน้าตัวแทน ', 
    keHuLeiXing:  ' ประเภทลูกค้า ', 
        vipDengji: 'vip 等级',

    xiaoXiShu:  ' จำนวนข้อความ ', 
    zhiJianZhuangTai:  ' สถานะการตรวจสอบ ', 
    jieShuFangShi:  ' วิธีการสิ้นสุด ', 
    kaiShiShiJian:  ' เวลาเริ่มต้น ', 
         fou:  ' ไม่ ', 
              daYu:  ' มากกว่า ', 
              zhiNengShuRuZheng:  ' ป้อนได้เฉพาะตัวเลขจำนวนเต็ม ', 
    zuiDaXianZhiS:  ' ขีดจำกัดสูงสุด 1800 วินาที ', 
    youCeBuNengXiao:  ' ด้านขวาต้องไม่เล็กกว่าด้านซ้าย ', 
    zuoCeBuNengDa:  ' ด้านซ้ายต้องไม่ใหญ่กว่าด้านขวา ', 
    huiHuaJiLu:  ' บันทึกบทสนทนา ', 
                   pingJiaLeiXing:  ' ประเภทการประเมิน ', 
         yeWu:  ' ธุรกิจ ', 
         wenTiShiChang2:  ' คำถาม/ระยะเวลา ', 
    sheZhiZhanShiZi:  ' ตั้งค่าฟิลด์แสดงผล ', 
                   quanBuYeWuLei:  ' ประเภทธุรกิจทั้งหมด ', 
    quanBuYeWu:  ' ธุรกิจทั้งหมด ', 
    zuiChangXiangYingShi:  ' ระยะเวลาตอบสนองที่ยาวที่สุด ', 
         qingShuRuKeHu2:  ' โปรดป้อนหัวหน้าตัวแทนของลูกค้า ', 
    qingShuRuKeHu3:  ' กรุณากรอกชื่อบัญชีลูกค้า ', 
       }
}
