export default {
    fanKuiLeiBie:  'feedback category', 
    biTianXiangBuNeng:  'Required fields cannot be empty', 
    huoDongXinJian:  'promotion letter', 
    xuanZe:  'choose', 
    duoGeYongHuMing:  'Multiple usernames should be separated by commas (,) or newlines, and a maximum of {val1} accounts can be sent at a time', 
    faSongZhangHao:  'send the account', 
    qingXuanZeHuiYuan:  'please choose a member level', 
    huiYuanCengJi:  'member level', 
    faSongZhanNeiXin:  'Send inbox message', 
    geNBSP:  'a,&nbsp;&nbsp;', 
    nBSPN:  ',&nbsp;&nbsp; fail', 
    ge:  'a', 
    chengGongFaSong:  'successful sent', 
    dianJiZhangHaoZhang:  '(Click on the account name to copy it)', 
    gongXiNiXiuGai:  'Congratulations, the modification is successful!', 
    tiao:  ')pieces:', 
    huiYuanLieBiao:  'member list(', 
    qingShuRuSuoShu:  'please enter the affiliate belongs to', 
    qingXuanZeVI:  'please choose a VIP level', 
    xuanZeHuiYuan:  'choose a member', 
    qingChaXunHuiYuan:  'please inquiry a member account', 
    zhangHao:  'account', 
    xiTongXiaoXi:  'system message', 
    baoCunShiBaiD:  'Save failed.{val1}', 
    changDuZaiDaoGe:  '1 to 30 characters in length', 
    qingShuRuLeiBie:  'please enter the category description', 
    leiBieMiaoShu:  'category description', 
    qingShuRuLeiBie2:  'please enter the category name', 
    leiBieMing:  'category name', 
    xiangQing:  'detail', 
    xiuGaiRen:  'editor', 
    yiDuRenShu:  'number of who readed', 
    faSongRenShu:  'number of sent out', 
    souSuo:  'search', 
    zhiDuiAnZhaoYong:  'Only effective for sending by username', 
    shanChuShiBaiM:  'Delete failed!{val1}', 
    queDingYaoShanChu:  'Are you sure you want to delete and change the message in the inbox?', 
    shanChuZhanNeiXin:  'Delete inbox message ({val1})', 
    xiuGaiShiJian:  'edit time', 
    fanKuiLeiXing:  'feedback type', 
    queDingYaoShanChu2:  'Are you sure you want to delete this feedback category?', 
    shanChuFanKuiLei:  'delete feedback category（{val1}）', 
    aCTIO:  '{val1}successful!', 
    queDingYaoAC:  'Are you sure you want to {val1} this feedback category?', 
    aCTIO2:  '{val1}feedback category（{val2}）', 
};
