export default {
  center: {
        touXiangXiuGaiCheng: '头像修改失败',
                        baoCunPeiZhi:  ' บันทึกการกำหนดค่า ', 
              xingBie:  ' เพศ ', 
    shouJiHaoMaBu:  ' หมายเลขโทรศัพท์มือถือไม่สามารถซ้ำได้ ', 
    shouJiHao:  ' หมายเลขโทรศัพท์มือถือ ', 
    yongHuNiChengBu:  ' ชื่อเล่นผู้ใช้ไม่ได้ใช้สำหรับการเข้าสู่ระบบ ', 
    niCheng:  ' ชื่อเล่น ', 
    yongHuZiLiao:  ' ข้อมูลผู้ใช้ ', 
              anQuanSheZhi:  ' การตั้งค่าความปลอดภัย\n \n', 
    suoShuBuMen:  ' แผนก ', 
    yongHuYouXiang:  ' อีเมลผู้ใช้ ', 
    shouJiHaoMa:  ' หมายเลขโทรศัพท์ ', 
         dengLuZhangHao:  ' เข้าสู่ระบบบัญชี ', 
    dianJiShangChuanTou:  ' คลิกเพื่ออัปโหลดโปรไฟล์ต้อง ', 
    geRenXinXi:  ' ข้อมูลส่วนตัว ', 
  },
  index: {
    jueSeBuNengWei:  ' บทบาท ห้ามเว้นว่าง ', 
    gangWeiBuNengWei:  ' ตำแหน่ง ห้ามเว้นว่าง ', 
    buMenBuNengWei:  ' แผนก ห้ามเว้นว่าง ', 
    zhuangTaiXiuGaiCheng:  ' แก้ไขสถานะสำเร็จ ', 
    kaiQiChengGong:  ' เปิดสำเร็จ ', 
    shiFouJiXu:  ' ดำเนินการต่อหรือไม่? ', 
        'wenHao': '？',
    queDingKaiQi:  ' ตกลงเพื่อเปิด ', 
    tuPianYanZheng:  ' ยืนยันรูปภาพ ', 
    guGeYanZheng:  ' ยืนยันของ Google ', 
         queDingYaoZhongZhi:  ' แน่ใจไหมว่าต้องการรีเซ็ตการยืนยันของ Google และเชื่อมต่อใหม่ ', 
         qingShuRuShouJi:  ' กรอกหมายเลขโทรศัพท์ ', 
         qingShuRuYouXiang:  ' กรุณากรอกอีเมลของคุณ ', 
         zhiNengShuRuZi:  ' สามารถป้อนได้เฉพาะตัวอักษรและตัวเลขเท่านั้น ', 
                  qingXuanZeZongDai: '请选择总代id',
        qingXuanZeDaiLi: '请选择代理账号',
         qingXuanZeGangWei:  ' กรุณาเลือกตำแหน่ง ', 
    qingXuanZeBuMen:  ' กรุณาเลือกแผนก ', 
    suoDing:  ' ล็อค ', 
    jiHuo:  ' เปิดใช้งาน ', 
    yongHu:  ' ผู้ใช้ ', 
    zhongZhiMiMa:  ' รีเซ็ตรหัสผ่าน ', 
    jieSuo:  ' ปลดล็อค ', 
    zhongZhiYanZhengMa:  ' รีเซ็ตรหัสยืนยัน ', 
         guGe:  ' Google ', 
    yanZhengMaLeiXing:  ' ประเภทรหัสยืนยัน ', 
    buMenGangWei:  ' แผนก/ตำแหน่ง ', 
    yongHuMingNiCheng:  ' ชื่อผู้ใช้/ชื่อเล่น ', 
    ruGuoYuanKeFu:  ' หากผู้ใช้ของแผนกบริการลูกค้าเดิมถูกเปลี่ยนแปลงไม่ใช่แผนกบริการลูกค้าอีกต่อไป บัญชีบริการลูกค้าจะถูกยกเลิกโดยอัตโนมัติและ และหากฝ่ายบริการลูกค้าได้เข้าสู่ระบบ บัญชีจะออฟไลน์โดยอัตโนมัติ ', 
    qingXianXuanZeA:  ' กรุณาเลือก app ก่อน ', 
    qingXianXuanZeChan:  ' กรุณาเลือกสินค้าก่อน ', 
    chanPin:  ' สินค้า ', 
    zhiNengChuangJianXiu:  ' คุณสามารถสร้าง/แก้ไขบทบาทผู้ใช้ที่มีระดับน้อยกว่าระดับบทบาทของคุณเท่านั้น ', 
    qingXianXuanZe:  ' กรุณาเลือกก่อน! ', 
              keFuLeiXing:  ' ประเภทการบริการลูกค้า ', 
    qingXianXuanZeBu:  ' กรุณาเลือกแผนกก่อน ', 
    youXiang:  ' อีเมล ', 
    dianHua:  ' หมายเลขโทรศัพท์ ', 
       },
  updatePass: {
    xiuGaiChengGongT:  ' การแก้ไขสำเร็จ และรหัสผ่านใหม่ของ {val1} มีค่าเริ่มต้นเป็น {val2} ', 
    tHISE:  ' ปลดล็อก {val1} สำเร็จแล้ว ', 
    qingShuRuGuanLi:  ' กรุณาใส่รหัสผ่านผู้ดูแลระบบ ', 
    zhongZhiMiMaWei:  ' รีเซ็ตรหัสผ่านเป็น ', 
         dengLuMiMa:  ' รหัสผ่านในการเข้าสู่ระบบ ', 
    dengLuYongHuMing:  ' เข้าสู่ระบบด้วยชื่อผู้ใช้ ', 
    xuYaoYanZhengNin:  ' จำเป็นต้องมีการยืนยันตัวตนของคุณ ', 
    jieSuoZhangHu:  ' ปลดล็อกบัญชีของคุณ ', 
    weiLeBaoZhengZhang:  ' เพื่อจุดประสงค์ด้านความปลอดภัยของบัญชี ', 
  },
};
