export default {
      zhuDuiYuKuaiSu: '注：对于快速转卡的提现方式必须要上传转账图片',
      dongTaiTuPian: '动态图片',
      xuanZeShangChuanDe: '选择上传的图片格式有误，请重新选择',
      jiSuZhuanKaDe: '急速转卡的提现方式必须要上传转账图片',
      guGeShenFenYan: '谷歌身份验证码',
      shuRuFanHuiZhong: '输入返回中心钱包的金额',
      zhuQuanBuTuiHui: '注：全部退回，订单状态为失败；部分退回，提现状态为成功',
      buFenTuiHui: '部分退回',
      quanBuTuiHui: '全部退回',
      zhiNengShuRuZheng: '只能输入正整数且输入的退回金额不能大于提现金额',
      dengDaiFuKuanJ: '等待付款js',
      daiQueRenDaoZhang: '待确认到帐js',
    buFenTuiHuiCheng:  'Partially return was successful (extremely fast card transfer)', 
    buFenTuiHuiZhong:  'Some are being returned (extremely fast card transfer)', 
    chaoShiWeiQueRen:  'Unconfirmed after timeout (Extremely fast card transfer)', 
};
