  tuPian: '图片', \\constant.ts 
    fuYan: '附言', \\constant.ts 
    zhuDangGongSiJing: '注：当公司净输赢为负数时候（会员盈利），佣金比例默认为0%', \\agentList.ts 
    daHuaTou: '大话骰', \\agentList.ts 
    wanJiaPLA: "玩家：{val1}{val2}` : ''\n        }", \\agentList.ts 
    xieYi: '协议', \\constant.ts 
    qingShuRuSuoShu: '请输入所属上级', \\agentList.ts 
    qieJiDaiLiYue:    '切忌：代理月结算数据报表生成期间，不要进行玩家变更代理的更换。', \\memberList.ts 
    zhuYiWanJiaBian:    '注意：玩家变更代理需要谨慎操作，会造成代理输赢日报表的数据差异', \\memberList.ts 
    shiFouXuYaoPi:    '是否需要批量解锁选中的账户VIP等级？解锁后的账户会受VIP升降级规则限制', \\memberList.ts 
    quKuanJiLu: '取款纪录', \\financialManagement.ts 
    chaoShiWeiQueRen: '超时未确认到帐', \\financialManagement.ts 
    qingShuRuXingMing: '请输入姓名，多个姓名请用","隔开', \\financialManagement.ts 
    biZhong: '币种', \\financialManagement.ts 
    fuKuanRen: '付款人', \\financialManagement.ts 
    qingShuRuFuKuan: '请输入付款人', \\financialManagement.ts 
    hashZhi: '哈希值', \\financialManagement.ts 
    qingShurHashZhi: '请输入哈希值', \\financialManagement.ts 
    chuangJianXinDingDan: '创建新订单', \\financialManagement.ts 
    oRIGI: '{val1}原', \\financialManagement.ts 
    chongZhiBiZhong: '充值币种', \\financialManagement.ts 
    chongZhiShangHuXin: '充值商户信息', \\financialManagement.ts 
    shouKuanKaXinXi: '收款卡信息', \\financialManagement.ts 
    zhuSuoShuShangJi:    '注：所属上级默认为admin，可以填写其他代理，设定后无法再次修改', \\agentList.ts 
    shouKuanKaYinHang2: '收款卡银行', \\financialManagement.ts 
    shiJianNeiRong: '事件内容', \\financialManagement.ts 
    cuoHeSuoDing: '撮合锁定', \\financialManagement.ts 
    queRenFuKuan: '确认付款', \\financialManagement.ts 
    queRenShouKuan: '确认收款', \\financialManagement.ts 
    buDan: '补单', \\financialManagement.ts 
    chongZhiDingDanQu: '充值订单取消', \\financialManagement.ts 
    cuoHeSuoDingJie: '撮合锁定解除', \\financialManagement.ts 
    cuoHeChengGong: '撮合成功', \\financialManagement.ts 
    daEChongZhi: '大额充值', \\financialManagement.ts 
    xuNiDaiLi: '虚拟代理', \\models.ts 
    zhengZaiQieHuanZhu: '正在切换主题！', \\models.ts 
    daiLiYuMingGuan: '代理域名管理', \\models.ts 
    xuNiHuiYuan: '虚拟会员', \\models.ts 
    tiXianDingDanChuang: '提现订单创建', \\financialManagement.ts 
    shiFouQiYongJiao: '是否启用脚本', \\rechargeMerchantSet.ts 
    qingShuRuShiJi: '请输入实际脚本', \\rechargeMerchantSet.ts 
    shiJiJiaoBen: '实际脚本', \\rechargeMerchantSet.ts 
    shangHuID: '商户ID', \\rechargeMerchantSet.ts 
    sanFangPingTaiI: '三方平台ID', \\rechargeMerchantSet.ts 
    qingShuRuShangHu: '请输入商户号', \\rechargeMerchantSet.ts 
    qingXuanZeSanFang: '请选择三方平台', \\rechargeMerchantSet.ts 
    sanFangPingTai: '三方平台', \\rechargeMerchantSet.ts 
    bianJiJiaoBen: '编辑脚本', \\rechargeMerchantSet.ts 
    qingShuRuJiaoBen: '请输入脚本', \\rechargeMerchantSet.ts 
    qingShuRuYongHu2: '请输入用戶名', \\rechargeMerchantSet.ts 
    chongZhiXingMingCi: '充值姓名次数限制白名单', \\rechargeMerchantSet.ts 
    gongXiNinPeiZhi: '恭喜您，配置成功！', \\rechargeMerchantSet.ts 
    shiFouKaiQiTong: '是否开启通道展示:', \\rechargeMerchantSet.ts 
    meiRiRuKuanShang: '每日入款上限', \\rechargeMerchantSet.ts 
    zhuShangHuKaiQi:    '注：商户开启后才可以在“三方入款应用”中应用并上架，若是关闭则“三方入款应用”中的商户为关闭状态；关闭后前台也无法展示此三方商户', \\rechargeMerchantSet.ts 
    queDingYaoGuanBi: '确定要关闭此三方商户吗？', \\rechargeMerchantSet.ts 
    queDingYaoKaiQi: '确定要开启此三方商户吗？', \\rechargeMerchantSet.ts 
    guanBiSanFangShang: '关闭三方商户', \\rechargeMerchantSet.ts 
    kaiQiSanFangShang: '开启三方商户', \\rechargeMerchantSet.ts 
    gongDATA: '\n      共 {val1} 条记录，\n      第 {val2}/{val3} 页', \\rechargeMerchantSet.ts 
    queDingYaoGuanBi2: '确定要关闭通道展示吗？', \\rechargeMerchantSet.ts 
    queDingYaoShanChu: '确定要删除该三方商户吗？', \\rechargeMerchantSet.ts 
    jiaoYiHaXiZhi: '交易哈希值', \\models.ts 
    qingShuRuZhengShu: '请输入1-999整數', \\rechargeMerchantSet.ts 
    chongZhiXingMingCi2: '充值姓名次数限制需為1-999整數', \\rechargeMerchantSet.ts 
    chongZhiXingMingCi3: '充值姓名次数限制', \\rechargeMerchantSet.ts 
    bianJiSanFangPing: '编辑三方平台', \\rechargeMerchantSet.ts 
    xinZengSanFangPing: '新增三方平台', \\rechargeMerchantSet.ts 
    tingZhiShouKuanXian2: '停止收款限額', \\rechargeMerchantSet.ts 
    tingZhiShouKuanXian: '停止收款限額为必填项!', \\rechargeMerchantSet.ts 
    dangRiRuKuanShang: '当日入款上限为必填项!', \\rechargeMerchantSet.ts 
    dangRiRuKuanShang2: '当日入款上限', \\rechargeMerchantSet.ts 
    qingShuRuJieGuo: '请输入结果URL', \\rechargeMerchantSet.ts 
    jieGuoURL: '结果URL为必填项!', \\rechargeMerchantSet.ts 
    jieGuoURL2: '结果URL', \\rechargeMerchantSet.ts 
    jieShouURL: '接收URL为必填项!', \\rechargeMerchantSet.ts 
    qingShuRuJieShou: '请输入接收URL', \\rechargeMerchantSet.ts 
    jieShouURL2: '接收URL', \\rechargeMerchantSet.ts 
    qingShuRuQingQiu: '请输入请求URL', \\rechargeMerchantSet.ts 
    qingQiuURL: '请求URL为必填项!', \\rechargeMerchantSet.ts 
    qingQiuURL2: '请求URL', \\rechargeMerchantSet.ts 
    qingShuRuSiYao: '请输入私钥', \\rechargeMerchantSet.ts 
    siYaoWeiBiTian: '私钥为必填项!', \\rechargeMerchantSet.ts 
    siYao: '私钥', \\rechargeMerchantSet.ts 
    qingShuRuGongYao: '请输入公钥', \\rechargeMerchantSet.ts 
    sanFangShangHuTong: '三方商户通道代码', \\rechargeMerchantSet.ts 
    gongYao: '公钥', \\rechargeMerchantSet.ts 
    tongDaoChongZhiJin: '通道充值金额为必选项!', \\rechargeMerchantSet.ts 
    gongYaoWeiBiTian: '公钥为必填项!', \\rechargeMerchantSet.ts 
    qingShuRuTongDao: '请输入通道充值金额', \\rechargeMerchantSet.ts 
    shangHuHaoWeiBi: '商户号为必选项!', \\rechargeMerchantSet.ts 
    sanFangPingTaiWei: '三方平台为必选项!', \\rechargeMerchantSet.ts 
    quDaoLeiXing: '渠道类型', \\rechargeMerchantSet.ts 
    shiFouKaiQiTong2: '是否开启通道展示', \\rechargeMerchantSet.ts 
    tiXianDingDanQu: '提现订单取消', \\financialManagement.ts 
    tongDaoChongZhiJin2: '通道充值金额!', \\rechargeMerchantSet.ts 
    queDingYaoKaiQi2: '确定要开启通道展示吗？', \\rechargeMerchantSet.ts 
    kaiGuanZhuangTai: '开关状态', \\rechargeMerchantSet.ts 
    piLiangGuanBiShang: '批量关闭商户', \\rechargeMerchantSet.ts 
    piLiangKaiQiShang: '批量开启商户', \\rechargeMerchantSet.ts 
    chongZhiEDuLei: '充值额度类型', \\rechargeRecord.ts 
    queRenShouKuanShi: '确认收款时间', \\rechargeRecord.ts 
    queRenFuKuanShi: '确认付款时间', \\rechargeRecord.ts 
    chongZhiFaQiShi: '充值发起时间', \\rechargeRecord.ts 
    zhuDuiYuKuaiSu: '注：对于快速转卡的提现方式必须要上传转账图片', \\withdrawPayment.ts 
    dongTaiTuPian: '动态图片', \\withdrawPayment.ts 
    jiSuZhuanKaDe: '急速转卡的提现方式必须要上传转账图片', \\withdrawPayment.ts 
    shuRuFanHuiZhong: '输入返回中心钱包的金额', \\withdrawPayment.ts 
    guGeShenFenYan: '谷歌身份验证码', \\withdrawPayment.ts 
    zhuQuanBuTuiHui: '注：全部退回，订单状态为失败；部分退回，提现状态为成功', \\withdrawPayment.ts 
    buFenTuiHui: '部分退回', \\withdrawPayment.ts 
    quanBuTuiHui: '全部退回', \\withdrawPayment.ts 
    zhiNengShuRuZheng: '只能输入正整数且输入的退回金额不能大于提现金额', \\withdrawPayment.ts 
    xuanZeShangChuanDe: '选择上传的图片格式有误，请重新选择', \\withdrawPayment.ts 
    daiQueRenDaoZhang: '待确认到帐js', \\withdrawPayment.ts 
    dengDaiFuKuanJ: '等待付款js', \\withdrawPayment.ts 
  