export default {
  config: {
null    huiTiaoDiZhiBu: '回调地址不能为空',
huiTiaoDiZhiBu: "ที่อยู่ติดต่อกลับ (ห้ามเว้นว่าง)", 
zhiFuBaoGongYao: "คีย์สาธารณะของอาลีเพย์ (ห้ามเว้นว่าง)", 
shangHuSiYaoBu: "คีย์ส่วนตัวขอร้านค้า (ห้ามเว้นว่าง)", 
qingShuRuShangJia: "กรุณากรอกเลขที่บัญชีร้านค้า", 
qingShuRuAP: "กรุณากรอก appID", 
baoCunPeiZhi: "บันทึกการกำหนดค่า", 
zhiFuJieGuoYi: "ที่อยู่แจ้งผลการชำระเงินแบบอะซิงโครนัส", 
yiBuTongZhi: "การแจ้งเตือนแบบอะซิงโครนัส", 
dingDanWanChengHou: "ที่อยู่ที่ส่งกลับหลังจากการรายการเสร็จสมบูรณ์", 
huiTiaoDiZhi: "ที่อยู่เรียกกลับมา", 
zhiFuBaoGongYao2: "คีย์สาธารณะของ Alipay", 
shangHuSiYaoNi: "คีย์ส่วนตัวของร้านค้า คีย์ส่วนตัว RSA2 ของคุณในรูปแบบ PKCS8", 
shangHuSiYao: "คีย์ส่วนตัวของร้านค้า", 
shangJiaZhangHao: "เลขที่บัญชีร้านค้า", 
  },
  index: {
yingYongAPP: "ใช้ APPID บัญชีรับเงินต้องเป็น APPID ที่สอดคล้องกับบัญชี Alipay", 
    ruXuFuKuanCe:
      '\n如需付款测试，请使用\n账号：uuxesw9745@sandbox.com\n密码与支付密码：111111',
zhiFuSheZhi: "การตั้งค่าการชำระเงิน", 
zhiFuBaoKaiFa: "แพลตฟอร์มการพัฒนา Alipay", 
ceShiSuoYongCan: "พารามิเตอร์ที่ใช้ในการทดสอบคือสภาพแวดล้อมของแซนด์บ็อกซ์ทั้งหมดซึ่งมีไว้สําหรับการทดสอบเท่านั้น ที่อยู่แอปพลิเคชัน：", 
zhuYi: "ระวัง", 
shiYongShuoMing: "คำแนะนำสำหรับการใช้งาน", 
zhiFuCeShi: "การทดสอบการชำระเงิน", 
  },
  toPay: {
canShuPeiZhi: "การกำหนดค่าพารามิเตอร์", 
shangPinMiaoShuBu: "รายละเอียดสินค้า (ห้ามเว้นว่าง)", 
shangPinJiaGeBu: "ราคาสินค้า (ห้ามเว้นว่าง)", 
shangPinMingChengBu: "ชื่อสินค้า (ห้ามเว้นว่าง)", 
quZhiFu: "ไปที่การชำระเงิน", 
shangPinMiaoShu: "รายละเอียดสินค้า", 
ceShiYunXuQu: "ช่วงทดสอบที่อนุญาต(0,5000]", 
shangPinJiaGe: "ราคาสินค้า", 
shangPinMingCheng: "ชื่อสินค้า", 
  },
};
