export default {
  addAwake: {
    sCEEN: "[{val1}] เชื่อมโยงกับ [{val2}]!", 
    bianJiChengGong: "แก้ไขสำเร็จ!", 
    tianJiaChengGong: "เพิ่มสำเร็จ!", 
    qingXuanZeGuanLian: "โปรดเลือกกลุ่มทักษะที่เกี่ยวข้อง", 
    qingXuanZeHuanXing: "โปรดเลือกสถานการณ์ปลุก", 
        quXiao: '取消',
    quXiao: "ยกเลิก", 
    beiZhu: "หมายเหตุ", 
    ruoYouDuoGeYe: "หากมีหลายหน้า โปรดใช้", 
    huanXingYeMian: "หน้าปลุก", 
    qingXuanZeJiNeng: "กรุณาเลือกกลุ่มทักษะ", 
    guanLianJiNeng: "ทักษะที่เกี่ยวข้อง", 
    huanXingChangJing: "หน้าปลุก", 
  },
  awakenIndex: {
    huanXingID: "ไอดี ปลุก", 
    shanChuChengGong: "ลบสำเร็จแล้ว", 
    shuoMingRuGuoShang:
      '说明:如果商户端已调用该ID，删除后客户会直接进入询前页。',
    ninQueDingShanChu:
      '您确定删除【{val1}（ID{val2}）】的关联的【{val3}】的记录?',
        shanChuHuanXingChang: '删除唤醒场景',
    shanChuHuanXingChang: "ลบหน้าปลุก", 
    tianJiaHuanXingChang: "เพิ่มหน้าปลุก", 
    bianJiHuanXingChang: "แก้ไขหน้าปลุก", 
    huanXingChangJingLie: "รายการหน้าปลุก", 
        bianJi: '编辑',
    bianJi: "แก้ไข", 
    caoZuo: "การดำเนินการ", 
    tianJia: "เพิ่ม", 
    suoYouJiNengZu: "กลุ่มทักษะทั้งหมด", 
    suoYouHuanXingChang: "หน้าปลุกทั้งหมด", 
    suoYouHuanXingI: "ไอดี หน้าปลุกทั้งหมด", 
  },
};
