export default {
  index: {
        queDing: '确定',
    queDing: "ยืนยัน", 
    jieChuYongHuHei: "ปลดบล็อกรายการบัญชีผู้ใช้", 
    queDingJiangGaiYong: "ยืนยันเพื่อยกเลิกการบล็อกผู้ใช้รายนี้ {val1}?", 
    puTongKeHu: "ลูกค้าทั่วไป", 
        shi: '是',
    shi: "ใช่", 
        keHuZhangHuMing: '客户账户名',
        gengXinRiQi: '更新日期',
        chuangJianRiQi: '创建日期',
    chuangJianRiQi: "วันที่สร้าง", 
    heiMingDan: "บล็อก", 
    jieJin: "ปลดบล็อก", 
        caoZuo: '操作',
    caoZuo: "การดำเนินการ", 
    chuangJianGengXinRi: "วันที่สร้าง/อัปเดต", 
    laHeiLeiXing: "ประเภทบล็อก", 
        vIPJiBie: 'VIP级别',
        keHuDengJi: '客户等级',
    keHuDengJi: "ระดับลูกค้า", 
    shiFouXinKeHu: "ใช่ลูกค้าใหม่หรือไม่", 
        kaiShiRiQi: '开始日期',
    kaiShiRiQi: "วันที่เริ่มต้น", 
        qingShuRuSouSuo: '请输入搜索内容',
  },
};
