export default {
  index: {
    quXiao: '取消',
    queDing: '确定',
    jieChuYongHuHei: '解除用户黑名单',
jieChuYongHuHei: "ปลดบล็อกรายการบัญชีผู้ใช้", 
    puTongKeHu: '普通客户',
    fou: '否',
    shi: '是',
    xingMing: '姓名',
    keHuZhangHuMing: '客户账户名',
    gengXinRiQi: '更新日期',
    chuangJianRiQi: '创建日期',
    heiMingDan: '黑名单',
heiMingDan: "บล็อก", 
jieJin: "ปลดบล็อก", 
    caoZuo: '操作',
    chuangJianGengXinRi: '创建/更新日期',
chuangJianGengXinRi: "วันที่สร้าง/อัปเดต", 
    keHuFenZu: '客户分组',
    vIPJiBie: 'VIP级别',
    keHuDengJi: '客户等级',
    shiFouXinKeHu: '是否新客户',
shiFouXinKeHu: "ใช่ลูกค้าใหม่หรือไม่", 
    kaiShiRiQi: '开始日期',
    qingShuRuSouSuo: '请输入搜索内容',

  },
};
