export default {
  setFunction: {
    zhiNengXiuGaiCheng: '职能修改失败',
    zhiNengBuNengWei: '职能不能为空',
    qingXuanZeZhiNeng: '请选择职能',
    qingXianXuanZeZhi: '请先选择职能',
    xiuGaiZhiNeng: '修改职能',
  },
  updateEmail: {
    huoQuYanZhengMa: '获取验证码',
    youXiangXiuGaiCheng: '邮箱修改失败',
    chongXinFaSong: '重新发送',
    miaoHouChongXinFa: '秒后重新发送',
    faSongChengGongYan: '发送成功，验证码有效期5分钟',
    yanZhengMaFaSong: '验证码发送中',
    yanZhengMaBuNeng: '验证码不能为空',
    dangQianMiMaBu: '当前密码不能为空',
    xiuGaiYouXiang: '修改邮箱',
    youXiangGeShiCuo: '邮箱格式错误',
    xinYouXiangBuNeng: '新邮箱不能与旧邮箱相同',
    xinYouXiangBuNeng2: '新邮箱不能为空',
    dangQianMiMa: '当前密码',
    yanZhengMa: '验证码',
    xinYouXiang: '新邮箱',
  },
  updatePass: {
    miMaXiuGaiCheng: '密码修改失败，请重新登录',
    weiYiShangMiMa:
      '8-20位以上密码,数字,字母,字符至少包含两种,不能包含中文和空格',
    weiShuZiZiMu: '8-20位数字,字母,字符至少包含两种,不能包含中文和空格',
    qingShuRuXinMi: '请输入新密码',
    qingShuRuJiuMi: '请输入旧密码',
    qingShuRuZhangHu: '请输入账户名',
    xinMiMaBuNeng: '新密码不能与初始密码相同',
    qingZaiCiShuRu: '请再次输入密码',
    liangCiShuRuDe: '两次输入的密码不一致',
    queRenMiMa: '确认密码',
    xinMiMa: '新密码',
    chuShiMiMa: '初始密码',
    yuanZhangHuMiMa: '原账户密码',
    zhangHu: '账户',
    weiLeNinDeZhang:
      '为了您的账号安全，请您修改登录密码。修改完成后，需要重新登录。',
    xiuGaiMiMa: '修改密码',
    xiuGaiZhangHuHe: '修改账户和密码',

  },
};
