export default {
  setFunction: {
zhiNengXiuGaiCheng: "แก้ไขฟังก์ชันเรียบร้อยแล้ว", 
zhiNengXiuGaiCheng: "แก้ไขฟังก์ชันเรียบร้อยแล้ว", 
zhiNengBuNengWei: "ฟังก์ชัน (ห้ามเว้นว่าง)", 
qingXuanZeZhiNeng: "กรุณาเลือกฟังก์ชั่น", 
qingXianXuanZeZhi: "กรุณาเลือกฟังก์ชั่นก่อน", 
  },
  updateEmail: {
xiuGaiZhiNeng: "แก้ไขฟังก์ชั่น", 
huoQuYanZhengMa: "รับรหัสยืนยัน", 
youXiangXiuGaiCheng: "แก้ไขอีเมลเรียบร้อยแล้ว", 
chongXinFaSong: "ส่งใหม่อีกครั้ง", 
miaoHouChongXinFa: "ส่งอีกครั้งในไม่กี่วินาที", 
faSongChengGongYan: "ส่งสำเร็จ รหัสยืนยันมีอายุ 5 นาที", 
yanZhengMaFaSong: "กำลังส่งรหัสยืนยัน", 
    dangQianMiMaBu: '当前密码不能为空',
dangQianMiMaBu: "รหัสผ่านปัจจุบัน (ห้ามเว้นว่าง)", 
xiuGaiYouXiang: "แก้ไขอีเมล", 
youXiangGeShiCuo: "ข้อผิดพลาดของรูปแบบอีเมล", 
xinYouXiangBuNeng: "อีเมลใหม่ต้องไม่เหมือนกับอีเมลเก่า", 
xinYouXiangBuNeng2: "อีเมลใหม่ (ห้ามเว้นว่าง)", 
dangQianMiMa: "รหัสผ่านปัจจุบัน", 
    xinYouXiang: '新邮箱',
  },
  updatePass: {
xinYouXiang: "อีเมลใหม่", 
    weiYiShangMiMa:
      '8-20位以上密码,数字,字母,字符至少包含两种,不能包含中文和空格',
miMaXiuGaiCheng: "เปลี่ยนรหัสผ่านสำเร็จ กรุณาเข้าสู่ระบบอีกครั้ง", 
weiShuZiZiMu: "8-20 ตัว ประกอบด้วยตัวเลขและตัวอักษรอย่างน้อย 2 ชนิด ห้ามมีภาษาจีนและเว้นวรรค", 
qingShuRuXinMi: "กรุณาใส่รหัสผ่านใหม่", 
qingShuRuJiuMi: "กรุณาใส่รหัสผ่านเก่า", 
    xinMiMaBuNeng: '新密码不能与初始密码相同',
xinMiMaBuNeng: "รหัสผ่านใหม่ต้องไม่เหมือนกับรหัสผ่านเริ่มต้น", 
qingZaiCiShuRu: "กรุณาใส่รหัสผ่านอีกครั้ง", 
liangCiShuRuDe: "รหัสผ่านที่ป้อนสองครั้งไม่ตรงกัน", 
queRenMiMa: "ยืนยันรหัสผ่าน", 
xinMiMa: "รหัสผ่านใหม่", 
chuShiMiMa: "รหัสผ่านเริ่มต้น", 
yuanZhangHuMiMa: "รหัสผ่านบัญชีเดิม", 
    weiLeNinDeZhang:
      '为了您的账号安全，请您修改登录密码。修改完成后，需要重新登录。',
zhangHu: "บัญชี", 
xiuGaiMiMa: "เปลี่ยนรหัสผ่าน", 
xiuGaiZhangHuHe: "แก้ไขบัญชีและรหัสผ่าน", 
  },
};
