export default {
  index: {
    xiangYingCuoWuQing: "เกิดข้อผิดพลาดในการตอบกลับ โปรดลองอีกครั้งในภายหลัง!", 
    feiTiaoZhuan: "ไม่สามารถโดดข้าม", 
    weiJieJue: "ยังไม่ได้แก้ไข", 
    yiJieJue: "แก้ไขแล้ว", 
    wuXiaoHuiHua: "บทสนทนาไม่มีประสิทธิภาพ", 
    youXiaoHuiHua: "บทสนทนาที่มีประสิทธิภาพ", 
    weiZongJie: "ยังไม่สรุปผล", 
    keFuZhuanJie: "การโอนบริการลูกค้า", 
    yaoQingHuiHua: "เชิญบทสนทนา", 
    ziDongFenPei: "การจัดสรรอัตโนมัติ", 
    paiDuiLiKai: "คิวที่จะออก", 
    paiDuiJinRu: "เข้าคิว", 
    weiPaiDui: "ไม่มีคิว", 
    fou: "ไม่", 
    shi: "ใช่", 
    zhiJianRenZhiJian: "คนตรวจสอบ/เวลาตรวจสอบ", 
    xiaoXiShuKeHu: "จำนวนข้อความ (ลูกค้า / ฝ่ายบริการลูกค้า)", 
    keFuZongJie: "สรุปผลการบริการลูกค้า", 
        paiDuiXinXi: '排队信息',
    paiDuiXinXi: "ข้อมูลคิว", 
    jieDaiKeFu: "ฝ่ายต้อนรับลูกค้า", 
    huiHuaKaiShiShi: "เวลาเริ่มต้นบทสนทนา", 
    wenTiShiChang: "คำถาม/ระยะเวลา", 
    keHuQuDao: "ลูกค้า/ช่องทาง", 
    keFuLeiXing: "ประเภทการบริการลูกค้า", 
    keHuLeiXing: "ประเภทลูกค้า", 
    yiZhiJianHuiHua: "การสทนาที่ผ่านการตรวจสอบ", 
    weiZhiJianHuiHua: "การสทนาที่ยังไม่ผ่านการตรวจสอบ", 
    buHeGeLuShu: "อัตราไม่ผ่าน/จำนวน", 
    jiGeLuShu: "อัตราการผ่าน/จำนวน", 
    liangHaoLuShu: "อัตราดี/จำนวน", 
    youXiuLuShu: "อัตราที่ยอดเยี่ยม/จำนวน", 
    heGeLuShu: "อัตราผ่าน/จำนวน", 
    zhiJianLuShu: "อัตราการตรวจสอบคุณภาพ/จำนวน", 
    sheZhiXianShiZi: "ตั้งค่าฟิลด์แสดงผล", 
    gengDuoShaiXuanTiao: "เงื่อนไขการคัดกรองมากกว่านี้", 
    gengDuoShaiXuanTiao2: "เงื่อนไขการคัดกรองมากกว่านี้", 
    qingShuRuZhiJian: "โปรดกรอกผู้ตรวจสอบคุณภาพ", 
    huiHuaJieShuLei: "ประเภทการสิ้นสุดบทสนทนา", 
    huiHuaShiFouJie: "บทสนทนาได้รับการแก้ไขแล้วหรือไม่", 
    keFuZongJieLei: "หมวดหมู่สรุปผลการบริการลูกค้า", 
    pingJiaLeiXing: "ประเภทการประเมิน", 
    xingJiPingJia: "ระดับดาว", 
    miao: "วินาที", 
    pingJunXiangYingShi: "เวลาตอบสนองเฉลี่ย", 
    shouCiXiangYingShi: "เวลาตอบกลับครั้งแรก", 
    huiHuaShiChang: "ระยะเวลาบทสนทนา", 
    qingShuRuHuiHua: "โปรดกรอก ไอดี การสนทา", 
    quanBuJiNengZu: "ชุดทักษะทั้งหมด", 
    quanBuJieDaiKe: "ฝ่ายบริการลูกค้าทั้งหมด", 
  },
  session_table: {
    yiPingJia: "ประเมินแล้ว", 
    weiPingJia: "ยังไม่ประเมิน", 
    jieShuFangShi: "วิธีการสิ้นสุด", 
    zuiDaXiangYingShi: "ระยะเวลาตอบสนองสูงสุด", 
    shouXiangShiChang: "ระยะเวลาเสียงแรก", 
    xiangYingShiChang: "เวลาตอบสนอง", 
    shiFouJieJue: "แก้ไขแล้วหรือไม่", 
    zhuDongPingJia: "การประเมินเอง", 
    yaoQingPingJia: "ส่งเชิญประเมิน", 
    shiFouPingJia: "ประเมินหรือไม่", 
    keHuPingJia: "การประเมินของลูกค้า", 
    yeWu: "ธุรกิจ", 
        huiHuaLeiBie: '会话类别',
  },
};
