export default {
  PieChart: {
    bCGeZhanD: '{b} : {c}个(占{d}%)'
  },
  a: {
    danXuan: '单选',
    quanXuan: '全选',
quanXuan: "เลือกทั้งหมด", 
    queRen: '确认',
    sheZhiKanBanCan: '设置看板参数'
  },
  barOne: {
    shiChang: '时长'
  },
  chatInfo: {
    language: '语言',
language: "ภาษา", 
anZhuo: "แอนดรอยด์", 
    tiShi: '提示',
    fuWuYiChangQing: '服务异常，请安排接待客服主动关闭该会话！',
fuWuYiChangQing: "การบริการผิดปกติ โปรดจัดฝ่ายบริการลูกค้าต้อนรับเพื่อปิดบทสนทนานี้!", 
    paiDuiJinRu: '排队进入',
    weiPaiDui: '未排队',
    fou: '否',
    shi: '是',
shi: "ใช่", 
    wuXiaoHuiHua: '无效会话',
wuXiaoHuiHua: "บทสนทนไม่มีประสิทธิภาพ", 
    yiJieJue: '已解决',
    weiZhiJian: '未质检',
    yiZhiJian: '已质检',
yiZhiJian: "ตรวจสอบแล้ว", 
    keHuZiXunCi: '客户咨询次数：',
keHuZiXunCi: "จำนวนครั้งที่ลูกค้าสอบถาม", 
    keHuDuanKeFu: '客户端/客服系统版本：',
keHuDuanKeFu: "หน้าลูกค้า/เวอร์ชันระบบบริการลูกค้า", 
jinRuYuMing: "เข้าถึงชื่อโดเมน：", 
iPDiZhi: "ที่อยู่ IP.", 
fangWenLiuLanQi: "เข้าถึงเบราว์เซอร์：", 
    jinRuYeMian: '进入页面：',
jinRuYeMian: "หน้าการเข้าถึง", 
    keHuXingMing: '客户姓名：',
    keHuXinXi: '客户信息',
keHuXinXi: "ข้อมูลลูกค้า", 
    pingJiaNeiRong: '评价内容：',
pingJiaNeiRong: "เนื้อหาการประเมิน", 
    pingJiaXingJi: '评价星级：',
pingJiaXingJi: "การประเมินระดับดาว", 
    zhuDongPingJia: '主动评价',
    yaoQingPingJia: '邀请评价',
    pingJiaLeiXing: '评价类型：',
pingJiaLeiXing: "ประเภทการประเมิน", 
    fuWuZongJie: '服务总结',
fuWuZongJie: "สรุปบริการ", 
weiZhiJian2: "ยังไม่ผ่านการตรวจสอบ", 
yiZhiJian2: "ตรวจสอบแล้ว", 
    xiaZhuZhangHao: '下注账号:',
xiaZhuZhangHao: "วางบัญชี:", 
dingDanZhuangTai: "สถานะรายการ:", 
    yuyueDaozhang: '预约到账',
    xiaoshi: '小时',
    yuyueTixian: '预约提现',

    shuYingJieGuo: '输赢结果:',
shuYingJieGuo: "ผลการชนะ/แพ้:", 
xiaZhuJinE: "จำนวนเงินเดิมพัน:", 
youXiChanPin: "สินค้าเกม:", 
tiXianZhangHao: "หมายเลขบัญชีถอน:", 
daoZhangShuLiang: "จำนวนเงินที่เข้าบัญชี:", 
tiXianJinE: "จำนวนเงินที่ถอน:", 
tiXianFangShi: "วิธีการถอนเงิน:", 
    chongzhiBiZhong: '充值币种:',
    xiazhuBiZhong: '下注币种:',
    chongZhiZhangHao: '充值账号:',
chongZhiZhangHao: "เลขที่บัญชีเงินฝาก:", 
    zhiFuFangShi: '支付方式:',
zhiFuFangShi: "วิธีการชำระ", 
chongZhiFangShi: "วิธีการ ฝากเงิน", 
dingDanHao: "เลขรายการ", 
yiChangGuanBi: "ปิดผิดปกติ", 
chiXuShiChang: "ระยะเวลา:", 
    huiHuaZhong: '(会话中)',
    huiHuaXiaoXiShu: '\n                    会话消息数',
    keFu: '/客服:',
    keHu: '(客户:',
    paiDuiXinXi: '\n                    排队信息：',
    jieRuFangShi: '\n                    接入方式：',
jieRuFangShi: "วิธีการเข้าถึง", 
    chaXun: '查询',
    zongJieLeiXing: '总结类型',
zongJieLeiXing: "ประเภทสรุป", 
    zuoTian: '昨天',
zuoTian: "เมื่อวาน", 
jinTian: "วันนี้", 
  },
  chatInfoResult: {
    zhiJianShiJian: '质检时间：',
zhiJianShiJian: "เวลาตรวจสอบคุณภาพ", 
zhiJianRen: "คนตรวจสอบคุณภาพ", 
    keHuChaPingYuan2: '客户差评原因：',
    zhiJianYiJian: '质检意见：',
    zhiJianBiaoQian: '质检标签：',
    fen: '分',
    con: '：',
    fen2: '分)',
fen2: "คะแนน", 
    huiHuaZhiJian: '会话质检'
  },
  chatInfoSubmit: {
huiHuaZhiJian: "การตรวจสอบคุณภาพบทสนทนา", 
zhiJianChengGong: "การควบคุมคุณภาพสำเร็จ", 
fenShuBuZaiZhi: "คะแนนไม่อยู่กฎเกณฑ์ที่ตั้งไว้", 
    yiBan: '一般',
    manYi: '满意',
    feiChangManYi: '非常满意',
feiChangManYi: "พอใจมาก", 
    qingXuanZe: '请选择',
    queDing: '确 定',
    quXiao: '取 消',
    keHuChaPingYuan: '客户差评原因备注:',
    feiWuXingDuSuan: '非五星都算差评',
    keHuChaPingYuan2: '客户差评原因:',
keHuChaPingYuan2: "เหตุผลสำหรับแบบประเมินที่ไม่ดีจากลูกค้า:", 
    zhiJianBiaoQian: '质检标签:',
    fen: '\n          分\n          ',
fen: "คะแนน", 
    zhiJianJieGuo2: '质检结果：'
  },
  dateCommon: {
zhiJianJieGuo2: "ผลการตรวจสอบคุณภาพ.", 
shiJianXuanZeFan: "ช่วงเวลาเลือกได้ไม่เกิน 31 วัน!", 
    kaiShiRiQi: '开始日期'
  },
  editSelect: {
kaiShiRiQi: "วันที่เริ่มต้น", 
    woDeYeWuPei: '我的业务配置',
    yeWuMingCheng: '业务名称：'
  },
  filters: {
    chuFa: '11触发',
chuFa: "11 ทริกเกอร์", 
    shaiXuan: '筛选'
  },
  onlineServer: {
shaiXuan: "กรอง", 
    zhaKanZaiXianKe: '查看在线客服'
  },
  serviceSummary: {
zhaKanZaiXianKe: "ตรวจดูการบริการลูกค้าออนไลน์", 
feiKeFuWuFa: "ไม่ใช่ฝ่ายบริการลูกค้าไม่สามารถส่งได้!", 
qingXuanZeYeWu: "กรุณาเลือกธุรกิจ", 
iDPaiXu: "การเรียงลำดับ ไอดี", 
    yeWu: '业务',
yeWu: "ธุรกิจ", 
xuanZeYeWu: "เลือกธุรกิจ", 
    qingXuanZeSuoShu: '请选择所属业务',
qingXuanZeSuoShu: "กรุณาเลือกธุรกิจของคุณ", 
zongJie: "สรุป", 
    zongJie2: '\n        总结\n      ',
zongJie2: "สรุป", 
yu: "ใน", 
    beiZhuShuoMing: '备注说明:',
beiZhuShuoMing: "หมายเหตุ:", 
yeWuLeiXing2: "ประเภทธุรกิจ:", 
    youXiaoHuiHua: '有效会话',
    huiHuaLeiXing: '会话类型:',
    zheShiGeWuXiao: '这是个无效会话',
zheShiGeWuXiao: "นี่เป็นบทสนทนาที่ไม่มีประสิทธิภาพ", 
youXiaoHuiHuaTi: "บทสนทนาที่มีประสิทธิภาพ ส่งสรุป", 
qingTianXieBeiZhu: "กรุณากรอกหมายเหตุ", 
benYeWuWeiPei: "ไม่มีการกำหนดค่าประเภทสำหรับบริการนี้", 
qingXuanZeYeWu2: "กรุณาเลือกประเภทบริการ", 
wo: "ฉัน", 
  },
  setBoard: {
    zuiShaoYaoPeiZhi: '最少要配置5个哦',
    kePeiZhiDeBan: '\n              可配置的板块\n              '
kePeiZhiDeBan: "บอร์ดที่กำหนดค่าได้", 
  }
}
