export default {
  PieChart: {
  },
  a: {
        danXuan: '单选',
        quanXuan: '全选',
    quanXuan: "เลือกทั้งหมด", 
    quXiao: "ยกเลิก", 
    queRen: "ยืนยัน", 
  },
  barOne: {
    sheZhiKanBanCan: "ตั้งค่าพารามิเตอร์ป้ายโฆษณา", 
  },
  chatInfo: {
        language: '语言',
    language: "ภาษา", 
    anZhuo: "แอนดรอยด์", 
        tiShi: '提示',
        fuWuYiChangQing: '服务异常，请安排接待客服主动关闭该会话！',
    fuWuYiChangQing: "การบริการผิดปกติ โปรดจัดฝ่ายบริการลูกค้าต้อนรับเพื่อปิดบทสนทนานี้!", 
        paiDuiJinRu: '排队进入',
        weiPaiDui: '未排队',
        fou: '否',
        shi: '是',
    shi: "ใช่", 
        wuXiaoHuiHua: '无效会话',
    wuXiaoHuiHua: "บทสนทนไม่มีประสิทธิภาพ", 
        yiJieJue: '已解决',
        weiZhiJian: '未质检',
        yiZhiJian: '已质检',
    yiZhiJian: "ตรวจสอบแล้ว", 
    zanWuShuJu: "ไม่มีข้อมูลในขณะนี้", 
    keHuZiXunCi: "จำนวนครั้งที่ลูกค้าสอบถาม", 
        keHuDuanKeFu: '客户端/客服系统版本：',
    keHuDuanKeFu: "หน้าลูกค้า/เวอร์ชันระบบบริการลูกค้า", 
    jinRuYuMing: "เข้าถึงชื่อโดเมน：", 
    iPDiZhi: "ที่อยู่ IP.", 
    fangWenLiuLanQi: "เข้าถึงเบราว์เซอร์：", 
        jinRuYeMian: '进入页面：',
    jinRuYeMian: "หน้าการเข้าถึง", 
        keHuXingMing: '客户姓名：',
        keHuXinXi: '客户信息',
    keHuXinXi: "ข้อมูลลูกค้า", 
        pingJiaNeiRong: '评价内容：',
    pingJiaNeiRong: "เนื้อหาการประเมิน", 
    pingJiaBiaoQian: "แท็กการประเมิน", 
    pingJiaXingJi: "การประเมินระดับดาว", 
        zhuDongPingJia: '主动评价',
        yaoQingPingJia: '邀请评价',
        pingJiaLeiXing: '评价类型：',
    pingJiaLeiXing: "ประเภทการประเมิน", 
    keHuPingJia: "การประเมินของลูกค้า", 
    fuWuZongJie: "สรุปบริการ", 
    weiZhiJian2: "ยังไม่ผ่านการตรวจสอบ", 
    yiZhiJian2: "ตรวจสอบแล้ว", 
    chuangJianShiJian: "เวลาที่สร้าง", 
    xiaZhuZhangHao: "วางบัญชี:", 
    dingDanZhuangTai: "สถานะรายการ:", 
        yuyueDaozhang: '预约到账',
        xiaoshi: '小时',
        yuyueTixian: '预约提现',

        shuYingJieGuo: '输赢结果:',
    shuYingJieGuo: "ผลการชนะ/แพ้:", 
    xiaZhuJinE: "จำนวนเงินเดิมพัน:", 
    youXiChanPin: "สินค้าเกม:", 
    tiXianZhangHao: "หมายเลขบัญชีถอน:", 
    daoZhangShuLiang: "จำนวนเงินที่เข้าบัญชี:", 
    tiXianJinE: "จำนวนเงินที่ถอน:", 
    tiXianFangShi: "วิธีการถอนเงิน:", 
        chongzhiBiZhong: '充值币种:',
        xiazhuBiZhong: '下注币种:',
        chongZhiZhangHao: '充值账号:',
    chongZhiZhangHao: "เลขที่บัญชีเงินฝาก:", 
    chongZhiJinE: "จำนวนเงินฝาก", 
    zhiFuFangShi: "วิธีการชำระ", 
    chongZhiFangShi: "วิธีการ ฝากเงิน", 
    dingDanHao: "เลขรายการ", 
    yiChangGuanBi: "ปิดผิดปกติ", 
    chiXuShiChang: "ระยะเวลา:", 
    jieShuFangShi: "วิธีการสิ้นสุด", 
    huiHuaZhong: "อยู่ระหว่างบทสนทนา", 
    huiHuaXiaoXiShu: "จำนวนข้อความบทสนทนา", 
    keFu: "/บริการลูกค้า:", 
    keHu: "(ลูกค้า:", 
    paiDuiXinXi: "ข้อมูลคิว", 
    jieRuFangShi: "วิธีการเข้าถึง", 
    huiHuaID: "ไอดี บทสนทนา", 
    chaXun: "ตรวจสอบ", 
    zongJieLeiXing: "ประเภทสรุป", 
    tian: "7วัน", 
    zuoTian: "เมื่อวาน", 
    jinTian: "วันนี้", 
  },
  chatInfoResult: {
    quanBu: "ทั้งหมด", 
    zhiJianShiJian: "เวลาตรวจสอบคุณภาพ", 
    zhiJianRen: "คนตรวจสอบคุณภาพ", 
    keHuChaPingYuan: "หมายเหตุแบบประเมินที่ไม่ดีจากลูกค้า", 
        zhiJianYiJian: '质检意见：',
        zhiJianBiaoQian: '质检标签：',
        fen: '分',
        con: '：',
        fen2: '分)',
    fen2: "คะแนน", 
    zhiJianJieGuo: "ผลการตรวจสอบคุณภาพ.", 
  },
  chatInfoSubmit: {
    huiHuaZhiJian: "การตรวจสอบคุณภาพบทสนทนา", 
    zhiJianChengGong: "การควบคุมคุณภาพสำเร็จ", 
    fenShuBuZaiZhi: "คะแนนไม่อยู่กฎเกณฑ์ที่ตั้งไว้", 
        yiBan: '一般',
        manYi: '满意',
        feiChangManYi: '非常满意',
    feiChangManYi: "พอใจมาก", 
    qingShuRu: "กรุณากรอก", 
    qingXuanZe: "กรุณาเลือก", 
    queDing: "ยืนยัน", 
    quXiao: "ยกเลิก", 
    keHuChaPingYuan: "หมายเหตุแบบประเมินที่ไม่ดีจากลูกค้า", 
        keHuChaPingYuan2: '客户差评原因:',
    keHuChaPingYuan2: "เหตุผลสำหรับแบบประเมินที่ไม่ดีจากลูกค้า:", 
        zhiJianBiaoQian: '质检标签:',
        fen: '\n          分\n          ',
    fen: "คะแนน", 
    zhiJianJieGuo: "ผลการตรวจสอบคุณภาพ.", 
  },
  dateCommon: {
    zhiJianJieGuo2: "ผลการตรวจสอบคุณภาพ.", 
    shiJianXuanZeFan: "ช่วงเวลาเลือกได้ไม่เกิน 31 วัน!", 
        kaiShiRiQi: '开始日期'
  },
  editSelect: {
    kaiShiRiQi: "วันที่เริ่มต้น", 
    woDeYeWuLei: "การกำหนดค่าประเภทธุรกิจของฉัน", 
    woDeYeWuPei: "การกำหนดค่าธุรกิจของฉัน", 
  },
  filters: {
    yeWuMingCheng: "ชื่อธุรกิจ", 
    chuFa: "11 ทริกเกอร์", 
    zhongZhi: "รีเซ็ต", 
  },
  onlineServer: {
    shaiXuan: "กรอง", 
    gaiKeFuZuZan: "ไม่มีบริการลูกค้าออนไลน์สำหรับกลุ่มบริการลูกค้านี้", 
  },
  serviceSummary: {
    zhaKanZaiXianKe: "ตรวจดูการบริการลูกค้าออนไลน์", 
    feiKeFuWuFa: "ไม่ใช่ฝ่ายบริการลูกค้าไม่สามารถส่งได้!", 
    qingXuanZeYeWu: "กรุณาเลือกธุรกิจ", 
    iDPaiXu: "การเรียงลำดับ ไอดี", 
        yeWu: '业务',
    yeWu: "ธุรกิจ", 
    xuanZeYeWu: "เลือกธุรกิจ", 
        qingXuanZeSuoShu: '请选择所属业务',
    qingXuanZeSuoShu: "กรุณาเลือกธุรกิจของคุณ", 
    zongJie: "สรุป", 
    bianJi: "แก้ไข", 
    zongJie2: "สรุป", 
    yu: "ใน", 
    chuLiZhuangTai: "สถานะการประมวลผล:", 
    beiZhuShuoMing: "หมายเหตุ:", 
    yeWuLeiXing2: "ประเภทธุรกิจ:", 
    suoShuYeWu: "ธุรกิจ:", 
    youXiaoHuiHua: "บทสนทนาที่ถูกต้อง", 
    huiHuaLeiXing: "ประเภทบทสนทนา:", 
    zheShiGeWuXiao: "นี่เป็นบทสนทนาที่ไม่มีประสิทธิภาพ", 
    youXiaoHuiHuaTi: "บทสนทนาที่มีประสิทธิภาพ ส่งสรุป", 
    qingTianXieBeiZhu: "กรุณากรอกหมายเหตุ", 
    benYeWuWeiPei: "ไม่มีการกำหนดค่าประเภทสำหรับบริการนี้", 
    qingXuanZeYeWu2: "กรุณาเลือกประเภทบริการ", 
    wo: "ฉัน", 
  },
  setBoard: {
        zuiShaoYaoPeiZhi: '最少要配置5个哦',
    zuiShaoYaoPeiZhi: "การกำหนดค่าอย่างน้อย 5 รายการ", 
    kePeiZhiDeBan: "บอร์ดที่กำหนดค่าได้", 
  }
}
