export default {
  badReason: {
null    quXiao: '取消',
    queDing: '确定',
queDing: "ยืนยัน", 
shanChuChaPingYuan: "ลบประเภทของเหตุผลแบบประเมินที่ไม่ดี", 
caoZuoChengGong: "การดำเนินการสำเร็จ", 
qingShuRu: "กรุณากรอก", 
youYiTiaoJiLu: "มีหนึ่งบันทึกที่กำลังแก้ไข", 
tianJiaChaPingYuan: "เพิ่มประเภทเหตุผลแบบประเมินที่ไม่ดี", 
shanChu: "ลบ", 
baoCun: "บันทึก", 
    caoZuo: '操作',
caoZuo: "การดำเนินการ", 
keHuChaPingYuan: "ประเภทเหตุผลแบบประเมินที่ไม่ดี", 
qingShuRuChaPing: "กรุณากรอกประเภทเหตุผลแบบประเมินที่ไม่ดี", 
    keHuChaPingYuan2: '\n      客户差评原因\n      ',
keHuChaPingYuan2: "เหตุผลสำหรับแบบประเมินที่ไม่ดีจากลูกค้า:", 
  },
  scroreResult: {
keHuChaPingYuan3: "เหตุผลสำหรับแบบประเมินที่ไม่ดีจากลูกค้า:", 
zuiDaZhiBuNeng: "ค่าสูงสุดต้องไม่น้อยกว่าค่าต่ำสุด", 
buJiGe: "ไม่ผ่าน", 
jiGe: "ผ่าน", 
liangHao: "ดี", 
youXiu: "ยอดเยี่ยม", 
zuiZhongPingFenJie: "ผลคะแนนสุดท้าย", 
deFenFanWei: "ช่วงคะแนน", 
pingFenJieGuo: "ผลการให้คะแนน", 
geiZuiZhongFenShu: "กำหนด 4 ระดับสำหรับคะแนนสุดท้าย", 
zuiZhongPingFenJie2: "ผลคะแนนสุดท้าย", 
  },
  AppMain: {
zuiZhongPingFenJie3: "ผลคะแนนสุดท้าย", 
  },
  Navbar: {
    quXiao: '取消',
    queDing: '确定',
    tiShi: '提示',
tiShi: "แจ้งเตือน", 
queDingZhuXiaoBing: "แน่ใจว่าจะล็อกเอาท์และออกจากระบบ?", 
keFuHouTaiGuan: "บริการจัดการระบบหลังบ้านของฝ่ายบริการลูกค้า", 
jinRu: "เข้าสู่", 
huanYingNin: "ยินดีต้อนรับ", 
tuiChuDengLu: "ออกจากระบบ", 
geRenZhongXin: "บัญชีของฉัน", 
buJuSheZhi: "การตั้งค่าเค้าโครง", 

quanPingSuoFang: "ซูมเต็มหน้าจอ", 
    shanChu: '刪除',
    xiaZai: '下載',
xiaZai: "ดาวน์โหลด", 
    zhuangTai: '状态',
    chuangJianRiQi: '创建日期',
    wenJianMing: '文件名',
wenJianMing: "ชื่อไฟล์", 
    xiaZaiLieBiao2: '下載列表'
  },
  scroreTarget: {
    deFenFanWeiBu: '得分范围不能重叠',
deFenFanWeiBu: "ช่วงคะแนนไม่สามารถทับซ้อนกันได้", 
zuiDaZhiBuNeng: "ค่าสูงสุดต้องไม่เกินเกณฑ์การให้คะแนน", 
shanChuPingFenZhi: "ลบตัวดัชนีการให้คะแนน", 
pingFenZhiBiaoLie: "รายการตัวดัชนีการให้คะแนน", 

tianJiaPingFenZhi: "เพิ่มดัชนีการให้คะแนน", 

    buManYi: '不满意',
    yiBan: '一般',
    manYi: '满意',
    feiChangManYi: '非常满意',
feiChangManYi: "พอใจมาก", 
qingShuRuPingFen: "กรุณาใส่ค่าคะแนน", 
pingFenBiaoZhun: "เกณฑ์การให้คะแนน", 
qingShuRuPingFen2: "โปรดกรอกดัชนีการให้คะแนน", 
pingFenZhiBiao: "ดัชนีการให้คะแนน", 
xuHao: "หมายเลขซีเรียล", 
duoGeZhiBiaoDi: "คะแนนเฉลี่ยของตัวดัชนีหลายตัวคือคะแนนสุดท้ายของบทสนทนา", 
pingFenZhiBiao2: "ดัชนีการให้คะแนน", 
  },
  sessionTags: {
pingFenZhiBiao3: "ดัชนีการให้คะแนน", 
shanChuBiaoQian: "ลบแท็ก", 
xinZengChengGong: "เพิ่มเรียบร้อยแล้ว!", 
qingQianWangCanShu: "โปรดไปที่การกำหนดค่าพารามิเตอร์และกำหนดค่า chatField", 
tianJiaPingJiaBiao: "เพิ่มคลังแท็กแบบประเมิน", 
zanWuShuJu: "ไม่มีข้อมูลในขณะนี้", 
tianJia: "เพิ่ม", 
qingShuRuZhiJian: "โปรดป้อนชื่อแท็กตรวสอบคุณภาพ อักษรจีนไม่เกิน 8 ตัว", 
  },
  Editor: {
zhiJianBiaoQian: "แท็กตรวสอบคุณภาพ", 
tuPianShangChuanShi: "กรุณาอัพโหลดภาพเพื่อใช้", 
  },
  MarkDown: {
fuWenBenJiYu: "ขึ้นอยู่กับ Rich Text", 
  },
  YamlEdit: {
    zhanShiShuJuRu:
      '# 展示数据，如需更换主题，请在src/components/YamlEdit 目录中搜索原主题名称进行替换\n',
mARKD: "ขึ้นอยู่กับ Markdown", 
zhuTiYuLanDi: "ที่อยู่ดูตัวอย่างธีม", 
zhuTiYuLanDi2: "ที่อยู่ดูตัวอย่างธีม", 
yAMLBian: "โปรแกรมแก้ไข Yaml ขึ้นอยู่กับ", 
yAMLBian2: "โปรแกรมแก้ไข Yaml ขึ้นอยู่กับ", 
  }
}
