export default {
  badReason: {
    shanChuChengGong: "ลบสำเร็จ", 
    quXiao: "ยกเลิก", 
    queDing: "ยืนยัน", 
    shanChuChaPingYuan: "ลบประเภทของเหตุผลแบบประเมินที่ไม่ดี", 
    caoZuoChengGong: "การดำเนินการสำเร็จ", 
    qingShuRu: "กรุณากรอก", 
    youYiTiaoJiLu: "มีหนึ่งบันทึกที่กำลังแก้ไข", 
    tianJiaChaPingYuan: "เพิ่มประเภทเหตุผลแบบประเมินที่ไม่ดี", 
    shanChu: "ลบ", 
    baoCun: "บันทึก", 
    bianJi: "แก้ไข", 
    caoZuo: "การดำเนินการ", 
    keHuChaPingYuan: "หมายเหตุแบบประเมินที่ไม่ดีจากลูกค้า", 
    qingShuRuChaPing: "กรุณากรอกประเภทเหตุผลแบบประเมินที่ไม่ดี", 
    feiWuXingDuSuan: "ที่ไม่ใช่ห้าดาวถือเป็นแบบประเมินที่ไม่ดี", 
    keHuChaPingYuan2: "เหตุผลสำหรับแบบประเมินที่ไม่ดีจากลูกค้า:", 
    keHuChaPingYuan3: "เหตุผลสำหรับแบบประเมินที่ไม่ดีจากลูกค้า:", 
  },
  scroreResult: {
    zuiDaZhiBuNeng: "ค่าสูงสุดต้องไม่น้อยกว่าค่าต่ำสุด", 
    buJiGe: "ไม่ผ่าน", 
    jiGe: "ผ่าน", 
    liangHao: "ดี", 
    youXiu: "ยอดเยี่ยม", 
    zuiZhongPingFenJie: "ผลคะแนนสุดท้าย", 
    deFenFanWei: "ช่วงคะแนน", 
    pingFenJieGuo: "ผลการให้คะแนน", 
    geiZuiZhongFenShu: "กำหนด 4 ระดับสำหรับคะแนนสุดท้าย", 
    zuiZhongPingFenJie2: "ผลคะแนนสุดท้าย", 
    zuiZhongPingFenJie3: "ผลคะแนนสุดท้าย", 
  },
  AppMain: {
        quXiao: '取消',
  },
  Navbar: {
    quXiao: "ยกเลิก", 
    queDing: "ยืนยัน", 
    tiShi: "แจ้งเตือน", 
    queDingZhuXiaoBing: "แน่ใจว่าจะล็อกเอาท์และออกจากระบบ?", 
    keFuHouTaiGuan: "บริการจัดการระบบหลังบ้านของฝ่ายบริการลูกค้า", 
    jinRu: "เข้าสู่", 
    huanYingNin: "ยินดีต้อนรับ", 
    tuiChuDengLu: "ออกจากระบบ", 
    geRenZhongXin: "บัญชีของฉัน", 
    buJuSheZhi: "การตั้งค่าเค้าโครง", 
    quanPingSuoFang: "ซูมเต็มหน้าจอ", 

        shanChu: '刪除',
    shanChu: "ลบ", 
    xiaZai: "ดาวน์โหลด", 
    caoZuo: "การดำเนินการ", 
    zhuangTai: "สถานะ", 
    chuangJianRiQi: "วันที่สร้าง", 
    wenJianMing: "ชื่อไฟล์", 
        xiaZaiLieBiao2: '下載列表'
        deFenFanWeiBu: '得分范围不能重叠',
  },
  scroreTarget: {
    deFenFanWeiBu: "ช่วงคะแนนไม่สามารถทับซ้อนกันได้", 
    zuiDaZhiBuNeng: "ค่าสูงสุดต้องไม่น้อยกว่าค่าต่ำสุด", 
    shanChuPingFenZhi: "ลบตัวดัชนีการให้คะแนน", 
    pingFenZhiBiaoLie: "รายการตัวดัชนีการให้คะแนน", 
    tianJiaPingFenZhi: "เพิ่มดัชนีการให้คะแนน", 

        buManYi: '不满意',

    buManYi: "ไม่พอใจ", 
    yiBan: "ทั่วไป", 
    manYi: "พอใจ", 
    feiChangManYi: "พอใจมาก", 
    qingShuRuPingFen: "กรุณาใส่ค่าคะแนน", 
    pingFenBiaoZhun: "เกณฑ์การให้คะแนน", 
    qingShuRuPingFen2: "โปรดกรอกดัชนีการให้คะแนน", 
    pingFenZhiBiao: "ดัชนีการให้คะแนน", 
    xuHao: "หมายเลขซีเรียล", 
    duoGeZhiBiaoDi: "คะแนนเฉลี่ยของตัวดัชนีหลายตัวคือคะแนนสุดท้ายของบทสนทนา", 
    pingFenZhiBiao2: "ดัชนีการให้คะแนน", 
    pingFenZhiBiao3: "ดัชนีการให้คะแนน", 
  },
  sessionTags: {
    shanChuBiaoQian: "ลบแท็ก", 
    xinZengChengGong: "เพิ่มเรียบร้อยแล้ว!", 
    qingQianWangCanShu: "โปรดไปที่การกำหนดค่าพารามิเตอร์และกำหนดค่า chatField", 
    tianJiaPingJiaBiao: "เพิ่มคลังแท็กแบบประเมิน", 
    zanWuShuJu: "ไม่มีข้อมูลในขณะนี้", 
    tianJia: "เพิ่ม", 
    qingShuRuZhiJian: "โปรดกรอกผู้ตรวจสอบคุณภาพ", 
    zhiJianBiaoQian: "แท็กการตรวจสอบคุณภาพ", 
  },
  Editor: {
    tuPianShangChuanShi: "กรุณาอัพโหลดภาพเพื่อใช้", 
    fuWenBenJiYu: "ขึ้นอยู่กับ Rich Text", 
  },
  MarkDown: {
    mARKD: "ขึ้นอยู่กับ Markdown", 
  },
  YamlEdit: {
    zhanShiShuJuRu:
      '# 展示数据，如需更换主题，请在src/components/YamlEdit 目录中搜索原主题名称进行替换\n',
    zhuTiYuLanDi: "ที่อยู่ดูตัวอย่างธีม", 
    zhuTiYuLanDi2: "ที่อยู่ดูตัวอย่างธีม", 
    yAMLBian: "โปรแกรมแก้ไข Yaml ขึ้นอยู่กับ", 
    yAMLBian2: "โปรแกรมแก้ไข Yaml ขึ้นอยู่กับ", 
  }
}
