export default {
  CRUD: {
    qingZhiShaoXuanZe: "โปรดเลือกอย่างน้อยหนึ่งรายการ", 
        queDing: '确定',
        tiShi: '提示',
        queRenShanChuXuan: '确认删除选中的{val1}条数据?',
    queRenShanChuXuan: "ยืนยันการลบข้อมูล {val1} ที่เลือกไหม", 
    miMaBuNengWei: "รหัสผ่าน (ห้ามเว้นว่าง)", 
    queRen: "ยืนยัน", 
    queDingShanChuBen: "คุณแน่ใจหรือไม่ที่จะลบข้อมูลนี้", 
    qingShuRuMiMa: "กรุณาใส่รหัสผ่านของคุณ", 
    yongHuMiMa: "รหัสผ่านผู้ใช้", 
    yongHuMing: "ชื่อผู้ใช้", 
    shanChuPeiZhi: "ลบการกำหนดค่า", 
        daoChuBaoBiao: '导出报表',
    daoChuBaoBiao: "รายงานการส่งออก", 
        xiuGai: '\n        修改\n      ',
        tianJia: '\n        添加',
        shuaXin: '刷新',
  },
  RR: {
    shuaXin: "รีเฟรช", 
    zhongZhi: "รีเซ็ต", 
    chaXun: "ตรวจสอบ", 
  },
  UD: {
        bianJi: '\n      编辑\n    ',
        shuJu: '数据',
  },
  crud: {
    shuJu: "ข้อมูล", 
    tianJia: "เพิ่ม", 
    shanChuChengGong: "ลบสำเร็จ", 
    bianJiChengGong: "แก้ไขสำเร็จ!", 
        tiJiaoChengGong: '提交成功',
    tiJiaoChengGong: "ส่งสำเร็จ", 
        xinZengCRU: '新增{val1}',
        xinZengCRU: '新增{val1}',
  },
};
