export default {
  CRUD: {
    qingZhiShaoXuanZe: '请至少选择一列',
    quXiao: '取消',
    queDing: '确定',
    tiShi: '提示',
    queRenShanChuXuan: '确认删除选中的{val1}条数据?',
    miMaBuNengWei: '密码不能为空',
    queRen: '确认',
    queDingShanChuBen: '确定删除本条数据吗？',
    qingShuRuMiMa: '请输入密码',
    yongHuMiMa: '用户密码',
    yongHuMing: '用户名',
    shanChuPeiZhi: '删除配置',
    quanXuan: '\n          全选\n        ',
    daoChuBaoBiao: '导出报表',
    piLiangShanChu: '\n        批量删除\n      ',
    xiuGai: '\n        修改\n      ',
    tianJia: '\n        添加',
  },
  RR: {
    shuaXin: '刷新',
    zhongZhi: '重置',
    chaXun: '查询',
  },
  UD: {
    shanChu: '\n        删除\n      ',
    bianJi: '\n      编辑\n    ',
  },
  crud: {
    shuJu: '数据',
    tianJia: '添加',
    shanChuChengGong: '删除成功',
    bianJiChengGong: '编辑成功',
    xinZengChengGong: '新增成功',
    tiJiaoChengGong: '提交成功',
    bianJiCRU: '编辑{val1}',
    xinZengCRU: '新增{val1}',

  },
};
