export default {
  CRUD: {
    qingZhiShaoXuanZe: "โปรดเลือกอย่างน้อยหนึ่งรายการ", 
    quXiao: "ยกเลิก", 
    queDing: "ยืนยัน", 
    tiShi: "แจ้งเตือน", 
    queRenShanChuXuan: "ยืนยันการลบข้อมูล {val1} ที่เลือกไหม", 
    miMaBuNengWei: "รหัสผ่าน (ห้ามเว้นว่าง)", 
    queRen: "ยืนยัน", 
    queDingShanChuBen: "คุณแน่ใจหรือไม่ที่จะลบข้อมูลนี้", 
    qingShuRuMiMa: "กรุณาใส่รหัสผ่านของคุณ", 
    yongHuMiMa: "รหัสผ่านผู้ใช้", 
    yongHuMing: "ชื่อผู้ใช้", 
    shanChuPeiZhi: "ลบการกำหนดค่า", 
    quanXuan: "เลือกทั้งหมด", 
    daoChuBaoBiao: "รายงานการส่งออก", 
    piLiangShanChu: "การลบแบทช์", 
    xiuGai: "แก้ไข", 
    tianJia: "เพิ่ม", 
  },
  RR: {
    shuaXin: "รีเฟรช", 
    zhongZhi: "รีเซ็ต", 
    chaXun: "ตรวจสอบ", 
  },
  UD: {
    shanChu: "ลบ", 
    bianJi: "แก้ไข", 
  },
  crud: {
    shuJu: "ข้อมูล", 
    tianJia: "เพิ่ม", 
    shanChuChengGong: "ลบสำเร็จ", 
    bianJiChengGong: "แก้ไขสำเร็จ!", 
    xinZengChengGong: "เพิ่มเรียบร้อยแล้ว!", 
    tiJiaoChengGong: "ส่งสำเร็จ", 
    bianJiCRU: "แก้ไข {val1}", 
    xinZengCRU: "เพิ่ม {val1}", 
  },
};
