export default {
  autoAcceptCustomerType: {
    shanChuChengGong: '删除成功',
    quXiao: '取消',
    queDing: '确定',
queDing: "ยืนยัน", 
    shiFouShanChu: '是否删除',
shiFouShanChu: "ลบหรือไม่", 
    yaoQingJieDaiLie: '邀请接待列表',
yaoQingJieDaiLie: "รายการรับเชิญ", 
    caoZuo: '操作',
    zuiHouXiuGaiRen: '最后修改人',
zuiHouXiuGaiRen: "แก้ไขล่าสุดโดย", 
zuiHouXiuGaiRi: "วันที่แก้ไขล่าสุด", 
    keHuLeiXing: '客户类型',
    keFuLeiXing: '客服类型',
    tianJia: '添加',
    suoYouKeHuLei: '所有客户类型',
suoYouKeHuLei: "ประเภทลูกค้าทั้งหมด", 
  },
  receptSet: {
suoYouKeFuLei: "ประเภทการบริการลูกค้าทั้งหมด", 
qingNinQueRen: "คุณช่วยยืนยัน？", 
shanChuHouSE: "หลังจากลบ {val1} แล้ว คุณจะไม่สามารถรับ {val2} ได้", 
keJieDaiKeHu: "คลิกเลือกลูกค้าที่สามารถรับได้ ไม่สามารถเพิ่มได้！", 
keHuJieDaiLie: "รายการรับลูกค้า", 
    keHuZuMing: '客户组名',
keHuZuMing: "ชื่อกลุ่มลูกค้า", 
keFuZuMing: "ชื่อกลุ่มบริการลูกค้า", 
keJieDaiDeKe: "ลูกค้าที่มีอยู่", 
    keHuJieDaiPei: '客户接待配置',
keHuJieDaiPei: "การกำหนดค่าการรับลูกค้า", 
    quanBuKeFuZu: '全部客服组',
    ziDongJieDaiKe: '自动接待客户组',
    ziDongJieDaiKe2: '自动接待客户类型',
ziDongJieDaiKe2: "การรับประเภทลูกค้าโดยอัตโนมัติ", 
  },
};
