export default {
  index: {
    tiShi: '提示',
    queDingYaoZhiXing: "确定要执行'{val1}'该操作?",
queDingYaoZhiXing: "แน่ใจไหมว่าต้องการดำเนินการ {val1} นี้", 
buChuLi: "ไม่ดำเนินการ", 
yiHuiFang: "ตอบกลับ", 
    zhaKanLiuYan: '查看留言',
zhaKanLiuYan: "ดูข้อความ", 
weiShouLi: "ไม่ผ่านการประมวลผล", 
chuLiRen: "คนดำเนินการ", 
chuLiJieGuo: "ผลดำเนินการ", 
liuYanRiQi: "วันที่ข้อความ", 
    liuYanTuPian: '留言图片',
    liuYanNeiRong: '留言内容',
    lianxufangshi: '联系方式',

    weiXin: '微信',
    shouJi: '手机',
shouJi: "โทรศัพท์มือถือ", 
    nan: '男',
    xingMingXingBie: '姓名/性别',
xingMingXingBie: "ชื่อ/เพศ", 
    keHuDengJiV: '客户等级/VIP级别',
    keHuZhangHuNi: '客户账户/昵称',
    quanBuKeFu: '全部客服',
    suoYouKeFu: '所有客服',
    qingShuRuKeHu: '请输入客户账户',
    quanXuanJiNengZu: '全选技能组',
    quanBuJiNengZu: '全部技能组',
    quanBuKeHuV: '全部客户VIP级别',
quanBuKeHuV: "ระดับวีไอพีของลูกค้าทั้งหมด", 
  },
  lookPicture: {
quanBuKeHuDeng: "ลูกค้าทุกระดับ", 
  },
  passwordvalite: {
    qingShuRuMiMa: '请输入密码',
    qingShuRuNinDe: '请输入您的登录密码',
    dengLuMiMa: '登录密码',
    dengLuYongHuMing: '登录用户名',
    zhaKanXiangQingMi: '查看详情密码验证'
zhaKanXiangQingMi: "ตรวจดูรายละเอียดการยืนยันรหัสผ่าน", 
  }
}
