export default {
  index: {
    tiShi: '提示',
tiShi: "แจ้งเตือน", 
queDingYaoZhiXing: "แน่ใจไหมว่าต้องการดำเนินการ {val1} นี้", 
buChuLi: "ไม่ดำเนินการ", 
yiHuiFang: "ตอบกลับ", 
haoDe: "ตกลง", 
zhaKanLiuYan: "ดูข้อความ", 
weiShouLi: "ไม่ผ่านการประมวลผล", 
chuLiRen: "คนดำเนินการ", 
chuLiJieGuo: "ผลดำเนินการ", 
liuYanRiQi: "วันที่ข้อความ", 
zhaKan: "ตรวจดู", 
liuYanTuPian: "รูปภาพข้อความ", 
    lianxufangshi: '联系方式',

    weiXin: '微信',
weiXin: "วีแชท", 
shouJi: "โทรศัพท์มือถือ", 
    nan: '男',
nan: "ผู้ชาย", 
xingMingXingBie: "ชื่อ/เพศ", 
ziXunWenTi: "ปรึกษาปัญหา", 
keHuDengJiV: "ระดับลูกค้า/ระดับวีไอพี", 
keHuZhangHuNi: "บัญชีลูกค้า/ชื่อเล่น", 
quanBuKeFu: "ฝ่ายบริการลูกค้าทั้งหมด", 
suoYouKeFu: "ฝ่ายบริการลูกค้าทั้งหมด", 
    quanXuanJiNengZu: '全选技能组',
    quanBuJiNengZu: '全部技能组',
quanBuJiNengZu: "กลุ่มทักษะทั้งหมด", 
quanBuKeHuV: "ระดับวีไอพีของลูกค้าทั้งหมด", 
  },
  lookPicture: {
quanBuKeHuDeng: "ลูกค้าทุกระดับ", 
  },
  passwordvalite: {
jiaZaiZhong: "กำลังโหลด", 
qingShuRuMiMa: "กรุณากรอกรหัสผ่านของคุณ", 
    dengLuMiMa: '登录密码',
    dengLuYongHuMing: '登录用户名',
dengLuYongHuMing: "เข้าสู่ระบบด้วยชื่อผู้ใช้", 
zhaKanXiangQingMi: "ตรวจดูรายละเอียดการยืนยันรหัสผ่าน", 
  }
}
