export default {
  autoAcceptCustomerType: {
        quXiao: '取消',
        queDing: '确定',
    queDing: "ยืนยัน", 
    sERGR: "การกำหนดค่าสำหรับ [{val1}] เพื่อรับ [{val2}] โดยอัตโนมัติหรือไม่", 
    shiFouShanChu: "ลบหรือไม่", 
    queRenShanChu: "ยืนยันการลบ", 
    yaoQingJieDaiLie: "รายการรับเชิญ", 
    shanChu: "ลบ", 
    caoZuo: "การดำเนินการ", 
    zuiHouXiuGaiRen: "แก้ไขล่าสุดโดย", 
    zuiHouXiuGaiRi: "วันที่แก้ไขล่าสุด", 
    tuiGuangShangZongDai: "ไอดี ตัวแทนหัวหน้าผู้สนับสนุน", 
    keHuLeiXing: "ประเภทลูกค้า", 
    keFuLeiXing: "ประเภทการบริการลูกค้า", 
    tianJia: "เพิ่ม", 
    suoYouKeHuLei: "ประเภทลูกค้าทั้งหมด", 
  },
  receptSet: {
    suoYouKeFuLei: "ประเภทการบริการลูกค้าทั้งหมด", 
    qingNinQueRen: "คุณช่วยยืนยัน？", 
    shanChuHouSE: "หลังจากลบ {val1} แล้ว คุณจะไม่สามารถรับ {val2} ได้", 
    keJieDaiKeHu: "คลิกเลือกลูกค้าที่สามารถรับได้ ไม่สามารถเพิ่มได้！", 
    keHuJieDaiLie: "รายการรับลูกค้า", 
    chuangJianRiQi: "วันที่สร้าง", 
    keHuZuMing: "ชื่อกลุ่มลูกค้า", 
    keFuZuMing: "ชื่อกลุ่มบริการลูกค้า", 
    keJieDaiDeKe: "ลูกค้าที่มีอยู่", 
    qingXuanZeKeFu: "กรุณาเลือกกลุ่มบริการลูกค้า", 
    keHuJieDaiPei: "การกำหนดค่าการรับลูกค้า", 
    quanBuKeHuZu: "ทุกกลุ่มลูกค้า", 
    quanBuKeFuZu: "ทุกกลุ่มบริการลูกค้า", 
    ziDongJieDaiKe: "การรับกลุ่มลูกค้าโดยอัตโนมัติ", 
    ziDongJieDaiKe2: "การรับประเภทลูกค้าโดยอัตโนมัติ", 
  },
};
