export default {
  index: {
laHeiROW: "บล็อก {val1}", 
laHeiROW: "บล็อก {val1}", 
shanChuYongHuR: "ยืนยันการลบผู้ใช้ {val1}", 
queDingShanChuR: "ต้องการลบโปรไฟล์ผู้ใช้ {val1} หรือไม่ จะไม่สามารถกู้คืนได้หลังจากการลบ", 
queDingJiangGaiYong: "แน่ใจว่าจะปลดบล็อกผู้ใช้รายนี้ {val1}?", 
laHeiChengGong: "บล็อกเรียบร้อย!", 
shanChuChengGong: "ลบเรียบร้อย!", 
keHuZhangHu: "บัญชีลูกค้า", 
    qingShuRuLaHei: '请输入拉黑原因',
qingShuRuLaHei: "โปรดกรอกเหตุผลในการบล็อก", 
qingXuanZe: "โปรดเลือก", 
keHuLieBiao: "รายชื่อลูกค้า", 
queRen: "ยืนยัน", 
biTian: "จำเป็นต้องกรอก...", 
laHeiYuanYin: "เหตุผลการบล็อก", 
laHeiLeiXing: "ประเภทของการบล็อก", 
laHeiYongHu: "ผู้ใช้บัญชีที่ถูกบล็อก", 
laHei: "บล็อก", 
shiFouLaHei: "ต้องการบล็อกหรือไม่", 
liShiZiXunShu: "จำนวนการตรวจสอบประวัติ", 
    chaXun: '查询',

  },
};
