export default {
  execute: {
    zhiXingChengGong: '执行成功',
    guanBi: '关闭',
    shangChuanHouXiTong: '上传后，系统会自动执行SQL脚本',
    dianJiShangChuan: '点击上传',
    jiangWenJianTuoDao: '\n          将文件拖到此处，或\n          ',
    zhiXingJiaoBen: '执行脚本',
  },
  index: {
    lianJieShiBai: '连接失败',
    lianJieChengGong: '连接成功',
    qingShuRuShuJu: '请输入数据库密码',
    qingShuRuYongHu: '请输入用户名',
    qingShuRuShuJu2: '请输入数据库连接地址',
    qingShuRuShuJu3: '请输入数据库名称',
    shuJuKu: '数据库',
    yongHuMing: '用户名',
    lianJieDiZhi: '连接地址',
    shuJuKuMingCheng: '数据库名称',
    miMa: '密码',
    yongHu: '用户',
    ceShi: '测试',
    jDBCDi: 'JDBC地址',
    lianJieMingCheng: '连接名称',
    zhiXingJiaoBen: '执行脚本\n        ',
    moHuSouSuo: '模糊搜索',

  },
};
