export default {
  execute: {
nullzhiXingChengGong: "การดำเนินการสำเร็จ", 
guanBi: "ปิดทิ้ง", 
shangChuanHouXiTong: "หลังจากอัปโหลด ระบบจะเรียกใช้สคริปต์ SQL โดยอัตโนมัติ", 
dianJiShangChuan: "คลิกอัปโหลด", 
jiangWenJianTuoDao: "ลากและวางไฟล์ที่นี่ หรือ", 
  },
  index: {
zhiXingJiaoBen: "สคริปต์การดำเนินการ", 
lianJieShiBai: "การเชื่อมต่อล้มเหลว", 
lianJieChengGong: "การเชื่อมต่อสำเร็จ", 
qingShuRuShuJu: "กรุณากรอกรหัสผ่านของฐานข้อมูล", 
qingShuRuYongHu: "กรุณากรอกชื่อผู้ใช้ของคุณ", 
qingShuRuShuJu2: "โปรดกรอกที่อยู่การเชื่อมต่อฐานข้อมูล", 
qingShuRuShuJu3: "กรุณากรอกชื่อฐานข้อมูล", 
shuJuKu: "ฐานข้อมูล", 
yongHuMing: "ชื่อผู้ใช้", 
lianJieDiZhi: "ที่อยู่การเชื่อมต่อ", 
shuJuKuMingCheng: "ชื่อฐานข้อมูล", 
miMa: "รหัสผ่าน", 
yongHu: "ผู้ใช้", 
ceShi: "ทดสอบ", 
jDBCDi: "ที่อยู่ JDBC", 
lianJieMingCheng: "ชื่อการเชื่อมต่อ", 
zhiXingJiaoBen: "สคริปต์การดำเนินการ", 
    moHuSouSuo: '模糊搜索',
  },
};
