export default {
  execute: {
    zhiXingChengGong: '执行成功',
    guanBi: '关闭',
    shangChuanHouXiTong: '上传后，系统会自动执行SQL脚本',
shangChuanHouXiTong: "หลังจากอัปโหลด ระบบจะเรียกใช้สคริปต์ SQL โดยอัตโนมัติ", 
    jiangWenJianTuoDao: '\n          将文件拖到此处，或\n          ',
    zhiXingJiaoBen: '执行脚本',
  },
  index: {
    lianJieShiBai: '连接失败',
lianJieShiBai: "การเชื่อมต่อล้มเหลว", 
lianJieChengGong: "การเชื่อมต่อสำเร็จ", 
qingShuRuShuJu: "กรุณากรอกรหัสผ่านของฐานข้อมูล", 
    qingShuRuShuJu2: '请输入数据库连接地址',
qingShuRuShuJu2: "โปรดกรอกที่อยู่การเชื่อมต่อฐานข้อมูล", 
qingShuRuShuJu3: "กรุณากรอกชื่อฐานข้อมูล", 
shuJuKu: "ฐานข้อมูล", 
    lianJieDiZhi: '连接地址',
lianJieDiZhi: "ที่อยู่การเชื่อมต่อ", 
shuJuKuMingCheng: "ชื่อฐานข้อมูล", 
    yongHu: '用户',
    ceShi: '测试',
ceShi: "ทดสอบ", 
jDBCDi: "ที่อยู่ JDBC", 
lianJieMingCheng: "ชื่อการเชื่อมต่อ", 
    moHuSouSuo: '模糊搜索',

  },
};
