export default {
wEBSO: "เกิดข้อผิดพลาดในการเชื่อมต่อ WebSocket", 
wEBSO: "เกิดข้อผิดพลาดในการเชื่อมต่อ WebSocket", 
  tianJiaChengGong: '添加成功',
  duoGeYingYongShang:
    '多个应用上传文件名称为all.zip,数据库更新脚本扩展名为.sql,上传成功后系统自动部署系统。',
  yingYongBuShu: '应用部署',
  index: {
yingYongBuShu: "การปรับใช้แอปพลิเคชัน", 
fuWuQiBuNeng: "เซิร์ฟเวอร์ (ห้ามเว้นว่าง)", 
yingYongBuNengWei: "แอปพลิเคชัน (ห้ามเว้นว่าง)", 
buShu: "การปรับใช้", 
buShuRiQi: "วันที่ปรับใช้", 
fuWuQiLieBiao: "รายการเซิร์ฟเวอร์", 
    fuWuQi: '服务器',
fuWuQi: "เซิร์ฟเวอร์", 
yiJianBuShu: "ปรับใช้คลิกเดียว", 
yiJianBuShu2: "ปรับใช้คลิกเดียว", 
tingZhi: "หยุด", 
tingZhi2: "หยุด", 
qiDong: "เริ่ม", 
qiDong2: "เริ่ม", 
zhuangTaiChaXun: "ตรวจสอบสถานะ", 
zhuangTaiChaXun2: "ตรวจสอบสถานะ", 
xiTongHuanYuan: "ระบบการเรียกคืน", 
xiTongHuanYuan2: "ระบบการเรียกคืน", 
  },
  sysRestore: {
    qingXuanZeYaoHai: '请选择要还原的备份',
qingXuanZeYaoHai: "โปรดเลือกข้อมูลสำรองที่จะกู้คืน", 
buShuRenYuan: "ปรับใช้โดย", 
buShuShiJian: "เวลาปรับใช้", 
buShuIP: "IP การปรับใช้", 

  },
};
