export default {
  index: {
    vipDengji: 'VIP等级',
    chengGong: '成功',
    quXiao: '取消',
    queDing: '确定',
    tiShi: '提示',
tiShi: "แจ้งเตือน", 
buMenShiFouJi: "แผนก คุณต้องการดำเนินการต่อหรือไม่?", 
    shangJiBuMenBu: '上级部门不能为空',
shangJiBuMenBu: "หัวหน้าแผนก ห้ามเว้นว่าง", 
    zhengChang: '正常',
zhengChang: "ปกติ", 
    buMen: '部门',
buMen: "แผนก", 
queDingShanChuMa: "คุณแน่ใจหรือไม่ที่จะลบ หากมีโหนดรอง ให้ลบพร้อมกัน การดำเนินการนี้ไม่สามารถยกเลิกได้!", 
    chuangJianRiQi: '创建日期',
chuangJianRiQi: "วันที่สร้าง", 
    feiKeFu: '非客服',
feiKeFu: "บริการที่ไม่ใช่ลูกค้า", 
    buMenLeiXing: '部门类型',
buMenLeiXing: "ประเภทแผนก", 
    queRen: '确认',
    xuanZeShangJiLei: '选择上级类目',
xuanZeShangJiLei: "เลือกหมวดหมู่หลัก", 
zanWuPiPeiShu: "ไม่มีข้อมูลที่ตรงกัน", 
shangJiBuMen: "หัวหน้าแผนก", 
    quanBu: '全部',
    shuRuBuMenMing: '输入部门名称搜索'
shuRuBuMenMing: "ใส่ชื่อแผนกที่ต้องการค้นหา", 
  }
}
