export default {
  index: {
        chengGong: '成功',
    chengGong: "สำเร็จ", 
    quXiao: "ยกเลิก", 
    queDing: "ยืนยัน", 
    tiShi: "แจ้งเตือน", 
    buMenShiFouJi: "แผนก คุณต้องการดำเนินการต่อหรือไม่?", 
    ciCaoZuoJiang: "การดำเนินการนี้จะ", 
    shangJiBuMenBu: "หัวหน้าแผนก ห้ามเว้นว่าง", 
    jinYong: "ปิดการใช้งาน", 
    zhengChang: "ปกติ", 
    qingShuRuMingCheng: "กรุณากรอกชื่อ", 
    buMen: "แผนก", 
    queDingShanChuMa: "คุณแน่ใจหรือไม่ที่จะลบ หากมีโหนดรอง ให้ลบพร้อมกัน การดำเนินการนี้ไม่สามารถยกเลิกได้!", 
    caoZuo: "การดำเนินการ", 
    chuangJianRiQi: "วันที่สร้าง", 
    zhuangTai: "สถานะ", 
    feiKeFu: "บริการที่ไม่ใช่ลูกค้า", 
    keFu: "/บริการลูกค้า:", 
    buMenLeiXing: "ประเภทแผนก", 
    mingCheng: "ชื่อ", 
    queRen: "ยืนยัน", 
    xuanZeShangJiLei: "เลือกหมวดหมู่หลัก", 
    zanWuPiPeiShu: "ไม่มีข้อมูลที่ตรงกัน", 
    shangJiBuMen: "หัวหน้าแผนก", 
    zhongZhi: "รีเซ็ต", 
    quanBu: "ทั้งหมด", 
    shuRuBuMenMing: "ใส่ชื่อแผนกที่ต้องการค้นหา", 
  }
}
