export default {
  index: {
        tiShi: '提示',
    tiShi: "แจ้งเตือน", 
    gangWeiShiFouJi: "ตำแหน่ง คุณต้องการดำเนินการต่อหรือไม่?", 
    ciCaoZuoJiang: "การดำเนินการนี้จะ", 
    yuMing: "ชื่อโดเมน", 
    xiuGaiRiQi: "แก้ไขวันที่", 
    xiuGaiRen: "แก้ไขโดย", 
    chuangJianRiQi: "วันที่สร้าง", 
    chuangJianRen: "สร้างโดย", 
    yuMingLeiXing: "ประเภทโดเมน", 
    yuMingFuWu: "บริการชื่อโดเมน", 
    yuMingDiZhi: "ที่อยู่โดเมน", 
    yingYongMingCheng: "ชื่อ แอปพลิเคชัน", 
    yingYongID: "ไอดี แอปพลิเคชัน", 
    chanPinMingCheng: "ชื่อสินค้า", 
        chanPinID: '产品ID',
  },
};
