export default {
  config: {
sMTPDuan: "พอร์ต SMTP (ห้ามเว้นว่าง)", 
sMTPDuan: "พอร์ต SMTP (ห้ามเว้นว่าง)", 
sMTPDi: "ที่อยู่ SMTP (ห้ามเว้นว่าง)", 
miMaBuNengWei: "รหัสผ่าน (ห้ามเว้นว่าง)", 
qingShuRuFaJian: "กรุณากรอกชื่อผู้ส่ง", 
qingShuRuZhengQue: "กรุณาใส่ที่อยู่อีเมลที่ถูกต้อง", 
qingShuRuFaJian2: "กรุณากรอกที่อยู่อีเมลของผู้ส่ง", 
sMTPDuan2: "พอร์ต SMTP", 
sMTPDi2: "ที่อยู่ SMTP", 
youXiangMiMa: "รหัสผ่านอีเมล", 
faJianYongHuMing: "ชื่อผู้ส่ง", 
  },
  index: {
faJianRenYouXiang: "อีเมลของผู้ส่ง", 
hUTOO: "ชุดเครื่องมือ hutool", 
gengDuoBangZhuQing: "สำหรับความช่วยเหลือเพิ่มเติม โปรดตรวจสอบเอกสารประกอบที่", 
    youJianFuWuQi:
      ' # 邮件服务器的SMTP地址，可选，默认为smtp\n # 邮件服务器的SMTP端口，可选，默认465或者25\n # 发件人（必须正确，否则发送失败）\n # 用户名，默认为发件人邮箱前缀\n # 密码（注意，某些邮箱需要为SMTP服务单独设置密码，如QQ和163等等）\n # 是否开启ssl，默认开启',
gengDuoBangZhu: "ความช่วยเหลือเพิ่มเติม", 
youJianFuWuQi2: "การกำหนดค่าเซิร์ฟเวอร์อีเมล", 
faSongYouJian: "ส่งอีเมล", 
  },
  send: {
youXiangPeiZhi: "การกำหนดค่าอีเมล", 
faSongChengGong: "ส่งเรียบร้อย", 
shouJianYouXiangGe: "รูปแบบอีเมลผู้รับไม่ถูกต้อง", 
shouJianYouXiangBu: "อีเมลผู้รับ (ห้ามเว้นว่าง)", 
qingZhiShaoBaoLiu: "โปรดเหลือผู้ติดต่ออย่างน้อยหนึ่งคน", 
biaoTiBuNengWei: "หัวข้อเรื่อง (ห้ามเว้นว่าง)", 
shouJianYouXiang: "อีเมลผู้รับ", 
youJianBiaoTi: "หัวข้ออีเมล", 
  },
};
