export default {
  index: {
zanWuZaiXianKe: "ไม่มีบริการลูกค้าออนไลน์ในขณะนี้!", 
zanWuZaiXianKe: "ไม่มีบริการลูกค้าออนไลน์ในขณะนี้!", 
zanWuZaiXianKe2: "ไม่มีบริการลูกค้าออนไลน์ในขณะนี้!", 
    weiPaiDui: '未排队',
    ziXunShu: '咨询数',
ziXunShu: "จำนวนสอบถาม", 
    jiNengZu: '技能组',
    chaPingLu: '差评率%',
chaPingLu: "แบบประเมินที่ไม่ดี %", 
chaPingShuLu: "จำนวน/อัตราแบบประเมินที่ไม่ดี % (1-2)", 
zhongPingLu: "อัตราแบบประเมินปานกลาง %", 
zhongPingShuLu: "จำนวน/อัตราแบบประเมินปานกลาง (3-4)", 
haoPingLu: "แบบประเมินดี %", 
haoPingShuLuFen: "จำนวน/อัตราแบบประเมินที่ดี (5)", 
pingJiaJieJueLu: "อัตราความละเอียดในการประเมิน %", 
pingJiaJieJueShu: "จำนวน/อัตราความละเอียดในการประเมิน", 
pingJunKeHuPing: "คะแนนเฉลี่ยแบบประเมินของลูกค้า", 
keHuZhuDongPing: "อัตราการประเมินโดยลูกค้าเอง %", 
keHuZhuDongPing2: "จำนวน/อัตราของการประเมินโดยลูกค้าเอง", 
keFuYaoQingPing: "อัตราคำเชิญประเมินการบริการ %", 
keFuYaoQingPing2: "จำนวน/อัตราคำเชิญประเมินการบริการ", 
    keHuPingJiaShu: '客户评价数/率',
keHuPingJiaShu: "จำนวน/อัตราการประเมินของลูกค้า", 
    yaoQingPingJia: '邀请评价',
yaoQingPingJia: "คำเชิญประเมิน", 
    yiJieJue: '已解决',
yiJieJue: "แก้ไขแล้ว", 
    weiPingJia: '未评价',
weiPingJia: "ยังไม่ได้ประเมิน", 
    xing2: '4星',
    xing3: '3星',
    xing4: '2星',
    xing5: '1星',
xing5: "1 ดาว", 
    caoZuo: '操作',
caoZuo: "การดำเนินการ", 
    xing6: '星',
xing6: "ดาว", 
    shiFouJieJue: '是否解决',
    pingJiaLaiYuan: '评价来源',
pingJiaLaiYuan: "ที่มาการประเมิน", 
    pingJiaXinXi: '评价信息',
pingJiaXinXi: "รายละเอียดการประเมิน", 
    keFuZu: '客服组',
    jieDaiKeFu: '接待客服',
jieDaiKeFu: "ฝ่ายต้อนรับลูกค้า", 
    huiHuaID: '会话ID',
    zanWuShuJuQing:
      '\n            暂无数据，请重新选择搜索条件进行查询！\n          ',
    zaiXianKeFu: '在线客服',
    quanBuJiNengZu: '全部技能组',
    quanBuKeFu: '全部客服',
    keHuPingJiaJi: '客户评价记录',
keHuPingJiaJi: "บันทึกการประเมินของลูกค้า", 
  },
  serversevalua: {
keHuPingJiaTong: "สถิติการประเมินลูกค้า", 
    keFuPingJiaBao: '客服评价报表',
keFuPingJiaBao: "รายงานการประเมินการบริการลูกค้า", 
chaPingShuChaPing: "จำนวนการประเมินที่ไม่ดี/อัตราการประเมินที่ไม่ดี", 
zhongPingShuZhongPing: "จำนวนการประเมินปานกลาง/อัตราการประเมินปานกลาง", 
haoPingShuHaoPing: "จำนวนการประเมินดี/อัตราการประเมินดี", 
pingJunPingJiaFen: "คะแนนการประเมินเฉลี่ย", 
yaoQingPingJiaShu: "จำนวนคำเชิญประเมิน/อัตราการเชิญ", 
pingJiaShuPingJia: "จำนวนการประเมิน/อัตราการประเมิน", 
    daoChuBaoBiao: '导出报表',
    xianShiYinCangKong: '显示/隐藏空数据',
xianShiYinCangKong: "แสดง/ซ่อนข้อมูลที่ว่างเปล่า", 
keFuPingJiaTong: "รายงานสถิติการประเมินการบริการลูกค้า", 
  },
};
