export default {
  index: {
    zanWuZaiXianKe: "ไม่มีบริการลูกค้าออนไลน์ในขณะนี้!", 
    zanWuZaiXianKe2: "ไม่มีบริการลูกค้าออนไลน์ในขณะนี้!", 
    paiDuiLiKai: "คิวที่จะออก", 
    weiPaiDui: "ไม่มีคิว", 
    ziXunShu: "จำนวนสอบถาม", 
    paiDuiXinXi: "ข้อมูลคิว", 
    jiNengZu: "กลุ่มทักษะ", 
    chaPingLu: "แบบประเมินที่ไม่ดี %", 
    chaPingShuLu: "จำนวน/อัตราแบบประเมินที่ไม่ดี % (1-2)", 
    zhongPingLu: "อัตราแบบประเมินปานกลาง %", 
    zhongPingShuLu: "จำนวน/อัตราแบบประเมินปานกลาง (3-4)", 
    haoPingLu: "แบบประเมินดี %", 
    haoPingShuLuFen: "จำนวน/อัตราแบบประเมินที่ดี (5)", 
    pingJiaJieJueLu: "อัตราความละเอียดในการประเมิน %", 
    pingJiaJieJueShu: "จำนวน/อัตราความละเอียดในการประเมิน", 
    pingJunKeHuPing: "คะแนนเฉลี่ยแบบประเมินของลูกค้า", 
    keHuZhuDongPing: "อัตราการประเมินโดยลูกค้าเอง %", 
    keHuZhuDongPing2: "จำนวน/อัตราของการประเมินโดยลูกค้าเอง", 
    keFuYaoQingPing: "อัตราคำเชิญประเมินการบริการ %", 
    keFuYaoQingPing2: "จำนวน/อัตราคำเชิญประเมินการบริการ", 
    keHuPingJiaLu: "อัตราการประเมินของลูกค้า %", 
    keHuPingJiaShu: "จำนวน/อัตราการประเมินของลูกค้า", 
        yaoQingPingJia: '邀请评价',
    yaoQingPingJia: "คำเชิญประเมิน", 
        yiJieJue: '已解决',
    yiJieJue: "แก้ไขแล้ว", 
        weiPingJia: '未评价',
    weiPingJia: "ยังไม่ได้ประเมิน", 
        xing2: '4星',
        xing3: '3星',
        xing4: '2星',
        xing5: '1星',
    xing5: "1 ดาว", 
        caoZuo: '操作',
    caoZuo: "การดำเนินการ", 
    pingJiaBiaoQian: "แท็กการให้คะแนน", 
    xing6: "ดาว", 
        shiFouJieJue: '是否解决',
        pingJiaLaiYuan: '评价来源',
    pingJiaLaiYuan: "ที่มาการประเมิน", 
    shiFouPingJia: "ประเมินหรือไม่", 
    pingJiaXinXi: "รายละเอียดการประเมิน", 
    ziXunWenTi: "ปรึกษาปัญหา", 
        jieDaiKeFu: '接待客服',
    jieDaiKeFu: "ฝ่ายต้อนรับลูกค้า", 
    keHuZhangHu: "บัญชีลูกค้า", 
    zanWuShuJuQing:
      '\n            暂无数据，请重新选择搜索条件进行查询！\n          ',
        zaiXianKeFu: '在线客服',
    zaiXianKeFu: "ฝ่ายบริการลูกค้าออนไลน์", 
    quanBuJiNengZu: "กลุ่มทักษะทั้งหมด", 
    quanBuKeFu: "ฝ่ายบริการลูกค้าทั้งหมด", 
    keHuPingJiaJi: "บันทึกการประเมินของลูกค้า", 
  },
  serversevalua: {
    keHuPingJiaTong: "สถิติการประเมินลูกค้า", 
    gaiKeFuZuZan: "ไม่มีบริการลูกค้าออนไลน์ในกลุ่มบริการลูกค้านี้", 
    keFuPingJiaBao: "รายงานการประเมินการบริการลูกค้า", 
    chaPingShuChaPing: "จำนวนการประเมินที่ไม่ดี/อัตราการประเมินที่ไม่ดี", 
    zhongPingShuZhongPing: "จำนวนการประเมินปานกลาง/อัตราการประเมินปานกลาง", 
    haoPingShuHaoPing: "จำนวนการประเมินดี/อัตราการประเมินดี", 
    pingJunPingJiaFen: "คะแนนการประเมินเฉลี่ย", 
    yaoQingPingJiaShu: "จำนวนคำเชิญประเมิน/อัตราการเชิญ", 
    pingJiaShuPingJia: "จำนวนการประเมิน/อัตราการประเมิน", 
    keFuZhangHuNi: "บัญชีฝ่ายบริการลูกค้า/ชื่อเล่น", 
        xianShiYinCangKong: '显示/隐藏空数据',
    xianShiYinCangKong: "แสดง/ซ่อนข้อมูลที่ว่างเปล่า", 
    keFuPingJiaTong: "รายงานสถิติการประเมินการบริการลูกค้า", 
  },
};
