export default {
  App: {
  },
  home: {
    jianTing: "กำลังฟัง 11111", 
    keFuYiBeiJin: "บริการลูกค้าถูกปิดใช้งาน", 
    haoDeWoQuPei: "ตกลง ฉันจะไปกำหนดค่า", 
    ninYiXiaDeJi: "ยังไม่ได้กำหนดค่าข้อความต้อนรับส่วนตัวของคุณสำหรับกลุ่มทักษะต่อไปนี้ โปรดกำหนดค่าให้เสร็จสิ้นก่อนเข้าสู่ระบบในโต๊ะทำงาน", 
    tiShi: "แจ้งเตือน", 
    gongNengKaiFaZhong: "กำลังพัฒนาฟังก์ชั่น....", 
    qingQianWangCanShu: "คุณลักษณะในการพัฒนา ....", 
    yeLiHao: "ราตรีสวัสดิ์!", 
    wanShangHao: "สวัสดีตอนกลางคืน!", 
    bangWanHao: "สวัสดีตอนกลางคืน!", 
    xiaWuHao: "สวัสดีตอนกลางคืน!", 
    zhongWuHao: "สวัสดีตอนบ่าย!", 
    shangWuHao: "สวัสดีตอนเช้า!", 
    zaoShangHao: "สวัสดีตอนเช้า!", 
    lingChenHao: "สวัสดีตอนเช้า!", 
    keFuLieBiao: "รายการบริการลูกค้า", 
    keHuLieBiao: "รายชื่อลูกค้า", 
    shiShiJianKong: "การตรวจสอบตามเวลาจริง", 
    keFuGongZuoTai: "โต๊ะทำงานบริการลูกค้า", 
    kuaiSuKaiShiBian: "เริ่มต้นอย่างรวดเร็ว / การนำทางที่สะดวก", 
    shangCiDengLuShi: "\n เวลาเข้าสู่ระบบครั้งล่าสุด:\n", 
    zhouDaoDeFuWu: ")\n การบริการที่เอาใจใส่เป็นวิธีเดียวที่จะชนะใจลูกค้า!!! \n", 
    zhouDaoDeFuWu2: "")\n การบริการที่เอาใจใส่เป็นวิธีเดียวที่จะได้รับความไว้วางใจจากลูกค้าของเรา!!!", 
  },
  login: {
    zhuNinKaiXinMei: "เราหวังว่าคุณจะมีความสุขในวันนี้!", 
    jiesuonidezhanghao: "โปรดติดต่อผู้ดูแลระบบเพื่อปลดล็อกบัญชีของคุณ!", 
    haoDeWoZhiDao: "โอเค ฉันเข้าใจแล้ว", 
    ninDeZhangHaoMi: "บัญชี/รหัสผ่านของคุณถูกป้อนผิดหลายครั้งเกินไป บัญชีถูกล็อคและไม่สามารถเข้าสู่ระบบได้!", 
    zhangHaoYiBeiSuo: "บัญชีถูกล็อค", 
    zhongShi: "ลองอีกครั้ง", 
    wangLuoYiChangQing: "เครือข่ายผิดปกติ โปรดลองอีกครั้ง!", 
    yanZhengMaBuNeng: "รหัสยืนยัน (ห้ามเว้นว่าง)", 
    miMaBuNengWei: "รหัสผ่าน (ห้ามเว้นว่าง)", 
    yongHuMingBuNeng: "ชื่อผู้ใช้ (ห้ามเว้นว่าง)", 
        haoDeYiYongG: '好的，已用Google验证器绑定',
    haoDeYiYongG: "ตกลง ผูกกับ Google Authenticator แล้ว", 
    qingNinXianDaKai:
      '\n        请您先打开Google验证器，扫码绑定后再登录。\n      ',
    woYiShiYongG: "\n ฉันใช้ Google Authenticator โดยการสแกนรหัสเพื่อผูก \n", 
    gaiZhangHuHaiWei: "บัญชียังไม่ได้ผูกกับ Goolge Authenticator และไม่สามารถเข้าสู่ระบบได้", 
    saoMiaoErWeiMa: "สแกนคิวอาร์โค้ด", 
    dengLu: "เข้าสู่ระบบ", 
    yanZhengMaXianShi:
      '验证码显示不出来时，请尝试清除浏览器缓存后重新启动浏览器或者更换浏览器。',
    jiZhuWo: "\n จำฉันไว้\n", 
    qingShuRuGO: "โปรดป้อนรหัสยืนยันของ Google", 
    yanZhengMa: "รหัสยืนยัน", 
    miMa: "รหัส", 
    zhangHao: "บัญชี", 
    nCSPB: "\n B sport admin system\n", 
  },
};
