export default {
  App: {
    jianTing: '监听11111',
  },
  home: {
    keFuYiBeiJin: '客服已被禁用',
    haoDeWoQuPei: '好的, 我去配置',
    ninYiXiaDeJi: '您以下的技能组个人欢迎语未配置，请配置完再登录工作台：',
    tiShi: '提示',
    gongNengKaiFaZhong: '功能开发中....',
    qingQianWangCanShu: '请前往参数配置，配置',
    yeLiHao: '夜里好！',
    wanShangHao: '晚上好！',
    bangWanHao: '傍晚好！',
    xiaWuHao: '下午好！',
    zhongWuHao: '中午好！',
    shangWuHao: '上午好！',
    zaoShangHao: '早上好！',
    lingChenHao: '凌晨好！',
    keFuLieBiao: '客服列表',
    keHuLieBiao: '客户列表',
    shiShiJianKong: '实时监控',
    keFuGongZuoTai: '客服工作台',
    kuaiSuKaiShiBian: '快速开始 / 便捷导航',
    shangCiDengLuShi: '\n        上次登录时间:\n        ',
    zhouDaoDeFuWu: ')\n            周到的服务才能赢得客户的信任!！\n          ',
    zhouDaoDeFuWu2: ')\n            周到的服务才能赢得客户的信任!！',
    zhuNinKaiXinMei: '，祝您开心每一天！',
  },
  login: {
    jiesuonidezhanghao: '请联系您的管理员解锁您的账号！',
    haoDeWoZhiDao: '好的, 我知道了',
    ninDeZhangHaoMi: '您的账号/密码输入错误次数过多，账号已被锁定，无法登录!',
    zhangHaoYiBeiSuo: '账号已被锁定',
    zhongShi: '重试',
    wangLuoYiChangQing: '网络异常，请重试！',
    yanZhengMaBuNeng: '验证码不能为空',
    miMaBuNengWei: '密码不能为空',
    yongHuMingBuNeng: '用户名不能为空',
    'dot': ' ⋅ ',
    haoDeYiYongG: '好的，已用Google验证器绑定',
    woYiShiYongG: '\n        我已使用Google验证器扫码绑定\n      ',
    qingNinXianDaKai:
      '\n        请您先打开Google验证器，扫码绑定后再登录。\n      ',
    gaiZhangHuHaiWei: '该账户还未绑定Goolge验证码，无法登录。',
    saoMiaoErWeiMa: '扫描二维码',
    dengLu: '登 录',
    jiZhuWo: '\n          记住我\n        ',
    yanZhengMaXianShi:
      '验证码显示不出来时，请尝试清除浏览器缓存后重新启动浏览器或者更换浏览器。',
    qingShuRuGO: '请输入google验证码',
    yanZhengMa: '验证码',
    miMa: '密码',
    zhangHao: '账号',
    nCSPB: '\n          B体育客服 后台管理系统\n        ',

  },
};
