export default {
  addKey: {
    xiuGaiChengGong: "แก้ไขสำเร็จ!", 
    tianJiaChanPin: "เพิ่มสินค้า", 
    xiuGaiChanPin: "แก้ไขสินค้า", 
        fou: '否',
    fou: "ไม่", 
    shiFouJieRuZhong: "เข้าสู่ระบบหลังบ้านหรือไม่", 
        jinYong: '禁用',
    jinYong: "ปิดการใช้งาน", 
    zhuangTai: "สถานะ", 
    siYao: "คีย์ส่วนตัว", 
    gongYao: "คีย์สาธารณะ", 
    moRenHuanYingYu: "ข้อความต้อนรับเริ่มต้น", 
    zhuTiSe: "สีของธีม", 
    yingYongLeiXing: "ประเภทแอปพลิเคชัน", 
  },
  keyIndex: {
    chanPinID: "ไอดี สินค้า", 
    ninQueDingShanChu: "คุณแน่ใจหรือที่จะลบ [{val1}(ID{val2})]?", 
    bianJiChengGong: "แก้ไขสำเร็จ!", 
    chanPinLieBiao: "รายการสินค้า", 
    xiuGai: "แก้ไข", 
        chuangJianShiJian: '创建时间',
    chuangJianShiJian: "เวลาที่สร้าง", 
    qingShuRuChanPin: "กรุณาใส่ชื่อสินค้า", 
        qingShuRuYingYong2: '请输入应用编号',
    qingShuRuYingYong2: "กรุณากรอกเลขที่แอปพลิเคชัน", 
    suoYouYingYongLei: "แอปพลิเคชันทุกประเภท", 
    suoYouZhuangTai: "สถานะทั้งหมด", 
    chanPinZhuangTai: "สถานะสินค้า", 
  },
};
