export default {
  addKey: {
    xiuGaiChengGong: '修改失败！',
    tianJiaChanPin: '添加产品',
tianJiaChanPin: "เพิ่มสินค้า", 
xiuGaiChanPin: "แก้ไขสินค้า", 
    fou: '否',
fou: "ไม่", 
shiFouJieRuZhong: "เข้าสู่ระบบหลังบ้านหรือไม่", 
    jinYong: '禁用',
jinYong: "ปิดการใช้งาน", 
    siYao: '私钥',
siYao: "คีย์ส่วนตัว", 
gongYao: "คีย์สาธารณะ", 
moRenHuanYingYu: "ข้อความต้อนรับเริ่มต้น", 
zhuTiSe: "สีของธีม", 
yingYongLeiXing: "ประเภทแอปพลิเคชัน", 
  },
  keyIndex: {
    ninQueDingShanChu: '您确定删除【{val1}（ID{val2}）】?',
    bianJiChengGong: '编辑成功',
    chanPinLieBiao: '产品列表',
chanPinLieBiao: "รายการสินค้า", 
    gengXinShiJian: '更新时间',
    chuangJianShiJian: '创建时间',
chuangJianShiJian: "เวลาที่สร้าง", 
qingShuRuChanPin: "กรุณาใส่ชื่อสินค้า", 
    qingShuRuYingYong2: '请输入应用编号',
qingShuRuYingYong2: "กรุณากรอกเลขที่แอปพลิเคชัน", 
suoYouYingYongLei: "แอปพลิเคชันทุกประเภท", 
suoYouZhuangTai: "สถานะทั้งหมด", 
chanPinZhuangTai: "สถานะสินค้า", 
  },
};
