export default {
  editDialog: {
nullbianJiChengGong: "แก้ไขสำเร็จ!", 
danXuan: "เลือกเดี่ยว", 
weiXin: "วีแชท", 
shouJiHao: "หมายเลขโทรศัพท์มือถือ", 
    shi: '是',
shi: "ใช่", 
shiFouBiTian: "จำเป็นต้องกรอกหรือไม่", 
lianXiFangShi: "ข้อมูลติดต่อ", 
liuYanTuPian: "รูปภาพ", 
qingShuRuNeiRong: "โปรดป้อนการแจ้งเตือนเนื้อหา", 
liuYanNeiRong: "เนื้อหาข้อความ", 
ziXunWenTi: "คำถามปัญหา", 
xingXingBie: "นามสกุล(เพศ)", 
keHuZhangHao: "หมายเลขบัญชีลูกค้า", 
liuYanBanZiDuan: "กระดานฝากข้อความ", 
  },
  index: {
    ninShiFouQueDing: '您是否确定要{val1}留言功能?',
ninShiFouQueDing: "คุณแน่ใจหรือไม่ว่าต้องการฟังก์ชันฝากข้อความ {val1}", 
languageTemplate: "(ภาษา: {val1})", 
sheZhi: "ตั้งค่า", 
xuanTian: "ไม่จำเป็น", 
biTian: "จำเป็นต้องกรอก", 
liuYanZiDuanShe: "การตั้งค่าฝากข้อความ", 
keHuLiuYanDang: "หากข้อความของลูกค้าเกินจำนวนครั้งในวันนั้น จะไม่สามารถทิ้งข้อความได้อีก", 
shiFouKaiQiLiu: "ต้องการเปิดฟังก์ชั่นฝากข้อความหรือไม่", 
liuYanSheZhi: "การตั้งค่าฝากข้อความ", 
    qingShuRu: '请输入',
qingShuRu: "กรุณาป้อนข้อมูล", 
liuYanTuPian: "\n รูปภาพ\n", 
liuYanNeiRongBi: "\n เนื้อหาข้อความ (จำเป็น)\n", 
ziXunWenTiBi: "\n คำถามปัญหา (จำเป็น)\n", 
xingXingBieBiTian: "\n นามสกุล(เพศ)\n(จำเป็น)\n", 
keHuZhangHaoBi: "\n หมายเลขบัญชีลูกค้า (จำเป็น)\n", 
meiRiZuiDuoLiu: "จำนวนข้อความสูงสุดต่อวัน", 
    baoCun: '保存'
    baoCun: '保存'
  }
}
