export default {
  editDialog: {
    bianJiChengGong: '编辑成功',
    danXuan: '单选',
    weiXin: '微信',
    shouJiHao: '手机号',
    fou: '否',
    shi: '是',
    shiFouBiTian: '是否必填',
shiFouBiTian: "จำเป็นต้องกรอกหรือไม่", 
lianXiFangShi: "ข้อมูลติดต่อ", 
    qingShuRuNeiRong: '请输入内容提示语',
qingShuRuNeiRong: "โปรดป้อนการแจ้งเตือนเนื้อหา", 
    ziXunWenTi: '咨询问题',
    xingXingBie: '姓(性别)',
xingXingBie: "นามสกุล(เพศ)", 
keHuZhangHao: "หมายเลขบัญชีลูกค้า", 
liuYanBanZiDuan: "กระดานฝากข้อความ", 
  },
  index: {
    ninShiFouQueDing: '您是否确定要{val1}留言功能?',
    languageTemplate: '（语言：{val1}）',
languageTemplate: "(ภาษา: {val1})", 
sheZhi: "ตั้งค่า", 
xuanTian: "ไม่จำเป็น", 
    liuYanZiDuanShe: '留言字段设置',
liuYanZiDuanShe: "การตั้งค่าฝากข้อความ", 
keHuLiuYanDang: "หากข้อความของลูกค้าเกินจำนวนครั้งในวันนั้น จะไม่สามารถทิ้งข้อความได้อีก", 
shiFouKaiQiLiu: "ต้องการเปิดฟังก์ชั่นฝากข้อความหรือไม่", 
liuYanSheZhi: "การตั้งค่าฝากข้อความ", 
    qingShuRu: '请输入',
    liuYanTuPian: '\n                留言图片\n              ',
    liuYanNeiRongBi: '\n                留言内容（必填）\n              ',
liuYanNeiRongBi: "\n เนื้อหาข้อความ (จำเป็น)\n", 
ziXunWenTiBi: "\n คำถามปัญหา (จำเป็น)\n", 
xingXingBieBiTian: "\n นามสกุล(เพศ)\n(จำเป็น)\n", 
keHuZhangHaoBi: "\n หมายเลขบัญชีลูกค้า (จำเป็น)\n", 
meiRiZuiDuoLiu: "จำนวนข้อความสูงสุดต่อวัน", 
    baoCun: '保存'

  }
}
