export default {
  index: {
shangChuanChengGong: "อัปโหลดสำเร็จ", 
shangChuanChengGong: "อัปโหลดสำเร็จ", 
    wenJian: '文件',
wenJian: "ไฟล์", 
caoZuoRen: "ผู้ดำเนินการ", 
daXiao: "สูงต่ำ", 
leiBie: "หมวดหมู่", 
wenJianLeiXing: "ประเภทไฟล์", 
yuLanTu: "ภาพตัวอย่าง", 
luJing: "เส้นทาง", 
    keShangChuanRenYi: '可上传任意格式文件，且不超过100M',
keShangChuanRenYi: "คุณสามารถอัปโหลดไฟล์รูปแบบใดก็ได้และไม่เกิน 100M", 
tianJiaWenJian: "เพิ่มไฟล์", 
bianJiWenJian: "แก้ไขไฟล์", 
wenJianShangChuan: "อัปโหลดไฟล์", 
    shuRuNeiRongMo: '输入内容模糊搜索',
shuRuNeiRongMo: "ป้อนเนื้อหาสำหรับการค้นหา", 
  },
};
