export default {
  index: {
shangChuanChengGong: "อัปโหลดสำเร็จ", 
shangChuanChengGong: "อัปโหลดสำเร็จ", 
shangChuanWenJianDa: "ขนาดไฟล์ที่อัพโหลดต้องไม่เกิน 100MB!", 
wenJian: "ไฟล์", 
caoZuoRen: "ผู้ดำเนินการ", 
daXiao: "สูงต่ำ", 
leiBie: "หมวดหมู่", 
wenJianLeiXing: "ประเภทไฟล์", 
yuLanTu: "ภาพตัวอย่าง", 
luJing: "เส้นทาง", 
quXiao: "ยกเลิก", 
keShangChuanRenYi: "คุณสามารถอัปโหลดไฟล์รูปแบบใดก็ได้และไม่เกิน 100M", 
tianJiaWenJian: "เพิ่มไฟล์", 
bianJiWenJian: "แก้ไขไฟล์", 
wenJianShangChuan: "อัปโหลดไฟล์", 
shangChuan: "อัปโหลด \n", 
shuRuNeiRongMo: "ป้อนเนื้อหาสำหรับการค้นหา", 
  },
};
