export default {
  index: {
dingJiLeiMu: "หมวดหมู่ยอดนิยม", 
dingJiLeiMu: "หมวดหมู่ยอดนิยม", 
qingShuRuDiZhi: "กรุณากรอกที่อยู่", 
caiDan: "เมนู", 
    fou: '否',
fou: "ไม่", 
keJian: "มองเห็นได้", 
huanCun: "แคช", 
waiLian: "ลิงก์ภายนอก", 
zuJianLuJing: "เส้นทางส่วนประกอบ", 
quanXianBiaoZhi: "รหัสสิทธิ์", 
luYouDiZhi: "ที่อยู่เส้นทาง", 
tuBiao: "ไอคอน", 
caiDanMingCheng: "ชื่อเมนู", 
shangJiLeiMu: "หมวดหมู่หัวหน้า", 
piPeiZuJianNei: "จับคู่ช่องชื่อภายในส่วนประกอบ", 
zuJianMingCheng: "ชื่อส่วนประกอบ", 
caiDanPaiXu: "จัดเรียงเมนู", 
anNiuMingCheng: "ชื่อปุ่ม", 
caiDanBiaoTi: "ชื่อเมนู", 
caiDanKeJian: "มองเห็นเมนู", 
caiDanHuanCun: "แคชเมนู", 
waiLianCaiDan: "เมนูภายนอก", 
dianJiXuanZeTu: "คลิกเพื่อเลือกไอคอน", 
caiDanTuBiao: "ไอคอนเมนู", 
anNiu: "ปุ่ม", 
muLu: "ไดเรกทอรี", 
caiDanLeiXing: "ประเภทเมนู", 

  },
};
