export default {
  editDialog: {
        touXiangXiuGaiShi: '头像修改失败',
    touXiangXiuGaiShi: "แก้ไขรูปโปรไฟล์ล้มเหลว", 
    touXiangXiuGaiCheng: "แก้ไขรูปโปรไฟล์สำเร็จ", 
    shangChuanTouXiangTu: "อัพโหลดรูปโปรไฟล์ต้องไม่เกิน 2MB!", 
    qingXuanZe: "โปรดเลือก", 
    keFuNiChengBu: "ชื่อเล่นของฝ่ายบริการลูกค้า(ห้ามเว้นว่าง)", 
    shangChuanTouXiang: "อัพโหลดรูปโปรไฟล์", 
    queRen: "ยืนยัน", 
        peiZhiLeXinDe: '配置了新的技能组，系统会自动将该欢迎语配置给该客服新技能组',
    liRuGaiKeFu:
      '例如：该客服新增技能组1，则该客服技能组1的欢迎语为该默认配置。',
    peiZhiLeXinDe: "หลังจากกำหนดค่ากลุ่มทักษะใหม่ ระบบจะกำหนดค่าข้อความต้อนรับให้กับกลุ่มทักษะใหม่ของฝ่ายบริการลูกค้าโดยอัตโนมัติ", 
    shuoMing: "คำอธิบาย.", 
    xinJiNengZuHuan: "ข้อความต้อนรับกลุ่มทักษะใหม่:", 
    qingXuanZeJiNeng: "โปรดเลือกกลุ่มทักษะ", 
    jiNengZu: "กลุ่มทักษะ", 
    qingXuanZeKeFu: "กรุณาเลือกกลุ่มบริการลูกค้า", 
    keFuFenZu: "แบ่งกลุ่มบริการลูกค้า", 
    keFuZhuangTai: "สถานะการบริการลูกค้า", 
    keFuNiCheng: "ชื่อเล่นฝ่ายบริการลูกค้า", 
    qingXianXuanZe: "กรุณาเลือกก่อน", 
    zongDaiID: "ไอดี ตัวแทน", 
    suoShuDaiLi: "ตัวแทนในเครือ", 
    keFuLeiXing: "ประเภทการบริการลูกค้า", 
    keFuZhangHuMing: "ชื่อบัญชีบริการลูกค้า", 
    bianJiKeFu: "แก้ไขการบริการลูกค้า -", 
  },
  limitDialog: {
    jieDaiShangXianShe: "ตั้งค่าขีดจำกัดการรับสำเร็จแล้ว!", 
    zuiDaJieDaiShang: "ขีดจำกัดการรับสูงสุดคือ 100", 
    zhiNengShuRuDa: "สามารถป้อนได้เฉพาะจำนวนเต็มที่มากกว่าหรือเท่ากับ 0 เท่านั้น", 
    qingShuRu: "กรุณาป้อน", 
    biTian: "จำเป็นต้องกรอก", 
    qingShuRuKeFu: "โปรดป้อนขีดจำกัดสูงสุดของการรับบริการลูกค้า", 
    sheZhiKeFuJie: "กำหนดขีดจำกัดสูงสุดในการรับบริการลูกค้า --", 
  },
  addDialog: {
    fou: "ไม่", 
    shi: "ใช่", 
    qingShuRuMingCheng: "กรุณากรอกชื่อ", 
    qingShuRuJiNeng: "โปรดป้อนข้อความต้อนรับสำหรับกลุ่มทักษะ", 
    jiNengZuHuanYing: "ข้อความต้อนรับสำหรับกลุ่มทักษะ:", 
    shiFouQiYongLei: "เปิดใช้งานการจับคู่ประเภทหรือไม่", 
    tuiGuangShangShiFou: "มองเห็นผู้สนับสนุนหรือไม่", 
    xianShiZeYongHu:
      '显示则用户能看到该问题；不显示则用户看不到该问题\n        ',
    xianShiZeYongHu2: "ถ้าแสดง ผู้ใช้สามารถเห็นคำถาม; ถ้าไม่แสดง ผู้ใช้จะไม่เห็นคำถาม \n", 
    suoShuYeWu: "ธุรกิจ", 
    shiFouXianShi: "แสดงหรือไม่", 
    qingShuRuJiNeng2: "โปรดป้อนชื่อกลุ่มทักษะ", 
  },
  addMember: {
    qingXuanZeKeFu: "กรุณาเลือกฝ่ายบริการลูกค้า", 
    tianJiaChengGong: "เพิ่มเครดิตสำเร็จ", 
    dangQianYeVA: "หน้าปัจจุบัน: {val1}", 
    meiYeVAL: "{val1} รายการต่อหน้า", 
    qingShuRuGeRen: "กรุณากรอกข้อความต้อนรับส่วนตัว", 
    tianJia: "\n เพิ่ม \n", 
    qingPeiZhiMoRen: "โปรดกำหนดค่าข้อความต้อนรับเริ่มต้น:", 
  },
  deleteDialog: {
    qingXuanZeYaoYi: "โปรดเลือกสมาชิกที่คุณต้องการลบ", 
    yiChuChengGong: "ลบสำเร็จ!", 
    yiChu: "ลบ", 
    quXiaoGuanLianKe: "ยกเลิกการติดต่อฝ่ายบริการลูกค้า", 
    yiGuanLianKeFu: "ติดต่อฝ่ายบริการลูกค้าแล้ว", 
    keFuZhangHu: "บัญชีฝ่ายบริการลูกค้า", 
  },
  members: {
    chengYuanYiChu: "ลบสมาชิก", 
    congGaiJiNengZu: "】นำออกจากกลุ่มทักษะนี้หรือไม่ \n", 
    congGaiJiNengZu2: "】นำออกจากกลุ่มทักษะนี้หรือไม่", 
    queDingJiangKeFu: "\n ยืนยันว่าบริการลูกค้า【", 
    zuiJinDengLuShi: "เวลาเข้าสู่ระบบครั้งล่าสุด", 
  },
  skillDialog: {
    guanBi: "ปิด", 
    jiNengZuGuanLi: "การจัดการการบริการลูกค้ากลุ่มทักษะ:", 
    chuangJianRiQi: "วันที่สร้าง:", 
    shiFouXianShi: "แสดงหรือไม่:", 
    jiNengZuID: "ไอดี กลุ่มทักษะ:", 
    jiNengZuMingCheng: "ชื่อกลุ่มทักษะ:", 
    zhaKanJiNengZu: "ดูกลุ่มทักษะ", 
  },
  form: {
    suoShuBuMenBu: "แผนก(ห้ามเว้นว่าง)", 
    queRen: "\n ยืนยัน \n", 
    quXiao: "\n ยกเลิก \n", 
    xuanZeBuMen: "เลือกแผนก", 
    qingXuanZe: "โปรดเลือก", 
    qingShuRu: "กรุณาป้อนข้อมูล", 
    qingShuRuZhengQue: "กรุณาใส่รูปแบบที่ถูกต้อง", 
    yingYongBianHao: "เลขที่แอปพลิเคชัน", 
  },
  header: {
    shuRuGangWeiMing: "กรอกชื่อตำแหน่งที่ต้องการค้นหา", 
    shuRuChanPinMing: "กรอกชื่อสินค้า", 
    shuRuYingYongMing: "กรอกชื่อแอปพลิเคชัน", 
    shuRuYingYongI: "กรอก ไอดี แอปพลิเคชัน", 
  },
  infoDetail1: {
    fuZhiChengGong: "คัดลอกสำเร็จ", 
    keHuDuanLeiBie:
      '\n          客户端类别: {val1}\n          客户端版本: {val2}\n          发起请求界面: {val3}\n          发起请求路径: {val4}\n          咨询问题类型: {val5}\n          客户端IP: {val6}\n          接入域名: {val7}\n          联网类型: {val8}\n          客户端地理位置: {val9}\n          IMEI: {val10}\n          屏幕高度: {val11}\n          CPU总数目: {val12}\n          内存信息: {val13}\n          屏幕宽度: {val14}\n          是否有SD卡: {val15}\n          CPU使用比例: {val16}\n          ... : ...\n          ',
    iMEIT:
      '\n          IMEI: {val1}\n          屏幕高度: {val2}\n          CPU总数目: {val3}\n          内存信息: {val4}\n          屏幕宽度: {val5}\n          是否有SD卡: {val6}\n          CPU使用比例: {val7}\n          ...: ...\n          ',
    keHuDuanIP:
      '\n          客户端IP: {val1}\n          接入域名: {val2}\n          联网类型: {val3}\n          客户端地理位置: {val4}\n          ',
    keHuDuanLeiBie2:
      '\n          客户端类别: {val1}\n          客户端版本: {val2}\n          发起请求界面: {val3}\n          发起请求路径: {val4}\n          咨询问题类型: {val5}\n          ',
    suoShuBuMenBu: "แผนก(ห้ามเว้นว่าง)", 
    qingShuRuXuHao: "กรุณากรอกหมายเลขซีเรียล", 
    qingShuRuMingCheng: "กรุณากรอกชื่อ", 
    zanWuShuJu: "ยังไม่มีข้อมูล", 
    jiaZaiZhong: "กำลังโหลด", 
    yongHuShangChuan: "ผู้ใช้อัปโหลด", 
    shi: "ใช่", 
    fou: "ไม่", 
    fuZhi: "คัดลอก", 
    sheBeiXinXi: "ข้อมูลอุปกรณ์", 
    wangLuoXinXi: "ข้อมูลเครือข่าย", 
    yingYongXinXi: "ข้อมูล แอปพลิเคชัน", 
    quanBuFuZhi: "คัดลอกทั้งหมด", 
    xiTongCaiJi: "ระบบรวบรวม", 
    wenTiLeiXing: "ประเภทปัญหา", 
    caiJiShiJian: "เวลารวบรวม", 
    zhangHuMing: "ชื่อบัญชี", 
  },
  
}
