export default {
  index: {
woDeBaoBiao: "คำชี้แจงของฉัน", 
woDeBaoBiao: "คำชี้แจงของฉัน", 
    pingJunHuiHuaShi: '平均会话时长',
    jieDaiYaLiZhi: '接待压力值',
    huiFuLu: '回复率',
    jieDaiKeHuShu: '接待客户数',
    keHuKeFuXiao: '客户/客服消息数',
keHuKeFuXiao: "จำนวนข้อความของลูกค้า/บริการลูกค้า", 
dengLuShiChang: "ระยะเวลาการเข้าสู่ระบบ", 
    keHuPingJiaLu: '客户评价率/数',
    yaoQingPingJiaLu: '邀请评价率/数',
    keFuJieJueLu: '客服解决率/数',
    keFuZongJieLu: '客服总结率/数',
    sNeiXiangYingYing: '30s内响应应答率',
    zuiDaXiangYingShi: '最大响应时长',
    pingJunShouXiangShi: '平均首响时长',
pingJunShouXiangShi: "ระยะเวลาเสียงกริ่งแรกเฉลี่ย", 
pingJunXiangYingShi: "ระยะเวลาตอบสนองเฉลี่ย", 
    zhuanChuHuiHuaShu: '转出会话数',
    huiHuaShuYouXiao: '会话数/有效数',
huiHuaShuYouXiao: "จำนวนบทสทนา/ที่มีประสิทธภาพ", 
mangLu: "ยุ่ง", 
    xianShiYinCangKong: '显示/隐藏空数据',
xianShiYinCangKong: "แสดง/ซ่อนข้อมูลที่ว่างเปล่า", 
sheZhiXianShiCan: "ตั้งค่าพารามิเตอร์การแสดงผล", 
    keFuZhangHuNi: '客服账户/昵称：',

  },
};
