export default {
  index: {
null    queDing: '确定',
    tiShi: '提示',
tiShi: "แจ้งเตือน", 
queRenQiangTuiXuan: "ยืนยันการบังคับออกจากระบบของผู้ใช้ {val1} หรือไม่", 
    youXiaoHuiHua: '有效会话',
    weiZongJie: '未总结',
weiZongJie: "ยังไม่สรุปผล", 
yiZongJie: "สรุปผลแล้ว", 
    yiJieJue: '已解决',
    weiZhiJian: '未质检',
    yiZhiJian: '已质检',
yiZhiJian: "ตรวจสอบแล้ว", 
weiPaiDui: "ไม่มีคิว", 
paiDuiJinRu: "เข้าคิว", 
    yaoQingPingJia: '邀请评价',
yaoQingPingJia: "ส่งเชิญประเมิน", 
    weiPingJia: '未评价',
weiPingJia: "ยังไม่ประเมิน", 
zhiJianRenZhiJian: "คนตรวจสอบ/เวลาตรวจสอบ", 
zhiJianZhuangTai: "สถานะการตรวจสอบ", 
xing: "ดาว", 
    shiFouJieJue: '是否解决',
    pingJiaLaiYuan: '评价来源',
pingJiaLaiYuan: "ที่มาการประเมิน", 
pingJiaLeiXing: "ประเภทการประเมิน", 
    keHuPingJia: '客户评价',
    yeWu: '业务',
    huiHuaLeiBie: '会话类别',
huiHuaLeiBie: "ประเภทบทสทนา", 
    huiHuaLeiXing: '会话类型',
    paiDuiXinXi: '排队信息',
paiDuiXinXi: "ข้อมูลคิว", 
    wenTiShiChang: '问题/时长',
wenTiShiChang: "คำถาม/ระยะเวลา", 
keHuZu: "กลุ่มลูกค้า", 
keHuQuDao: "ลูกค้า/ช่องทาง", 
    quanXuanJiNengZu: '全选技能组',
    quanBuJiNengZu: '全部技能组',
quanBuJiNengZu: "กลุ่มทักษะทั้งหมด", 
    qingShuRuHuiHua: '请输入会话ID',
  },
};
