export default {
  BarChart: {
    shiJian: "เวลา", 
        shiChang: '时长',
    shiChang: "ระยะเวลา", 
  },
  BarMore: {
    zhiMang: "ยุ่ง", 
    liKai: "ออก", 
    xiLie: "ชุดที่ 2", 
        zhanBi: '占比：',
    zhanBi: "สัดส่วน:", 
    dengLuShiChang: "ระยะเวลาเข้าสู่ระบบ:", 
    zaiXian: "ออนไลน์", 
  },
  LineChart: {
    huiHuaXiaoXiShu: "จำนวนข้อความบทสนทนา", 
    huiHuaShu: "จำนวนบทสนทนา", 
    huiHuaXiaoXiShu2: "จำนวนข้อความบทสนทนา (อัน)", 
    huiHuaShuGe: "จำนวนบทสนทนา (อัน)", 
  },
  index: {
    fenMiao: "0 นาที 0 วินาที", 
    dengLuZhuangTai: "สถานะการเข้าสู่ระบบ", 
    ge: "อัน", 
    fen: "นาที", 
    shu: "/จำนวน", 
    huiHuaGuanBiFen: "การวิเคราะห์การปิดบทสนทนา", 
    huiHuaJieRuFang: "วิธีการเข้าถึงบทสนทนา", 
    huiHuaQuDaoFen: "การวิเคราะห์ช่องทางบทสนทนา", 
    huiHuaJiNengZu: "การวิเคราะห์กลุ่มทักษะบทสนทนา", 
    qingXuanZe: "โปรดเลือก", 
    zuiShaoYaoPeiZhi: "ต้องกำหนดค่าอย่างน้อย 5 รายการ", 
    xiangYingCuoWuQing: "เกิดข้อผิดพลาดในการตอบกลับ โปรดลองอีกครั้งในภายหลัง!", 
    zanWuShuJu: "ยังไม่มีข้อมูล", 
    huiHuaFenXi: "การวิเคราะห์บทสนทนา", 
    huiHuaQuXian: "เส้นโค้งบทสนทนา", 
    woDeShuJu: "ข้อมูลของฉัน", 
    shuaXin: "รีเฟรช", 
    sheZhiKanBanCan: "ตั้งค่าพารามิเตอร์ Kanban", 
    zhongZhi: "รีเซ็ต", 
    chaXun: "ตรวจสอบ", 
    suoYouKeFu: "ฝ่ายบริการลูกค้าทั้งหมด", 
  },
};
