export default {
  index: {
    quXiao: '取消',
    queDing: '确定',
    tiShi: '提示',
tiShi: "แจ้งเตือน", 
    wuXiaoHuiHua: '无效会话',
    youXiaoHuiHua: '有效会话',
    weiZongJie: '未总结',
weiZongJie: "ยังไม่สรุปผล", 
yiZongJie: "สรุปผลแล้ว", 
    yiJieJue: '已解决',
    weiZhiJian: '未质检',
    yiZhiJian: '已质检',
yiZhiJian: "ตรวจสอบแล้ว", 
    paiDuiJinRu: '排队进入',
    zhuDongPingJia: '主动评价',
    yaoQingPingJia: '邀请评价',
yaoQingPingJia: "ส่งเชิญประเมิน", 
    weiPingJia: '未评价',
weiPingJia: "ยังไม่ประเมิน", 
    zhiJianZhuangTai: '质检状态',
    xing: '星',
    pingFen: '评分',
    shiFouJieJue: '是否解决',
    pingJiaLaiYuan: '评价来源',
pingJiaLaiYuan: "ที่มาการประเมิน", 
    shiFouPingJia: '是否评价',
    keHuPingJia: '客户评价',
    yeWu: '业务',
    huiHuaLeiBie: '会话类别',
huiHuaLeiBie: "ประเภทบทสทนา", 
    huiHuaLeiXing: '会话类型',
    paiDuiXinXi: '排队信息',
paiDuiXinXi: "ข้อมูลคิว", 
    wenTiShiChang: '问题/时长',
wenTiShiChang: "คำถาม/ระยะเวลา", 
    keHuQuDao: '客户/渠道',
    qingShuRuKeHu: '请输入客户账户名',
    quanXuanJiNengZu: '全选技能组',
    quanBuJiNengZu: '全部技能组',
quanBuJiNengZu: "กลุ่มทักษะทั้งหมด", 

  },
};
