export default {
  index: {
        queDing: '确定',
        tiShi: '提示',
    tiShi: "แจ้งเตือน", 
    queRenQiangTuiXuan: "ยืนยันการบังคับออกจากระบบของผู้ใช้ {val1} หรือไม่", 
    wuXiaoHuiHua: "บทสนทนาไม่มีประสิทธิภาพ", 
    youXiaoHuiHua: "บทสนทนาที่มีประสิทธิภาพ", 
    weiZongJie: "ยังไม่สรุปผล", 
    yiZongJie: "สรุปผลแล้ว", 
    weiJieJue: "ยังไม่ได้แก้ไข", 
    yiJieJue: "แก้ไขแล้ว", 
    weiZhiJian: "ยังไม่ผ่านการตรวจสอบ", 
    yiZhiJian: "ตรวจสอบแล้ว", 
    weiPaiDui: "ไม่มีคิว", 
    paiDuiJinRu: "เข้าคิว", 
    zhuDongPingJia: "การประเมินเอง", 
    yaoQingPingJia: "ส่งเชิญประเมิน", 
    yiPingJia: "ประเมินแล้ว", 
    weiPingJia: "ยังไม่ประเมิน", 
    zhiJianRenZhiJian: "คนตรวจสอบ/เวลาตรวจสอบ", 
    zhiJianZhuangTai: "สถานะการตรวจสอบ", 
    xing: "ดาว", 
    pingFen: "ประเมิน", 
    shiFouJieJue: "แก้ไขแล้วหรือไม่", 
    pingJiaLaiYuan: "ที่มาการประเมิน", 
    pingJiaLeiXing: "ประเภทการประเมิน", 
    shiFouPingJia: "ประเมินหรือไม่", 
    keHuPingJia: "การประเมินของลูกค้า", 
    yeWu: "ธุรกิจ", 
    huiHuaLeiBie: "ประเภทบทสทนา", 
    keFuZongJie: "สรุปผลการบริการลูกค้า", 
        paiDuiXinXi: '排队信息',
    paiDuiXinXi: "ข้อมูลคิว", 
    huiHuaKaiShiShi: "เวลาเริ่มต้นบทสทนา", 
    wenTiShiChang: "คำถาม/ระยะเวลา", 
    keHuZu: "กลุ่มลูกค้า", 
    keHuQuDao: "ลูกค้า/ช่องทาง", 
    qingShuRuKeHu: "กรุณากรอกชื่อบัญชีลูกค้า", 
    quanXuanJiNengZu: "เลือกกลุ่มทักษะทั้งหมด", 
    quanBuJiNengZu: "กลุ่มทักษะทั้งหมด", 
    qingShuRuHuiHua: "โปรดกรอก ไอดี บทสทนา", 
  },
};
