export default {
  BarChart: {
        'con': '：',
        shiChang: '时长',
  },
  BarMore: {
    shiChang: "ระยะเวลา", 
        liKai: '离开',
        xiLie: '系列2',
        dengLuZhuangTaiM: '登录状态(min)',
        zhanBi: '占比：',
        dengLuShiChang: '登录时长:',
        zaiXian: '在线',
  },
  LineChart: {
    zaiXian: "ออนไลน์", 
    huiHuaXiaoXiShu: "จำนวนข้อความบทสนทนา", 
    huiHuaShu: "จำนวนบทสนทนา", 
    huiHuaXiaoXiShu2: "จำนวนข้อความบทสนทนา (อัน)", 
  },
  index: {
    huiHuaShuGe: "จำนวนบทสนทนา (อัน)", 
    fenMiao: "0 นาที 0 วินาที", 
    dengLuZhuangTai: "สถานะการเข้าสู่ระบบ", 
    ge: "อัน", 
    fen: "นาที", 
    shu: "/จำนวน", 
    huiHuaGuanBiFen: "การวิเคราะห์การปิดบทสนทนา", 
    huiHuaJieRuFang: "วิธีการเข้าถึงบทสนทนา", 
    huiHuaQuDaoFen: "การวิเคราะห์ช่องทางบทสนทนา", 
    huiHuaJiNengZu: "การวิเคราะห์กลุ่มทักษะบทสนทนา", 
    qingXuanZe: "โปรดเลือก", 
    zuiShaoYaoPeiZhi: "ต้องกำหนดค่าอย่างน้อย 5 รายการ", 
    xiangYingCuoWuQing: "เกิดข้อผิดพลาดในการตอบกลับ โปรดลองอีกครั้งในภายหลัง!", 
    zanWuShuJu: "ยังไม่มีข้อมูล", 
    huiHuaFenXi: "การวิเคราะห์บทสนทนา", 
    huiHuaQuXian: "เส้นโค้งบทสนทนา", 
    woDeShuJu: "ข้อมูลของฉัน", 
    shuaXin: "รีเฟรช", 
    sheZhiKanBanCan: "ตั้งค่าพารามิเตอร์ Kanban", 
        chaXun: '查询',
    chaXun: "ตรวจสอบ", 
        suoYouKeFu: '所有客服',
  },
};
