export default {
  index: {
    woDeBaoBiao: '我的报表',
    xiangYingShiChang: '响应时长',
    pingJunHuiHuaShi: '平均会话时长',
    jieDaiYaLiZhi: '接待压力值',
    huiFuLu: '回复率',
    jieDaiKeHuShu: '接待客户数',
    keHuKeFuXiao: '客户/客服消息数',
    dengLuShiChang: '登录时长',
    keHuPingJiaPing: '客户评价平均分',
    keHuPingJiaLu: '客户评价率/数',
    yaoQingPingJiaLu: '邀请评价率/数',
    keFuJieJueLu: '客服解决率/数',
    keFuZongJieLu: '客服总结率/数',
    sNeiXiangYingYing: '30s内响应应答率',
    zuiDaXiangYingShi: '最大响应时长',
    pingJunShouXiangShi: '平均首响时长',
    pingJunXiangYingShi: '平均响应时长',
    zuiDaJieDaiShu: '最大接待数',
    zhuanChuHuiHuaShu: '转出会话数',
    huiHuaShuYouXiao: '会话数/有效数',
    mangLu: '忙碌',
    daoChuBaoBiao: '导出报表',
    xianShiYinCangKong: '显示/隐藏空数据',
    sheZhiXianShiCan: '设置显示参数',
    keFuFenZu: '客服分组：',
    keFuZhangHuNi: '客服账户/昵称：',

  },
};
