export default {
  BarChart: {
    fangWenLaiYuan: '访问来源',
  },
  TimeChart: {
    miao: '秒',
    miao2: '(秒)',
  },
  index: {
    caoZuoChengGong: '操作成功!',
    quXiao: '取消',
    queDing: '确定',
    qiangZhiXiaXian: '强制下线',
    queRenJiangGaiKe: '确认将该客服强制下线吗？',
    shu: '数',
    tuiChuPaiDui: '退出排队',
    jinRuHuiHua: '进入会话',
    zhuanJieJieRu: '转接接入',
    paiDuiJieRu: '排队接入',
    ziDongJieRu: '自动接入',
    zongPaiDuiShiChang: '总排队时长',
    pingJunPaiDuiShi: '平均排队时长',
    huiHuaShu: '会话数',
    zaiXianKeFu: '在线客服',
    caoZuo: '操作',
    pingJiaLu: '评价率',
    yaoQingPingJiaLu: '邀请评价率',
    zongJieLu: '总结率',
    liKaiShiChang: '离开时长',
    zhuangtaiShiChang2:'登录时长 \n 当前状态持续时长',
    jiedaiRenshuShangXian:'接待人数 \n 接待上限',

    
    zaiXianJiNengZu: '在线技能组',
    keFuFenZu: '客服分组',
    mangLu: '忙碌',
    zaiXian: '在线',
    liKai: '离开',
    keFuZhangHuMing: '客服账户名/昵称',
    sZiDongShuaXin: '30s自动刷新',
    shuaXin: '刷新',
    qingShuRuKeFu: '请输入客服代理',
    qingShuRuKeFu2: '请输入客服账号',
    iTEML: 'item.label != `离线`',
    quanBu: '全部',
    qingXuanZeZaiXian: '请选择在线状态',
    qingXuanZeKeFu: '请选择客服技能组',
    quanBuKeFuZu: '全部客服组',
    dangQianZaiXianJie: '\n      当前在线接待概况\n    ',
    zanWuShuJu: '暂无数据',
    chaXun: '查询',
    jinRiHuiHuaGai: '今日会话概况',
    shiShiShuJu: '实时数据',

  },
};
