export default {
  BarChart: {
    fangWenLaiYuan: '访问来源',
  },
  TimeChart: {
    miao: '秒',
    miao2: '(秒)',
  },
  index: {
miao2: "(วินาที)", 
    quXiao: '取消',
    queDing: '确定',
    qiangZhiXiaXian: '强制下线',
qiangZhiXiaXian: "บังคับออฟไลน์", 
queRenJiangGaiKe: "คุณแน่ใจหรือไม่ว่าจะบังคับบริการลูกค้านี้ให้ออฟไลน์", 
    tuiChuPaiDui: '退出排队',
tuiChuPaiDui: "ออกจากคิว", 
jinRuHuiHua: "ออกจากบทสนทนา", 
    paiDuiJieRu: '排队接入',
    ziDongJieRu: '自动接入',
    zongPaiDuiShiChang: '总排队时长',
zongPaiDuiShiChang: "ระยะเวลาการเข้าคิว", 
    huiHuaShu: '会话数',
    zaiXianKeFu: '在线客服',
    caoZuo: '操作',
    pingJiaLu: '评价率',
pingJiaLu: "อัตราการประเมิน", 
    zongJieLu: '总结率',
zongJieLu: "อัตราผลสรุป", 
    zhuangtaiShiChang2:'登录时长 \n 当前状态持续时长',
    jiedaiRenshuShangXian:'接待人数 \n 接待上限',

    
liKaiShiChang: "ระยะเวลาที่ออก", 
    keFuFenZu: '客服分组',
    mangLu: '忙碌',
    zaiXian: '在线',
    liKai: '离开',
    keFuZhangHuMing: '客服账户名/昵称',
    sZiDongShuaXin: '30s自动刷新',
    shuaXin: '刷新',
    qingShuRuKeFu: '请输入客服代理',
    qingShuRuKeFu2: '请输入客服账号',
qingShuRuKeFu2: "กรุณากรอกบัญชีบริการลูกค้า", 
    quanBu: '全部',
    qingXuanZeZaiXian: '请选择在线状态',
qingXuanZeZaiXian: "กรุณาเลือกสถานะออนไลน์", 
    quanBuKeFuZu: '全部客服组',
    dangQianZaiXianJie: '\n      当前在线接待概况\n    ',
dangQianZaiXianJie: "สถานการณ์การรับลูกค้าปัจุจบัน", 
    chaXun: '查询',
    jinRiHuiHuaGai: '今日会话概况',
jinRiHuiHuaGai: "สถานการณ์บทสนทนาของวันนี้", 
shiShiShuJu: "ข้อมูลเรียลไทม์", 
  },
};
