export default {
  index: {
xiTongNeiZhi: "ระบบในตัว", 
xiTongNeiZhi: "ระบบในตัว", 
canShuJianMing: "ชื่อคีย์พารามิเตอร์", 
canShuMingCheng: "ชื่อพารามิเตอร์", 
canShuJianZhiBu: "ค่าคีย์พารามิเตอร์ ห้ามเว้นว่าง", 
canShuJianMingBu: "ชื่อคีย์พารามิเตอร์ ห้ามเว้นว่าง", 
canShuMingChengBu: "ชื่อพารามิเตอร์ ห้ามเว้นว่าง", 
    xiTongCanShuPei: '系统参数配置',
xiTongCanShuPei: "การกำหนดค่าระบบพารามิเตอร์", 
    chuangJianShiJian: '创建时间',
    canShuJianZhi: '参数键值',
canShuJianZhi: "ชื่อคีย์พารามิเตอร์", 
canShuZhuJian: "คีย์หลักของพารามิเตอร์", 
    yongHuMiMa: '用户密码',
    yongHuMing: '用户名',
yongHuMing: "ชื่อผู้ใช้", 
shuRuCanShuJian: "กรอกชื่อคีย์พารามิเตอร์", 
shuRuCanShuMing: "กรอกชื่อพารามิเตอร์", 
  },
};
