export default {
  publicEdit: {
    shanChuNeiRong: "ลบเนื้อหา", 
    xinZengChengGong: "เพิ่มเรียบร้อยแล้ว!", 
    bianJiGongGongKu: "แก้ไขเนื้อหาคลังข้อมูลสาธารณะ", 
    tianJiaGongGongKu: "เพิ่มเนื้อหาคลังข้อมูลสาธารณะ", 
    paiXuZhiBiXu: "ค่าการเรียงลำดับต้องเป็นจำนวนเต็มที่มากกว่า 0 และไม่เกิน 8 ตัว", 
    qingShuRuPaiXu: "กรุณากรอกค่าการเรียงลำดับ", 
    qingShuRuGongGong: "กรุณาใส่เนื้อหาของคลังข้อมูลสาธารณะ", 
    gongGongKuNeiRong: "รายละเอียดเนื้อหาของคลังข้อมูลสาธารณะ", 
    neiRongPaiXuI: "ไอดี การจัดเรียงเนื้อหา", 
    gongGongKuNeiRong2: "เนื้อหาคลังข้อมูลสาธารณะ", 
    shuRuGongGongKu: "ป้อนเนื้อหาคลังข้อมูลสาธารณะเพื่อค้นหา", 
    dianJiBiaoQianCha: "คลิกที่แท็กเพื่อดูรายละเอียด", 
    gongGongKuNeiRong3: "ค่าการเรียงลำดับเนื้อหาคลังข้อมูลสาธารณะ", 
    suoShuBiaoQian: "แท็กที่เกี่ยวข้อง", 
    xinZeng: "เพิ่มใหม่", 
  },
  publicIndex: {
    qingXianShanChuNei: "กรุณาลบเนื้อหาออกก่อน", 
    ninQueDingShanChu: "คุณแน่ใจหรือไม่ที่จะลบบันทึกของ [{val3}] ที่เชื่อมโยงกับ [{val1} (ID{val2})]", 
    shanChuBiaoQian: "ลบแท็ก", 
    gongGongKuXL: "คลังข้อมูลสาธารณะ.xlsx", 
    shangChuanWenJianDa: "ขนาดไฟล์ที่อัพโหลดต้องไม่เกิน 100MB!", 
    yiCiZhiYunXu: "อนุญาตให้นำเข้าไฟล์ได้ครั้งละหนึ่งไฟล์เท่านั้น!", 
    daoRuChengGong: "นำเข้าเรียบร้อยแล้ว", 
    qingXianXuanZeWen: "กรุณาเลือกไฟล์ก่อน!", 
    changDuZaiDaoGe: "ความยาวอยู่ระหว่าง 1 ถึง 20 ตัวอักษร", 
    qingShuRuBiaoQian: "กรุณากรอกชื่อแท็ก", 
    qingShuRuBiaoQian2: "โปรดกรอกค่าการจัดเรียงแท็ก", 
    gongGongKuBiaoQian: "แท็กคลังข้อมูลสาธารณะ", 
    daoRu: "นำเข้า", 
    dianJiDaoRuHou:
      '点击“导入”后，系统将自动执行，请确认文件是否正确，确认后请点击导入。',
    yiCiZhiYunXu2: "อนุญาตให้นำเข้าไฟล์ได้ครั้งละหนึ่งไฟล์เท่านั้น!", 
    dianJiXuanZeWen: "คลิกเพื่อเลือกไฟล์", 
    jiangWenJianTuoDao: "ลากและวางไฟล์ที่นี่ หรือ", 
    daoRuWenJian: "นำเข้าไฟล์", 
    biaoQianPaiXuI: "ไอดี การจัดเรียงเนื้อหา", 
    daoChuShuJu: "ส่งออกข้อมูล", 
    daoRuShuJu: "นำเข้าข้อมูล", 
    shuRuGongGongKu: "ป้อนเนื้อหาคลังข้อมูลสาธารณะเพื่อค้นหา", 
    quanBuBiaoQian: "แท็กทั้งหมด", 
  },
};
