export default {
  publicEdit: {
    shanChuNeiRong: '删除内容',
    xinZengChengGong: '新增成功！',
    bianJiGongGongKu: '编辑公共库内容',
    tianJiaGongGongKu: '添加公共库内容',
    paiXuZhiBiXu: '排序值必须是大于0的整数且不能超过8位',
    qingShuRuPaiXu: '请输入排序值',
    qingShuRuGongGong: '请输入公共库内容',
    gongGongKuNeiRong: '公共库内容详情',
    neiRongPaiXuI: '内容排序ID',
    gongGongKuNeiRong2: '公共库内容',
    shuRuGongGongKu: '输入公共库内容查询',
    dianJiBiaoQianCha: '点击标签查看详情',
    gongGongKuNeiRong3: '公共库内容排序值',
    suoShuBiaoQian: '所属标签',
    xinZeng: '新增',
  },
  publicIndex: {
    qingXianShanChuNei: '请先删除内容',
    ninQueDingShanChu: '您确定删除【{val1}】该标签',
    shanChuBiaoQian: '删除标签',
    gongGongKuXL: '公共库.xlsx',
    shangChuanWenJianDa: '上传文件大小不能超过 10MB!',
    yiCiZhiYunXu: '一次只允许导入一个文件哦！',
    daoRuChengGong: '导入成功',
    qingXianXuanZeWen: '请先选择文件！',
    changDuZaiDaoGe: '长度在 1 到 20 个字符',
    qingShuRuBiaoQian: '请输入标签名称',
    qingShuRuBiaoQian2: '请输入标签排序值',
    gongGongKuBiaoQian: '公共库标签',
    daoRu: '导入',
    dianJiDaoRuHou:
      '点击“导入”后，系统将自动执行，请确认文件是否正确，确认后请点击导入。',
    yiCiZhiYunXu2: '一次只允许导入一个文件',
    dianJiXuanZeWen: '点击选择文件',
    jiangWenJianTuoDao: '将文件拖到此处，或',
    daoRuWenJian: '导入文件',
    biaoQianPaiXuI: '标签排序ID',
    daoChuShuJu: '导出数据',
    daoRuShuJu: '导入数据',
    shuRuGongGongKu: '输入公共库标签名称搜索',
    quanBuBiaoQian: '全部标签',

  },
};
