export default {
  index: {
    qingXuanZe: '请选择',
    qingShuRuMingCheng: '请输入名称',
    qingXuanZeJueSe: '请选择角色级别',
    zhiJianBaoBiao: '质检报表',
    quanBu: '全部',
    zhiJianBuHeGe: '质检不合格率/数',
    zhiJianJiGeLu: '质检及格率/数',
    zhiJianLiangHaoLu: '质检良好率/数',
    zhiJianYouXiuLu: '质检优秀率/数',
    zhiJianHeGeLu: '质检合格率/数',
    zhiJianPingJunFen: '质检平均分',
    zhiJianLu: '质检率',
    zhiJianShu: '质检数',
    keFuZongHuiHua: '客服总会话数',
    keFuFenZu: '客服分组',
    keFu: '客服',
    zhongZhi: '重置',
    suoYouKeFu: '所有客服',
    quanBuKeFuZu: '全部客服组',
    zhiJianHuiZong: '质检汇总',
    zhiJianJieGuo: '质检结果',
  },
  qualitySummary: {
    keHuChaPingYuan: '客户差评原因',
    zhiJianBiaoQian: '质检标签',
    huiHuaShu: '会话数',

  },
};
