export default {
  index: {
nullqingXuanZe: "โปรดเลือก", 
qingShuRuMingCheng: "กรุณากรอกชื่อ", 
qingXuanZeJueSe: "โปรดเลือกระดับบทบาท", 
zhiJianBaoBiao: "รายงานการตรวจสอบคุณภาพ", 
quanBu: "ทั้งหมด", 
zhiJianBuHeGe: "อัตรา/จำนวนการตรวจสอบคุณภาพที่ไม่ผ่าน", 
zhiJianJiGeLu: "อัตรา/จำนวนการตรวจสอบคุณภาพที่ผ่าน", 
zhiJianLiangHaoLu: "อัตรา/จำนวนการตรวจสอบคุณภาพที่ดี", 
zhiJianYouXiuLu: "อัตรา/จำนวนการตรวจสอบคุณภาพที่ยอดเยี่ยม", 
zhiJianHeGeLu: "อัตรา/จำนวนการตรวจสอบคุณภาพที่ผ่าน", 
zhiJianPingJunFen: "คะแนนเฉลี่ยของการตรวจสอบคุณภาพ", 
zhiJianLu: "อัตราการตรวจสอบคุณภาพ", 
zhiJianShu: "จำนวนการตรวจสอบคุณภาพ", 
keFuZongHuiHua: "จำนวนบทสนทนาฝ่ายบริการลูกค้าทั้งหมด", 
keFuFenZu: "แบ่งกลุ่มบริการลูกค้า", 
keFu: "ฝ่ายบริการลูกค้า", 
zhongZhi: "รีเซ็ต", 
suoYouKeFu: "บริการลูกค้าทั้งหมด", 
quanBuKeFuZu: "กลุ่มบริการลูกค้าทั้งหมด", 
zhiJianHuiZong: "สรุปผลการตรวจสอบคุณภาพ", 
  },
  qualitySummary: {
zhiJianJieGuo: "ผลการตรวจสอบคุณภาพ", 
keHuChaPingYuan: "เหตุผลสำหรับแบบประเมินที่ไม่ดีจากลูกค้า:", 
zhiJianBiaoQian: "แท็กการตรวจสอบคุณภาพ", 
    huiHuaShu: '会话数',
  },
};
