export default {
  index: {
    puTongKeHu: '普通客户',
    xingMing: '姓名',
    keHuZhangHuMing: '客户账户名',
    gengXinRiQi: '更新日期',
    chuangJianRiQi: '创建日期',
    buYunXuShuRu: '不允许输入非法字符',
    qingShuRuLaHei: '请输入拉黑原因',
    keHuLieBiao: '客户列表',
    zhaKan: '查看',
    chongZhiMa: '充值码',
chongZhiMa: "รหัสเติมเงิน", 
    paiDuiShiChang: '排队时长',
    kaiShiPaiDuiShi: '开始排队时间',
    jiNengZuMingCheng: '技能组名称',
    huanXingChangJingMing: '唤醒场景名称',
    keHuFenZu: '客户分组',
    vIPJiBie: 'VIP级别',
    keHuDengJi: '客户等级',
    keHuMingCheng: '客户名称',
keHuMingCheng: "ชื่อลูกค้า", 
keHuID: "ไอดี ลูกค้า", 
    quanBu: '全部',
    qingXuanZeVI: '请选择VIP级别',
qingXuanZeVI: "กรุณาเลือกระดับ VIP", 
suoYouKeHuDeng: "ลูกค้าทุกระดับ", 
    suoYouJiNengZu: '所有技能组',
    puTongKeHu: '普通客户',
    xingMing: '姓名',
    keHuZhangHuMing: '客户账户名',
    gengXinRiQi: '更新日期',
    chuangJianRiQi: '创建日期',
    buYunXuShuRu: '不允许输入非法字符',
    qingShuRuLaHei: '请输入拉黑原因',
    keHuLieBiao: '客户列表',
    zhaKan: '查看',
    chongZhiMa: '充值码',
chongZhiMa: "รหัสเติมเงิน", 
    paiDuiShiChang: '排队时长',
    kaiShiPaiDuiShi: '开始排队时间',
    jiNengZuMingCheng: '技能组名称',
    huanXingChangJingMing: '唤醒场景名称',
    keHuFenZu: '客户分组',
    vIPJiBie: 'VIP级别',
    keHuDengJi: '客户等级',
    keHuMingCheng: '客户名称',
keHuMingCheng: "ชื่อลูกค้า", 
keHuID: "ไอดี ลูกค้า", 
    qingXuanZeVI: '请选择VIP级别',
qingXuanZeVI: "กรุณาเลือกระดับ VIP", 
suoYouKeHuDeng: "ลูกค้าทุกระดับ", 
    suoYouJiNengZu: '所有技能组'
  },
  look: {
    jiaZaiZhong: '加载中',
    tuPian: '图片：',
    paiDuiShiChang: '排队时长:',
    kaiShiPaiDuiShi: '开始排队时间:',
    jiNengZuMingCheng: '技能组名称:',
    huanXingChangJingMing: '唤醒场景名称:',
    vIPJiBie: 'VIP级别:',
    keHuDengJi: '客户等级:',
    keHuMingChengI: '客户名称&ID:',
keHuMingChengI: "ชื่อและไอดี ลูกค้า:", 
keHuPaiDuiXin: "ข้อมูลคิวลูกค้า", 
  }
}
