export default {
  BarChart: {
nullpaiDuiTongJi: "สถิติการเข้าคิว", 
    zaiCiXuanRan: '再次渲染',
  },
  LineChart: {
zaiCiXuanRan: "แสดงผลอีกครั้ง", 
paiDuiJieRu: "ต่อแถวเข้าคิว", 
  },
  index: {
paiDuiShu: "จำนวนคิว", 
pingJunPaiDuiShi: "ระยะเวลาคิวเฉลี่ย", 
paiDuiLiKaiShu: "อัตรา/จำนวนคิวที่จะออก", 
paiDuiJinRuHui: "อัตรา/จำนวนที่เข้าคิวบทสนทนา", 
zongHuiHuaShu: "จำนวนบทสนทนาทั้งหมด", 
paiDuiTongJiShi: "สถิติเวลาคิว", 
paiDuiBaoBiao: "รายงานการเข้าคิว", 
    paiDuiZhong: '排队中',
paiDuiZhong: "อยู่ในคิว", 
tongJiWeiDu: "มิติทางสถิติ", 
paiDuiJieGuo: "ผลการจัดคิว", 
paiDuiShiChang: "ระยะเวลาของคิว", 
paiDuiKaiShiShi: "เวลาที่เริ่มเข้าคิว", 
ziXunLaiYuan: "ที่มาสอบถาม", 
keHuZu: "กลุ่มลูกค้า", 
keHu: "ลูกค้า", 
qingShuRuKeHu: "กรุณากรอกบัญชีลูกค้า", 
paiDuiJiLu: "บันทึกคิว", 
  },
};
