export default {
  BarChart: {
paiDuiTongJi: "สถิติการเข้าคิว", 
paiDuiTongJi: "สถิติการเข้าคิว", 
    zaiCiXuanRan: '再次渲染',
  },
  LineChart: {
zaiCiXuanRan: "แสดงผลอีกครั้ง", 
    paiDuiShu: '排队数',
  },
  index: {
paiDuiShu: "จำนวนคิว", 
    paiDuiLiKaiShu: '排队离开数/率',
paiDuiLiKaiShu: "อัตรา/จำนวนคิวที่จะออก", 
paiDuiJinRuHui: "อัตรา/จำนวนที่เข้าคิวบทสนทนา", 
zongHuiHuaShu: "จำนวนบทสนทนาทั้งหมด", 
paiDuiTongJiShi: "สถิติเวลาคิว", 
paiDuiBaoBiao: "รายงานการเข้าคิว", 
    paiDuiZhong: '排队中',
paiDuiZhong: "อยู่ในคิว", 
    paiDuiJieGuo: '排队结果',
paiDuiJieGuo: "ผลการจัดคิว", 
    paiDuiKaiShiShi: '排队开始时间',
paiDuiKaiShiShi: "เวลาที่เริ่มเข้าคิว", 
ziXunLaiYuan: "ที่มาสอบถาม", 
    keHu: '客户',
    qingShuRuKeHu: '请输入客户账户',
    paiDuiJiLu: '排队记录',
paiDuiJiLu: "บันทึกคิว", 
  },
};
