export default {
  rechargeIndex: {
        qingShuRu: '请输入',
    qingShuRu: "กรุณากรอก", 
    keHuNiCheng: "ชื่อเล่นลูกค้า", 
    keHuZhangHuMing: "ชื่อบัญชีลูกค้า", 
    keFuNiCheng: "ชื่อเล่นฝ่ายบริการลูกค้า", 
    keFuZhangHuMing: "ชื่อบัญชีฝ่ายบริการลูกค้า", 
    dingDanJiLuLie: "รายการบันทึก", 
    shouKuanErWeiMa: "คิวอาร์โค้ดรับเงิน:", 
    shuZiHuoBiDi: "ที่อยู่สกุลเงินดิจิทัล：", 
    shuZiHuoBiZhuan: "โปรโตคอลการโอนสกุลเงินดิจิทัล：", 
    shuZiHuoBiHui: "อัตราแลกเปลี่ยนสกุลเงินดิจิทัล：", 
    shuZiHuoBiShu: "จำนวนสกุลเงินดิจิทัล：", 
    shuZiHuoBiBi: "สกุลเงินดิจิทัล：", 
    chiKaRenXingMing: "ชื่อผู้ถือบัตร：", 
    yinHangKaHao: "หมายเลขบัตรธนาคาร：", 
        weiZhi: '未知（',
    weiZhi: "ไม่รู้", 
    yinHangMingCheng: "ชื่อธนาคาร", 
    chongZhiJinE: "จำนวนยอดฝาก", 
    chongZhiURL: "URL ฝากเงิน", 
    chongZhiFangShi: "วิธีการ ฝากเงิน", 
    pingTaiDingDanHao: "หมายเลขรายการบนแพลตฟอร์ม", 
    dingDanChongZhiXin: "ข้อมูลรายการฝากเงิน", 
    keHuZhangHuNi: "บัญชีลูกค้า/ชื่อเล่น.", 
    keFuZhangHuNi: "บัญชีฝ่ายบริการลูกค้า/ชื่อเล่น", 
    huiHuaID: "ไอดี บทสนทนา", 
    xiaDanHuiHuaXin: "ข้อมูลบทสนทนรายการ", 
    xiaDanJiLuI: "ไอดี บันทึกรายการ", 
    chongZhiXinXi: "ข้อมูลการฝากเงิน", 
    pingTaiDingDanZhuang: "สถานะรายการบนแพลตฟอร์ม", 
    shiJian: "เวลา", 
    chuFaShiJian: "เหตุการณ์เริ่มต้น", 
    xuHao: "หมายเลขซีเรียล", 
    dingDanGengXinXin: "อัปเดตข้อมูลรายการ", 
    dangQianYeJinE: "จำนวนยอดเงินหน้าปัจจุบัน:", 
    zongJinE: "จำนวนเงินทั้งหมด:", 
    dingDanGengXinJi: "อัปเดตรายการบันทึก", 
    caoZuo: "การดำเนินการ", 
        chuangJianShiJian: '创建时间',
    chuangJianShiJian: "เวลาที่สร้าง", 
    chongZhiJinE2: "จำนวนยอดฝาก", 
    chongZhiFangShi2: "ช่องทางการฝาก", 
    pingTaiDingDanHao2: "หมายเลขรายการบนแพลตฟอร์ม", 
    xiaDanJiLuI2: "ไอดี บันทึกรายการ", 
    keFuZhangHuNi2: "บัญชีฝ่ายบริการลูกค้า/ชื่อเล่น", 
    keHuZhangHuNi2: "บัญชีฝ่ายบริการลูกค้า/ชื่อเล่น", 
    huiHuaID2: "ไอดี บทสนทนา", 
        chaXun: '查询',
    chaXun: "ตรวจสอบ", 
    chongZhiJinEFan: "ขอบเขตจำนวนเงินฝาก/หยวน", 
    qingShuRuXiaDan: "โปรดป้อนไอดี บันทึกรายการ", 
    qingShuRuPingTai: "โปรดป้อนหมายเลขรายการบนแพลตฟอร์ม", 
        qingShuRuSouSuo: '请输入搜索内容',
  },
};
