export default {
  rechargeIndex: {
    zhiNengShuRuDa: '只能输入大于0的正数',
    qingShuRu: '请输入',
qingShuRu: "กรุณากรอก", 
    keHuZhangHuMing: '客户账户名',
    keFuNiCheng: '客服昵称',
    keFuZhangHuMing: '客服账户名',
    dingDanJiLuLie: '订单记录列表',
dingDanJiLuLie: "รายการบันทึก", 
shouKuanErWeiMa: "คิวอาร์โค้ดรับเงิน:", 
shuZiHuoBiDi: "ที่อยู่สกุลเงินดิจิทัล：", 
shuZiHuoBiZhuan: "โปรโตคอลการโอนสกุลเงินดิจิทัล：", 
shuZiHuoBiHui: "อัตราแลกเปลี่ยนสกุลเงินดิจิทัล：", 
shuZiHuoBiShu: "จำนวนสกุลเงินดิจิทัล：", 
shuZiHuoBiBi: "สกุลเงินดิจิทัล：", 
chiKaRenXingMing: "ชื่อผู้ถือบัตร：", 
yinHangKaHao: "หมายเลขบัตรธนาคาร：", 
    weiZhi: '未知（',
    yinHangMingCheng: '银行名称：',
yinHangMingCheng: "ชื่อธนาคาร", 
    chongZhiURL: '充值url：',
chongZhiURL: "URL ฝากเงิน", 
chongZhiFangShi: "วิธีการ ฝากเงิน", 
pingTaiDingDanHao: "หมายเลขรายการบนแพลตฟอร์ม", 
dingDanChongZhiXin: "ข้อมูลรายการฝากเงิน", 
    keFuZhangHuNi: '客服账户/昵称：',
    huiHuaID: '会话ID：',
    xiaDanHuiHuaXin: '下单会话信息',
xiaDanHuiHuaXin: "ข้อมูลบทสนทนรายการ", 
xiaDanJiLuI: "ไอดี บันทึกรายการ", 
chongZhiXinXi: "ข้อมูลการฝากเงิน", 
pingTaiDingDanZhuang: "สถานะรายการบนแพลตฟอร์ม", 
    chuFaShiJian: '触发事件',
chuFaShiJian: "เหตุการณ์เริ่มต้น", 
    dingDanGengXinXin: '订单更新信息',
dingDanGengXinXin: "อัปเดตข้อมูลรายการ", 
dangQianYeJinE: "จำนวนยอดเงินหน้าปัจจุบัน:", 
zongJinE: "จำนวนเงินทั้งหมด:", 
dingDanGengXinJi: "อัปเดตรายการบันทึก", 
    gengXinShiJian: '更新时间',
    chuangJianShiJian: '创建时间',
chuangJianShiJian: "เวลาที่สร้าง", 
chongZhiJinE2: "จำนวนยอดฝาก", 
chongZhiFangShi2: "ช่องทางการฝาก", 
pingTaiDingDanHao2: "หมายเลขรายการบนแพลตฟอร์ม", 
xiaDanJiLuI2: "ไอดี บันทึกรายการ", 
keFuZhangHuNi2: "บัญชีฝ่ายบริการลูกค้า/ชื่อเล่น", 
keHuZhangHuNi2: "บัญชีฝ่ายบริการลูกค้า/ชื่อเล่น", 
huiHuaID2: "ไอดี บทสนทนา", 
    chaXun: '查询',
chaXun: "ตรวจสอบ", 
chongZhiJinEFan: "ขอบเขตจำนวนเงินฝาก/หยวน", 
qingShuRuXiaDan: "โปรดป้อนไอดี บันทึกรายการ", 
qingShuRuPingTai: "โปรดป้อนหมายเลขรายการบนแพลตฟอร์ม", 

  },
};
