export default {
    zuiDuoZhiNengTian: "คุณสามารถเพิ่มการแจ้งเตือนแบบกราฟิกได้สูงสุด 3 รายการเท่านั้น!", 
    gaiBiaoQianYiTian: "แท็กนี้ถูกเพิ่มแล้ว!", 
    qingDianJiBianJi: "โปรดคลิกแก้ไขเพื่อลบและบันทึก!", 
    guanBiChengGong: "ปิดสำเร็จ", 
    kaiQiChengGong: "เปิดสำเร็จ", 
    sheZhiChengGong: "ตั้งค่าสำเร็จ", 
  chaoGuoGaiShiJian:
    '超过该时间客服与客户未进行会话，系统将主动结束该会话;不可少于5分钟。',
    huiHuaShiXiaoShi: "เวลาหมดอายุของบทสนทนา", 
  chaoGuoGaiShiJian2:
    '超过该时间客服与客户未进行会话，客服可在工作台主动关闭该会话;不可少于3分钟',
    keFuZhuDongGuan: "ฝ่ายบริการลูกค้าปิดบทสนทนาเอง", 
    huiHuaJieShuShe: "ตั้งค่าสิ้นสุดบทสนทนา", 
    qingShuRuZhiJian: "โปรดกรอกผู้ตรวจสอบคุณภาพ", 
    qingShuRuBuXiao: "กรุณาป้อนจำนวนเต็มไม่น้อยกว่า 5", 
    qingShuRuBuXiao2: "กรุณาป้อนจำนวนเต็มไม่น้อยกว่า 3", 
    fuWuZongJiePei: "การกำหนดค่าผลสรุปการบริการ", 
    xingShuoMing: "คำอธิบายดาว:", 
    xing: "1 ดาว", 
    xing2: "2 ดาว", 
    xingJiPingJiaShe: "การตั้งค่าการประเมินระดับดาว", 
    quanBuShanChu: "ลบทั้งหมด", 
    yiTianJiaBiaoQian: "เพิ่มแท็กแล้ว: (", 
    zuiDuoShuRuGe: "ป้อนได้สูงสุด 8 คำ (รวมอักขระ)", 
    tianJiaPingJiaBiao: "เพิ่มคลังแท็กแบบประเมิน", 
  kaiQiCiGongNeng:
    ' 开启此功能后，客户端在评价会话的时候可以对本次会话是否已解决进行选择。',
    keFuShiFouJie: "ฝ่ายบริการลูกค้าได้แก้ไขปัญหาแล้วหรือไม่", 
    manYiDuPingJia: "การตั้งค่าการประเมินความพึงพอใจ", 
    manYiDuPingJia2: "การกำหนดค่าการประเมินความพึงพอใจ", 
  yongHuPaiDuiChao:
    '用户排队超过该时间仍未进入会话，系统将会自动结束该用户排队。',
    fen: "คะแนน", 
    paiDuiChaoShiShi: "หมดเวลาของคิว", 
    paiDuiJieShuShe: "การตั้งค่าสิ้นสุดคิว", 
  serverConfig: {
    xinZengChengGong: "เพิ่มเรียบร้อยแล้ว!", 
    bianJiChengGong: "แก้ไขสำเร็จ!", 
    qingXianShanChuYe: "โปรดลบประเภทธุรกิจออกก่อน", 
    ninQueDingShanChu: "คุณแน่ใจหรือไม่ที่จะลบบันทึกของ [{val3}] ที่เชื่อมโยงกับ [{val1} (ID{val2})]", 
    shanChuYeWuMing: "ลบชื่อธุรกิจ", 
    changDuZaiDaoGe: "ความยาวอยู่ระหว่าง 1 ถึง 20 ตัวอักษร", 
    qingShuRuYeWu: "กรุณากรอกชื่อธุรกิจ", 
    paiXuZhiBiXu: "ค่าการเรียงลำดับต้องเป็นจำนวนเต็มที่มากกว่า 0 และไม่เกิน 8 ตัว", 
    qingShuRuYeWu2: "โปรดป้อนค่าการจัดเรียงชื่อธุรกิจ", 
    fuWuZongJiePei: "การกำหนดค่าผลสรุปการบริการ", 
    chuangJianRen: "สร้างโดย", 
    yeWuMingCheng: "ชื่อธุรกิจ", 
    yeWuPaiXuI: "ไอดี การจัดเรียงธุรกิจ", 
    xinZeng: "เพิ่มใหม่", 
    quanBu: "ทั้งหมด", 
    yeWuMingChengPai: "ไอดี การจัดเรียงลำดับชื่อธุรกิจ", 
  },
  serverType: {
    shanChuNeiRong: "ลบเนื้อหา", 
    bianJiYeWuLei: "แก้ไขประเภทธุรกิจ", 
    tianJiaYeWuLei: "เพิ่มประเภทธุรกิจ", 
    qingShuRuPaiXu: "กรุณากรอกค่าการเรียงลำดับ", 
    qingShuRuYeWu: "กรุณากรอกชื่อธุรกิจ", 
    yeWuLeiXingXiang: "รายละเอียดประเภทธุรกิจ", 
    yeWuLeiXingPai: "ไอดี การจัดเรียงประเภทธุรกิจ", 
    yeWuLeiXingMing: "ชื่อประเภทธุรกิจ", 
    dianJiYeWuMing: "คลิกที่ชื่อธุรกิจเพื่อดู", 
    yeWuLeiXing: "ประเภทธุรกิจ", 
  },
};
