export default {
    zuiDuoZhiNengTian: "จำนวนแท็กสูงสุดที่คุณสามารถเพิ่มได้คือ 24!", 
    gaiBiaoQianYiTian: "แท็กนี้ถูกเพิ่มแล้ว!", 
    qingDianJiBianJi: "โปรดคลิกแก้ไขเพื่อลบและบันทึก!", 
    guanBiChengGong: "ปิดสำเร็จ", 
    kaiQiChengGong: "เปิดสำเร็จ", 
  chaoGuoGaiShiJian:
    '超过该时间客服与客户未进行会话，系统将主动结束该会话;不可少于5分钟。',
    sheZhiChengGong: "ตั้งค่าสำเร็จ", 
  chaoGuoGaiShiJian2:
    '超过该时间客服与客户未进行会话，客服可在工作台主动关闭该会话;不可少于3分钟',
    huiHuaShiXiaoShi: "เวลาหมดอายุของบทสนทนา", 
    keFuZhuDongGuan: "ฝ่ายบริการลูกค้าปิดบทสนทนาเอง", 
    huiHuaJieShuShe: "ตั้งค่าสิ้นสุดบทสนทนา", 
    qingShuRuZhiJian: "โปรดป้อนจำนวนเต็มระหว่าง 10 ถึง 120", 
    qingShuRuBuXiao: "กรุณาป้อนจำนวนเต็มไม่น้อยกว่า 5", 
    qingShuRuBuXiao2: "กรุณาป้อนจำนวนเต็มไม่น้อยกว่า 3", 
    fuWuZongJiePei: "การกำหนดค่าผลสรุปการบริการ", 
    xingShuoMing: "คำอธิบายดาว:", 
      xing2: '星',
    xing2: "ดาว", 
    xingJiPingJiaShe: "การตั้งค่าการประเมินระดับดาว", 
    quanBuShanChu: "ลบทั้งหมด", 
    yiTianJiaBiaoQian: "เพิ่มแท็กแล้ว: (", 
    zuiDuoShuRuGe: "ป้อนได้สูงสุด 8 คำ (รวมอักขระ)", 
  kaiQiCiGongNeng:
    ' 开启此功能后，客户端在评价会话的时候可以对本次会话是否已解决进行选择。',
      keFuShiFouJie: '客服是否解决问题：',
    keFuShiFouJie: "ฝ่ายบริการลูกค้าได้แก้ไขปัญหาแล้วหรือไม่", 
    manYiDuPingJia: "การตั้งค่าการประเมินความพึงพอใจ", 
  yongHuPaiDuiChao:
    '用户排队超过该时间仍未进入会话，系统将会自动结束该用户排队。',
    manYiDuPingJia2: "การกำหนดค่าการประเมินความพึงพอใจ", 
    fen: "คะแนน", 
    paiDuiChaoShiShi: "หมดเวลาของคิว", 
  serverConfig: {
    paiDuiJieShuShe: "การตั้งค่าสิ้นสุดคิว", 
    xinZengChengGong: "เพิ่มใหม่สำเร็จ!", 
    bianJiChengGong: "แก้ไขสำเร็จ!", 
    qingXianShanChuYe: "โปรดลบประเภทธุรกิจออกก่อน", 
    ninQueDingShanChu: "คุณแน่ใจหรือที่จะลบแท็กนี้ [{val1}]?", 
    shanChuYeWuMing: "ลบชื่อธุรกิจ", 
    changDuZaiDaoGe: "ความยาวตั้งแต่ 1 ถึง 20 ตัวอักษร", 
    qingShuRuYeWu: "กรุณากรอกชื่อธุรกิจ", 
    paiXuZhiBiXu: "ค่าการเรียงลำดับต้องเป็นจำนวนเต็มที่มากกว่า 0", 
    qingShuRuYeWu2: "โปรดป้อนค่าการจัดเรียงชื่อธุรกิจ", 
    fuWuZongJiePei: "รายการการกำหนดค่าผลสรุปการบริการ", 
    chuangJianRen: "สร้างโดย", 
    yeWuMingCheng: "ชื่อธุรกิจ", 
    yeWuPaiXuI: "ไอดี การจัดเรียงธุรกิจ", 
    xinZeng: "เพิ่มใหม่", 
    quanBu: "ทั้งหมด", 
  },
  serverType: {
    yeWuMingChengPai: "ไอดี การจัดเรียงลำดับชื่อธุรกิจ", 
    shanChuNeiRong: "ลบเนื้อหา", 
    bianJiYeWuLei: "แก้ไขประเภทธุรกิจ", 
    tianJiaYeWuLei: "เพิ่มประเภทธุรกิจ", 
    qingShuRuPaiXu: "กรุณากรอกค่าการเรียงลำดับ", 
    qingShuRuYeWu: "กรุณากรอกชื่อประเภทธุรกิจ", 
    yeWuLeiXingXiang: "รายละเอียดประเภทธุรกิจ", 
    yeWuLeiXingPai: "ไอดี การจัดเรียงประเภทธุรกิจ", 
    yeWuLeiXingMing: "ชื่อประเภทธุรกิจ", 
    dianJiYeWuMing: "คลิกที่ชื่อธุรกิจเพื่อดู", 
        yeWuLeiXing: '业务类型',
  },
};
