export default {
  zuiDuoZhiNengTian: '最多只能添加24个标签哦！',
  gaiBiaoQianYiTian: '该标签已添加！',
gaiBiaoQianYiTian: "แท็กนี้ถูกเพิ่มแล้ว!", 
qingDianJiBianJi: "โปรดคลิกแก้ไขเพื่อลบและบันทึก!", 
guanBiChengGong: "ปิดสำเร็จ", 
  sheZhiChengGong: '设置成功',
  chaoGuoGaiShiJian:
    '超过该时间客服与客户未进行会话，系统将主动结束该会话;不可少于5分钟。',
sheZhiChengGong: "ตั้งค่าสำเร็จ", 
  chaoGuoGaiShiJian2:
    '超过该时间客服与客户未进行会话，客服可在工作台主动关闭该会话;不可少于3分钟',
huiHuaShiXiaoShi: "เวลาหมดอายุของบทสนทนา", 
keFuZhuDongGuan: "ฝ่ายบริการลูกค้าปิดบทสนทนาเอง", 
huiHuaJieShuShe: "ตั้งค่าสิ้นสุดบทสนทนา", 
  qingShuRuBuXiao: '请输入不小于5的整数',
qingShuRuBuXiao: "กรุณาป้อนจำนวนเต็มไม่น้อยกว่า 5", 
qingShuRuBuXiao2: "กรุณาป้อนจำนวนเต็มไม่น้อยกว่า 3", 
  xingShuoMing: '星说明:',
xingShuoMing: "คำอธิบายดาว:", 
  xing2: '星',
  xingJiPingJiaShe: '星级评价设置',
xingJiPingJiaShe: "การตั้งค่าการประเมินระดับดาว", 
quanBuShanChu: "ลบทั้งหมด", 
yiTianJiaBiaoQian: "เพิ่มแท็กแล้ว: (", 
zuiDuoShuRuGe: "ป้อนได้สูงสุด 8 คำ (รวมอักขระ)", 
  kaiQiCiGongNeng:
    ' 开启此功能后，客户端在评价会话的时候可以对本次会话是否已解决进行选择。',
  keFuShiFouJie: '客服是否解决问题：',
keFuShiFouJie: "ฝ่ายบริการลูกค้าได้แก้ไขปัญหาแล้วหรือไม่", 
manYiDuPingJia: "การตั้งค่าการประเมินความพึงพอใจ", 
  yongHuPaiDuiChao:
    '用户排队超过该时间仍未进入会话，系统将会自动结束该用户排队。',
manYiDuPingJia2: "การกำหนดค่าการประเมินความพึงพอใจ", 
  paiDuiChaoShiShi: '排队超时时间：',
paiDuiChaoShiShi: "หมดเวลาของคิว", 
  serverConfig: {
paiDuiJieShuShe: "การตั้งค่าสิ้นสุดคิว", 
    bianJiChengGong: '编辑成功！',
    qingXianShanChuYe: '请先删除业务类型',
qingXianShanChuYe: "โปรดลบประเภทธุรกิจออกก่อน", 
    shanChuYeWuMing: '删除业务名称',
shanChuYeWuMing: "ลบชื่อธุรกิจ", 
    qingShuRuYeWu: '请输入业务名称',
    paiXuZhiBiXu: '排序值必须是大于0的整数',
    qingShuRuYeWu2: '请输入业务名称排序值',
qingShuRuYeWu2: "โปรดป้อนค่าการจัดเรียงชื่อธุรกิจ", 
    chuangJianRen: '创建人',
    yeWuMingCheng: '业务名称',
    yeWuPaiXuI: '业务排序ID',
yeWuPaiXuI: "ไอดี การจัดเรียงธุรกิจ", 
    quanBu: '全部',
    yeWuMingChengPai: '业务名称排序ID',
  },
  serverType: {
yeWuMingChengPai: "ไอดี การจัดเรียงลำดับชื่อธุรกิจ", 
    bianJiYeWuLei: '编辑业务类型',
bianJiYeWuLei: "แก้ไขประเภทธุรกิจ", 
tianJiaYeWuLei: "เพิ่มประเภทธุรกิจ", 
    qingShuRuYeWu: '请输入业务类型名称',
    yeWuLeiXingXiang: '业务类型详情',
yeWuLeiXingXiang: "รายละเอียดประเภทธุรกิจ", 
yeWuLeiXingPai: "ไอดี การจัดเรียงประเภทธุรกิจ", 
yeWuLeiXingMing: "ชื่อประเภทธุรกิจ", 
dianJiYeWuMing: "คลิกที่ชื่อธุรกิจเพื่อดู", 

  },
};
