export default {
  index: {
    qingPeiZhiGaiKe: "โปรดกำหนดค่าบริการลูกค้ากลุ่มนี้!", 
    jianTing: "กำลังฟัง 11111", 
    keFuBaoBiao: "รายงานการบริการลูกค้า", 
    qieHuan: "การสลับ", 
    ge: "/อัน", 
    xing: "/ดาว", 
    dengLuShiChang: "ระยะเวลาเข้าสู่ระบบ", 
    mangLu: "ยุ่ง", 
    zaiXianQieHuan: "การสลับออนไลน์", 
        pingJunHuiHuaShi: '平均会话时长',
        jieDaiYaLiZhi: '接待压力值',
        huiFuLu: '回复率',
        jieDaiKeHuShu: '接待客户数',
        keHuKeFuXiao: '客户/客服消息数',
    keHuKeFuXiao: "จำนวนข้อความของลูกค้า/บริการลูกค้า", 
    shiJian: "เวลา", 
    keHuPingJia: "การประเมินของลูกค้า", 
    keFuZongJie: "สรุปผลการบริการลูกค้า", 
    zanWuShuJuQing: "ไม่มีข้อมูล โปรดเลือกเกณฑ์การค้นหาเพื่อค้นหาอีกครั้ง!", 
    tongJiZhi: "ค่าทางสถิติ", 
    suoYouKeFu: "บริการลูกค้าทั้งหมด", 
    renYuan: "บุคลากร", 
    keFuRenYuan: "พนักงานบริการลูกค้า", 
        keHuPingJiaLu: '客户评价率/数',
        yaoQingPingJiaLu: '邀请评价率/数',
        keFuJieJueLu: '客服解决率/数',
        keFuZongJieLu: '客服总结率/数',
        sNeiXiangYingYing: '30s内响应应答率',
        zuiDaXiangYingShi: '最大响应时长',
        pingJunShouXiangShi: '平均首响时长',
    pingJunShouXiangShi: "ระยะเวลาเสียงกริ่งแรกเฉลี่ย", 
        zhuanChuHuiHuaShu: '转出会话数',
        huiHuaShuYouXiao: '会话数/有效数',
    huiHuaShuYouXiao: "จำนวนบทสทนา/ที่มีประสิทธภาพ", 
    mangLu2: "ยุ่ง", 
    sheZhiXianShiCan: "ตั้งค่าการแสดงผลพารามิเตอร์", 
    quanBuKeFuZhang: "บัญชีบริการลูกค้าทั้งหมด", 
    keFuTongJi: "สถิติการบริการลูกค้า", 
    suoYouKeFuBao: "รายงานการบริการลูกค้าทั้งหมด", 
  },
  moreBar: {
    danGeKeFuBao: "รายงานการบริการลูกค้ารายบุคคล", 
    ziDongJieRu: "เข้าอัตโนมัติ", 
        zhuanJieJieRu: '转接接入',
  },
};
