export default {
  index: {
null    xingMing: '姓名',
    keHuZhangHuMing: '客户账户名',
    gengXinRiQi: '更新日期',
gengXinRiQi: "วันที่อัปเดต", 
    qingShuRuLaHei: '请输入拉黑原因',
qingShuRuLaHei: "โปรดกรอกเหตุผลในการบล็อก", 
keFuHuanYingYu: "ข้อความต้อนรับการบริการลูกค้า", 
    huanYingYu: '欢迎语',
huanYingYu: "ข้อความต้อนรับ", 
keFuZhangHaoNi: "บัญชีบริการลูกค้า/ชื่อเล่น", 
    chaXun: '查询',
chaXun: "ตรวจสอบ", 
qingShuRuKeFu: "กรุณากรอกบัญชีบริการลูกค้า", 
suoYouKeFuZu: "กลุ่มบริการลูกค้าทั้งหมด", 
  },
  look: {
    bianJiChengGong: '编辑成功！',
bianJiChengGong: "แก้ไขสำเร็จ!", 
peiZhi: "การกำหนดค่า", 
    jiNengZuMingCheng: '技能组名称：',
    keFuNiCheng: '客服昵称：',
    keFuZhangHao: '客服账号：',
    huanYingYuPeiZhi: '欢迎语配置',
    huanYingYuPeiZhi: '欢迎语配置',
  },
};
