export default {
  chengGong: '成功！',
chengGong: "สำเร็จ!", 
queDing: "ยืนยัน", 
queDingSTA: "แน่ใจเกี่ยวกับ '{val1}{val2}' ไหม", 
sTATE: "{val1}ฝ่ายบริการลูกค้า", 
queRenShanChu: "ยืนยันการลบ", 
ruGuoGaiKeFu: "หากฝ่ายบริการลูกค้าออนไลน์ ระบบจะแจ้งว่าบัญชีฝ่ายบริการลูกค้าถูกปิดใช้งานและปิดโต๊ะบริการลูกค้าลูกค้า", 
qiYong: "เปิดใช้งาน", 
tingYong: "ปิดการใช้งาน", 
keFuZhangHao: "บัญชีบริการลูกค้า", 
keFuLieBiao: "รายการบริการลูกค้า", 
jieDaiShangXian: "ขีดจำกัดการรับ", 
jieSuo: "ปลดล็อค", 
bianJi: "แก้ไข", 
qiYong2: "เปิดใช้งาน", 
tingYong2: "ปิดการใช้งาน", 
  chuangJianRiQi: '创建日期',
chuangJianRiQi: "วันที่สร้าง", 
suoDing: "ล็อค", 
zhangHuZhuangTai: "สถานะบัญชี", 
zuiDaJieDaiShang: "ขีดจำกัดการรับมากสุด", 
zaiXianJiNengZu: "กลุ่มทักษะที่ออนไลน์", 
keFuZu: "กลุ่มบริการลูกค้า", 
keFuGangWei: "ตำแหน่งบริการลูกค้า", 
touXiang: "รูปโปรไฟล์", 
qingShuRuKeFu: "กรุณาป้อนตัวแทนฝ่ายบริการลูกค้า", 
quanBuZhangHuZhuang: "สถานะบัญชีทั้งหมด", 
quanBuJiNengZu: "กลุ่มทักษะทั้งหมด", 

};
