export default {
  chengGong: '成功！',
  queDing: '确定',
  queDingSTA: "确定'{val1}{val2}' 吗？",
  sTATE: '{val1}客服',
  queRenShanChu: '确认删除',
  ruGuoGaiKeFu: '如果该客服在线，会提示该客服账户已停用并关闭客服工作台。',
  qiYong: '启用',
  tingYong: '停用',
  keFuZhangHao: '客服账号',
  keFuLieBiao: '客服列表',
  jieDaiShangXian: '接待上限',
  jieSuo: '解 锁',
  bianJi: '编辑',
  qiYong2: '启 用',
  tingYong2: '停 用',
  caoZuo: '操作',
  chuangJianRiQi: '创建日期',
  suoDing: '锁 定',
  zhangHuZhuangTai: '账户状态',
  zuiDaJieDaiShang: '最大接待上限',
  zaiXianJiNengZu: '在线技能组',
  keFuZu: '客服组',
  keFuGangWei: '客服岗位',
  touXiang: '头像',
  qingShuRuKeFu: '请输入客服代理',
  quanBuZhangHuZhuang: '全部账户状态',
  quanBuJiNengZu: '全部技能组',
  quanBuKeFuZu: '全部客服组',

};
