export default {
  index: {
qingPeiZhiGaiKe: "โปรดกำหนดค่าบริการลูกค้ากลุ่มนี้!", 
qingPeiZhiGaiKe: "โปรดกำหนดค่าบริการลูกค้ากลุ่มนี้!", 
    keFuBaoBiao: '客服报表',
keFuBaoBiao: "รายงานการบริการลูกค้า", 
    ge: '/个',
    xing: '/星',
    dengLuShiChang: '登录时长',
    mangLu: '忙绿',
    zaiXianQieHuan: '在线切换',
zaiXianQieHuan: "การสลับออนไลน์", 
    pingJunHuiHuaShi: '平均会话时长',
    jieDaiYaLiZhi: '接待压力值',
    huiFuLu: '回复率',
    jieDaiKeHuShu: '接待客户数',
    keHuKeFuXiao: '客户/客服消息数',
keHuKeFuXiao: "จำนวนข้อความของลูกค้า/บริการลูกค้า", 
    keHuPingJia: '客户评价',
    keFuZongJie: '客服总结',
    zanWuShuJuQing: '暂无数据，请重新选择搜索条件进行查询！',
    tongJiZhi: '统计值',
tongJiZhi: "ค่าทางสถิติ", 
    renYuan: '人员',
renYuan: "บุคลากร", 
    keHuPingJiaPing: '客户评价平均分',
    keHuPingJiaLu: '客户评价率/数',
    yaoQingPingJiaLu: '邀请评价率/数',
    keFuJieJueLu: '客服解决率/数',
    keFuZongJieLu: '客服总结率/数',
    sNeiXiangYingYing: '30s内响应应答率',
    zuiDaXiangYingShi: '最大响应时长',
    pingJunShouXiangShi: '平均首响时长',
pingJunShouXiangShi: "ระยะเวลาเสียงกริ่งแรกเฉลี่ย", 
    zhuanChuHuiHuaShu: '转出会话数',
    huiHuaShuYouXiao: '会话数/有效数',
huiHuaShuYouXiao: "จำนวนบทสทนา/ที่มีประสิทธภาพ", 
mangLu2: "ยุ่ง", 
    quanBuKeFuZhang: '全部客服账户',
quanBuKeFuZhang: "บัญชีบริการลูกค้าทั้งหมด", 
keFuTongJi: "สถิติการบริการลูกค้า", 
suoYouKeFuBao: "รายงานการบริการลูกค้าทั้งหมด", 
  },
  moreBar: {
danGeKeFuBao: "รายงานการบริการลูกค้ารายบุคคล", 
    zhuanJieJieRu: '转接接入',

  },
};
