export default {
  chengGong: '成功！',
  queDing: '确定',
  queDingSTA: "确定'{val1}{val2}' 吗？",
queDingSTA: "แน่ใจเกี่ยวกับ '{val1}{val2}' ไหม", 
sTATE: "{val1}ฝ่ายบริการลูกค้า", 
  ruGuoGaiKeFu: '如果该客服在线，会提示该客服账户已停用并关闭客服工作台。',
ruGuoGaiKeFu: "หากฝ่ายบริการลูกค้าออนไลน์ ระบบจะแจ้งว่าบัญชีฝ่ายบริการลูกค้าถูกปิดใช้งานและปิดโต๊ะบริการลูกค้าลูกค้า", 
  tingYong: '停用',
tingYong: "ปิดการใช้งาน", 
  keFuLieBiao: '客服列表',
  jieDaiShangXian: '接待上限',
jieDaiShangXian: "ขีดจำกัดการรับ", 
  bianJi: '编辑',
  qiYong2: '启 用',
qiYong2: "เปิดใช้งาน", 
tingYong2: "ปิดการใช้งาน", 
  chuangJianRiQi: '创建日期',
chuangJianRiQi: "วันที่สร้าง", 
  zhangHuZhuangTai: '账户状态',
zhangHuZhuangTai: "สถานะบัญชี", 
  zaiXianJiNengZu: '在线技能组',
  keFuZu: '客服组',
  keFuGangWei: '客服岗位',
keFuGangWei: "ตำแหน่งบริการลูกค้า", 
touXiang: "รูปโปรไฟล์", 
  quanBuZhangHuZhuang: '全部账户状态',
quanBuZhangHuZhuang: "สถานะบัญชีทั้งหมด", 
  quanBuKeFuZu: '全部客服组',

};
