export default {
  index: {
    qingPeiZhiGaiKe: "โปรดกำหนดค่าบริการลูกค้ากลุ่มนี้!", 
    jianTing: "กำลังฟัง 11111", 
    keFuBaoBiao: "รายงานการบริการลูกค้า", 
    qieHuan: "การสลับ", 
    ge: "/อัน", 
    xing: "/ดาว", 
    dengLuShiChang: "ระยะเวลาเข้าสู่ระบบ", 
    mangLu: "ยุ่ง", 
    zaiXianQieHuan: "การสลับออนไลน์", 
    xiangYingShiChang: "เวลาตอบสนอง", 
        jieDaiYaLiZhi: '接待压力值',
    jieDaiYaLiZhi: "ค่าความกดดันการรับ", 
        jieDaiKeHuShu: '接待客户数',
    jieDaiKeHuShu: "จำนวนลูกค้าที่ได้รับ", 
    keHuKeFuXiao: "จำนวนข้อความของลูกค้า/บริการลูกค้า", 
    shiJian: "เวลา", 
    keHuPingJia: "การประเมินของลูกค้า", 
    keFuZongJie: "สรุปผลการบริการลูกค้า", 
    zanWuShuJuQing: "ไม่มีข้อมูล โปรดเลือกเกณฑ์การค้นหาเพื่อค้นหาอีกครั้ง!", 
    tongJiZhi: "ค่าทางสถิติ", 
    suoYouKeFu: "บริการลูกค้าทั้งหมด", 
    renYuan: "บุคลากร", 
    keFuRenYuan: "พนักงานบริการลูกค้า", 
    keHuPingJiaPing: "อัตราคะแนนการประเมินของลูกค้า", 
    keHuPingJiaLu: "อัตรา/จำนวน การให้คะแนนของลูกค้า %", 
    yaoQingPingJiaLu: "อัตรา/จำนวน เชิญประเมิน", 
    keFuJieJueLu: "อัตรา/จำนวน การแก้ปัญหา", 
        sNeiXiangYingYing: '30s内响应应答率',
    sNeiXiangYingYing: "อัตราการตอบกลับภายใน 30 วินาที", 
    zuiDaXiangYingShi: "ระยะเวลาตอบสนองสูงสุด", 
    pingJunShouXiangShi: "ระยะเวลาเสียงกริ่งแรกเฉลี่ย", 
    zuiDaJieDaiShu: "จำนวนการรับสูงสุด", 
    zhuanChuHuiHuaShu: "จำนวนบทสทนาส่งต่อ", 
    huiHuaShuYouXiao: "จำนวนบทสทนา/ที่มีประสิทธภาพ", 
    mangLu2: "ยุ่ง", 
    sheZhiXianShiCan: "ตั้งค่าการแสดงผลพารามิเตอร์", 
    quanBuKeFuZhang: "บัญชีบริการลูกค้าทั้งหมด", 
    keFuTongJi: "สถิติการบริการลูกค้า", 
    suoYouKeFuBao: "รายงานการบริการลูกค้าทั้งหมด", 
    danGeKeFuBao: "รายงานการบริการลูกค้ารายบุคคล", 
  },
  moreBar: {
    ziDongJieRu: "เข้าอัตโนมัติ", 
    zhuanJieJieRu: "โอนเข้า", 
  },
};
