export default {
  index: {
nullqiangJieChengGong: "แย่งการเชื่อมต่อสำเร็จ!", 
    tiShi: '提示',
    fuWuYiChangQing: '服务异常，请安排接待客服主动关闭该会话！',
fuWuYiChangQing: "การบริการผิดปกติ โปรดให้ฝ่ายบริการลูกค้าปิดการสนทนานี้！", 
quanXuan: "เลือกทั้งหมด", 
qiangTuiChengGong: "บังคับออกสำเร็จ", 
pCWangZhan: "เว็บไซต์คอมพิวเตอร์", 
yiDongWangZhan: "เว็บไซต์มือถือ", 
yiDongAPP: "แอพมือถือ", 
    shi: '是',
shi: "ใช่", 
huiHuaJianKong: "ตรวจสอบบทสนทนา", 
qiangZhiGuanBi: "บังคับปิด", 
zhaKanHuiHua: "ตรวจดูบทสนทนา", 
qiangJie: "แย่งรับ", 
shiFouYiChang: "ผิดปกติหรือไม่", 
keHuXingBiao: "ลูกค้าติดดาว", 
xiangYingChaoShi: "หมดเวลาการตอบสนอง", 
huiHuaChaoShi: "หมดเวลาบทสนทนา", 
shouXiangChaoShi: "หมดเวลาเสียงกริ่งแรก", 
jingBaoZhuangTai: "สถานะการเตือน", 
ziXunQuDaoXi: "ระบบ/ช่องทางสอบถาม", 
huiHuaLeiXing: "ประเภทบทสนทนา", 
huiHuaJianLiShi: "เวลาในการสร้างบทสนทนา", 
keHuYongHuMing: "ชื่อผู้ใช้ของลูกค้า", 
huiHuaShiChang: "ระยะเวลาบทสนทนา", 
jiNengZu: "กลุ่มทักษะ", 
keFuZu: "กลุ่มบริการลูกค้า", 
keFuZhangHuNi: "บัญชีฝ่ายบริการลูกค้า/ชื่อเล่น", 
miaoZiDongShuaXin: "รีเฟรชอัตโนมัติ 10 วินาที", 
jingBaoHuiHuaZhi: "\nแจ้งเตือนบทสนทนาสูงสุด\n", 
tiao: "บทความ \n", 
tiaoZaiXianHuiHua: "\n บทสนทนาออนไลน์ บทสนทนาการแจ้งเตือน", 
gong: "\n รวม \n", 
qingShuRuKeHu: "กรุณากรอกชื่อผู้ใช้ของลูกค้า", 
quanBuZiXunLai: "ที่มาการสอบถามทั้งหมด", 
quanBuKeHuZu: "กลุ่มลูกค้าทั้งหมด", 
suoYouKeHuZu: "กลุ่มลูกค้าทั้งหมด", 
quanBuKeFu: "ฝ่ายบริการลูกค้าทั้งหมด", 
quanBuJingBaoZhuang: "สถานะการแจ้งเตือนทั้งหมด", 
suoYouHuiHuaLei: "ประเภทบทสนทนาทั้งหมด", 
    qingShuRuHuiHua: '请输入会话ID',
  },
};
