export default {
  index: {
qiangJieChengGong: "แย่งการเชื่อมต่อสำเร็จ!", 
qiangJieChengGong: "แย่งการเชื่อมต่อสำเร็จ!", 
    tiShi: '提示',
    fuWuYiChangQing: '服务异常，请安排接待客服主动关闭该会话！',
    quanXuan: '全选',
    qiangTuiChengGong: '强退成功！',
    pCWangZhan: 'PC网站',
pCWangZhan: "เว็บไซต์คอมพิวเตอร์", 
yiDongWangZhan: "เว็บไซต์มือถือ", 
yiDongAPP: "แอพมือถือ", 
    shi: '是',
    huiHuaJianKong: '会话监控',
huiHuaJianKong: "ตรวจสอบบทสนทนา", 
qiangZhiGuanBi: "บังคับปิด", 
zhaKanHuiHua: "ตรวจดูบทสนทนา", 
qiangJie: "แย่งรับ", 
shiFouYiChang: "ผิดปกติหรือไม่", 
keHuXingBiao: "ลูกค้าติดดาว", 
xiangYingChaoShi: "หมดเวลาการตอบสนอง", 
huiHuaChaoShi: "หมดเวลาบทสนทนา", 
shouXiangChaoShi: "หมดเวลาเสียงกริ่งแรก", 
jingBaoZhuangTai: "สถานะการเตือน", 
ziXunQuDaoXi: "ระบบ/ช่องทางสอบถาม", 
    huiHuaJianLiShi: '会话建立时间',
huiHuaJianLiShi: "เวลาในการสร้างบทสนทนา", 
keHuYongHuMing: "ชื่อผู้ใช้ของลูกค้า", 
    jiNengZu: '技能组',
    keFuZu: '客服组',
    keFuZhangHuNi: '客服账户/昵称',
    miaoZiDongShuaXin: ' 10 秒自动刷新',
miaoZiDongShuaXin: "รีเฟรชอัตโนมัติ 10 วินาที", 
jingBaoHuiHuaZhi: "\nแจ้งเตือนบทสนทนาสูงสุด\n", 
tiao: "บทความ \n", 
tiaoZaiXianHuiHua: "\n บทสนทนาออนไลน์ บทสนทนาการแจ้งเตือน", 
gong: "\n รวม \n", 
    quanBuZiXunLai: '全部咨询来源',
quanBuZiXunLai: "ที่มาการสอบถามทั้งหมด", 
    suoYouKeHuZu: '所有客户组',
    quanBuKeFu: '全部客服',
    quanBuJingBaoZhuang: '全部警报状态',
quanBuJingBaoZhuang: "สถานะการแจ้งเตือนทั้งหมด", 
suoYouHuiHuaLei: "ประเภทบทสนทนาทั้งหมด", 

  },
};
