export default {
  index: {

        cHANG: 'change业务',
    cHANG: "เปลี่ยนธุรกิจ", 
    qiangTuiChengGong: "บังคับออกสำเร็จ!", 
    you: "มี", 
        youXiaoHuiHua: '有效会话',
        weiZongJie: '未总结',
    weiZongJie: "ยังไม่สรุปผล", 
        yiZhiJian: '已质检',
    yiZhiJian: "ตรวจสอบแล้ว", 
    zongDaiID: "ไอดีตัวแทน", 
    keFuDaiLi: "ตัวแทนบริการลูกค้า", 
    keFuLeiXing: "ประเภทการบริการลูกค้า", 
        wenTiShiChang: '问题/时长',
    wenTiShiChang: "คำถาม/ระยะเวลา", 
    shangJiDaiLi: "หัวหน้าตัวแทน", 
        vipDengji: 'vip 等级',

        xiaoXiShu: '消息数',
    xiaoXiShu: "จำนวนข้อความ", 
    zhiJianZhuangTai: "สถานะการตรวจสอบ", 
    jieShuFangShi: "วิธีการสิ้นสุด", 
    kaiShiShiJian: "เวลาเริ่มต้น", 
    huiHuaLeiXing: "ประเภทบทสนทนา", 
        shi: '是',
    shi: "ใช่", 
    xiaoYu: "น้อยกว่า", 
    daYu: "มากกว่า", 
        qingShuRu: '请输入',
    qingShuRu: "กรุณาป้อน", 
    zhiNengShuRuZheng: "ป้อนได้เฉพาะตัวเลขจำนวนเต็ม", 
    zuiDaXianZhiS: "ขีดจำกัดสูงสุด 1800 วินาที", 
    youCeBuNengXiao: "ด้านขวาต้องไม่เล็กกว่าด้านซ้าย", 
    zuoCeBuNengDa: "ด้านซ้ายต้องไม่ใหญ่กว่าด้านขวา", 
    huiHuaJiLu: "บันทึกบทสนทนา", 
        xiangYingShiChang: '响应时长11',
    xiangYingShiChang: "เวลาตอบสนอง11", 
    xiaoXiShuKeHu: "จำนวนข้อความ (ลูกค้า/ฝ่ายบริการลูกค้า)", 
    pingJiaLeiXing: "ประเภทการประเมิน", 
        yeWu: '业务',
    yeWu: "ธุรกิจ", 
    huiHuaLeiBie: "ประเภทบทสนทนา", 
    wenTiShiChang2: "คำถาม/ระยะเวลา", 
    sheZhiZhanShiZi: "ตั้งค่าฟิลด์แสดงผล", 
        gengDuoShaiXuanTiao2: '更多筛选条件',
    gengDuoShaiXuanTiao2: "เกณฑ์การกรองเพิ่มเติม", 
    qingShuRuKeHu: "กรุณาใส่คีย์เวิร์ดแชทของลูกค้า / ฝ่ายบริการลูกค้า", 
    quanBuYeWuLei: "ประเภทธุรกิจทั้งหมด", 
    quanBuYeWu: "ธุรกิจทั้งหมด", 
    zuiChangXiangYingShi: "ระยะเวลาตอบสนองที่ยาวที่สุด", 
    qingShuRuKeFu: "กรุณาป้อนตัวแทนฝ่ายบริการลูกค้า", 
    qingShuRuKeHu2: "โปรดป้อนหัวหน้าตัวแทนของลูกค้า", 
    qingShuRuKeHu3: "กรุณากรอกชื่อบัญชีลูกค้า", 
        qingShuRuHuiHua: '请输入会话ID'
  }
}
