export default {
  index: {
    qiangJieChengGong: '抢接成功！',
    haoDe: '好的',
    tiShi: '提示',
    fuWuYiChangQing: '服务异常，请安排接待客服主动关闭该会话！',
    quanXuan: '全选',
    qiangTuiChengGong: '强退成功！',
    pCWangZhan: 'PC网站',
    yiDongWangZhan: '移动网站',
    yiDongAPP: '移动APP',
    fou: '否',
    shi: '是',
    huiHuaJianKong: '会话监控',
    qiangZhiGuanBi: '强制关闭',
    zhaKanHuiHua: '查看会话',
    qiangJie: '抢接',
    shiFouYiChang: '是否异常',
    keHuXingBiao: '客户星标',
    xiangYingChaoShi: '响应超时',
    huiHuaChaoShi: '会话超时',
    shouXiangChaoShi: '首响超时',
    jingBaoZhuangTai: '警报状态',
    ziXunQuDaoXi: '咨询渠道/系统',
    huiHuaLeiXing: '会话类型',
    huiHuaJianLiShi: '会话建立时间',
    keHuYongHuMing: '客户用户名',
    huiHuaShiChang: '会话时长',
    jiNengZu: '技能组',
    keFuZu: '客服组',
    keFuZhangHuNi: '客服账户/昵称',
    miaoZiDongShuaXin: ' 10 秒自动刷新',
    jingBaoHuiHuaZhi: '\n            警报会话置顶\n          ',
    tiao: ' 条\n        ',
    tiaoZaiXianHuiHua: '\n          条在线会话，警报会话 ',
    gong: '\n          共\n          ',
    qingShuRuKeHu: '请输入客户用户名',
    quanBuZiXunLai: '全部咨询来源',
    quanBuKeHuZu: '全部客户组',
    suoYouKeHuZu: '所有客户组',
    quanBuKeFu: '全部客服',
    quanBuJingBaoZhuang: '全部警报状态',
    suoYouHuiHuaLei: '所有会话类型',
    qingShuRuHuiHua: '请输入会话ID',

  },
};
