export default {
  index: {
    kehuYuyan: '客户语言',

    cHANG: 'change业务',
cHANG: "เปลี่ยนธุรกิจ", 
    you: '有',
you: "มี", 
    youXiaoHuiHua: '有效会话',
    weiZongJie: '未总结',
    weiZhiJian: '未质检',
    yiZhiJian: '已质检',
    zongDaiID: '总代id',
    keFuDaiLi: '客服代理',
    keFuLeiXing: '客服类型',
    huiHuaKaiShiShi: '会话开始时间',
    wenTiShiChang: '问题/时长',
    shangJiDaiLi: '上级代理',
    keHuLeiXing: '客户类型',
    vipDengji: 'vip 等级',

    xiaoXiShu: '消息数',
xiaoXiShu: "จำนวนข้อความ", 
    jieShuFangShi: '结束方式',
    kaiShiShiJian: '开始时间',
kaiShiShiJian: "เวลาเริ่มต้น", 
    fou: '否',
    shi: '是',
    xiaoYu: '小于',
    daYu: '大于',
    zhiNengShuRuDa: '只能输入大于0的正数',
    qingShuRu: '请输入',
    zhiNengShuRuZheng: '只能输入正数',
zhiNengShuRuZheng: "ป้อนได้เฉพาะตัวเลขจำนวนเต็ม", 
zuiDaXianZhiS: "ขีดจำกัดสูงสุด 1800 วินาที", 
youCeBuNengXiao: "ด้านขวาต้องไม่เล็กกว่าด้านซ้าย", 
zuoCeBuNengDa: "ด้านซ้ายต้องไม่ใหญ่กว่าด้านขวา", 
huiHuaJiLu: "บันทึกบทสนทนา", 
    xiangYingShiChang: '响应时长11',
    xiaoXiShuKeHu: '消息数（客户/客服）',
    pingJiaLeiXing: '评价类型',
    yeWuLeiXing: '业务类型',
    yeWu: '业务',
    huiHuaLeiBie: '会话类别',
    wenTiShiChang2: '问题 / 时长',
wenTiShiChang2: "คำถาม/ระยะเวลา", 
sheZhiZhanShiZi: "ตั้งค่าฟิลด์แสดงผล", 
    gengDuoShaiXuanTiao2: '更多筛选条件',
    qingShuRuKeHu: '请输入客户/客服聊天关键词',
    quanBuYeWuLei: '全部业务类型',
quanBuYeWuLei: "ประเภทธุรกิจทั้งหมด", 
quanBuYeWu: "ธุรกิจทั้งหมด", 
zuiChangXiangYingShi: "ระยะเวลาตอบสนองที่ยาวที่สุด", 
    qingShuRuKeHu2: '请输入客户上级代理',
qingShuRuKeHu2: "โปรดป้อนหัวหน้าตัวแทนของลูกค้า", 
qingShuRuKeHu3: "กรุณากรอกชื่อบัญชีลูกค้า", 

  }
}
