export default {
bianJiJiNengZu: "แก้ไขกลุ่มทักษะ", 
bianJiJiNengZu: "แก้ไขกลุ่มทักษะ", 
yiChuJiNengZu: "ลบสมาชิกชุดทักษะ -", 
tianJiaChengYuanDao: "เพิ่มสมาชิกใน", 
zuChengYuan: "สมาชิกกลุ่ม", 
tianJiaJiNengZu: "เพิ่มกลุ่มทักษะ", 
rOWNA: "[{val1}] เชื่อมโยงกับ [{val2}] แล้วและไม่สามารถลบได้!", 
  youKeWenTiJi: '游客问题技能组不能删除哦！',
youKeWenTiJi: "คำถามผู้เยี่ยมชมกลุ่มทักษะไม่สามารถลบได้", 
youKe: "ผู้เยี่ยมชม", 
  jiNengZuLieBiao: '技能组列表',
jiNengZuLieBiao: "รายการกลุ่มทักษะ", 
yiChuChengYuan: "ลบสมาชิก", 
  tianJiaChengYuan: '添加成员',
tianJiaChengYuan: "เพิ่มสมาชิก", 
  jiNengZuMingCheng: '技能组名称',
  quanBu: '全部',
  shiFouXianShi: '是否显示：',

};
