export default {
    bianJiJiNengZu: "แก้ไขกลุ่มทักษะ", 
    yiChuJiNengZu: "ลบสมาชิกชุดทักษะ -", 
    tianJiaChengYuanDao: "เพิ่มสมาชิกใน", 
    zuChengYuan: "สมาชิกกลุ่ม", 
    tianJiaJiNengZu: "เพิ่มกลุ่มทักษะ", 
    rOWNA: "[{val1}] เชื่อมโยงกับ [{val2}] แล้วและไม่สามารถลบได้!", 
    shanChuChengGong: "ลบสำเร็จ", 
    youKeWenTiJi: "คำถามผู้เยี่ยมชมกลุ่มทักษะไม่สามารถลบได้", 
    youKe: "ผู้เยี่ยมชม", 
    ninShiFouQueRen: "คุณยืนยัน {val1}{val2} หรือไม่", 
    jiNengZuLieBiao: "รายการกลุ่มทักษะ", 
    yiChuChengYuan: "ลบสมาชิก", 
    shanChu: "ลบ", 
    tianJiaChengYuan: "เพิ่มสมาชิก", 
    jiNengZuID: "ไอดี กลุ่มทักษะ:", 
    jiNengZuMingCheng: "ชื่อกลุ่มทักษะ:", 
    quanBu: "ทั้งหมด", 
    shiFouXianShi: "แสดงหรือไม่", 
};
