export default {
    bianJiJiNengZu: "แก้ไขกลุ่มทักษะ", 
    yiChuJiNengZu: "ลบสมาชิกชุดทักษะ -", 
    tianJiaChengYuanDao: "เพิ่มสมาชิกใน", 
    zuChengYuan: "สมาชิกกลุ่ม", 
    tianJiaJiNengZu: "เพิ่มกลุ่มทักษะ", 
    rOWNA: "[{val1}] เชื่อมโยงกับ [{val2}] แล้วและไม่สามารถลบได้!", 
    shanChuChengGong: "ลบสำเร็จแล้ว", 
    youKeWenTiJi: "คำถามผู้เยี่ยมชมกลุ่มทักษะไม่สามารถลบได้", 
    youKe: "ผู้เยี่ยมชม", 
    ninShiFouQueRen: "คุณแน่ใจหรือไม่ว่าต้องการลบกลุ่มทักษะ [{val1}]", 
    jiNengZuLieBiao: "รายการกลุ่มทักษะ", 
    yiChuChengYuan: "ลบสมาชิก", 
    shanChu: "ลบ", 
    tianJiaChengYuan: "เพิ่มสมาชิก", 
      jiNengZuMingCheng: '技能组名称',
    jiNengZuMingCheng: "ชื่อกลุ่มทักษะ", 
    quanBu: "ทั้งหมด", 
      shiFouXianShi: '是否显示：',
};
