export default {
  index: {
        qingShuRuCR: '请输入Cron表达式',
    qingShuRuCR: "โปรดป้อนการแสดงออกของ Cron", 
    qingShuRuFangFa: "กรุณากรอกชื่อวิธีการ", 
    qingShuRuBE: "กรุณากรอกชื่อBean", 
    qingShuRuRenWu: "กรุณากรอกชื่องาน", 
    dingShiRenWu: "งานหมดเวลา", 
    shanChu: "ลบ", 
    queDingTingZhiBing: "ต้องการหยุดและลบงานนี้หรือไม่", 
    zanTing: "หยุด", 
    huiFu: "ฟื้นฟู", 
    zhiXing: "ดำเนินการ", 
    bianJi: "แก้ไข", 
    yunXingZhong: "อยู่ในระหว่างการดำเนินการ", 
    yiZanTing: "ถูกระงับ", 
    cRONBiao: "การแสดงออกของ cron", 
    canShu: "พารามิเตอร์", 
    zhiXingFangFa: "วิธีการดำเนินการ", 
    bEANMing: "ชื่อBean", 
    renWuMingCheng: "ชื่องาน", 
    renWuMiaoShu: "คำอธิบายงาน", 
    qiYong: "เปิดใช้งาน", 
    renWuZhuangTai: "สถานะงาน", 
    cRONBiao2: "การแสดงออกของ cron", 
    canShuNeiRong: "เนื้อหาพารามิเตอร์", 
    riZhi: "บันทึก", 
    shuRuRenWuMing: "ป้อนชื่องานเพื่อค้นหา", 
  },
  log: {
    shiBai: "ล้มเหลว", 
    renWuRiZhi: "บันทึกงาน", 
    yiChangXiangQing: "รายละเอียดที่ผิดปกติ", 
    haoShiHaoMiao: "เวลาที่ใช้ (มิลลิวินาที)", 
    zhaKanXiangQing: "ตรวจดูรายละเอียด", 
    daoChu: "ส่งออก", 
    souSuo: "ค้นหา", 
    riZhiZhuangTai: "สถานะบันทึก", 
    jieShuRiQi: "วันที่สิ้นสุด", 
    kaiShiRiQi: "วันที่เริ่มต้น", 
    zhiXingRiZhi: "บันทึกการดำเนินการ", 
  },
};
