export default {
  center: {
    touXiangXiuGaiCheng: "แก้ไขรูปโปรไฟล์สำเร็จ", 
    shangChuanTouXiangTu: "อัพโหลดรูปโปรไฟล์ต้องไม่เกิน 2MB!", 
    changDuZaiDaoGe: "ความยาวอยู่ระหว่าง 1 ถึง 20 ตัวอักษร", 
    qingShuRuYongHu: "กรุณากรอกชื่อผู้ใช้ของคุณ", 
    qingShuRuZhengQue: "กรุณาใส่ที่อยู่อีเมลที่ถูกต้อง", 
    baoCunPeiZhi: "บันทึกการกำหนดค่า", 
    nu: "ผู้หญิง", 
    nan: "ผู้ชาย", 
    xingBie: "เพศ", 
    shouJiHaoMaBu: "หมายเลขโทรศัพท์มือถือไม่สามารถซ้ำได้", 
    shouJiHao: "หมายเลขโทรศัพท์มือถือ", 
    yongHuNiChengBu: "ชื่อเล่นผู้ใช้ไม่ได้ใช้สำหรับการเข้าสู่ระบบ", 
    niCheng: "ชื่อเล่น", 
    yongHuZiLiao: "ข้อมูลผู้ใช้", 
    miMa: "รหัสผ่าน", 
    xiuGai: "แก้ไข", 
    anQuanSheZhi: "การตั้งค่าความปลอดภัย\n", 
    suoShuBuMen: "แผนก", 
    yongHuYouXiang: "อีเมลผู้ใช้", 
    shouJiHaoMa: "หมายเลขโทรศัพท์", 
    yongHuNiCheng: "ชื่อผู้ใช้", 
    dengLuZhangHao: "เข้าสู่ระบบบัญชี", 
    dianJiShangChuanTou: "คลิกเพื่ออัปโหลดโปรไฟล์ต้อง", 
    geRenXinXi: "ข้อมูลส่วนตัว", 
  },
  index: {
    jueSeBuNengWei: "บทบาท ห้ามเว้นว่าง", 
    gangWeiBuNengWei: "ตำแหน่ง ห้ามเว้นว่าง", 
    buMenBuNengWei: "แผนก ห้ามเว้นว่าง", 
    zhuangTaiXiuGaiCheng: "แก้ไขสถานะสำเร็จ", 
    kaiQiChengGong: "เปิดสำเร็จ", 
    shiFouJiXu: "ดำเนินการต่อหรือไม่?", 
        queDingKaiQi: '确定开启',
    queDingKaiQi: "ตกลงเพื่อเปิด", 
    tuPianYanZheng: "ยืนยันรูปภาพ", 
    guGeYanZheng: "ยืนยันของ Google", 
    xiuGaiChengGong: "แก้ไขเรียบร้อยแล้ว", 
    queDingYaoZhongZhi: "แน่ใจไหมว่าต้องการรีเซ็ตการยืนยันของ Google และเชื่อมต่อใหม่", 
    qingShuRuZhengQue: "กรุณาใส่ที่อยู่อีเมลที่ถูกต้อง", 
    qingShuRuShouJi: "กรอกหมายเลขโทรศัพท์", 
    qingShuRuZhengQue2: "กรุณกรอกที่อยู่อีเมลที่ถูกต้อง", 
    qingShuRuYouXiang: "กรุณากรอกอีเมลของคุณ", 
    changDuZaiDaoGe: "ความยาวอยู่ระหว่าง 1 ถึง 20 ตัวอักษร", 
    zhiNengShuRuZi: "สามารถป้อนได้เฉพาะตัวอักษรและตัวเลขเท่านั้น", 
    qingShuRuYongHu: "กรุณากรอกชื่อผู้ใช้ของคุณ", 
    qingXuanZeJueSe: "โปรดเลือกระดับบทบาท", 
        qingXuanZeDaiLi: '请选择代理账号',
    qingXuanZeDaiLi: "กรุณาเลือกเลขที่บัญชีตัวแทน", 
    qingXuanZeKeFu: "โปรดเลือกบริการลูกค้าหรือกําหนดค่าการบริการลูกค้ากลุ่มนี้", 
    qingXuanZeGangWei: "กรุณาเลือกตำแหน่ง", 
    qingXuanZeBuMen: "กรุณาเลือกแผนก", 
    suoDing: "ล็อค", 
    jiHuo: "เปิดใช้งาน", 
    yongHu: "ผู้ใช้", 
    zhongZhiMiMa: "รีเซ็ตรหัสผ่าน", 
    jieSuo: "ปลดล็อค", 
    zhongZhiYanZhengMa: "รีเซ็ตรหัสยืนยัน", 
    tuPian: "รูปภาพ", 
    guGe: "Google", 
    yanZhengMaLeiXing: "ประเภทรหัสยืนยัน", 
    buMenGangWei: "แผนก/ตำแหน่ง", 
    yongHuMingNiCheng: "ชื่อผู้ใช้/ชื่อเล่น", 
    ruGuoYuanKeFu:
      '如果原客服类部门的用户修改为非客服类的用户，将会将该客服账号自动停用，客服如果已登录，将会自动下线。',
    qingXianXuanZeA: "กรุณาเลือก app ก่อน", 
    qingXianXuanZeChan: "กรุณาเลือกสินค้าก่อน", 
    chanPin: "สินค้า", 
    zhiNengChuangJianXiu: "คุณสามารถสร้าง/แก้ไขบทบาทผู้ใช้ที่มีระดับน้อยกว่าระดับบทบาทของคุณเท่านั้น", 
    qingXianXuanZe: "กรุณาเลือกก่อน!", 
    zongDaiID: "ไอดี ตัวแทน", 
    daiLiZhangHao: "หมายเลขบัญชีตัวแทน", 
    keFuLeiXing: "ประเภทการบริการลูกค้า", 
    qingXianXuanZeBu: "กรุณาเลือกแผนกก่อน", 
    youXiang: "อีเมล", 
    dianHua: "หมายเลขโทรศัพท์", 
    shuRuMingChengHuo: "กรอกชื่อหรือคำอธิบายเพื่อค้นหา", 
  },
  updatePass: {
    xiuGaiChengGongT: "การแก้ไขสำเร็จ และรหัสผ่านใหม่ของ {val1} มีค่าเริ่มต้นเป็น {val2}", 
    tHISE: "ปลดล็อก {val1} สำเร็จแล้ว", 
    qingShuRuGuanLi: "กรุณาใส่รหัสผ่านผู้ดูแลระบบ", 
    zhongZhiMiMaWei: "รีเซ็ตรหัสผ่านเป็น", 
    qingShuRuNinDe: "กรุณากรอกรหัสผ่านเข้าสู่ระบบของคุณ", 
    dengLuMiMa: "รหัสผ่านในการเข้าสู่ระบบ", 
    dengLuYongHuMing: "เข้าสู่ระบบด้วยชื่อผู้ใช้", 
    xuYaoYanZhengNin: "จำเป็นต้องมีการยืนยันตัวตนของคุณ", 
    jieSuoZhangHu: "ปลดล็อกบัญชีของคุณ", 
    weiLeBaoZhengZhang: "เพื่อจุดประสงค์ด้านความปลอดภัยของบัญชี", 
  },
};
