export default {
  directive: {
    guDing: "คงที่", 
  },
  index: {
    sECON: "{val1} วินาที", 
    mINTO: "{val1} นาที {val2} วินาที", 
    hTOST: "{val1}ชั่วโมง {val2}นาที {val3}วินาที", 
    dTOST: "{val1} วัน {val2} ชั่วโมง {val3} นาที {val4} วินาที", 
    fuZhiShiBai: "คัดลอกล้มเหลว!", 
    fuZhiChengGong: "คัดลอกสำเร็จ", 
    fen: "คะแนน", 
    shi: "ใช่", 
    ri: "วัน", 
    yue: "เดือน", 
    tianQian: "1 วันที่ผ่านมา", 
    xiaoShiQian: "ชั่วโมงที่ผ่านมา", 
    fenZhongQian: "นาทีที่ผ่านมา", 
    gangGang: "ตอนนี้", 
    liu: "หก", 
    wu: "ไม่", 
    si: "สี่", 
    san: "สาม", 
    er: "สอง", 
    yi: "หนึ่ง", 
    fou: "ไม่", 
    shi2: "เวลา", 
    miao: "วินาที", 
    tian: "7วัน", 
  },
  request: {
    jieKouQingQiuShi: "คำขออินเทอร์เฟซล้มเหลว", 
    zhangHaoYiBeiSuo: "บัญชีถูกล็อค", 
    guanBi: "ปิดทิ้ง", 
    chongXinDengLu: "เข้าสู่ระบบอีกครั้ง", 
    xiTongTiShi: "แนะนำระบบ", 
    dengLuYiChangDeng: "การเข้าสู่ระบบผิดปกติ/การเข้าสู่ระบบของสถานะผู้ใช้ผิดปกติ โปรดเข้าสู่ระบบอีกครั้ง!", 
    wangLuoQingQiuChao: "คำขอเครือข่ายหมดเวลา", 
    shuJuJiaZaiZhong: "กำลังโหลดข้อมูล......", 
  },
  validate: {
    qingShuRuZhengQue: "กรุณาใส่ที่อยู่อีเมลที่ถูกต้อง", 
    qingShuRuZhengQue2: "กรุณกรอกที่อยู่อีเมลที่ถูกต้อง", 
    qingShuRuZhengQue3: "โปรดป้อนหมายเลขโทรศัพท์พื้นฐานที่ถูกต้อง (รูปแบบ: รหัสพื้นที่ + หมายเลข เช่น 010-1234567)", 
    qingShuRuZhengQue4: "โปรดป้อนหมายเลขโทรศัพท์หรือหมายเลขโทรศัพท์พื้นฐานที่ถูกต้อง", 
    qingShuRuZhengQue5: "กรุณาป้อนที่อยู่ IP ที่ถูกต้อง", 
    qingShuRuZhengQue6: "กรุณาใส่รูปแบบที่ถูกต้อง", 
  },
  settings:{
    title: "บริการลูกค้า ST", 
        caseNumber: 'B体育客服 后台管理系统'
  }
};
