export default {
  directive: {
guDing: "คงที่", 
  },
  index: {
guDing: "คงที่", 
sECON: "{val1} วินาที", 
mINTO: "{val1} นาที {val2} วินาที", 
hTOST: "{val1}ชั่วโมง {val2}นาที {val3}วินาที", 
dTOST: "{val1} วัน {val2} ชั่วโมง {val3} นาที {val4} วินาที", 
fuZhiShiBai: "คัดลอกล้มเหลว!", 
    fen: '分',
    shi: '时',
    ri: '日',
ri: "วัน", 
yue: "เดือน", 
tianQian: "1 วันที่ผ่านมา", 
xiaoShiQian: "ชั่วโมงที่ผ่านมา", 
fenZhongQian: "นาทีที่ผ่านมา", 
gangGang: "ตอนนี้", 
liu: "หก", 
    si: '四',
si: "สี่", 
san: "สาม", 
er: "สอง", 
yi: "หนึ่ง", 
    shi2: '是',
    miao: '秒',
    tian: '天',
  },
  request: {
    jieKouQingQiuShi: '接口请求失败',
jieKouQingQiuShi: "คำขออินเทอร์เฟซล้มเหลว", 
    guanBi: '关闭111',
    chongXinDengLu: '重新登录',
chongXinDengLu: "เข้าสู่ระบบอีกครั้ง", 
xiTongTiShi: "แนะนำระบบ", 
dengLuYiChangDeng: "การเข้าสู่ระบบผิดปกติ/การเข้าสู่ระบบของสถานะผู้ใช้ผิดปกติ โปรดเข้าสู่ระบบอีกครั้ง!", 
wangLuoQingQiuChao: "คำขอเครือข่ายหมดเวลา", 
  },
  validate: {
shuJuJiaZaiZhong: "กำลังโหลดข้อมูล......", 
    qingShuRuZhengQue2: '请输入正确的电话号码',
    qingShuRuZhengQue3: '请输入正确的固话（格式：区号+号码,如010-1234567）',
qingShuRuZhengQue3: "โปรดป้อนหมายเลขโทรศัพท์พื้นฐานที่ถูกต้อง (รูปแบบ: รหัสพื้นที่ + หมายเลข เช่น 010-1234567)", 
qingShuRuZhengQue4: "โปรดป้อนหมายเลขโทรศัพท์หรือหมายเลขโทรศัพท์พื้นฐานที่ถูกต้อง", 
qingShuRuZhengQue5: "กรุณาป้อนที่อยู่ IP ที่ถูกต้อง", 
  },
  settings:{
qingShuRuZhengQue6: "กรุณาใส่รูปแบบที่ถูกต้อง", 
title: "บริการลูกค้า ST", 

  }
};
