export default {
  gongXiNiGuanBi: '恭喜你，关闭成功',
  shiFouYaoQuXiao: '是否要取消此条消息的弹窗提醒',
  jieZhiDaoFO:
    '截止到{val1}， 目前会员{val2}中心钱包已到达{val3}元（当前实际中心钱包余额），\n            若需要人工处理资金，请尽快操作！',
  wenXinTiShi: '温馨提示',
  woZhiDaoLe: '我知道了',
  gaiJiLu: '该记录',
  qingQueRenShiFou: '请确认是否要',
  jieShuShiJian: '结束时间',
  kaiShiShiJian: '开始时间',
  xuanZeRiQi: '选择日期',
  chaXunRiQiQu: '查询日期区间不能超过{val1}天',
  shangChuanTuPianZhi: '上传图片只能是 jpg/png/jpeg/gif/webp 格式!',
  shangChuanTuPianCheng: '上传图片成功',
  shangChuanJieKouYi: '上传接口异常',
  xiaZaiCiYeMian: '下载此页面到本地项目',
  daoChuEXC: '导出Excel',
  shaiXuanTiaoJian: '筛选条件',
  shaiXuan: '筛选',
  shangChuan: '上传',
  zuiDuoShangChuanL: '(最多上传{val1}张)',
  jieShuYueFen: '结束月份',
  kaiShiYueFen: '开始月份',
  quZhong: '去重',
  gongJi: '共计：',
  beiShu: '倍数：',
  haoMa: '号码：',
  jieGuo: '结果：',
  weiZhi: '位置：',
  wanFa: '玩法：',
  weiZhi2: '位置',
  touZhuWeiZhi: '投注位置',
  haoMa2: '号码',
  touZhuHaoMa: '投注号码',
  wanFaPLA: '玩法：{val1}，位置：{val2}，号码：{val3}，',
  touZhu: '投注:',
  touZhuXiang: '投注项：',
  zhuang: '庄',
  zhuangXian: '庄闲',
  xiangGang: '香港',
  ouZhou: '欧洲',
  tuoZhuaiTuPianHuo: '拖拽图片、或点击图片上传',
  tuPianShuLiangChao: '图片数量超出限制，最多上传5张',
  iNFOF: '{val1} 移除成功.',
  iNFOF2: '{val1} 上传失败.',
  iNFOF3: '{val1} 上传成功.',
  xiaZaiLieBiaoE: '下载列表({val1})',
  quanBuQingChu: '全部清除',
  xiaZaiLieBiao: '下载列表',
  chuangJianRiQi: '创建日期',
  wenJianMing: '文件名',
  jianTiZhongWen: '简体中文',
  huiYuanZhangHaoShou: '会员账号/手机',
  gaiYongHuBuCun: '该用户不存在',
  guanBiSuoYou: '关闭所有',
  guanBiQiTa: '关闭其他',
  qingShuRuXinMi: '请输入新密码',
  xinMiMa: '新密码',
  qingShuRuJiuMi: '请输入旧密码',
  jiuMiMa: '旧密码',
  tiXianZiJinYu: '提现资金预警：',
  tiXianZiJinDi: '提现资金低额预警',
  tiShi: '提示',
  tiXianZiJinGao: '提现资金高额预警',
  chongZhiZiJinDi: '充值资金低额预警',
  chongZhiZiJinGao: '充值资金高额预警',
  qinNinZanShiMei: '亲， 您暂时没有任何子管理系统的权限噢 😯 ',
  shenHeWanCheng: '审核完成',
  fanTiZhongWen: '繁体中文',
  xuYaoXianChuShi: '需要先初始化createModal',
  xuanZhuan: '旋转',
  chaKanYuanTu: '查看原图',
};
