export default {
  index: {
    vipDengji: 'VIP等级',
    chengGong: '成功',
    quXiao: '取消',
    queDing: '确定',
    tiShi: '提示',
    buMenShiFouJi: '部门, 是否继续？',
    ciCaoZuoJiang: '此操作将 "',
    shangJiBuMenBu: '上级部门不能为空',
    jinYong: '禁用',
    zhengChang: '正常',
    qingShuRuMingCheng: '请输入名称',
    buMen: '部门',
    queDingShanChuMa: '确定删除吗,如果存在下级节点则一并删除，此操作不能撤销！',
    caoZuo: '操作',
    chuangJianRiQi: '创建日期',
    zhuangTai: '状态',
    feiKeFu: '非客服',
    keFu: '客服',
    buMenLeiXing: '部门类型',
    mingCheng: '名称',
    queRen: '确认',
    xuanZeShangJiLei: '选择上级类目',
    zanWuPiPeiShu: '暂无匹配数据',
    shangJiBuMen: '上级部门',
    zhongZhi: '重置',
    quanBu: '全部',
    shuRuBuMenMing: '输入部门名称搜索'
  }
}
