export default {
  shenQingBeiZhu: '申请备注',
  tiaoZhengJinE: '调整金额',
  ziJinTiaoZhengDan: '资金调整单号',
  shenHeRen: '审核人',
  erShenZhuangTai: '二审状态',
  yiShenZhuangTai: '一审状态',
  keTiEDu: '可提额度',
  tiaoZhengZiLeiXing: '调整子类型',
  tiaoZhengLeiXing: '调整类型',
  zhangHuXinXi: '账户信息',
  sanFangShangHuDing: '三方商户订单号',
  guanLianDanHao: '关联单号',
  qingShuRuDanHao: '请输入单号',
  qingShuRuTiaoZheng: '请输入调整原因',
  qingShuRuSanFang: '请输入三方商户订单号',
  qingShuRuGuanLian: '请输入关联订单号',
  guanLianDingDanHao: '关联订单号',
  qingShuRuXuQiu: '请输入需求流水金额',
  qingShuRuTiXian: '请输入提现额度，不可大于调整金额',
  danBiADJ: '单笔≤{val1} 元',
  qingShuRuChongZhi: '请输入充值金额，无充值填入0',
  tiXianLiuShui: '提现流水',
  shiJiFaFangJin: '实际发放金额',
  jiangLiJinE: '奖励金额',
  daiLiHuoDongXuan: '代理活动选择',
  ziJinTiaoZhengShen: '资金调整申请',
  qingXuanZeDaiLi: '请选择代理活动',
  zhangHaoSUC: '账号 {val1} 资金调整申请成功',
  zhangHaoFAI: '账号 {val1} 不支持{val2}',
  zhangHaoINV: '账号 {val1} 不存在',
  jinBanNianJiaBi: '近半年加币记录',
  qingXuanZeShenHe: '请选择审核结果',
  shenHeJieGuo: '审核结果',
  erShenBeiZhu: '二审备注',
  yiShenBeiZhu: '一审备注',
  shenQingYuanYou: '申请原由',
  erCiShenHe: '二次审核',
  yiCiShenHe: '一次审核',
};
