export default {
  zhuangTai: '狀態',
  shiJianZhouQi: '时间週期',
  zuiHouXiuGaiRen: '最后修改人',
  leiXing: '類型',
  duanKou: '端口',
  zhuTi: '主題',
  vIPDengJi: 'vip等级',
  sTATU: '{val1}成功',
  queDingYaoST: '确定要{val1}该条弹窗？',
  sTATU2: '{val1}首页弹窗（{val2}）',
  shanChuChengGong: '删除成功',
  queDingYaoShanChu: '确定要删除该条弹窗？',
  shanChuTanChuangR: '删除弹窗（{val1}）',
  tanChuangLeiXing: '弹窗类型',
  shangChuanTuPian: '上传图片',
  tuPianShangChuan: '圖片上傳',
  danChuBinLu: '彈出頻率',
  tiaoZhuan: '跳轉',
  zhuTi2: '主题',
  shiJianZhouQi2: '时间周期',
  tYPEA: '{val1}',
  aPPDanChuang: 'APP彈窗及浮窗配置',
  xinZeng: '新增',
  bianJi: '编辑',
};
