export default {
  jiaoYiBianHao: '交易编号',
  qingShuRuZhangHao: '请输入帐号',
  daiLiShuYingBao: '代理输赢报表',
  huiYuanJiaoYiJi: '会员交易纪录',
  daiChongMingXi: '代充明细',
  ziJinTiaoZhengJian: '资金调整-减币',
  ziJinTiaoZhengJia: '资金调整-加币',
  fanShuiJinE: '返水金额',
  hongLiJinE: '红利金额',
  gongSiZongYingLi: '公司总盈利(代理)',
  gongSiChouShui: '公司抽水',
  wanJiaDuiZhanLei: '玩家对战类',
  gongSiYingLi: '公司盈利',
  paiCaiJinE: '派彩金额',
  pingTaiZuoZhuang: '平台坐庄',
  youXiRenShu: '游戏人数',
  quKuanRenShu: '取款人数',
  quKuanJinE: '取款金额',
  cunKuanRenShu: '存款人数',
  shouCunRenShu: '首存人数',
  zhuCeRenShu: '注册人数',
  dangQianYeHuiZong: '当前页汇总',
  pingTaiShuYingDao: '平台输赢导出',
  daoChuLieBiao: '导出列表',
  shuJuLeiXing: '数据类型',
  riQi: '日期',
  gongSiZongYingLi2: '公司总盈利 (代理)',
  tiKuanJinE: '提款金额',
  fuKuanRenTE: '付款人：{val1}',
};
