export default {
  zuiDuoZhiNengTian: '最多只能添加24个标签哦！',
  gaiBiaoQianYiTian: '该标签已添加！',
  qingDianJiBianJi: '请点击编辑进行删除保存！',
  guanBiChengGong: '关闭成功',
  kaiQiChengGong: '开启成功',
  sheZhiChengGong: '设置成功',
  chaoGuoGaiShiJian:
    '超过该时间客服与客户未进行会话，系统将主动结束该会话;不可少于5分钟。',
  huiHuaShiXiaoShi: '会话失效时间',
  chaoGuoGaiShiJian2:
    '超过该时间客服与客户未进行会话，客服可在工作台主动关闭该会话;不可少于3分钟',
  keFuZhuDongGuan: '客服主动关闭会话时间',
  huiHuaJieShuShe: '会话结束设置',
  qingShuRuZhiJian: '请输入10-120之间的整数',
  qingShuRuBuXiao: '请输入不小于5的整数',
  qingShuRuBuXiao2: '请输入不小于3的整数',
  fuWuZongJiePei: '服务总结配置',
  xingShuoMing: '星说明:',
  xing: '星\n                  ',
  xing2: '星',
  xingJiPingJiaShe: '星级评价设置',
  quanBuShanChu: '全部删除',
  yiTianJiaBiaoQian: '已添加标签：(',
  zuiDuoShuRuGe: '最多输入8个字（含字符',
  tianJiaPingJiaBiao: '添加评价标签库',
  kaiQiCiGongNeng:
    ' 开启此功能后，客户端在评价会话的时候可以对本次会话是否已解决进行选择。',
  keFuShiFouJie: '客服是否解决问题：',
  manYiDuPingJia: '满意度评价设置',
  manYiDuPingJia2: '满意度评价配置',
  yongHuPaiDuiChao:
    '用户排队超过该时间仍未进入会话，系统将会自动结束该用户排队。',
  fen: '分',
  paiDuiChaoShiShi: '排队超时时间：',
  paiDuiJieShuShe: '排队结束设置',
  serverConfig: {
    xinZengChengGong: '新增成功！',
    bianJiChengGong: '编辑成功！',
    qingXianShanChuYe: '请先删除业务类型',
    ninQueDingShanChu: '您确定删除【{val1}】该标签',
    shanChuYeWuMing: '删除业务名称',
    changDuZaiDaoGe: '长度在 1 到 20 个字符',
    qingShuRuYeWu: '请输入业务名称',
    paiXuZhiBiXu: '排序值必须是大于0的整数',
    qingShuRuYeWu2: '请输入业务名称排序值',
    fuWuZongJiePei: '服务总结配置列表',
    chuangJianRen: '创建人',
    yeWuMingCheng: '业务名称',
    yeWuPaiXuI: '业务排序ID',
    xinZeng: '新增',
    quanBu: '全部',
    yeWuMingChengPai: '业务名称排序ID',
  },
  serverType: {
    shanChuNeiRong: '删除内容',
    bianJiYeWuLei: '编辑业务类型',
    tianJiaYeWuLei: '添加业务类型',
    qingShuRuPaiXu: '请输入排序值',
    qingShuRuYeWu: '请输入业务类型名称',
    yeWuLeiXingXiang: '业务类型详情',
    yeWuLeiXingPai: '业务类型排序ID',
    yeWuLeiXingMing: '业务类型名称',
    dianJiYeWuMing: '点击业务名称查看',
    yeWuLeiXing: '业务类型',
  },
};
