export default {
  fanKuiLeiBie: '反馈类别',
  biTianXiangBuNeng: '必填项不能为空',
  huoDongXinJian: '活动信件',
  xuanZe: '选择',
  duoGeYongHuMing: '多个用户名请用逗号(,)或换行隔开，一次最多发送{val1}个账号',
  faSongZhangHao: '发送账号',
  qingXuanZeHuiYuan: '请选择会员层级',
  huiYuanCengJi: '会员层级',
  faSongZhanNeiXin: '发送站内信',
  geNBSP: '个,&nbsp;&nbsp;',
  nBSPN: ',&nbsp;&nbsp; 失败',
  ge: '个',
  chengGongFaSong: '成功发送',
  dianJiZhangHaoZhang: '（点击账号账号名可以复制）',
  gongXiNiXiuGai: '恭喜你，修改成功！',
  tiao: ')条:',
  huiYuanLieBiao: '会员列表(',
  qingShuRuSuoShu: '请输入所属代理',
  qingXuanZeVI: '请选择VIP等级',
  xuanZeHuiYuan: '选择会员',
  qingChaXunHuiYuan: '请查询会员账号',
  zhangHao: '账号',
  xiTongXiaoXi: '系统消息',
  baoCunShiBaiD: '保存失败.{val1}',
  changDuZaiDaoGe: '长度在 1 到 30 个字符',
  qingShuRuLeiBie: '请输入类别描述',
  leiBieMiaoShu: '类别描述',
  qingShuRuLeiBie2: '请输入类别名',
  leiBieMing: '类别名',
  xiangQing: '詳情',
  xiuGaiRen: '修改人',
  yiDuRenShu: '已读人数',
  faSongRenShu: '发送人数',
  souSuo: '搜索',
  zhiDuiAnZhaoYong: '只对按照用户名发送的生效',
  shanChuShiBaiM: '删除失败!{val1}',
  queDingYaoShanChu: '确定要删除改站内信吗？',
  shanChuZhanNeiXin: '删除站内信（{val1}）',
  xiuGaiShiJian: '修改时间',
  fanKuiLeiXing: '反馈类型',
  queDingYaoShanChu2: '确定要删除此反馈类别吗？',
  shanChuFanKuiLei: '删除反馈类别（{val1}）',
  aCTIO: '{val1}成功!',
  queDingYaoAC: '确定要{val1}此反馈类别吗？',
  aCTIO2: '{val1}反馈类别（{val2}）',
};
