export default {
  baoBiaoXLS: '报表.xlsx',
  chuXianWeiZhiCuo: '出现未知错误！请联系管理员！错误码为{val1}',
  qingQiuChuCuo: '请求出错',
  qingQiuCuoWuS: '请求错误 {val1}: {val2}',
  wangGuanChaoShi: '网关超时。',
  fuWuBuKeYong: '服务不可用，服务器暂时过载或维护。',
  wangGuanCuoWu: '网关错误。',
  fuWuQiFaSheng: '服务器发生错误，请检查服务器。',
  dangChuangJianYiGe: '当创建一个对象时，发生一个验证错误。',
  qingQiuDeZiYuan: '请求的资源被永久删除，且不会再得到的。',
  qingQiuDeGeShi: '请求的格式不可得。',
  faChuDeQingQiu: '发出的请求针对的是不存在的记录，服务器没有进行操作。',
  yongHuDeDaoShou: '用户得到授权，但是访问是被禁止的。',
  yongHuMeiYouQuan: '用户没有权限（令牌、用户名、密码错误）。',
  faChuDeQingQiu2: '发出的请求有错误，服务器没有进行新建或修改数据的操作。',
  shanChuShuJuCheng: '删除数据成功。',
  yiGeQingQiuYi: '一个请求已经进入后台排队（异步任务）。',
  xinJianHuoXiuGai: '新建或修改数据成功。',
  fuWuQiChengGong: '服务器成功返回请求的数据。',
  liuLanQiChuangKou: '浏览器窗口未改变',
  dISPL: '{val1}原',
  baoCunChengGong: '保存成功',
  gPiPeiHT:
    "?>', 'g'); // 匹配html标签的正则表达式，\"g\"是搜索匹配多个符合的内容\n  const msg = html.replace(re1, ''); // 执行替换成空字符\n  return msg;\n};\n\nconst trimsParams = (params: StateType) =>",
  oNELI:
    "` : oneLine;\n    j = i * maxLength;\n  }\n  return newText;\n};\n\n/**\n * 替换list中的字段\n * @param list\n * @param targetField\n * @param resultField\n */\nconst toReplaceList = (list: any[], targetField: string, resultField: string = 'value') =>",
  jOINZi:
    "`)\n    .join('&');\n};\n\n/**\n * 字符串折行\n * @param text 需要折行的字符串\n * @param maxLength 一行显示的最大长度\n */\nconst wrapText = (text: string, maxLength: number) =>",
  qingShuRuZhengShu: '请输入正数',
  buKeShuRuE: '不可输入emoji表情符号',
  weiZiFuZiMu: '8-20位字符、字母及数字组合',
  weiShuZiZiMu: '3-16位数字、字母组合',
  qingShuRuWeiDe: '请输入8-20位的密码',
  zhangHaoBiXuYi:
    '账号必须以字母开头，只能包含英文字母、数字，长度在 6 到 16 个字符',
  biXuZaiZhiJian: '必须在0-100之间',
  banBenHaoGeShi: '版本号格式不正确',
  miMaChangDuZai:
    '密码长度在8到20个字符，至少包含“数字/字母/特殊字符”的2种组合',
  yongHuMingBiXu:
    '用户名必须以字母开头，只能包含英文字母、数字，长度在 6 到 16 个字符',
  qingShuRuYongDou: '请输入用逗号分割的整数',
  yongHuMingZhiNeng: '用户名只能是汉字,数字,字母,下划线组合',
  yongHuMingChangDu: '用户名长度最大支持32位',
  zuiDuoZhiChiWei: '最多支持128位字符(中文不可超过64位)',
  qingShuRuYiH: '请输入以http或https开头的正确网址',
  weiDeShuZiZi: '5-12位的数字、字母组合',
  weiShuZiZiMu2: '5-20位数字、字母或下划线组合',
  weiShuZiZiMu3: '5-20位数字、字母组合',
  ziMuKaiTouZhi: '字母开头，只能由数字、字母_.组成',
  qingShuRuWeiDe2: '请输入6-20位的密码',
  qingShuRuZhengQue: '请输入正确的IP地址',
  yinHangKaBiXu: '银行卡必须是15到19位的数字',
  ninShuRuDeZhi: '您输入的支付宝账号有误',
  feiKaiTouDeWei: '非0开头的5-15位数字',
  weiDeShuZiZi2: '6-20位的数字、字母或下划线',
  tuPianGeShiBu: '图片格式不正确',
  buNengShuRuTe: '不能输入特殊字符',
  baoHanLiangWeiXiao: '包含两位小数',
  qingShuRuZhengQue2: '请输入正确的电话号码',
  qingShuRuZhengQue3: '请输入正确的邮箱地址',
  qingShuRuZhongWen: '请输入中文',
  qingShuRuDaYu: '请输入大于0的正整数',
  qingShuRuZhengZheng: '请输入正整数',
  qingShuRuZhengShu2: '请输入正数,且小数点不能大于两位',
  qingShuRuShuZi: '请输入数字',
  jianYanXiangWeiKong: '检验项为空',
  zuiDuoZhiChiR: '最多支持{val1}位字符(中文不可超过{val2}位)',
  henYiHanZuiDuo: '很遗憾！最多支持输入{val1}个{val2}！',
  ninShuRuDeT:
    "您输入的{val1}有重复，重复{val2}为：\n      {val3}\n      {val4})` : ''}",
};
