export default {
  xieYiLeiXing: '协议类型',
  shangHuZhuangTai: '商户状态',
  shangJiaZhuangTai: '上架状态',
  jinRiYiChuKuan: '今日已出款',
  meiRiChuKuanShang: '每日出款上限',
  rOWST: '{val1}三方提现设置',
  shangHuKaiQiHou:
    '商户开启后才可以在“出款配置及应用”中应用并上架， 若是关闭则“出款配置及应用”中的商户为关闭状态；关闭后财务出款人员无法使用此三方商户出款',
  rOWOP: '{val1}三方商户',
  shanChuSanFangZhi: '删除三方支付',
  iSEDI: '{val1}提现三方商户应用成功',
  daiFuFeiLuWei: '代付费率为纯数字，请重新输入',
  iSEDI2: '{val1}提现三方商户应用',
  qingXuanZeZhiChi: '请选择支持协议',
  zhiChiXieYi: '支持协议',
  qingXuanZeZhiChi2: '请选择支持的姓名格式',
  zhiChiXingMingGe: '支持姓名格式',
  qingXuanZeShiFou: '请选择是否启用脚本',
  qingShuRuMeiRi: '请输入每日出款上限数值',
  qingXuanZeChuKuan: '请选择出款银行配置',
  chuKuanYinHangPei: '出款银行配置',
  zhuanZhangJinE: '转账金额',
  qingShuRuChaXun: '请输入查询URL',
  chaXunURL: '查询URL',
  qingShuRuDaiFu: '请输入代付费率数值',
  daiFuFeiLu: '代付费率',
  uSDTTi: 'USDT提现',
  tITLE: '{val1}成功',
  zhuTITL: '注：{val1}',
  queDingTIT: '确定{val1}吗？',
};
