export default {
  index: {
    xiTongNeiZhi: '系统内置',
    canShuJianMing: '参数键名',
    canShuMingCheng: '参数名称',
    canShuJianZhiBu: '参数键值不能为空',
    canShuJianMingBu: '参数键名不能为空',
    canShuMingChengBu: '参数名称不能为空',
    miMaBuNengWei: '密码不能为空',
    xiTongCanShuPei: '系统参数配置',
    beiZhu: '备注',
    chuangJianShiJian: '创建时间',
    canShuJianZhi: '参数键值',
    canShuZhuJian: '参数主键',
    qingShuRuMiMa: '请输入密码',
    yongHuMiMa: '用户密码',
    yongHuMing: '用户名',
    shuRuCanShuJian: '输入参数键名',
    shuRuCanShuMing: '输入参数名称',
  },
};
