export default {
  BarChart: {
    paiDuiTongJi: '排队统计',
    zhan: '，占',
    zaiCiXuanRan: '再次渲染',
  },
  LineChart: {
    paiDuiJieRu: '排队接入',
    paiDuiShu: '排队数',
  },
  index: {
    pingJunPaiDuiShi: '平均排队时长',
    paiDuiLiKaiShu: '排队离开数/率',
    paiDuiJinRuHui: '排队进入会话数/率',
    zongHuiHuaShu: '总会话数',
    paiDuiTongJiShi: '排队统计时间',
    paiDuiBaoBiao: '排队报表',
    daNianALL: '大年allContents',
    paiDuiZhong: '排队中',
    tongJiWeiDu: '统计维度',
    paiDuiJieGuo: '排队结果',
    paiDuiShiChang: '排队时长',
    paiDuiKaiShiShi: '排队开始时间',
    ziXunLaiYuan: '咨询来源',
    keHuZu: '客户组',
    keHu: '客户',
    qingShuRuKeHu: '请输入客户账户',
    paiDuiJiLu: '排队记录',
  },
};
