export default {
  index: {
    zhiXingChengGong: '执行成功',
    qingShuRuCR: '请输入Cron表达式',
    qingShuRuFangFa: '请输入方法名称',
    qingShuRuBE: '请输入Bean名称',
    qingShuRuRenWu: '请输入任务名称',
    dingShiRenWu: '定时任务',
    shanChu: '删除',
    queDingTingZhiBing: '确定停止并删除该任务吗？',
    zanTing: '暂停',
    huiFu: '恢复',
    zhiXing: '执行',
    bianJi: '编辑',
    yunXingZhong: '运行中',
    yiZanTing: '已暂停',
    cRONBiao: 'cron表达式',
    canShu: '参数',
    zhiXingFangFa: '执行方法',
    bEANMing: 'Bean名称',
    renWuMingCheng: '任务名称',
    renWuMiaoShu: '任务描述',
    qiYong: '启用',
    renWuZhuangTai: '任务状态',
    cRONBiao2: 'Cron表达式',
    canShuNeiRong: '参数内容',
    riZhi: '日志',
    shuRuRenWuMing: '输入任务名称搜索',
  },
  log: {
    shiBai: '失败',
    renWuRiZhi: '任务日志',
    yiChangXiangQing: '异常详情',
    haoShiHaoMiao: '耗时(毫秒)',
    zhaKanXiangQing: '查看详情',
    daoChu: '导出',
    souSuo: '搜索',
    riZhiZhuangTai: '日志状态',
    jieShuRiQi: '结束日期',
    kaiShiRiQi: '开始日期',
    zhiXingRiZhi: '执行日志',
  },
};
