export default {
  index: {
undefinedundefinedundefinedweiJieJue: "Chưa giải quyết", 
yiJieJue: "Đã giải quyết", 
wuXiaoHuiHua: "Đối thoại vô hiệu", 
youXiaoHuiHua: "Đối thoại có hiệu lực", 
weiZongJie: "Chưa tổng kết", 
undefinedundefinedundefinedundefinedundefinedundefinednullnullundefinedxiaoXiShuKeHu: "Số lượng tin nhắn (khách hàng / chăm sóc khách hàng)", 
keFuZongJie: "Tổng kết chăm sóc khách hàng", 
nullundefinedundefinedhuiHuaKaiShiShi: "Thời gian bắt đầu đối thoại", 
wenTiShiChang: "Câu hỏi / Thời gian", 
undefinednullnullundefinedundefinedundefinedundefinedundefinedundefinedundefinedundefinedundefinedgengDuoShaiXuanTiao: "Các bộ lọc khác \ n", 
gengDuoShaiXuanTiao2: "Các bộ lọc khác", 
undefinedundefinedundefinedundefinednullundefinedmiao: "Giây", 
undefinedundefinedhuiHuaShiChang: "Thời gian đối thoại", 
nullquanBuJiNengZu: "Tất cả nhóm kỹ năng", 
  },
  session_table: {
yiPingJia: "Đã đánh giá", 
yiPingJia: "Đã đánh giá", 
weiPingJia: "Chưa đánh giá", 
nullzuiDaXiangYingShi: "Thời gian phản hồi lớn nhất", 
shouXiangShiChang: "Thời gian phản hồi đầu tiên", 
nullshiFouJieJue: "Đã giải quyết chưa", 
zhuDongPingJia: "Chủ động đánh giá", 
yaoQingPingJia: "Mời đánh giá·", 
shiFouPingJia: "Đã đánh giá", 
keHuPingJia: "Khách hàng đánh giá", 
yeWu: "Doanh nghiệp", 
  },
};
