export default {
  PieChart: {
null  },
  a: {
nullnullnullnullnull  },
  barOne: {
null  },
  chatInfo: {
language: "ภาษา", 
language: "ภาษา", 
anZhuo: "แอนดรอยด์", 
nullnullnullnullnullnullnullnullnullnullnullnullnullnullnullkeHuZiXunCi: "จำนวนครั้งที่ลูกค้าสอบถาม", 
nullkeHuDuanKeFu: "หน้าลูกค้า/เวอร์ชันระบบบริการลูกค้า", 
jinRuYuMing: "เข้าถึงชื่อโดเมน：", 
iPDiZhi: "ที่อยู่ IP.", 
fangWenLiuLanQi: "เข้าถึงเบราว์เซอร์：", 
nulljinRuYeMian: "หน้าการเข้าถึง", 
nullnullkeHuXinXi: "ข้อมูลลูกค้า", 
nullpingJiaNeiRong: "เนื้อหาการประเมิน", 
nullpingJiaXingJi: "การประเมินระดับดาว", 
nullnullnullnullnullfuWuZongJie: "สรุปบริการ", 
weiZhiJian2: "ยังไม่ผ่านการตรวจสอบ", 
yiZhiJian2: "ตรวจสอบแล้ว", 
nullxiaZhuZhangHao: "วางบัญชี:", 
dingDanZhuangTai: "สถานะรายการ:", 
nullnullnull
shuYingJieGuo: "ผลการชนะ/แพ้:", 
shuYingJieGuo: "ผลการชนะ/แพ้:", 
xiaZhuJinE: "จำนวนเงินเดิมพัน:", 
youXiChanPin: "สินค้าเกม:", 
tiXianZhangHao: "หมายเลขบัญชีถอน:", 
daoZhangShuLiang: "จำนวนเงินที่เข้าบัญชี:", 
tiXianJinE: "จำนวนเงินที่ถอน:", 
tiXianFangShi: "วิธีการถอนเงิน:", 
nullnullnullchongZhiZhangHao: "เลขที่บัญชีเงินฝาก:", 
nullzhiFuFangShi: "วิธีการชำระ", 
chongZhiFangShi: "วิธีการ ฝากเงิน", 
dingDanHao: "เลขรายการ", 
yiChangGuanBi: "ปิดผิดปกติ", 
chiXuShiChang: "ระยะเวลา:", 
nullnullnullnullnullnulljieRuFangShi: "วิธีการเข้าถึง", 
nullnullzongJieLeiXing: "ประเภทสรุป", 
nullzuoTian: "เมื่อวาน", 
jinTian: "วันนี้", 
  },
  chatInfoResult: {
zhiJianShiJian: "เวลาตรวจสอบคุณภาพ", 
zhiJianShiJian: "เวลาตรวจสอบคุณภาพ", 
zhiJianRen: "คนตรวจสอบคุณภาพ", 
nullnullnullnullnullnullfen2: "คะแนน", 
null  },
  chatInfoSubmit: {
zhiJianChengGong: "การควบคุมคุณภาพสำเร็จ", 
zhiJianChengGong: "การควบคุมคุณภาพสำเร็จ", 
fenShuBuZaiZhi: "คะแนนไม่อยู่กฎเกณฑ์ที่ตั้งไว้", 
nullnullnullnullnullnullnullnullnullnullnullnullnullnullnull  },
  dateCommon: {
shiJianXuanZeFan: "ช่วงเวลาเลือกได้ไม่เกิน 31 วัน!", 
shiJianXuanZeFan: "ช่วงเวลาเลือกได้ไม่เกิน 31 วัน!", 
null  },
  editSelect: {
nullnullnull  },
  filters: {
chuFa: "11 ทริกเกอร์", 
chuFa: "11 ทริกเกอร์", 
null  },
  onlineServer: {
nullnull  },
  serviceSummary: {
feiKeFuWuFa: "ไม่ใช่ฝ่ายบริการลูกค้าไม่สามารถส่งได้!", 
feiKeFuWuFa: "ไม่ใช่ฝ่ายบริการลูกค้าไม่สามารถส่งได้!", 
qingXuanZeYeWu: "กรุณาเลือกธุรกิจ", 
iDPaiXu: "การเรียงลำดับ ไอดี", 
nullnullxuanZeYeWu: "เลือกธุรกิจ", 
nullqingXuanZeSuoShu: "กรุณาเลือกธุรกิจของคุณ", 
zongJie: "สรุป", 
nullzongJie2: "สรุป", 
yu: "ใน", 
nullbeiZhuShuoMing: "หมายเหตุ:", 
yeWuLeiXing2: "ประเภทธุรกิจ:", 
nullnullnullzheShiGeWuXiao: "นี่เป็นบทสนทนาที่ไม่มีประสิทธิภาพ", 
youXiaoHuiHuaTi: "บทสนทนาที่มีประสิทธิภาพ ส่งสรุป", 
qingTianXieBeiZhu: "กรุณากรอกหมายเหตุ", 
benYeWuWeiPei: "ไม่มีการกำหนดค่าประเภทสำหรับบริการนี้", 
qingXuanZeYeWu2: "กรุณาเลือกประเภทบริการ", 
wo: "ฉัน", 
  },
  setBoard: {
nullnull  }
}
