export default {
  index: {
    qieHuan: '切换',
    laiYuanZhongHouTai: '来源中后台',
    laiYuanYouKe: '来源游客',
    qiYong: '启用',
    jinYong: '禁用',
    keHuMOM: '客户 momo699 与客服 shirry 的会话详情',
    laHeiLiShiJi: '拉黑历史记录',
    lianXiKeFuJi: '联系客服记录',
    keHuXiangQingLie: '客户详情列表',
    jieChuKeFu: '解除客服',
    jieChuLeiXing: '解除类型',
    laHeiYuanYin: '拉黑原因',
    laHeiLaiYuan: '拉黑来源',
    laHeiKeFu: '拉黑客服',
    laHeiShiJian: '拉黑时间',
    huiHuaZhong: '会话中',
    renGongXiaoXiShu: '人工消息数',
    weiPingJia: '未评价',
    manYiDu: '满意度',
    weiChuLi: '未处理',
    yiChuLi: '已处理',
    chuLiZhuangTai: '处理状态',
    suoShuYeWu: '所属业务',
    huiHuaLaiYuan: '会话来源',
    jieDaiKeFu: '接待客服',
    jiNengZu: '技能组',
    paiDuiShiChang: '排队时长',
    huiHuaShiChang: '会话时长',
    huiHuaKaiShiShi: '会话开始时间',
    chuangJianShiJian: '创建时间：',
    fangWenLaiYuan: '访问来源：',
    keHuFenZu: '客户分组：',
    keHuDengJiV: '客户等级/VIP级别：',
    liXian: '离线',
    zaiXianHuiHuaZhong: '在线会话中',
  },
};
