export default {
  index: {
nullnulllaiYuanZhongHouTai: "ที่มาระบบหลังบ้าน", 
laiYuanYouKe: "ที่มาผู้เยี่ยมชม", 
nullnullkeHuMOM: "รายละเอียดบทสนทนาของลูกค้า momo699 และเชอร์รีฝ่ายบริการลูกค้า", 
laHeiLiShiJi: "ประวัติการถูกบล็อก", 
lianXiKeFuJi: "ติดต่อบันทึกการบริการลูกค้า", 
keHuXiangQingLie: "รายการรายละเอียดลูกค้า", 
jieChuKeFu: "ยกเลิกบริการลูกค้า", 
jieChuLeiXing: "ประเภทการยกเลิก", 
nulllaHeiLaiYuan: "ที่มาการบล็อก", 
laHeiKeFu: "บริการลูกค้าบล็อก", 
laHeiShiJian: "เวลาบล็อก", 
nullrenGongXiaoXiShu: "จำนวนข้อความของพนังงาน", 
nullmanYiDu: "ความพึงพอใจ", 
weiChuLi: "ยังไม่ดำเนินการ", 
yiChuLi: "ดำเนินการแล้ว", 
nullnullhuiHuaLaiYuan: "ที่มาบทสนทนา", 
nullnullnullnullnullnullnullnullnullliXian: "ออฟไลน์", 
  },
};
