export default {
  Category: {
diSanChanYe: "Công nghiệp cấp 3", 
diSanChanYe: "Công nghiệp cấp 3", 
diSanChanYe: "Công nghiệp cấp 3", 
diSanChanYe: "Công nghiệp cấp 3", 
diErChanYe: "Công nghiệp cấp 2", 
diYiChanYe: "Công nghiệp cấp 1", 
quanGuoHongGuanJing: "Các chỉ tiêu Kinh tế Vĩ mô Quốc gia 2011", 
quanGuoHongGuanJing2: "Các chỉ tiêu Kinh tế Vĩ mô Quốc gia 2010", 
quanGuoHongGuanJing3: "Các chỉ tiêu Kinh tế Vĩ mô Quốc gia 2009", 
quanGuoHongGuanJing4: "Các chỉ tiêu Kinh tế Vĩ mô Quốc gia 2008", 
quanGuoHongGuanJing5: "Các chỉ tiêu Kinh tế Vĩ mô Quốc gia 2007", 
quanGuoHongGuanJing6: "Các chỉ tiêu Kinh tế Vĩ mô Quốc gia 2006", 
quanGuoHongGuanJing7: "Các chỉ tiêu Kinh tế Vĩ mô Quốc gia 2005", 
quanGuoHongGuanJing8: "Các chỉ tiêu Kinh tế Vĩ mô Quốc gia 2004", 
quanGuoHongGuanJing9: "Các chỉ tiêu Kinh tế Vĩ mô Quốc gia 2003", 
quanGuoHongGuanJing10: "Các chỉ tiêu Kinh tế Vĩ mô Quốc gia 2002", 
gDPZhanBi: "Tỷ lệ GDP", 
fangDiChan: "Giá bất động sản", 
jinRong: "Tài chính", 
gDPYiYuan: "GDP (100 triệu CNY)", 
xinJiang: "Tân Cương", 
ningXia: "Ninh Hạ", 
qingHai: "Thanh Hải", 
ganSu: "Cam Túc", 
shanXi: "Thiểm Tây", 
xiZang: "Tây Tạng", 
yunNan: "Vân Nam", 
guiZhou: "Quý Châu", 
siChuan: "Tứ Xuyên", 
chongQing: "Trùng Khánh", 
haiNan: "Hải Nam", 
guangXi: "Guảng Tây", 
guangDong: "Guảng Đông", 
huNan: "Hồ Nam", 
huBei: "Hồ Bắc", 
heNan: "Hà Nam", 
shanDong: "Sơn Đông", 
jiangXi: "Giang Tây", 
zheJiang: "Triết Giang", 
jiangSu: "Giang Tô", 
shangHai: "Thượng Hải", 
heiLongJiang: "Hắc Long Giang", 
jiLin: "Cát Lâm", 
liaoNing: "Liêu Ninh", 
neiMengGu: "Nội Mông", 
shanXi2: "Sơn Tây", 
heBei: "Hà Bắc", 
tianJin: "Thiên Tân", 
beiJing: "Bắc Kinh", 
shuJuLaiZiGuo: "Dữ liệu từ Cục Thống kê Quốc gia", 
gDPDaDao: "GDP đạt mức cao khác", 
bGDPDa: "{b} GDP đạt mức cao", 
ningXia2: "Ninh Hạ", 
ganSu2: "Cam Túc", 
xiZang2: "Tây Tạng", 
guiZhou2: "Quý Châu", 
chongQing2: "Trùng Khánh", 
guangXi2: "Guảng Tây", 
huNan2: "Hồ Nam", 
heNan2: "Hà Nam", 
jiangXi2: "Giang Tây", 
anHui2: "An Huy", 
jiangSu2: "Giang Tô", 
heiLongJiang2: "Hắc Long Giang", 
  },
  Funnel: {
zhanXian: "Hiển thị", 
zhanXian: "Hiển thị", 
zhanXian: "Hiển thị", 
zhanXian: "Hiển thị", 
dianJi: "Nhấp vào", 
dingDan: "Giao dịch", 
  Gauge: {
wanChengLu: "Tỷ lệ thành công", 
wanChengLu: "Tỷ lệ thành công", 
  },
  Graph: {
diKaErZuoBiao: "Đồ thị trên tọa độ Đề-các", 
diKaErZuoBiao: "Đồ thị trên tọa độ Đề-các", 
diKaErZuoBiao: "Đồ thị trên tọa độ Đề-các", 
diKaErZuoBiao: "Đồ thị trên tọa độ Đề-các", 
zhouRi: "Chủ nhật", 
zhouLiu: "Thứ 7", 
zhouWu: "Thứ 6", 
henChangHenChangDe: "Ngày dài của thứ 5", 
  },
  Point: {
jieDian: "Node 4", 
jieDian: "Node 4", 
jieDian: "Node 4", 
jieDian: "Node 4", 
jieDian2: "Node 1", 
  },
  Rich: {
nullnullbiYing: "Cần thiết", guGe: "Google", guGe: "Google", baiDu: "Baidu", baiDu: "Baidu", 
shiPinGuangGao: "Video quảng cáo", 
lianMengGuangGao: "Liên kết quảng cáo", 
youJianYingXiao: "Email tiếp thị", 
  },
  Scatter: {
yuNianGeGuoJia: "Tuổi thọ trung bình và GDP theo quốc gia trong năm 1990 và 2015", 
  },
  WordCloud: {
chuGuoYou: "Du lịch nước ngoài", 
chuGuoYou: "Du lịch nước ngoài", 
chuGuoYou: "Du lịch nước ngoài", 
chuGuoYou: "Du lịch nước ngoài", 
luYouWangZhanPian: "Tùy chọn trang web du lịch", 
guanZhuJingDian: "Theo dõi các địa điểm du lịch", 
jiuDian: "Khách sạn", 
yuanTuChuXingFang: "Du lịch xa", 
guoNeiYou: "Du lịch nội địa", 
jingDianLeiXing: "Địa điểm hấp dẫn", 
luYouChuXing: "Du lịch", 
wangLuoQiWen: "Giai thoại trên Internet", 
shiShang: "Thời trang", 
sheHuiShiZheng: "Thời sự xã hội", 
keJiZiXun: "Thông tin công nghệ", 
junShi: "Quân sự", 
yuLeBaGua: "Thông tin giải trí", 
shangYeCaiJing: "Tài chính kinh doanh", 
yanChuPiaoWu: "Bán vé show diễn", 
xiQuQuYi: "Nghệ thuật Opera", 
guangBoDianTai: "Đài phát thanh", 
zhiBo: "Live Streaming", 
yinYue: "Âm nhạc", 
dongMan: "Động vật", 
dianShi: "TV", 
  },
};
