export default {
  index: {
zanWuZaiXianKe: "ไม่มีบริการลูกค้าออนไลน์ในขณะนี้!", 
zanWuZaiXianKe: "ไม่มีบริการลูกค้าออนไลน์ในขณะนี้!", 
zanWuZaiXianKe2: "ไม่มีบริการลูกค้าออนไลน์ในขณะนี้!", 
nullnullziXunShu: "จำนวนสอบถาม", 
nullnullchaPingLu: "แบบประเมินที่ไม่ดี %", 
chaPingShuLu: "จำนวน/อัตราแบบประเมินที่ไม่ดี % (1-2)", 
zhongPingLu: "อัตราแบบประเมินปานกลาง %", 
zhongPingShuLu: "จำนวน/อัตราแบบประเมินปานกลาง (3-4)", 
haoPingLu: "แบบประเมินดี %", 
haoPingShuLuFen: "จำนวน/อัตราแบบประเมินที่ดี (5)", 
pingJiaJieJueLu: "อัตราความละเอียดในการประเมิน %", 
pingJiaJieJueShu: "จำนวน/อัตราความละเอียดในการประเมิน", 
pingJunKeHuPing: "คะแนนเฉลี่ยแบบประเมินของลูกค้า", 
keHuZhuDongPing: "อัตราการประเมินโดยลูกค้าเอง %", 
keHuZhuDongPing2: "จำนวน/อัตราของการประเมินโดยลูกค้าเอง", 
keFuYaoQingPing: "อัตราคำเชิญประเมินการบริการ %", 
keFuYaoQingPing2: "จำนวน/อัตราคำเชิญประเมินการบริการ", 
nullkeHuPingJiaShu: "จำนวน/อัตราการประเมินของลูกค้า", 
nullnullnullnullnullnullnullnullnullnullnullnullnullnullxing6: "ดาว", 
nullnullnullnullpingJiaXinXi: "รายละเอียดการประเมิน", 
nullnullnullnull    zanWuShuJuQing:
      '\n            暂无数据，请重新选择搜索条件进行查询！\n          ',
nullnullnullnullkeHuPingJiaJi: "บันทึกการประเมินของลูกค้า", 
  },
  serversevalua: {
nullnullkeFuPingJiaBao: "รายงานการประเมินการบริการลูกค้า", 
chaPingShuChaPing: "จำนวนการประเมินที่ไม่ดี/อัตราการประเมินที่ไม่ดี", 
zhongPingShuZhongPing: "จำนวนการประเมินปานกลาง/อัตราการประเมินปานกลาง", 
haoPingShuHaoPing: "จำนวนการประเมินดี/อัตราการประเมินดี", 
pingJunPingJiaFen: "คะแนนการประเมินเฉลี่ย", 
yaoQingPingJiaShu: "จำนวนคำเชิญประเมิน/อัตราการเชิญ", 
pingJiaShuPingJia: "จำนวนการประเมิน/อัตราการประเมิน", 
nullnullnull  },
};
