export default {
  index: {
zanWuZaiXianKe: "Dịch vụ khách hàng không có online!", 
zanWuZaiXianKe: "Dịch vụ khách hàng không có online!", 
zanWuZaiXianKe: "Dịch vụ khách hàng không có online!", 
zanWuZaiXianKe: "Dịch vụ khách hàng không có online!", 
zanWuZaiXianKe2: "Dịch vụ khách hàng không có online!", 
zhongPingLu: "% Đánh giá trung bình", zhongPingLu: "% Đánh giá trung bình", 
zhongPingShuLu: "（1-2）Số lượng/tỷ lệ đánh giá trung bình", 
haoPingLu: "% Đánh giá tốt", 
haoPingShuLuFen: "（1-2）Số lượng/tỷ lệ đánh giá tốt", 
pingJiaJieJueLu: "% Tỷ lệ đánh giá giải quyết", 
pingJiaJieJueShu: "% Số lượng đánh giá giải quyết", 
pingJunKeHuPing: "Đánh giá trung bình của khách hàng", 
keHuZhuDongPing: "% Tỷ lệ chủ động đánh giá của khách hàng", 
keHuZhuDongPing2: "% Số lượng chủ động đánh giá của khách hàng", 
keFuYaoQingPing: "% Tỷ lệ đánh giá lời mời dịch vụ khách hàng", 
keFuYaoQingPing2: "% Số lượng đánh giá lời mời dịch vụ khách hàng", 
      '\n            暂无数据，请重新选择搜索条件进行查询！\n          ',
nullnullnullnullkeHuPingJiaJi: "Lịch sử đánh giá của khách hàng",   },  serversevalua: {
nullnullkeFuPingJiaBao: "Báo cáo đánh giá dịch vụ khách hàng", chaPingShuChaPing: "Số lượng / tỷ lệ đánh giá tệ", chaPingShuChaPing: "Số lượng / tỷ lệ đánh giá tệ", zhongPingShuZhongPing: "Số lượng / tỷ lệ đánh giá trung bình", zhongPingShuZhongPing: "Số lượng / tỷ lệ đánh giá trung bình", 
haoPingShuHaoPing: "Số lượng / tỷ lệ đánh giá trung tốt", 
pingJunPingJiaFen: "Đánh giá trung bình", 
nullnullnull  },
};
