export default {
  config: {
undefinedundefinedundefinedundefinedundefinedundefinedundefinedundefinedundefinedundefinednullnullundefinedundefinedundefinedundefinedundefinedundefinedundefinedundefinedundefinedundefinedundefinedundefinedundefinedundefinedundefinedundefinedqingXuanZe: "Chọn", 
undefinedundefinedundefinedundefinedundefinedundefinedundefinedundefinedundefinedundefinedundefinedundefinedundefinedundefinedundefinedundefinedundefinedundefinedundefinedundefined  },
  index: {
undefinedundefinednullundefinedundefinedcaoZuo: "Thao tác", 
chuangJianRiQi: "Ngày tạo", 
undefinedundefinedundefinedundefined  },
};
