export default {
  config: {
shengChengChengGong: "Tạo thành công", 
shengChengChengGong: "Tạo thành công", 
shengChengChengGong: "Tạo thành công", 
shengChengChengGong: "Tạo thành công", 
jieKouMingChengBu: "Tên kết nối không được để trống", 
qianDuanLuJingBu: "Front-end không thể để trống", 
baoLuJingBuNeng: "Đường dẫn gói không được để trống", 
zuoZheBuNengWei: "Tác giả không được để trống", 
jinFangWuCaoZuo: "Cẩn thận với việc thao tác sai, hãy lựa chọn cẩn thận", 
moRenBuQuChu: "Tiền tố bảng không bị loại bỏ theo mặc định và có thể được tùy chỉnh", 
moRenBuQuChu2: "Tiền tố bảng không bị xóa theo mặc định", 
quBiaoQianZhui: "Tiền tố bàn", 
shuRuVIE: "Nhập thư mục dưới mục views, tạo nó nếu không tồn tại", 
qianDuanLuJing: "Front-end", 
jieKouDeMingCheng: "Tên của giao diện, được sử dụng trong bộ điều khiển và tài liệu giao diện", 
jieKouMingCheng: "Tên giao diện", 
xiangMuBaoDeMing: "Tên của dự án, trong gói mà mã được tạo được đặt", 
zhiYuBaoXia: "Đối với gói", 
moKuaiDeMingCheng: "Tên của mô-đun, vui lòng chọn một mô-đun đã tồn tại trong dự án", 
moKuaiMingCheng: "Tên mô-đun", 
leiShangMianDeZuo: "Tên tác giả trên lớp", 
zuoZheMingCheng: "Tên tác giả", 
ziDongChuangJianShi: "Thời gian tạo tự động", ziDongChuangJianShi: "Thời gian tạo tự động", 
riQiZhuJie: "Chú thích ngày tháng", 
chaXunFangShi: "Hình thức kiểm tra", 
riQiKuang: "Khung ngày tháng", 
xiaLaKuang: "Khung kéo xuống", 
danXuanKuang: "Khung đơn", 
wenBenYu: "Lĩnh vực căn bản", 
wenBenKuang: "Khung văn bản", 
biaoDanLeiXing: "Loại biểu mẫu", 
biaoDan: "Biểu mẫu", 
lieBiao: "Danh sách", 
ziDuanLeiXing: "Loại lĩnh vực", 
  },
  index: {
shengCheng: "Tạo", 
shengCheng: "Tạo", 
shengCheng: "Tạo", 
shengCheng: "Tạo", 
yuLan: "Xem trước", 
  },
};
