export default {
  App: {
jianTing: "Giám thính 11111", 
  },
  home: {
keFuYiBeiJin: "Dịch vụ khách hàng đã bị vô hiệu", 
keFuYiBeiJin: "Dịch vụ khách hàng đã bị vô hiệu", 
keFuYiBeiJin: "Dịch vụ khách hàng đã bị vô hiệu", 
keFuYiBeiJin: "Dịch vụ khách hàng đã bị vô hiệu", 
haoDeWoQuPei: "Ok, tôi sẽ cấu hình", 
ninYiXiaDeJi: "Lời chào cá nhân cho nhóm kỹ năng của bạn chưa định cấu hình. Vui lòng đăng nhập vào trang làm việc sau khi cấu hình:", 
bangWanHao: "Chào buổi chiều!", bangWanHao: "Chào buổi chiều!", 
xiaWuHao: "Chào buổi trưa!", 
zhongWuHao: "Chào buổi trưa!", 
shangWuHao: "Chào buổi sáng!", 
zaoShangHao: "Chào buổi sáng!", 
lingChenHao: "Chào buổi sáng!", 
keFuLieBiao: "Danh sách dịch vụ khách hàng", 
keFuGongZuoTai: "Trang làm việc của hỗ trợ khách hàng", 
kuaiSuKaiShiBian: "Bắt đầu nhanh / Điều hướng dễ dàng", 
shangCiDengLuShi: "\ n Lần đăng nhập cuối cùng: \ n", 
  },
  login: {
jiesuonidezhanghao: "Liên hệ với quản trị viên của bạn để mở khóa tài khoản của bạn!", 
jiesuonidezhanghao: "Liên hệ với quản trị viên của bạn để mở khóa tài khoản của bạn!", 
jiesuonidezhanghao: "Liên hệ với quản trị viên của bạn để mở khóa tài khoản của bạn!", 
jiesuonidezhanghao: "Liên hệ với quản trị viên của bạn để mở khóa tài khoản của bạn!", 
haoDeWoZhiDao: "OK, Tôi biết rồi", 
ninDeZhangHaoMi: "Tài khoản / mật khẩu của bạn bị khóa và không thể đăng nhập lại do đăng nhập sai quá nhiều lần", 
zhangHaoYiBeiSuo: "Tài khoản bị khoá", 
zhongShi: "Thử lại", 
wangLuoYiChangQing: "Mạng bất thường, thử lại!", 
      '\n        请您先打开Google验证器，扫码绑定后再登录。\n      ',
gaiZhangHuHaiWei: "Tài khoản chưa liên kết với mã xác minh của Google và không thể đăng nhập.", 
gaiZhangHuHaiWei: "Tài khoản chưa liên kết với mã xác minh của Google và không thể đăng nhập.", 
gaiZhangHuHaiWei: "Tài khoản chưa liên kết với mã xác minh của Google và không thể đăng nhập.", 
null    yanZhengMaXianShi:
      '验证码显示不出来时，请尝试清除浏览器缓存后重新启动浏览器或者更换浏览器。',
qingShuRuGO: "Nhập mã xác minh google", 
qingShuRuGO: "Nhập mã xác minh google", 
qingShuRuGO: "Nhập mã xác minh google", 
  },
};
