export default {
caiJiNeiRongXiang: "รายละเอียดเนื้อหาคอลเลกชัน", 
caiJiNeiRongXiang: "รายละเอียดเนื้อหาคอลเลกชัน", 
nullneiCunXinXi: "ข้อมูลหน่วยความจำ", 
nullcPUZongShu: "จำนวนซีพียูทั้งหมด", 
shiFouYouSD: "มี SD การ์ดหรือไม่", 
pingMuGaoDu: "ความสูงของหน้าจอ", 
pingMuKuanDu: "ความกว้างของหน้าจอ", 
keHuDuanDiLi: "ที่ตั้งทางภูมิศาสตร์ของหน้าลูกค้า", 
lianWangLeiXing: "ประเภทเครือข่าย", 
jieRuYuMing: "เข้าถึงชื่อโดเมน", 
nullziXunWenTiLei: "ประเภทคำถามให้คำปรึกษา", 
faQiQingQiuLu: "เส้นทางขอ", 
faQiQingQiuJie: "เริ่มต้นอินเทอร์เฟซคำขอ", 
keHuDuanBanBen: "เวอร์ชันหน้าลูกค้า", 
nullcaiJiLieBiao: "รายการรวบรวม", 
caiJiXiangQing: "รายละเอียดรวบรวม", 
nullnulldiLiWeiZhi: "ที่ตั้ง", 
caiJiJieMianMing: "ชื่อส่วนต่อประสานรวบรวม", 
xiTongHuanJing: "สภาพแวดล้อมของระบบ", 
zhongDuanLeiBie: "ประเภทเทอร์มินัล", 
nullnulltiJiaoShiJian: "เวลายื่น", 
nullqingXuanZeZhongDuan: "โปรดเลือกประเภทเทอร์มินัล", 
nullqingXuanZeXiTong: "กรุณาเลือกสภาพแวดล้อมของระบบ", 
};
