export default {
undefinedundefinedundefinedundefinedcPUShiYong: "Sử dụng CPU", 
undefinedundefinedundefinedundefinedundefinedundefinedundefinedundefinedundefinedundefinedundefinedundefinedundefinedundefinedundefinedcaoZuo: "Thao tác", 
undefinedundefinedundefinedundefinedundefinedundefinedundefinedundefinednullundefinednullundefined};
