export default {
  index: {
dingJiLeiMu: "Danh mục hàng đầu", 
dingJiLeiMu: "Danh mục hàng đầu", 
dingJiLeiMu: "Danh mục hàng đầu", 
dingJiLeiMu: "Danh mục hàng đầu", 
qingShuRuDiZhi: "Nhập địa chỉ", 
caiDan: "Mục lục", 
huanCun: "Cache", 
waiLian: "Liên kết bên ngoài", 
zuJianLuJing: "Thành phần đường dẫn", 
quanXianBiaoZhi: "ID quyền hạn", 
luYouDiZhi: "Địa chỉ định tuyến", 
tuBiao: "Biểu tượng", 
caiDanMingCheng: "Tên mục lục", 
shangJiLeiMu: "Mục lục cấp trên", 
piPeiZuJianNei: "Khớp tên trong thành phần", 
zuJianMingCheng: "Tên thành phần", 
caiDanPaiXu: "Sắp xếp mục lục", 
anNiuMingCheng: "Tên nút", 
caiDanBiaoTi: "Tiêu đề mục lục", 
caiDanKeJian: "Mục lục thấy được", 
caiDanHuanCun: "Mục lục cache", 
waiLianCaiDan: "Mục lục liên kết bên ngoài", 
dianJiXuanZeTu: "Nhấp chọn biểu tượng", 
caiDanTuBiao: "Mục lục biểu tượng", 
anNiu: "Nút", 
  },
};
