export default {
  index: {
undefinedundefinednullpingJunHuiHuaShi: "Thời gian trung bình đối thoại", 
jieDaiYaLiZhi: "Giá trị áp tiếp đón", 
huiFuLu: "Tỷ lệ phản hồi", 
jieDaiKeHuShu: "Số lượng khách hàng đã nhận", 
keHuKeFuXiao: "Khách hàng / tin nhắn chăm sóc khách hàng", 
dengLuShiChang: "Thời gian đăng nhập:", 
keHuPingJiaPing: "Đánh giá trung bình của khách hàng", 
keHuPingJiaLu: "Tỷ lệ / số lượng khách hàng đánh giá", 
yaoQingPingJiaLu: "Tỷ lệ / số lượng lời mời đánh giá", 
keFuJieJueLu: "Tỷ lệ / Số lượng giải quyết chăm sóc khách hàng", 
keFuZongJieLu: "Tỷ lệ / số lượng tổng kết chăm sóc khách hàng", 
sNeiXiangYingYing: "Tốc độ phản hồi trong vòng 30 giây", 
zuiDaXiangYingShi: "Thời gian phản hồi lớn nhất", 
pingJunShouXiangShi: "Thời lượng trung bình phản hồi đầu tiên", 
undefinedzuiDaJieDaiShu: "Số lần tiếp nhận tối đa", 
zhuanChuHuiHuaShu: "Số lượng đối thoại chuyển đi", 
huiHuaShuYouXiao: "Số lượng đối thoại / số lượng hợp lệ", 
mangLu: "Bận", 
undefinedundefinedsheZhiXianShiCan: "Đặt thông số hiển thị", 
keFuFenZu: "Nhóm dịch vụ khách hàng", 
  },
};
