export default {
  index: {
undefinedundefinedqueDing: "Xác nhận", 
tiShi: "Gợi ý", 
undefinedwuXiaoHuiHua: "Đối thoại vô hiệu", 
youXiaoHuiHua: "Đối thoại có hiệu lực", 
weiZongJie: "Chưa tổng kết", 
undefinedweiJieJue: "Chưa giải quyết", 
yiJieJue: "Đã giải quyết", 
weiZhiJian: "Chưa kiểm chứng", 
yiZhiJian: "Đã kiểm chứng", 
undefinedundefinedzhuDongPingJia: "Chủ động đánh giá", 
yaoQingPingJia: "Mời đánh giá·", 
yiPingJia: "Đã đánh giá", 
weiPingJia: "Chưa đánh giá", 
undefinedzhiJianZhuangTai: "Trạng thái kiểm duyệt", 
xing: "Sao", 
undefinedshiFouJieJue: "Đã giải quyết chưa", 
undefinednullshiFouPingJia: "Đã đánh giá", 
keHuPingJia: "Khách hàng đánh giá", 
yeWu: "Doanh nghiệp", 
huiHuaLeiBie: "Phân loại đối thoại", 
keFuZongJie: "Tổng kết chăm sóc khách hàng", 
nullundefinedhuiHuaKaiShiShi: "Thời gian bắt đầu đối thoại", 
wenTiShiChang: "Câu hỏi / Thời gian", 
undefinedundefinednullundefinedquanBuJiNengZu: "Tất cả nhóm kỹ năng", 
  },
};
