export default {
  addInfoDialog: {
    tuPianShangChuanShi: '图片上传失败',
    tuPianShangChuanCheng: '图片上传成功！',
    shangChuanDeTuPian: '上传的图片宽高比列必须是2:3且最宽不能超过120px',
    shangChuanTouXiangTu: '上传头像图片大小不能超过 2MB!',
    biaoTiBuNengWei: '标题不能为空',
    waiBuLianJie: '外部链接',
    neiBuLianJie: '内部链接',
    wu: '无',
    luJingBuNengBao: '路径不能包含中文',
    luJingBiXuYi: '路径必须以/开头',
    qingShuRuYiH: '请输入以http或https开头的url地址',
    qingShuRuZhengQue: '请输入正确的格式',
    qingShuRuLianJie: '请输入链接url，例:http或https://www.baidu.com',
    qingShuRuUR: '请输入url路径，例:/systemSetting',
    lianJieURL: '链接url',
    lianJieURL2: '链接url路径',
    lianJieLeiXing: '链接类型',
    jianYiShangChuanDe: '建议上传120*180的图片',
    kuanGaoBiZuiDa: '宽高比2:3，最大宽度120',
    shuoMing: '说明：',
    tianJiaTuPian: '添加图片',
    qingShuRuBiaoTi: '请输入标题,最多6个字符！',
    biaoTi: '标题',
    tianJiaTuWenTong: '添加图文通知',
  },
  index: {
    ninQueRenYaoShan: '您确认要删除该通告？',
    queRenShanChu: '确认删除',
    xiaJia: '下架',
    chengGong: '成功！',
    shangJia: '上架',
    gaiTongGao: '该通告？',
    ninQueRenYao: '您确认要',
    xiangQing: '详情',
    xiaJiaShiJian: '下架时间',
    shangJiaShiJian: '上架时间',
    tongZhiGuanLi: '通知管理',
    yunWeiXiaJia: '运维下架',
    yunWeiShangJia: '运维上架',
    sheZhiShangJiaShi: '设置上架时间',
    gengXinShangJiaShi: '更新上架时间',
    gengXinRiQi: '更新日期',
    guanLianJiNengZu: '关联技能组',
    yiXiaJia: '已下架',
    weiShangJia: '未上架',
    yiShangJia: '已上架',
    tongZhiZhuangTai: '通知状态',
    tongZhiLeiXing: '通知类型',
    tongZhiMingCheng: '通知名称',
    tongZhiID: '通知ID',
    shuoMingPuTongTong:
      '说明: 普通通知&图文通知只能上架一类，不能同时上架，滚动通知可以和普通通知/图文通知同时上架。',
    quanXuanJiNengZu: '全选技能组',
    quanBuJiNengZu: '全部技能组',
    quanBuTongZhiLei: '全部通知类型',
    quanBuKeFu: '全部客服',
    qingShuRuTongZhi: '请输入通知名称',
  },
  richText: {
    danXuan: '单选',
    quanXuan: '全选',
    zuiDuoZhiNengTian: '最多只能添加3个图文通知哦！',
    qingXuanZhongLianJie: '请选中链接文字！',
    buYunXuShuRu: '不允许输入特殊字符',
    qingTianJiaTuWen: '请添加图文',
    qingXuanZeShiJian: '请选择时间',
    buShangJia: '不上架',
    xiaJiaShiJianBi: '下架时间必须比上架时间大5分钟',
    shangJiaShiJianBu: '上架时间不得小于当前时间！',
    qingShuRuXiangQing: '请输入详情内容！',
    puTongTongZhiXiang: '普通通知详情长度不得超过100',
    qingShuRuYiH: '请输入以http开头的url地址',
    qingShuRuLianJie: '请输入链接url，例:http://www.baidu.com',
    lianJieURL: '链接url:',
    lianJieURL2: '链接url路径:',
    lianJieLeiXing: '链接类型：',
    lianJieWenZi: '链接文字',
    jieShuRiQi: '结束日期',
    kaiShiRiQi: '开始日期',
    shangJiaShiDuan: '上架时段：',
    buShangJia2: '\n            不上架\n          ',
    shiFouShangJia: '是否上架：',
    xuTongZhiDeJi: '需通知的技能组：',
    lianJieLuJing: '链接路径：',
    tongZhiXiangQing: '通知详情：',
    tongZhiLeiXing: '通知类型：',
    tongZhiMingCheng: '通知名称：',
    tongZhiPeiZhi: '通知配置',
  },
  upTime: {
    shangJiaShiJianShe: '上架时间设置成功',
    shangJiaSheZhi: '上架设置',
  },
};
