export default {
  addInfoDialog: {
nullnulltuPianShangChuanCheng: "อัปโหลดรูปภาพสำเร็จแล้ว!", 
shangChuanDeTuPian: "อัตราส่วนของภาพที่อัพโหลดต้องเป็น 2:3 และความกว้างสูงสุดต้องไม่เกิน 120px", 
nullnullwaiBuLianJie: "ลิงก์ภายนอก", 
neiBuLianJie: "ลิงค์ภายใน", 
nullluJingBuNengBao: "เส้นทางต้องไม่มีภาษาจีน", 
luJingBiXuYi: "เส้นทางต้องขึ้นต้นด้วย /", 
nullnullnullqingShuRuUR: "โปรดป้อนเส้นทาง URL เช่น:/systemSetting", 
nullnullnulljianYiShangChuanDe: "แนะนำให้อัพโหลดภาพขนาด 120*180", 
kuanGaoBiZuiDa: "อัตราส่วนภาพ 2:3 ความกว้างสูงสุด 120", 
nulltianJiaTuPian: "เพิ่มรูปภาพ", 
qingShuRuBiaoTi: "กรุณากรอกหัวข้อเรื่องไม่เกิน 6 ตัวอักษร!", 
null  },
  index: {
ninQueRenYaoShan: "คุณแน่ใจหรือไม่ว่าต้องการลบประกาศนี้", 
ninQueRenYaoShan: "คุณแน่ใจหรือไม่ว่าต้องการลบประกาศนี้", 
nullxiaJia: "เอาออก", 
nullshangJia: "เอาขึ้น", 
gaiTongGao: "ประกาศนี้?", 
ninQueRenYao: "คุณยืนยันที่จะ", 
nullxiaJiaShiJian: "เวลาที่เอาออก", 
shangJiaShiJian: "เวลาที่เอาขึ้น", 
tongZhiGuanLi: "การจัดการการแจ้งเตือน", 
yunWeiXiaJia: "ลบผู้ดูแลระบบ", 
yunWeiShangJia: "ผู้ดูแลระบบอัปโหลด", 
sheZhiShangJiaShi: "การตั้งค่าเวลาขึ้น", 
gengXinShangJiaShi: "อัปเดตเวลาขึ้น", 
nullguanLianJiNengZu: "กลุ่มทักษะที่เกี่ยวข้อง", 
yiXiaJia: "เอาลงแล้ว", 
weiShangJia: "ยังไม่เอาขึ้น", 
yiShangJia: "เอาขึ้นแล้ว", 
tongZhiZhuangTai: "สถานะการแจ้งเตือน", 
nullnull    shuoMingPuTongTong:
      '说明: 普通通知&图文通知只能上架一类，不能同时上架，滚动通知可以和普通通知/图文通知同时上架。',
nullnullnullquanBuTongZhiLei: "ประเภทการแจ้งเตือนทั้งหมด", 
null  },
  richText: {
nullnullnullnullqingXuanZhongLianJie: "กรุณาตรวจสอบข้อความลิงค์!", 
nullqingTianJiaTuWen: "กรุณาเพิ่มกราฟิก", 
qingXuanZeShiJian: "กรุณาเลือกเวลา", 
buShangJia: "ไม่เอาขึ้น", 
xiaJiaShiJianBi: "เวลาเอาลงต้องนานกว่าเวลาเอาขึ้น 5 นาที", 
shangJiaShiJianBu: "เวลาเอาขึ้นต้องไม่น้อยกว่าเวลาปัจจุบัน!", 
qingShuRuXiangQing: "กรุณากรอกรายละเอียด!", 
puTongTongZhiXiang: "รายละเอียดการประกาศทั่วไปต้องมีความยาวไม่เกิน 100", 
nullnullnullnullnulllianJieWenZi: "ข้อความลิงค์", 
nullnullshangJiaShiDuan: "ระยะเวลาการเอาขึ้น", 
buShangJia2: "\n ไม่เอาขึ้น \n", 
shiFouShangJia: "เอาขึ้นหรือไม่", 
xuTongZhiDeJi: "กลุ่มทักษที่ต้องการแจ้งให้ทราบ:", 
lianJieLuJing: "เส้นทางลิงก์", 
tongZhiXiangQing: "รายละเอียดการแจ้งเตือน:", 
nullnull  },
  upTime: {
shangJiaShiJianShe: "ตั้งค่าเวลาขึ้นเรียบร้อยแล้ว", 
shangJiaShiJianShe: "ตั้งค่าเวลาขึ้นเรียบร้อยแล้ว", 
  },
};
