export default {
  publicEdit: {
shanChuNeiRong: "Xóa nội dung", 
shanChuNeiRong: "Xóa nội dung", 
shanChuNeiRong: "Xóa nội dung", 
shanChuNeiRong: "Xóa nội dung", 
tianJiaGongGongKu: "Thêm nội dung dữ liệu chung", 
paiXuZhiBiXu: "Giá trị sắp xếp phải là số nguyên lớn hơn 0 và không được vượt quá 8 bit", 
qingShuRuPaiXu: "Nhập giá trị sắp xếp", 
qingShuRuGongGong: "Nhập nội dung dữ liệu chung", 
gongGongKuNeiRong: "Chi tiết nội dung dữ liệu chung", 
neiRongPaiXuI: "ID sắp xếp nội dung", 
gongGongKuNeiRong2: "Nội dung dữ liệu chung", 
  },
  publicIndex: {
qingXianShanChuNei: "Vui lòng xóa nội dung trước", 
qingXianShanChuNei: "Vui lòng xóa nội dung trước", 
qingXianShanChuNei: "Vui lòng xóa nội dung trước", 
qingXianShanChuNei: "Vui lòng xóa nội dung trước", 
qingXianXuanZeWen: "Vui lòng chọn một tập tin trước!", qingXianXuanZeWen: "Vui lòng chọn một tập tin trước!", 
changDuZaiDaoGe: "Dài từ 1 đến 20 ký tự", 
qingShuRuBiaoQian: "Nhập tên thẻ", 
    dianJiDaoRuHou:
      '点击“导入”后，系统将自动执行，请确认文件是否正确，确认后请点击导入。',
yiCiZhiYunXu2: "1 lần chỉ nhập 1 tệp tin", 
yiCiZhiYunXu2: "1 lần chỉ nhập 1 tệp tin", 
yiCiZhiYunXu2: "1 lần chỉ nhập 1 tệp tin", 
yiCiZhiYunXu2: "1 lần chỉ nhập 1 tệp tin", 
dianJiXuanZeWen: "Nhấp để chọn 1 tệp tin", 
biaoQianPaiXuI: "ID sắp xếp thẻ", 
null  },
};
