export default {
  publicEdit: {
nullnullnullbianJiGongGongKu: "แก้ไขเนื้อหาคลังข้อมูลสาธารณะ", 
tianJiaGongGongKu: "เพิ่มเนื้อหาคลังข้อมูลสาธารณะ", 
nullnullqingShuRuGongGong: "กรุณาใส่เนื้อหาของคลังข้อมูลสาธารณะ", 
gongGongKuNeiRong: "รายละเอียดเนื้อหาของคลังข้อมูลสาธารณะ", 
neiRongPaiXuI: "ไอดี การจัดเรียงเนื้อหา", 
gongGongKuNeiRong2: "เนื้อหาคลังข้อมูลสาธารณะ", 
nulldianJiBiaoQianCha: "คลิกที่แท็กเพื่อดูรายละเอียด", 
gongGongKuNeiRong3: "ค่าการเรียงลำดับเนื้อหาคลังข้อมูลสาธารณะ", 
suoShuBiaoQian: "แท็กที่เกี่ยวข้อง", 
  },
  publicIndex: {
qingXianShanChuNei: "กรุณาลบเนื้อหาออกก่อน", 
qingXianShanChuNei: "กรุณาลบเนื้อหาออกก่อน", 
nullnullgongGongKuXL: "คลังข้อมูลสาธารณะ.xlsx", 
nullyiCiZhiYunXu: "อนุญาตให้นำเข้าไฟล์ได้ครั้งละหนึ่งไฟล์เท่านั้น!", 
daoRuChengGong: "นำเข้าเรียบร้อยแล้ว", 
qingXianXuanZeWen: "กรุณาเลือกไฟล์ก่อน!", 
nullqingShuRuBiaoQian: "กรุณากรอกชื่อแท็ก", 
qingShuRuBiaoQian2: "โปรดกรอกค่าการจัดเรียงแท็ก", 
gongGongKuBiaoQian: "แท็กคลังข้อมูลสาธารณะ", 
    dianJiDaoRuHou:
      '点击“导入”后，系统将自动执行，请确认文件是否正确，确认后请点击导入。',
yiCiZhiYunXu2: "อนุญาตให้นำเข้าไฟล์ได้ครั้งละหนึ่งไฟล์เท่านั้น!", 
yiCiZhiYunXu2: "อนุญาตให้นำเข้าไฟล์ได้ครั้งละหนึ่งไฟล์เท่านั้น!", 
dianJiXuanZeWen: "คลิกเพื่อเลือกไฟล์", 
nulldaoRuWenJian: "นำเข้าไฟล์", 
biaoQianPaiXuI: "ไอดี การจัดเรียงเนื้อหา", 
daoChuShuJu: "ส่งออกข้อมูล", 
daoRuShuJu: "นำเข้าข้อมูล", 
null  },
};
