export default {
  form: {
kongJianLeiXingBu: "Loại dấu cách không thể trống", 
kongJianLeiXingBu: "Loại dấu cách không thể trống", 
kongJianLeiXingBu: "Loại dấu cách không thể trống", 
kongJianLeiXingBu: "Loại dấu cách không thể trống", 
qingShuRuWaiLian: "Nhập tên miền bên ngoài", 
qingShuRuKongJian: "Nhập tên khoảng trắng", 
qingShuRuSE: "Nhập secretKey", 
qingShuRuAC: "Nhập accessKey", 
dongNanYa: "Đông Nam Á", 
beiMei: "Bắc Mỹ", 
huaNan: "Miền Nam Trung Quốc", 
huaBei: "Miền Bắc Trung Quốc", 
huaDong: "Miền Đông Trung Quốc", 
siYou: "Cá nhân", 
gongKai: "Công chúng", 
kongJianLeiXing: "Loại không gian", 
qingXuanZeCunChu: "Chọn khu lưu trữ", 
cunChuQuYu: "Khu lưu trữ", 
waiLianYuMingKe: "Tên miền bên ngoài, có thể tùy chỉnh và cần liên kết trong Qiniu Cloud", 
waiLianYuMing: "Tên miền bên ngoài", 
cunChuKongJianMing: "Tên không gian lưu trữ định Bucket nhóm duy nhất", 
kongJianMingCheng: "Tên không gian", 
  },
  index: {
shuJuTongBuCheng: "Đồng bộ hóa dữ liệu thành công", 
shuJuTongBuCheng: "Đồng bộ hóa dữ liệu thành công", 
shuJuTongBuCheng: "Đồng bộ hóa dữ liệu thành công", 
shuJuTongBuCheng: "Đồng bộ hóa dữ liệu thành công", 
qiNiuYunWenJian: "Tập tin Qiniu", 
  },
};
