export default {
  rechargeIndex: {
nullnullnullnullnullnullnulldingDanJiLuLie: "Lịch sử danh sách giao dịch", shouKuanErWeiMa: "Mã QR người nhận:", shouKuanErWeiMa: "Mã QR người nhận:", shuZiHuoBiDi: "Địa chỉ tiền tệ mã hóa", shuZiHuoBiDi: "Địa chỉ tiền tệ mã hóa", 
shuZiHuoBiZhuan: "Địa chỉ ví tiền tệ mã hóa", 
shuZiHuoBiHui: "Tỷ giá tiền tệ mã hóa", 
shuZiHuoBiShu: "Số lượng tiền mã hóa", 
shuZiHuoBiBi: "Loại tiền tệ mã hóa", 
chiKaRenXingMing: "Tên chủ thẻ", 
yinHangKaHao: "Số tài khoản ngân hàng", 
pingTaiDingDanHao: "Mã giao dịch nền tảng", pingTaiDingDanHao: "Mã giao dịch nền tảng", 
dingDanChongZhiXin: "Thông tin giao dịch gửi tiền", 
xiaDanJiLuI: "Lịch sử giao dịch ID:", 
chongZhiXinXi: "Thông tin gửi tiền", 
pingTaiDingDanZhuang: "Trạng thái giao dịch nền tảng", 
zongJinE: "Tổng tiền", zongJinE: "Tổng tiền", 
dingDanGengXinJi: "Cập nhật lịch sử giao dịch", 
chongZhiFangShi2: "Hình thức gửi tiền", 
pingTaiDingDanHao2: "Mã giao dịch nền tảng", 
xiaDanJiLuI2: "Lịch sử giao dịch ID:", 
keFuZhangHuNi2: "Tài khoản / Biệt danh dịch vụ Khách hàng", 
keHuZhangHuNi2: "Tài khoản / Biệt danh khách hàng", 
huiHuaID2: "ID đối thoại", 
  },
};
