export default {
  rechargeIndex: {
nullnullnullnullnullnullnulldingDanJiLuLie: "รายการบันทึก", 
shouKuanErWeiMa: "คิวอาร์โค้ดรับเงิน:", 
shuZiHuoBiDi: "ที่อยู่สกุลเงินดิจิทัล：", 
shuZiHuoBiZhuan: "โปรโตคอลการโอนสกุลเงินดิจิทัล：", 
shuZiHuoBiHui: "อัตราแลกเปลี่ยนสกุลเงินดิจิทัล：", 
shuZiHuoBiShu: "จำนวนสกุลเงินดิจิทัล：", 
shuZiHuoBiBi: "สกุลเงินดิจิทัล：", 
chiKaRenXingMing: "ชื่อผู้ถือบัตร：", 
yinHangKaHao: "หมายเลขบัตรธนาคาร：", 
nullnullyinHangMingCheng: "ชื่อธนาคาร", 
nullchongZhiURL: "URL ฝากเงิน", 
chongZhiFangShi: "วิธีการ ฝากเงิน", 
pingTaiDingDanHao: "หมายเลขรายการบนแพลตฟอร์ม", 
dingDanChongZhiXin: "ข้อมูลรายการฝากเงิน", 
nullnullnullxiaDanHuiHuaXin: "ข้อมูลบทสนทนรายการ", 
xiaDanJiLuI: "ไอดี บันทึกรายการ", 
chongZhiXinXi: "ข้อมูลการฝากเงิน", 
pingTaiDingDanZhuang: "สถานะรายการบนแพลตฟอร์ม", 
nullchuFaShiJian: "เหตุการณ์เริ่มต้น", 
nulldingDanGengXinXin: "อัปเดตข้อมูลรายการ", 
dangQianYeJinE: "จำนวนยอดเงินหน้าปัจจุบัน:", 
zongJinE: "จำนวนเงินทั้งหมด:", 
dingDanGengXinJi: "อัปเดตรายการบันทึก", 
nullnullnullchongZhiJinE2: "จำนวนยอดฝาก", 
chongZhiFangShi2: "ช่องทางการฝาก", 
pingTaiDingDanHao2: "หมายเลขรายการบนแพลตฟอร์ม", 
xiaDanJiLuI2: "ไอดี บันทึกรายการ", 
keFuZhangHuNi2: "บัญชีฝ่ายบริการลูกค้า/ชื่อเล่น", 
keHuZhangHuNi2: "บัญชีฝ่ายบริการลูกค้า/ชื่อเล่น", 
huiHuaID2: "ไอดี บทสนทนา", 
nullnullchongZhiJinEFan: "ขอบเขตจำนวนเงินฝาก/หยวน", 
qingShuRuXiaDan: "โปรดป้อนไอดี บันทึกรายการ", 
qingShuRuPingTai: "โปรดป้อนหมายเลขรายการบนแพลตฟอร์ม", 
  },
};
