export default {
  index: {
    ziDingYi: '自定义',
    ziDingYiShuJu: '自定义数据权限不能为空',
    qingXuanZe: '请选择',
    zhiNengShuRuDa: '只能输入大于1的整数哦',
    qingXuanZeJueSe: '请选择角色级别',
    benJi: '本级',
    qingShuRuDaYu: '请输入大于1的整数',
    jueSe: '角色',
    caiDanFenPei: '菜单分配',
    xuanZeZhiDingJiao: '选择指定角色分配菜单',
    keFuJueSe: '客服角色',
    jueSeJiBie: '角色级别 ',
    jueSeJiBie2: '角色级别',
    liRuKeFuJing:
      '例如：客服经理角色级别是3，客服经理能够创建和管理角色级别数字大于3的角色，不能创建和管理角色级别数字小于3的.',
    jueSeJiBieShu: '角色级别数字越小，角色级别越大。',
    jueSeQuanXian: '角色权限',
    shuJuQuanXian: '数据权限',
    jueSeLieBiao: '角色列表',
    miaoShuXinXi: '描述信息',
    qingXuanZeShuJu: '请选择数据范围',
    shuJuFanWei: '数据范围',
    jueSeMingCheng: '角色名称',
    chaXun: '查询',
    jueSeLeiXing: '角色类型',
    qingXuanZeJueSe2: '请选择角色',
  },
};
