export default {
  index: {
ziDingYi: "กำหนดเอง", 
ziDingYi: "กำหนดเอง", 
ziDingYiShuJu: "สิทธิ์ในข้อมูลที่กำหนดเอง ห้ามเว้นว่าง", 
nullnullnullbenJi: "ระดับนี้", 
qingShuRuDaYu: "กรุณากรอกจำนวนเต็มมากกว่า 1", 
jueSe: "บทบาท", 
caiDanFenPei: "การกำหนดเมนู", 
xuanZeZhiDingJiao: "เลือกบทบาทที่กำหนดเพื่อกำหนดเมนู", 
keFuJueSe: "บทบาทการบริการลูกค้า", 
jueSeJiBie: "ระดับบทบาท", 
    liRuKeFuJing:
      '例如：客服经理角色级别是3，客服经理能够创建和管理角色级别数字大于3的角色，不能创建和管理角色级别数字小于3的.',
jueSeJiBieShu: "ยิ่งจำนวนระดับบทบาทน้อยลงเท่าใด ระดับบทบาทก็จะยิ่งมากขึ้นเท่านั้น", 
jueSeJiBieShu: "ยิ่งจำนวนระดับบทบาทน้อยลงเท่าใด ระดับบทบาทก็จะยิ่งมากขึ้นเท่านั้น", 
jueSeQuanXian: "สิทธิ์ในบทบาท", 
shuJuQuanXian: "สิทธิ์ข้อมูล", 
jueSeLieBiao: "รายการบทบาท", 
miaoShuXinXi: "คำอธิบายข้อมูล", 
nullshuJuFanWei: "ช่วงข้อมูล", 
jueSeMingCheng: "ชื่อบทบาท", 
nulljueSeLeiXing: "ประเภทบทบาท", 
  },
};
