export default {
undefinedundefinedundefinedundefinedundefinedkaiQiChengGong: "Kịch hoạt thành công", 
  chaoGuoGaiShiJian:
    '超过该时间客服与客户未进行会话，系统将主动结束该会话;不可少于5分钟。',
undefined  chaoGuoGaiShiJian2:
    '超过该时间客服与客户未进行会话，客服可在工作台主动关闭该会话;不可少于3分钟',
undefinedundefinedundefinedundefinedundefinedundefinedfuWuZongJiePei: "Danh sách cấu hình tổng kết dịch vụ", 
undefinedxing: "Sao", 
undefinedundefinedquanBuShanChu: "Xóa tất cả", 
yiTianJiaBiaoQian: "Thêm thẻ", 
zuiDuoShuRuGe: "hập tối đa 8 từ (bao gồm các ký tự)", 
  kaiQiCiGongNeng:
    ' 开启此功能后，客户端在评价会话的时候可以对本次会话是否已解决进行选择。',
keFuShiFouJie: "Chăm sóc khách hàng có giải quyết được vấn đề hay không:", 
keFuShiFouJie: "Chăm sóc khách hàng có giải quyết được vấn đề hay không:", 
manYiDuPingJia: "Cài đặt đánh giá mức độ hài lòng", 
  yongHuPaiDuiChao:
    '用户排队超过该时间仍未进入会话，系统将会自动结束该用户排队。',
nullnullpaiDuiChaoShiShi: "Hàng chờ quá thời gian", 
  serverConfig: {
xinZengChengGong: "Thêm thành công", 
xinZengChengGong: "Thêm thành công", 
nullqingXianShanChuYe: "Xóa loại hình doanh nghiệp trước", 
ninQueDingShanChu: "Bạn chắc chắn muốn xóa thẻ [{val1}]", 
shanChuYeWuMing: "Xóa tên doanh nghiệp", 
nullnullpaiXuZhiBiXu: "Giá trị sắp xếp phải là số nguyên lớn hơn 0 và không được vượt quá 8 bit", 
qingShuRuYeWu2: "Nhập giá trị sắp xếp tên doanh nghiệp", 
fuWuZongJiePei: "Danh sách cấu hình tổng kết dịch vụ", 
chuangJianRen: "Người tạo", 
yeWuMingCheng: "Tên doanh nghiệp", 
yeWuPaiXuI: "ID Sắp xếp doanh nghiệp", 
xinZeng: "Thêm", 
null  },
  serverType: {
shanChuNeiRong: "Xóa nội dung", 
shanChuNeiRong: "Xóa nội dung", 
bianJiYeWuLei: "Chỉnh sửa loại hình doanh nghiệp", 
tianJiaYeWuLei: "Thêm loại hình kinh doanh", 
qingShuRuPaiXu: "Nhập giá trị sắp xếp", 
nullyeWuLeiXingXiang: "Chi tiết loại hình doanh nghiệp", 
yeWuLeiXingPai: "ID sắp xếp loại hình doanh nghiệp", 
yeWuLeiXingMing: "Tên loại hình doanh nghiệp", 
dianJiYeWuMing: "Bấm vào tên doanh nghiệp để xem", 
  },
};
