export default {
  index: {
shangChuanWenJianNeng: "Tệp tải lên có thể ở định dạng txt!", 
shangChuanWenJianNeng: "Tệp tải lên có thể ở định dạng txt!", 
minGanCiDaoRu: "Đã nhập thành công các từ nhạy cảm", 
nullyiXiaMinGanCi: "Các từ nhạy cảm sau đã tồn tại và chưa được nhập:", 
minGanCiDaoRu2: "Đã nhập thành công các từ nhạy cảm", 
minGanCiDuYi: "Các từ nhạy cảm đã tồn tại", 
minGanCiDaoRu3: "Nhập từ nhạy cảm thất bại", 
minGanCiDaoRu4: "Nhập từ nhạy cảm thất bại", 
changDuZaiBuNeng: "Chiều dài không được lớn hơn 10", 
qingShuRuMinGan: "Nhập các từ nhạy cảm", 
minGanCi: "Từ nhạy cảm", 
queDingYaoShanChu: "Chắc chắn muốn xóa từ nhạy cảm này không?", 
minGanCiID: "ID từ nhạy cảm", 
meiHangMinGanCi: "Mỗi dòng từ nhạy cảm phải bằng tiếng Trung, kết thúc.", 
meiGeMinGanCi: "Mỗi từ nhạy cảm cần được tách biệt trong tiếng Trung Quốc;", 
benMinGanCiZhi: "Từ nhạy cảm này chỉ hỗ trợ nhập các tệp txt;", 
null  },
};
