export default {
chengGong: "Thành công", 
chengGong: "Thành công", 
queDing: "Xác nhận", 
queDingSTA: "Chắc chắn về '{val1} {val2}' không?", 
sTATE: "Chăm sóc khách hàng của {val1}", 
queRenShanChu: "Xác nhận xóa", 
ruGuoGaiKeFu: "Nếu chăm sóc khách hàng trực tuyến, nó sẽ nhắc rằng tài khoản dịch vụ khách hàng đã bị vô hiệu hóa và đóng bàn dịch vụ khách hàng.", 
nulltingYong: "Vô hiệu", 
nullkeFuLieBiao: "Danh sách chăm sóc khách hàng", 
jieDaiShangXian: "Tiếp nhận giới hạn", 
nullnullqiYong2: "Kích hoạt", 
tingYong2: "Vô hiệu", 
caoZuo: "Thao tác", 
chuangJianRiQi: "Ngày tạo", 
nullzhangHuZhuangTai: "Trạng thái tài khoản", 
zuiDaJieDaiShang: "Giới hạn tiếp nhận tối đa", 
zaiXianJiNengZu: "Nhóm kỹ năng trực tuyến", 
nullkeFuGangWei: "Ví trí chăm sóc khách hàng", 
touXiang: "Hình đại diện", 
nullquanBuZhangHuZhuang: "Tất cả trạng thái tài khoản", 
quanBuJiNengZu: "Tất cả nhóm kỹ năng", 
};
