export default {
  index: {
qingPeiZhiGaiKe: "Cấu hình nhóm chăm sóc khách hàng!", 
qingPeiZhiGaiKe: "Cấu hình nhóm chăm sóc khách hàng!", 
jianTing: "Giám thính 11111", 
keFuBaoBiao: "Báo cáo chăm sóc khách hàng", 
qieHuan: "Chuyển đổi", 
ge: "Cái", 
xing: "Sao", 
dengLuShiChang: "Thời gian đăng nhập:", 
mangLu: "Bận", 
zaiXianQieHuan: "Hoán đổi online", 
nullpingJunHuiHuaShi: "Thời gian trung bình đối thoại", 
jieDaiYaLiZhi: "Giá trị áp tiếp đón", 
huiFuLu: "Tỷ lệ phản hồi", 
jieDaiKeHuShu: "Số lượng khách hàng đã nhận", 
keHuKeFuXiao: "Khách hàng / tin nhắn chăm sóc khách hàng", 
shiJian: "Thời gian", 
keHuPingJia: "Khách hàng đánh giá", 
keFuZongJie: "Tổng kết chăm sóc khách hàng", 
zanWuShuJuQing: "Không có dữ liệu, chọn lại điều kiện tìm kiếm!", 
tongJiZhi: "Giá trị thống kê", 
nullrenYuan: "Nhân viên", 
keFuRenYuan: "Nhân viên chăm sóc khách hàng", 
keHuPingJiaPing: "Đánh giá trung bình của khách hàng", 
keHuPingJiaLu: "Tỷ lệ / số lượng khách hàng đánh giá", 
yaoQingPingJiaLu: "Tỷ lệ / số lượng lời mời đánh giá", 
keFuJieJueLu: "Tỷ lệ / Số lượng giải quyết chăm sóc khách hàng", 
keFuZongJieLu: "Tỷ lệ / số lượng tổng kết chăm sóc khách hàng", 
sNeiXiangYingYing: "Tốc độ phản hồi trong vòng 30 giây", 
zuiDaXiangYingShi: "Thời gian phản hồi lớn nhất", 
pingJunShouXiangShi: "Thời lượng trung bình phản hồi đầu tiên", 
zuiDaJieDaiShu: "Số lần tiếp nhận tối đa", 
zhuanChuHuiHuaShu: "Số lượng đối thoại chuyển đi", 
huiHuaShuYouXiao: "Số lượng đối thoại / số lượng hợp lệ", 
mangLu2: "Bận", 
sheZhiXianShiCan: "Đặt thông số hiển thị", 
quanBuKeFuZhang: "Tất cả tài khoản chăm sóc khách hàng", 
keFuTongJi: "Thống kê chăm sóc khách hàng", 
suoYouKeFuBao: "Tất cả báo cáo chăm sóc khách hàng", 
  },
  moreBar: {
ziDongJieRu: "Tự động vào hàng chờ", 
ziDongJieRu: "Tự động vào hàng chờ", 
  },
};
