export default {
  index: {
qiangJieChengGong: "Tranh thành công", 
qiangJieChengGong: "Tranh thành công", 
nulltiShi: "Gợi ý", 
undefinednullnullpCWangZhan: "Trang web máy tính", 
yiDongWangZhan: "Trang di động", 
yiDongAPP: "Ứng dụng", 
nullnullhuiHuaJianKong: "Giám sát đối thoại", 
qiangZhiGuanBi: "Kích để đóng", 
zhaKanHuiHua: "Kiểm tra đối thoại", 
qiangJie: "Tranh nhận", 
shiFouYiChang: "Không bình thường", 
keHuXingBiao: "Sao của khách hàng", 
xiangYingChaoShi: "Phản hồi quá giờ", 
huiHuaChaoShi: "Đối thoại quá giờ", 
shouXiangChaoShi: "Phản hồi đầu tiên quá giờ", 
jingBaoZhuangTai: "Trạng thái cảnh báo", 
ziXunQuDaoXi: "Các kênh / hệ thống tư vấn", 
nullhuiHuaJianLiShi: "Thời gian tạo đối thoại", 
keHuYongHuMing: "Tên tài khoản của khách hàng", 
huiHuaShiChang: "Thời gian đối thoại", 
jiNengZu: "Nhóm kỹ năng", 
nullkeFuZhangHuNi: "Tài khoản / Biệt danh chăm sóc khách hàng", 
miaoZiDongShuaXin: "Từ làm mới mỗi 10 giây", 
jingBaoHuiHuaZhi: "\ n Đối thoại cảnh báo đã được cài lên đầu trang\ n", 
tiao: "thanh \ n", 
tiaoZaiXianHuiHua: "\ n Thanh đối thoại trực tuyến, cảnh báo đối thoại", 
gong: "\ n Tổng số \ n", 
nullquanBuZiXunLai: "Tất cả các nguồn yêu cầu", 
quanBuKeHuZu: "Tất cả các nhóm khách hàng", 
suoYouKeHuZu: "Tất cả các nhóm khách hàng", 
quanBuKeFu: "Tất cả chăm sóc khách hàng", 
quanBuJingBaoZhuang: "Tất cả các trạng thái cảnh báo", 
suoYouHuiHuaLei: "Tất cả ID đối thoại", 
  },
};
