export default {
  index: {
undefined
cHANG: "Đổi danh nghiệp", 
cHANG: "Đổi danh nghiệp", 
nullyou: "Có", 
wuXiaoHuiHua: "Đối thoại vô hiệu", 
youXiaoHuiHua: "Đối thoại có hiệu lực", 
weiZongJie: "Chưa tổng kết", 
weiZhiJian: "Chưa kiểm chứng", 
yiZhiJian: "Đã kiểm chứng", 
nullnullnullhuiHuaKaiShiShi: "Thời gian bắt đầu đối thoại", 
wenTiShiChang: "Câu hỏi / Thời gian", 
nullnull
xiaoXiShu: "Số lượng tin nhắn", 
xiaoXiShu: "Số lượng tin nhắn", 
zhiJianZhuangTai: "Trạng thái kiểm duyệt", 
nullkaiShiShiJian: "Ngày bắt đầu", 
nullnullnullxiaoYu: "Ít hơn", 
daYu: "Nhiều hơn", 
zhiNengShuRuDa: "Chỉ những số dương lớn hơn 0 mới có thể được nhập", 
qingShuRu: "Nhập vào", 
zhiNengShuRuZheng: "Chỉ có thể nhập số dương", 
zuiDaXianZhiS: "Giới hạn tối đa 1800", 
youCeBuNengXiao: "Cạnh phải không được nhỏ hơn cạnh trái", 
zuoCeBuNengDa: "Cạnh trái không được lớn hơn cạnh phải", 
huiHuaJiLu: "Lịch sử đối thoại", 
shouXiangShiChang: "Thời gian phản hồi đầu tiên", 
nullxiaoXiShuKeHu: "Số lượng tin nhắn (khách hàng / chăm sóc khách hàng)", 
nullnullyeWu: "Doanh nghiệp", 
huiHuaLeiBie: "Phân loại đối thoại", 
wenTiShiChang2: "Câu hỏi / Thời gian", 
sheZhiZhanShiZi: "Thiết lập các hiển thị", 
gengDuoShaiXuanTiao: "Các bộ lọc khác \ n", 
gengDuoShaiXuanTiao2: "Các bộ lọc khác", 
nullquanBuYeWuLei: "Tất cả các loại hình doanh nghiệp", 
quanBuYeWu: "Tất cả doanh nghiệp", 
zuiChangXiangYingShi: "Thời gian phản hồi lâu nhất", 
nullqingShuRuKeHu2: "Nhập đại lý cấp trên của khách hàng", 
qingShuRuKeHu3: "Nhập tài khoản khách hàng", 
  }
}
