export default {
  index: {
qiangJieChengGong: "แย่งการเชื่อมต่อสำเร็จ!", 
qiangJieChengGong: "แย่งการเชื่อมต่อสำเร็จ!", 
nullnullnullnullnullpCWangZhan: "เว็บไซต์คอมพิวเตอร์", 
yiDongWangZhan: "เว็บไซต์มือถือ", 
yiDongAPP: "แอพมือถือ", 
nullnullhuiHuaJianKong: "ตรวจสอบบทสนทนา", 
qiangZhiGuanBi: "บังคับปิด", 
zhaKanHuiHua: "ตรวจดูบทสนทนา", 
qiangJie: "แย่งรับ", 
shiFouYiChang: "ผิดปกติหรือไม่", 
keHuXingBiao: "ลูกค้าติดดาว", 
xiangYingChaoShi: "หมดเวลาการตอบสนอง", 
huiHuaChaoShi: "หมดเวลาบทสนทนา", 
shouXiangChaoShi: "หมดเวลาเสียงกริ่งแรก", 
jingBaoZhuangTai: "สถานะการเตือน", 
ziXunQuDaoXi: "ระบบ/ช่องทางสอบถาม", 
nullhuiHuaJianLiShi: "เวลาในการสร้างบทสนทนา", 
keHuYongHuMing: "ชื่อผู้ใช้ของลูกค้า", 
nullnullnullnullmiaoZiDongShuaXin: "รีเฟรชอัตโนมัติ 10 วินาที", 
jingBaoHuiHuaZhi: "\nแจ้งเตือนบทสนทนาสูงสุด\n", 
tiao: "บทความ \n", 
tiaoZaiXianHuiHua: "\n บทสนทนาออนไลน์ บทสนทนาการแจ้งเตือน", 
gong: "\n รวม \n", 
nullquanBuZiXunLai: "ที่มาการสอบถามทั้งหมด", 
nullnullnullquanBuJingBaoZhuang: "สถานะการแจ้งเตือนทั้งหมด", 
suoYouHuiHuaLei: "ประเภทบทสนทนาทั้งหมด", 
  },
};
