export default {
bianJiJiNengZu: "Chỉnh sửa nhóm kỹ năng", 
bianJiJiNengZu: "Chỉnh sửa nhóm kỹ năng", 
yiChuJiNengZu: "Xóa thành viên nhóm kỹ năng", 
tianJiaChengYuanDao: "Thêm thành viên vào", 
zuChengYuan: "Nhóm thành viên", 
tianJiaJiNengZu: "Thêm nhóm kỹ năng", 
rOWNA: "[{val1}] đã được liên kết với [{val2}] và không thể bị xóa!", 
shanChuChengGong: "Xóa thành công", 
youKeWenTiJi: "Không thể xóa nhóm kỹ năng giải quyết vấn đề du khách", 
youKe: "Du khách", 
nulljiNengZuLieBiao: "Danh sách nhóm kỹ năng", 
yiChuChengYuan: "Loại bỏ thành viên", 
nulltianJiaChengYuan: "Thêm thành viên", 
jiNengZuID: "ID nhóm kỹ năng", 
nullnull};
