export default {
  index: {
nullnullqingShuRuCR: "โปรดป้อนการแสดงออกของ Cron", 
qingShuRuFangFa: "กรุณากรอกชื่อวิธีการ", 
qingShuRuBE: "กรุณากรอกชื่อBean", 
qingShuRuRenWu: "กรุณากรอกชื่องาน", 
dingShiRenWu: "งานหมดเวลา", 
nullqueDingTingZhiBing: "ต้องการหยุดและลบงานนี้หรือไม่", 
zanTing: "หยุด", 
huiFu: "ฟื้นฟู", 
zhiXing: "ดำเนินการ", 
nullyunXingZhong: "อยู่ในระหว่างการดำเนินการ", 
yiZanTing: "ถูกระงับ", 
cRONBiao: "การแสดงออกของ cron", 
canShu: "พารามิเตอร์", 
zhiXingFangFa: "วิธีการดำเนินการ", 
bEANMing: "ชื่อBean", 
renWuMingCheng: "ชื่องาน", 
renWuMiaoShu: "คำอธิบายงาน", 
nullrenWuZhuangTai: "สถานะงาน", 
cRONBiao2: "การแสดงออกของ cron", 
canShuNeiRong: "เนื้อหาพารามิเตอร์", 
null  },
  log: {
shiBai: "ล้มเหลว", 
shiBai: "ล้มเหลว", 
renWuRiZhi: "บันทึกงาน", 
nullhaoShiHaoMiao: "เวลาที่ใช้ (มิลลิวินาที)", 
nulldaoChu: "ส่งออก", 
nullriZhiZhuangTai: "สถานะบันทึก", 
nullnull  },
};
