export default {
  index: {
zhiXingChengGong: "Thực hiện thành công", 
zhiXingChengGong: "Thực hiện thành công", 
qingShuRuCR: "Nhập biểu thức cron", 
qingShuRuFangFa: "Nhập tên hình thức", 
qingShuRuBE: "Nhập tên Bean", 
qingShuRuRenWu: "Nhập tên nhiệm vụ", 
dingShiRenWu: "Thời gian định nhiệm vụ", 
nullqueDingTingZhiBing: "Chắc chắn muốn dừng và xóa nhiệm vụ này?", 
zanTing: "Tạm ngừng", 
huiFu: "Phục hồi", 
zhiXing: "Chấp hành", 
nullyunXingZhong: "Đang tiến hành", 
yiZanTing: "Đã ngưng", 
cRONBiao: "cron diễn đạt", 
canShu: "Thông số", 
zhiXingFangFa: "Phương thức chấp hành", 
bEANMing: "Tên Bean", 
renWuMingCheng: "Tên nhiệm vụ", 
renWuMiaoShu: "Mô tả nhiệm vụ", 
nullrenWuZhuangTai: "Trạng thái nhiệm vụ", 
cRONBiao2: "Cron hình thức diễn đạt", 
canShuNeiRong: "Nội dung thông số", 
riZhi: "Nhật ký", 
  },
  log: {
shiBai: "Thất bại", 
shiBai: "Thất bại", 
renWuRiZhi: "Nhiệm vụ nhật ký", 
yiChangXiangQing: "Chi tiết ngoại lệ", 
haoShiHaoMiao: "Thời gian (mili giây)", 
zhaKanXiangQing: "Kiểm tra chi tiết", 
daoChu: "Xuất", 
souSuo: "Tìm kiếm", 
riZhiZhuangTai: "Trạng thái nhật ký", 
jieShuRiQi: "Ngày kết thúc", 
kaiShiRiQi: "Ngày bắt đầu", 
  },
};
