export default {
  center: {
touXiangXiuGaiCheng: "Sửa đổi hình đại diện thành công", 
touXiangXiuGaiCheng: "Sửa đổi hình đại diện thành công", 
shangChuanTouXiangTu: "Kích thước của ảnh đại diện tải lên không vượt quá 2MB!", 
nullnullnullbaoCunPeiZhi: "Lưu cấu hình", 
nu: "Quý bà", 
nan: "Quý ông", 
xingBie: "Giới tính", 
shouJiHaoMaBu: "Số điện thoại không được lặp lại", 
shouJiHao: "Số điện thoại", 
yongHuNiChengBu: "Biệt danh của người dùng không được sử dụng để đăng nhập", 
niCheng: "Biệt danh", 
yongHuZiLiao: "Thông tin tài khoản", 
miMa: "Mật khẩu", 
xiuGai: "Chỉnh sửa", 
anQuanSheZhi: "Cài đặt an toàn", 
nullyongHuYouXiang: "Email tài khoản", 
shouJiHaoMa: "Số điện thoại", 
yongHuNiCheng: "Biệt danh tài khoản", 
dengLuZhangHao: "Đăng nhập tài khoản", 
dianJiShangChuanTou: "Nhấp để tải hình đại diện lên", 
  },
  index: {
jueSeBuNengWei: "Vai trò không được để trống", 
jueSeBuNengWei: "Vai trò không được để trống", 
gangWeiBuNengWei: "Vị trí không được để trống", 
buMenBuNengWei: "Bộ phận không được để trống", 
zhuangTaiXiuGaiCheng: "Trạng thái thay đổi thành công", 
kaiQiChengGong: "Kịch hoạt thành công", 
shiFouJiXu: "tiếp tục?", 
undefinedqueDingKaiQi: "Xác nhận muốn mở", 
tuPianYanZheng: "Hình ảnh xác minh", 
guGeYanZheng: "Xác minh Google", 
xiuGaiChengGong: "Chỉnh sửa thành công", 
queDingYaoZhongZhi: "Chắc chắn muốn đặt lại xác minh Google và đóng lại không?", 
nullqingShuRuShouJi: "Nhập số điện thoại", 
nullqingShuRuYouXiang: "Nhập địa chỉ email", 
nullzhiNengShuRuZi: "Chỉ có thể nhập chữ cái và số", 
nullnullqingXuanZeZongDai: "ID Tổng đại lý", 
qingXuanZeDaiLi: "Chọn tài khoản đại lý", 
nullqingXuanZeGangWei: "Chọn vị trí", 
qingXuanZeBuMen: "Chọn bộ phận", 
nulljiHuo: "Kích hoạt", 
yongHu: "Tài khoản", 
zhongZhiMiMa: "Đặt lại mật khẩu", 
nullzhongZhiYanZhengMa: "đặt lại mã xác minh", 
tuPian: "Hình ảnh", 
guGe: "Google", 
yanZhengMaLeiXing: "Loại mã xác minh", 
buMenGangWei: "Bộ phận / Chức vụ", 
    ruGuoYuanKeFu:
      '如果原客服类部门的用户修改为非客服类的用户，将会将该客服账号自动停用，客服如果已登录，将会自动下线。',
qingXianXuanZeA: "Chọn ứng dụng trước", 
qingXianXuanZeA: "Chọn ứng dụng trước", 
qingXianXuanZeChan: "Chọn sản phẩm trước", 
chanPin: "Sản phẩm", 
zhiNengChuangJianXiu: "Chỉ có thể tạo / sửa đổi vai trò người dùng có cấp thấp hơn cấp vai trò của chính bạn", 
qingXianXuanZe: "Chọn trước", 
nulldaiLiZhangHao: "Tài khoản đại lý", 
nullqingXianXuanZeBu: "Chọn một bộ phận trước tiên", 
youXiang: "Email", 
dianHua: "Số điện thoại", 
  },
  updatePass: {
xiuGaiChengGongT: "Sửa đổi thành công, mật khẩu mới của {val1} được mặc định là {val2}", 
xiuGaiChengGongT: "Sửa đổi thành công, mật khẩu mới của {val1} được mặc định là {val2}", 
tHISE: "Đã mở khóa {val1} thành công", 
qingShuRuGuanLi: "Nhập mật khẩu của quản trị viên", 
zhongZhiMiMaWei: "Đặt lại mật khẩu thành", 
qingShuRuNinDe: "Nhập mật khẩu đăng nhập", 
dengLuMiMa: "Mật khẩu đăng nhập", 
dengLuYongHuMing: "Tài khoản đăng nhập", 
xuYaoYanZhengNin: "Danh tính của bạn cần được xác minh", 
jieSuoZhangHu: "Mở khóa tài khoản", 
  },
};
