export default {
  center: {
nullnullnullnullnullnullnullnullnullxingBie: "เพศ", 
shouJiHaoMaBu: "หมายเลขโทรศัพท์มือถือไม่สามารถซ้ำได้", 
nullyongHuNiChengBu: "ชื่อเล่นผู้ใช้ไม่ได้ใช้สำหรับการเข้าสู่ระบบ", 
niCheng: "ชื่อเล่น", 
yongHuZiLiao: "ข้อมูลผู้ใช้", 
nullnullanQuanSheZhi: "การตั้งค่าความปลอดภัย\n", 
nullyongHuYouXiang: "อีเมลผู้ใช้", 
shouJiHaoMa: "หมายเลขโทรศัพท์", 
nulldengLuZhangHao: "เข้าสู่ระบบบัญชี", 
dianJiShangChuanTou: "คลิกเพื่ออัปโหลดโปรไฟล์ต้อง", 
  },
  index: {
jueSeBuNengWei: "บทบาท ห้ามเว้นว่าง", 
jueSeBuNengWei: "บทบาท ห้ามเว้นว่าง", 
gangWeiBuNengWei: "ตำแหน่ง ห้ามเว้นว่าง", 
buMenBuNengWei: "แผนก ห้ามเว้นว่าง", 
zhuangTaiXiuGaiCheng: "แก้ไขสถานะสำเร็จ", 
nullshiFouJiXu: "ดำเนินการต่อหรือไม่?", 
nullqueDingKaiQi: "ตกลงเพื่อเปิด", 
tuPianYanZheng: "ยืนยันรูปภาพ", 
guGeYanZheng: "ยืนยันของ Google", 
nullqueDingYaoZhongZhi: "แน่ใจไหมว่าต้องการรีเซ็ตการยืนยันของ Google และเชื่อมต่อใหม่", 
nullqingShuRuShouJi: "กรอกหมายเลขโทรศัพท์", 
nullqingShuRuYouXiang: "กรุณากรอกอีเมลของคุณ", 
nullzhiNengShuRuZi: "สามารถป้อนได้เฉพาะตัวอักษรและตัวเลขเท่านั้น", 
nullnullnullnullnullqingXuanZeGangWei: "กรุณาเลือกตำแหน่ง", 
qingXuanZeBuMen: "กรุณาเลือกแผนก", 
nulljiHuo: "เปิดใช้งาน", 
nullzhongZhiMiMa: "รีเซ็ตรหัสผ่าน", 
nullzhongZhiYanZhengMa: "รีเซ็ตรหัสยืนยัน", 
nullnullyanZhengMaLeiXing: "ประเภทรหัสยืนยัน", 
buMenGangWei: "แผนก/ตำแหน่ง", 
    ruGuoYuanKeFu:
      '如果原客服类部门的用户修改为非客服类的用户，将会将该客服账号自动停用，客服如果已登录，将会自动下线。',
qingXianXuanZeA: "กรุณาเลือก app ก่อน", 
qingXianXuanZeA: "กรุณาเลือก app ก่อน", 
qingXianXuanZeChan: "กรุณาเลือกสินค้าก่อน", 
chanPin: "สินค้า", 
zhiNengChuangJianXiu: "คุณสามารถสร้าง/แก้ไขบทบาทผู้ใช้ที่มีระดับน้อยกว่าระดับบทบาทของคุณเท่านั้น", 
nullnullnullnullqingXianXuanZeBu: "กรุณาเลือกแผนกก่อน", 
youXiang: "อีเมล", 
dianHua: "หมายเลขโทรศัพท์", 
  },
  updatePass: {
xiuGaiChengGongT: "การแก้ไขสำเร็จ และรหัสผ่านใหม่ของ {val1} มีค่าเริ่มต้นเป็น {val2}", 
xiuGaiChengGongT: "การแก้ไขสำเร็จ และรหัสผ่านใหม่ของ {val1} มีค่าเริ่มต้นเป็น {val2}", 
tHISE: "ปลดล็อก {val1} สำเร็จแล้ว", 
qingShuRuGuanLi: "กรุณาใส่รหัสผ่านผู้ดูแลระบบ", 
zhongZhiMiMaWei: "รีเซ็ตรหัสผ่านเป็น", 
nullnullnullxuYaoYanZhengNin: "จำเป็นต้องมีการยืนยันตัวตนของคุณ", 
jieSuoZhangHu: "ปลดล็อกบัญชีของคุณ", 
  },
};
