export default {
  directive: {
guDing: "Cố định", 
  },
  index: {
sECON: "{val1} giây", 
sECON: "{val1} giây", 
mINTO: "{val1} phút {val2} giây", 
hTOST: "{val1} giờ {val2} phút {val3} giây", 
dTOST: "{val1} ngày {val2} giờ {val3} phút {val4} giây", 
fuZhiShiBai: "Sao chép thất bại", 
fuZhiChengGong: "Sao chép thành công", 
nullnullri: "Ngày", 
yue: "Tháng", 
tianQian: "1 ngày trước", 
xiaoShiQian: "1 tiếng trước", 
fenZhongQian: "Mấy phút trước", 
gangGang: "Vừa mới", 
liu: "Sáu", 
wu: "Năm", 
si: "Bốn", 
san: "Ba", 
er: "Hai", 
yi: "Một", 
nullnullmiao: "Giây", 
  },
  request: {
jieKouQingQiuShi: "Yêu cầu kết nối thất bại", 
jieKouQingQiuShi: "Yêu cầu kết nối thất bại", 
zhangHaoYiBeiSuo: "Tài khoản bị khoá", 
guanBi: "Đóng 111", 
chongXinDengLu: "Đăng nhập lại", 
xiTongTiShi: "Hệ thống gợi ý", 
dengLuYiChangDeng: "Đăng nhập bất thường / trạng thái người dùng đăng nhập bất thường, đăng nhập lại!", 
wangLuoQingQiuChao: "Yêu cầu mạng quá giờ", 
  },
  validate: {
nullnullnullqingShuRuZhengQue3: "Nhập đúng số điện thoại cố định (định dạng: mã vùng + số, Ví dụ: 010-1234567)", 
qingShuRuZhengQue4: "Nhập số điện thoại hoặc số điện thoại cố định chính xác", 
qingShuRuZhengQue5: "Nhập địa chỉ IP chính xác", 
  },
  settings:{
title: "Chăm sóc khách hàng ST", 
title: "Chăm sóc khách hàng ST", 
  }
};
