export default {
  index: {
    laHeiROW: '拉黑 {val1}',
    shanChuYongHuR: '删除用户 {val1} 确认',
    queDingShanChuR: '确定删除 {val1} 用户资料？删除后将无法恢复。',
    queDingJiangGaiYong: '确定将该用户 {val1} 解除黑名单？',
    laHeiChengGong: '拉黑成功！',
    shanChuChengGong: '删除成功！',
    keHuZhangHu: '客户账户',
    buYunXuShuRu: '不允许输入非法字符',
    qingShuRuLaHei: '请输入拉黑原因',
    qingXuanZe: '请选择',
    keHuLieBiao: '客户列表',
    queRen: '确认',
    biTian: '必填...',
    laHeiYuanYin: '拉黑原因：',
    laHeiLeiXing: '拉黑类型：',
    laHeiYongHu: '拉黑用户：',
    laHei: '拉黑',
    shiFouLaHei: '是否拉黑',
    liShiZiXunShu: '历史咨询数',
    zhongZhi: '重置',
    chaXun: '查询',
  },
};
