export default {
  editDialog: {
    bianJiChengGong: '编辑成功',
    danXuan: '单选',
    weiXin: '微信',
    shouJiHao: '手机号',
    fou: '否',
    shi: '是',
    shiFouBiTian: '是否必填',
    lianXiFangShi: '联系方式',
    liuYanTuPian: '留言图片',
    qingShuRuNeiRong: '请输入内容提示语',
    liuYanNeiRong: '留言内容',
    ziXunWenTi: '咨询问题',
    xingXingBie: '姓(性别)',
    keHuZhangHao: '客户账号',
    liuYanBanZiDuan: '留言板字段',
    tianXieShengR: '请必须填写你生日'
  },
  index: {
    ninShiFouQueDing: '您是否确定要{val1}留言功能?',
    languageTemplate: '（语言：{val1}）',
    sheZhi: '设置',
    xuanTian: '选填',
    biTian: '必填',
    liuYanZiDuanShe: '留言字段设置',
    keHuLiuYanDang: '客户留言当天超过该次数，则不能再留言。',
    shiFouKaiQiLiu: '是否开启留言功能',
    liuYanSheZhi: '留言设置',
    zhiNengShuRuDa: '只能输入大于0的正数',
    qingShuRu: '请输入',
    liuYanTuPian: '\n                留言图片\n              ',
    liuYanNeiRongBi: '\n                留言内容（必填）\n              ',
    ziXunWenTiBi: '\n              咨询问题（必填)\n            ',
    xingXingBieBiTian: '\n              姓(性别)（必填)\n            ',
    keHuZhangHaoBi: '\n              客户账号（必填）\n            ',
    meiRiZuiDuoLiu: '每日最多留言次数：',
    bianJi: '编辑',
    baoCun: '保存'
  }
}
