export default {
  index: {
    dingJiLeiMu: '顶级类目',
    qingShuRuDiZhi: '请输入地址',
    caiDan: '菜单',
    shi: '是',
    fou: '否',
    keJian: '可见',
    huanCun: '缓存',
    waiLian: '外链',
    zuJianLuJing: '组件路径',
    quanXianBiaoZhi: '权限标识',
    luYouDiZhi: '路由地址',
    tuBiao: '图标',
    caiDanMingCheng: '菜单名称',
    shangJiLeiMu: '上级类目',
    piPeiZuJianNei: '匹配组件内Name字段',
    zuJianMingCheng: '组件名称',
    caiDanPaiXu: '菜单排序',
    anNiuMingCheng: '按钮名称',
    caiDanBiaoTi: '菜单标题',
    caiDanKeJian: '菜单可见',
    caiDanHuanCun: '菜单缓存',
    waiLianCaiDan: '外链菜单',
    dianJiXuanZeTu: '点击选择图标',
    caiDanTuBiao: '菜单图标',
    anNiu: '按钮',
    muLu: '目录',
    caiDanLeiXing: '菜单类型',
    moHuSouSuo: '模糊搜索',
  },
};
