export default {
  index: {
    shangChuanWenJianNeng: '上传文件能是 txt 格式!',
    minGanCiDaoRu: '敏感词导入成功',
    haoDe: '好的',
    yiXiaMinGanCi: '以下敏感词已存在，未导入：',
    minGanCiDaoRu2: '敏感词导入成功。',
    minGanCiDuYi: '敏感词都已存在',
    minGanCiDaoRu3: '敏感词导入失败。',
    minGanCiDaoRu4: '敏感词导入失败',
    changDuZaiBuNeng: '长度在 不能大于 10',
    qingShuRuMinGan: '请输入敏感词',
    minGanCi: '敏感词',
    queDingYaoShanChu: '确定要删除该敏感词吗？',
    minGanCiID: '敏感词ID',
    meiHangMinGanCi: '每行敏感词必须中文，结束.',
    meiGeMinGanCi: '每个敏感词需要以中文，隔开；',
    benMinGanCiZhi: '本敏感词只支持txt文件的导入；',
    zhongZhi: '重置',
    shuRuMinGanCi: '输入敏感词搜索',
  },
};
